### ISSUE TITLE
Keep getting kicked out of server

### ISSUE THREAD

**Issue by Villatine** [StarQuestMinecraft/StarQuestPublic#1002]
I keep getting kicked out of the server and it says
-Internal Exception:io.netty.handler.codec.DecoderException:Badly compressed packet-size of 22 is below server threshold 256. 
I don't know if it is just me or the server or maybe both. I am new to the server as well. If anyone has a idea on how to fix this bug. I would be grateful,  thank you.

**Comment by awangatboo** [comment]
I keep getting kicked out of the server and it says -Internal Exception:io.netty.handler.codec.DecoderException:Badly compressed packet-size of 22 is below server threshold 256. I don't know if it is just me or the server or maybe both. I am new to the server as well. If anyone has a idea on how to fix this bug. I would be grateful, thank you.

**Comment by awangatboo** [comment]
Make sure you are using minecraft 1.9.2.

**Comment by GingerWalnut** [comment]
Is this still happening?
