### ISSUE TITLE
Re-logging on planet, suffocating in space.

### ISSUE THREAD

**Issue by FlyingTaurus523** [StarQuestMinecraft/StarQuestPublic#1003]
I was on xira then I suddenly somehow time out or it mightve been planet transfer but I got no message so I relogged then suddenly Im in space suffocating and die. A manager checked and said there was no trace of my ship though so its probably lost through planet transfer or something. It happened around 5:38 PM EST on apr. 6 2016 is that helps any.

**Comment by GingerWalnut** [comment]
With the new craft transfer system, this has most likely been fixed. If this still happens, please reopen/create a new report.
