### ISSUE TITLE
Inventory disappeared

### ISSUE THREAD

**Issue by Masafu** [StarQuestMinecraft/StarQuestPublic#1006]
I was in my ship - the inside was lit, very small cockpit, closed trapdoor. I had to leave my computer, idle logged from Starquest, and when I came back, my entire Inventory was gone - I was in the same place, no death message. My inventory was full of ship building materials, I had a tier III power suit, 2 tier III pickaxes, a tier III axe, a tier III shovel, tier III trowel and a tier III power shield. I don't have a current screen shot, but I have one from yesterday with everything but the shears, second pick and ship stuff.
![screen shot 2016-06-06 at 14 57 52](https://cloud.githubusercontent.com/assets/19654758/15856796/00bb15ec-2cc9-11e6-9c0b-e54d1be32150.png)

**Comment by GingerWalnut** [comment]
Has this happened to anyone else?

**Comment by Masafu** [comment]
Not that I am Aware, but don't worry about it, I'll just get on with playing (when I have time), just reported it in case it comes up again,

**Comment by Millibyte1** [comment]
No repro
