### ISSUE TITLE
Players still being a Guest when joining an empire

### ISSUE THREAD

**Issue by Generaltyler1** [StarQuestMinecraft/StarQuestPublic#1008]
have a few players that joined an empire, but they are still guests, examples being Chaos_Ghoul, Creatia, Jas02, each being in the respective empire, Requiem, Arator and Yavari.

**Comment by awangatboo** [comment]
I have seen that as well.  I will ask a Dev staff member about it.

**Comment by awangatboo** [comment]
I have been told this has been fixed.
