### ISSUE TITLE
Some Dropper/ Dispenser Inventories emptied on entry to Xira/ Core space

### ISSUE THREAD

**Issue by Cutout1** [StarQuestMinecraft/StarQuestPublic#1009]
I filled up my droppers and dispenser storages with potions and other items, but after flying to Xira I noticed that a few of the droppers were empty. I know no one was in my ship, so they must have been erased by a bug some how. Here is a picture of my items before flying:
http://imgur.com/gm8h6Hx
I don't need a refund anymore, Zorecknor is handling it in game, but thought I should report it.

**Comment by awangatboo** [comment]
There is a bug with potions.  It was fixed but due to a check-in error, it is broken again.  Should be fixed in the next day or so.

**Comment by martinjonsson01** [comment]
@Cutout1 I belive I've fixed this problem. If you could tell me what happens next time if you try it again, that'd be great. So we can close this issue.

**Comment by martinjonsson01** [comment]
I tested this with both splash and normal potions between Core Space and Xira, and my fix worked.
