### ISSUE TITLE
Regular Turret "trapped"

### ISSUE THREAD

**Issue by mcdouble** [StarQuestMinecraft/StarQuestPublic#1010]
When in my regular turret, I had potatoes in my offhand slot and when I right clicked to leave the turret it gave me the entrance message and wouldn't let me leave until cutout told me to remove the taters.

**Comment by sergio-carli** [comment]
Yes, one of my faction members experienced this also.

(This is KillerMidget)

**Comment by GingerWalnut** [comment]
This should be fixed.
