### ISSUE TITLE
Someone stole by gold out of a faction chest

### ISSUE THREAD

**Issue by ltrester** [StarQuestMinecraft/StarQuestPublic#1012]
I made a refund request on the forums for inter-empire aggression and they sent me here. I have screen shots to prove I had the gold.

Let me know what to do now

**Comment by awangatboo** [comment]
You will need a mod / manager for this one.  Also use [private] on your chests that you want to keep stuff.

**Comment by ltrester** [comment]
The mods said to make a github!
