### ISSUE TITLE
Inventory glitch out of Erilon

### ISSUE THREAD

**Issue by JC3371** [StarQuestMinecraft/StarQuestPublic#1015]
CrowkEngineer and I, JC3371 flew out of Erilon today then lost our inventory and suffocated to death in sapce. A few mods tried to use the command to restore inventory, but it would not work. 

Plz fix.

**Comment by JC3371** [comment]
I was unable to get a screenshot of my inventory before i flew out of Erilon.

**Comment by awangatboo** [comment]
You need to see a mod about this.  If you have a real bug with exact data like what time, if the server was laggy then please create a bug report. 

 If you go to https://github.com/StarQuestMinecraft/StarQuestPublic/blob/master/README.md You can see this is not the place for a refund request.
