### ISSUE TITLE
Glitched and Suffocated in Boarding Ramp

### ISSUE THREAD

**Issue by IggyW** [StarQuestMinecraft/StarQuestPublic#1016]
This is creativbuildr.
So yesterday I was at the Arator Beachhead and I closed the boarding ramp on my ship. I was standing on a solid block that would not move. As soon as I hit the sign, the boarding ramp shut and I seemingly got teleported into the far side of the boarding ramp - the one that doesnt move. It was as if that block and the block underneath didnt exist, because I could jump up and down, but I was still suffocating to death, and died.
Masafu, a training mod, tried to help me by getting all my items, but he did not pick up a lot of my items. He basically picked up the items in /kit starter and several stacks of bread. He could not tp me back to my ship so I had to fly back on my own, and that is when I realized he did not get most of my stuff.
I would like a refund of all items shown below, since I died to a glitch. Yes, including the items in the droppers, because either they had been moved into my inventory for the time being, or they were not in my droppers when I came back to my ship.
![2016-06-07_16 11 50](https://cloud.githubusercontent.com/assets/19827420/15912955/57b9055c-2d8c-11e6-9390-0da472df735c.png)
![2016-06-07_16 11 52](https://cloud.githubusercontent.com/assets/19827420/15912975/73e68bd2-2d8c-11e6-9b5e-a23d8b6b3e83.png)
![2016-06-07_16 11 55](https://cloud.githubusercontent.com/assets/19827420/15912979/73f182da-2d8c-11e6-98b0-94f5ff2c6fdf.png)
![2016-06-07_16 11 57](https://cloud.githubusercontent.com/assets/19827420/15912977/73eaae4c-2d8c-11e6-8ecb-c303801f40c4.png)
![2016-06-07_16 51 52](https://cloud.githubusercontent.com/assets/19827420/15912978/73eb91b8-2d8c-11e6-9208-05c0490e0fde.png)
![2016-06-07_16 52 02](https://cloud.githubusercontent.com/assets/19827420/15912976/73e926da-2d8c-11e6-939f-4335586bc9b8.png)

**Comment by awangatboo** [comment]
https://github.com/StarQuestMinecraft/StarQuestPublic/blob/master/README.md

This states that this is not the place for refund requests.  I will leave this open for a few days so it is easy for the mods to see the pic's.  It is up to the mods if they refund you or not.

**Comment by IggyW** [comment]
Arkkson752 (thats his name in discord, its something else in minecraft) who is a mod, told me to put the refund request here. I just followed his instruction.
