### ISSUE TITLE
Transporting potions across different servers

### ISSUE THREAD

**Issue by JC3371** [StarQuestMinecraft/StarQuestPublic#1017]
If a player has a potion in their inventory and they travel across servers, their inventory still gets wiped. 

This is how CrowkEngineer and JC3371 lost their inventory, which could not be refunded.

**Comment by awangatboo** [comment]
This has been brought back up to the Dev team.  From what I understand someone forgot to check-in some changes they made to the code so when they made the new plugin it was missing the code.

**Comment by martinjonsson01** [comment]
Did this problem occur with normal potions, splash potions, or both types of potions?

**Comment by JC3371** [comment]
Both types of potions

**Comment by martinjonsson01** [comment]
I believe I might have fixed it now, could you please try it again with just one potion of both types in your inventory? If you don't want to risk losing items again, tell me between what 2 servers this happened.

**Comment by JC3371** [comment]
This happened between the erilon planet and quillion space system.

**Comment by JC3371** [comment]
Looks like it has been fixed.....traveled out of planets a couple of times and have kept my inventory as well as potions. 

Thank you!!

**Comment by martinjonsson01** [comment]
Great. Thanks for testing it.
