### ISSUE TITLE
Cannot activate turret on some servers

### ISSUE THREAD

**Issue by BatFC** [StarQuestMinecraft/StarQuestPublic#1018]
Turret is not activating (newly placed turret sign not changing when clicked) on Arator, Tyder and Arator space servers. I know the turrets were built right because they activate just fine on Jurion.

**Comment by sergio-carli** [comment]
Yes this also happens to me.

**Comment by buba141** [comment]
I could not reproduce this on Tyder, but it does happen on Arator and in Arator space. Should be fixed after the next restart.

**Comment by GingerWalnut** [comment]
This is fixed
