### ISSUE TITLE
Miners Stopping Fall Damage When Nearby

### ISSUE THREAD

**Issue by Cutout1** [StarQuestMinecraft/StarQuestPublic#1020]
Usaid2002 had me tp over earlier today, and jumped off of a large cliff while miners were running near by. Flaammeer, his faction mate, said it was because of the miners. To test just set up a aminer and have it mine some stone or something, then jump off of something high nearby.

**Comment by AlinaFicalton** [comment]
its not that they give you an anti fall damage buff, its that they switch you in and out of creative rapidly as they mine, witch makes out invincible for vary small amounts of time, witch is why you took no fall dmg

**Comment by Cutout1** [comment]
Well regardless, that sounds like something that should be fixed.

**Comment by martinjonsson01** [comment]
This has been fixed.
