### ISSUE TITLE
Active Miners' furnaces not burning

### ISSUE THREAD

**Issue by Mindaugas3** [StarQuestMinecraft/StarQuestPublic#1022]
As title states, there's no legit way to indicate if a miner is running(other than see the block mining process itself)

**Comment by awangatboo** [comment]
This is not a bug that SQ can fix.  This is a Minecraft 1.9 issue.  Minecraft 1.9 set the value for a furnace to not burn if there was no substance in the furnace that is burning.  If you want this one fixed please go bug Mojang
