### ISSUE TITLE
Hoverpad to spawn in core space

### ISSUE THREAD

**Issue by 15l** [StarQuestMinecraft/StarQuestPublic#1023]
I was flying a hoverpad in core space and was randomly teleported back to Requiem, in my empires spawn

**Comment by Cutout1** [comment]
He still had all his items in his inventory. I teleported him back where he was.

**Comment by Consue** [comment]
the same thing happened to me, but I lost my ship

**Comment by Millibyte1** [comment]
Not enough info to repro
