### ISSUE TITLE
Inventory Wiped When Entering Xira

### ISSUE THREAD

**Issue by Cutout1** [StarQuestMinecraft/StarQuestPublic#1026]
Recently I have been getting my inventory wiped and my ship deleted a lot of times. At first, I thought it was from a known bug with splash potions, but that has turned out not to be the case. This most recent time, I exited Xira to go back to the rim, but when I tried to fly away from the atmosphere I was sent back to Xira (Shouldn't have flown diagonally, that's not the bug) Anyway, upon re-entry to Xira, I appeared up in the sky with no inventory or ship, and fell to my death. Here is a picture of my inventory right before it happened:
![2016-06-09_20 21 15](https://cloud.githubusercontent.com/assets/10093818/15953511/7957802c-2e80-11e6-93a0-50cdd53e26c2.png)

**Comment by Millibyte1** [comment]
Has this issue been resolved? I'm guessing this was from the first time I tried putting the new craft transfer system up, but want to make sure

**Comment by Cutout1** [comment]
I haven't had an issue with it recently.
