### ISSUE TITLE
Powertool/Block lagout glitch

### ISSUE THREAD

**Issue by Aven666** [StarQuestMinecraft/StarQuestPublic#1030]
I charged a lvl 3 power pick, pulled it out and started breaking down a wall on my base.  While I was doing this, the blocks were replacing themselves as fast as I could break them, leading me to believe that I was lagging.  However, when I typed in chat, my text came right up, so lag wasn't it.  So I broke more blocks and they were replacing themselves.  I thought I would try to break several different blocks instead of the same one over and over and hope they would eventually disappear but what ended up happening was the pick disappeared out of my inventory.  I went everywhere to try and find the pick and eventually found it still sitting in the charger.

Not sure if this is due to block lag, or if it's something to do with the pick itself.  Another possibility is I had just set up the charging station before I used it.

**Comment by awangatboo** [comment]
can you reproduce this?  I have never seen it.

**Comment by GingerWalnut** [comment]
This is probably just lag. If this still happens, please reopen/create a new report.
