### ISSUE TITLE
Wierd teleport in core space

### ISSUE THREAD

**Issue by Consue** [StarQuestMinecraft/StarQuestPublic#1031]
So i was going along in my ship and suddely I get teleported to the medical bay of Yav spawn, I do not have cords of when this happened. I did not louse mi inv but I think I lost my ship.

**Comment by awangatboo** [comment]
What system were you in.  What day and what time?  Hopefully if you provide these someone can look in the logs.

**Comment by Millibyte1** [comment]
Not enough info to repro
