### ISSUE TITLE
Quillion Gate 2 Teleportation Glitch 

### ISSUE THREAD

**Issue by JC3371** [StarQuestMinecraft/StarQuestPublic#1032]
Everytime anyone goes through the Quillion Gate 2, they get teleported all the way north in the core system. I've seen this happen to multiple people including myself.

**Comment by JC3371** [comment]
Sorry, this happens from every Quillion Gate. I entered from Quillion Gate 1 today and I found myself in the position I described above.

**Comment by QuietHelper** [comment]
This should be fixed now.
