### ISSUE TITLE
New Username, Chests Are Private To My Old One

### ISSUE THREAD

**Issue by Cariadd** [StarQuestMinecraft/StarQuestPublic#1033]
My old user is Cariadd, my new user is Treesus_The_Tree. One of my freighters cannot be reclaimed as i have private signs there and 2 of my chests have private signs to my old user.

**Comment by gregolegomonkey** [comment]
This is not a bug, and you are responsible for any issues that arise as a result of changing your username.  This is stated in the server rules, and your issue will likely not be fixed by staff.

**Comment by GingerWalnut** [comment]
^ and this might be fixed at the next restart.
