### ISSUE TITLE
Entering Xira sometimes spawns you in a mountain and never in your beachead.

### ISSUE THREAD

**Issue by APnaptime** [StarQuestMinecraft/StarQuestPublic#1039]
entering the planet spawns you underground in a mountain near the highlands, y is around 200, it seems to be able to happen from any direction.

**Comment by awangatboo** [comment]
I think they were going to work on this after the new ship transfer system was complete.

**Comment by Millibyte1** [comment]
Is this issue still occurring? It should be fixed with the new system due to the transfer cancellation feature
