### ISSUE TITLE
Power armor indicator 

### ISSUE THREAD

**Issue by BatFC** [StarQuestMinecraft/StarQuestPublic#1040]
My tier3 power armor armor indicator is showing wrong. I am wearing full tier3 power armor yet the armor indicator shows 5.5, it should be full 10.

![armor](https://cloud.githubusercontent.com/assets/7577409/16141195/ea5a4cdc-3493-11e6-8263-02e3700325b0.png)

I tried updating the armor by breaking blocks with them, taking damage while wearing. Armor updates but the armor indicator remains same at 5.5.

**Comment by mcdouble** [comment]
Same problem with tier 3 prot 4 for me

**Comment by JC3371** [comment]
I've seen this too. I think it has been tested that the armor is actually equivalent to full 10, but can't be changed to 10 bars as it is technically gold armor. Minecraft detects it as gold armor, but it still protects as if it is full diamond.

**Comment by Laserlance141** [comment]
Break dirt, not any other block, only dirt will update the armor, as once I do, it shows all 10 armor points

**Comment by BatFC** [comment]
Already did, I broke all kinds of blocks with the armor. Armor updates just fine (damage indicator disapears), just not showing correct armor indicator.

**Comment by GingerWalnut** [comment]
This should be fixed at the next restart, but if it isn't please reopen/ create a new bug
