### ISSUE TITLE
Lag-Related Autopilot glitching.

### ISSUE THREAD

**Issue by TacoLink** [StarQuestMinecraft/StarQuestPublic#1042]
(Thanks to Shady for reminding me to do this stuff and refunding)

So about 1:00PM(EST) on Xira,  I got into an SvS. I **autopiloted** to 'strafe' my opponent, and ended up glitching out of my ship, because the **ship's blocks moved without me, the player, inside**. It seems apparent that the detectionbox of the ship was also glitched, the ship kept attempting to put me in the same spot over and over, **leaving me suspended in air** until a ghast fireball hit me, forcing a ship release.

**It seems to be completely lag-related**, but my opponent was ALSO glitched in his ship in some manner.

**Comment by awangatboo** [comment]
Yes something like this happens with lag.  If the server is upgraded then things like this should go away.
