### ISSUE TITLE
Spawning in lava when entering Xira

### ISSUE THREAD

**Issue by Generaltyler1** [StarQuestMinecraft/StarQuestPublic#1043]
Entered Xira on the south east side, but instead of being in my ship, i spawned in lava. When Shady tried to load my ship, I ended up getting tped into the mountain.

additional note, when I was leaving Xira earlier today when my ship left the planet, I did not. And I proceeded to die from lava. But instead of respawning normally I got tped to my ship with my items

**Comment by awangatboo** [comment]
I think that Evan was going to make it with his new system to have ships spawn at the empire beachheads.  I could be wrong on this.

**Comment by Millibyte1** [comment]
Going to go ahead and close this since it should be fixed, feel free to reopen if the issue reappears
