### ISSUE TITLE
Jungle Log price discrepency

### ISSUE THREAD

**Issue by eventsbeyondme** [StarQuestMinecraft/StarQuestPublic#1045]
Jungle Logs report both /value and left clicking the sign at spawn as being worth 8.0 per block, but when you complete the transaction, you are given only 3.0 per block.
![2016-06-21_09 31 22](https://cloud.githubusercontent.com/assets/2521455/16233153/03836cf0-3793-11e6-9bae-ecd60e31b97e.png)
![2016-06-21_09 31 29](https://cloud.githubusercontent.com/assets/2521455/16233152/037fb9d4-3793-11e6-9e36-2b45c3093739.png)
![2016-06-21_09 31 36](https://cloud.githubusercontent.com/assets/2521455/16233151/0376d080-3793-11e6-99d8-e09774660ec0.png)
![2016-06-21_09 31 41](https://cloud.githubusercontent.com/assets/2521455/16233150/0373ee06-3793-11e6-81f1-762a5d831e57.png)

**Comment by eventsbeyondme** [comment]
is specific to jungle wood so far as I can tell, oak, dark oak, spruce and acacia all sell for 8.0

**Comment by Millibyte1** [comment]
Has this continued to occur?

**Comment by Millibyte1** [comment]
Seems to be fixed
