### ISSUE TITLE
Ship Atmospheric Failure and Random Flight Endowment.

### ISSUE THREAD

**Issue by oreomium** [StarQuestMinecraft/StarQuestPublic#1048]
EDIT: I discovered that my GitHub account was "Fishy111", so my Minecraft username is Oriomium.

Frankly, tonight has been an interesting night. But down to business:

A few days ago, my starship suffered two internal creeper explosions and failed to regen, meaning it was relatively wrecked, but somehow still flyable despite all of it's armor. Then, during a turn I suppose, it somehow became even more malformed when just a part of the ship turned or something. It was still flyable, so I decided to fly it to Quillion to MrNoty to see if he could repair it, or just scrap it, being a rather high-quality and expensive starship. Then, as I flew up to reach the atmosphere barrier of Erilon, it gave the normal messages of

[Alert] Leaving the atmosphere!
Preparing serverjump...

And then nothing happened. Whenever I tried to move, it said the same thing and was unable to move without repiloting, even though it was apparently still piloted. I had Cutout teleport over to have a look, and we found out that the droppers were empty. This starship held the 90% of OsculoErilon's resources and building materials. Cutout then told me to make this report after being unable to reload the ship or do anything else, and so then, after he left, and I went back to building with some of the materials I had in reserve, when I tapped the spacebar twice in rapid succession to try to sprint-leap from one place to another, I randomly found myself in flymode, but in survival. Cutout tp'd over again. I relogged and could no longer fly, fixing that problem.

Here is an approximate list of the items lost in the droppers:
- 40 stacks of Polished Andesite.
- 10 stacks of Polished Diorite.
- 108 stacks of Stone Bricks.
- 11 Iron Blocks.
- 100 stacks of Sugarcane. 
- 6 stacks of Acacia Wood Planks.

It is possible that there are more items that I may remember with time, but I assure you that I am completely honest in these item approximations. I understand if you do not wish to refund these glitch-lost items due to the lack of screenshot proof.

With hope of fixing,

~Oriomium

**Comment by awangatboo** [comment]
You need to talk to a mod on getting a refund

**Comment by Millibyte1** [comment]
This issue has been resolved aside from the refund
