### ISSUE TITLE
Arator 1 Gate - Server Jump Box

### ISSUE THREAD

**Issue by PatchyFox** [StarQuestMinecraft/StarQuestPublic#1049]
Hi there,

The Arator 1 Gate's server jump detection box is very displaced. Rather than flying directly into the "portal" to warp to Core Space, you must fly from the north, into the side of the gate to trigger a jump. 

Can this region please be corrected? 

Thanks,

**Comment by Millibyte1** [comment]
@Tongonto

**Comment by Millibyte1** [comment]
This has been fixed
