### ISSUE TITLE
Broken everything

### ISSUE THREAD

**Issue by ghost** [StarQuestMinecraft/StarQuestPublic#1051]
I was flying to Erilon from Quillon just fine in my world's ugliest ship contest winner and I flew into Erilon's atmosphere. I spawned on the ground, with no inventory, and no ship. I got my starter kit to block up to a ship to steal it, upon getting there, I realized that is illegal and went to break my tower up, but I fell and spawned on the other side of the planet.

**Comment by awangatboo** [comment]
ask a mod to help with a refund.  I was told by Ginger that Movecraft was broken on this planet.  He said he fixed it at the 2PM server reboot today.
