### ISSUE TITLE
Ships not working

### ISSUE THREAD

**Issue by JC3371** [StarQuestMinecraft/StarQuestPublic#1053]
After the 1.10 update, I've tried many times to pilot ships and I think the plugin itself is broken. When I've tried to put warship on a sign, it does not autofill my username below it.

**Comment by JC3371** [comment]
This is occurring on Erilon in Quillion System.

**Comment by JC3371** [comment]
Just got on to Starquest and ships are working again on Erilon. But Erilon itself needs a big fix.

**Comment by awangatboo** [comment]
What else on Erilon is wrong?  I was told by Ginger that he had to update movecraft on that server and after the 2pm restart today it should have been working.

**Comment by JC3371** [comment]
This is fixed. Thank you!
