### ISSUE TITLE
Chat kick issue

### ISSUE THREAD

**Issue by gregolegomonkey** [StarQuestMinecraft/StarQuestPublic#1054]
The cause of people being kicked due to global chat use is when a player says something that takes up two lines of chat, like the following example:

[GC][Colonist]gregolegomonkey: This is one line which will eventually
extend into another line

**Comment by Mindaugas3** [comment]
Mardos works OK for /l chat, gchat and rchat. People from other servers are experiencing kicks every 2 seconds.
Also seems like special characters like "." and "," cause higher probablity to be kicked in affected planets.

EDIT: Latest analysis suggests that staff/dev tags are the most affected by the issue.

**Comment by GingerWalnut** [comment]
This has been fixed.
