### ISSUE TITLE
Blocks Disappearing

### ISSUE THREAD

**Issue by mcdouble** [StarQuestMinecraft/StarQuestPublic#1055]
I tried using thrusters. I forgot to redetect before using it so it just kept piloting me down. Even after I went back and fixed that, it kept going with the "blocked by stained clay" until I relogged.

Also, thrusters create this insane glitch where blocks keep disappearing, but not ACTUALLY disappearing. It appears to be a visual thing, but it causes a lot of glitching into blocks and getting stuck. It won't stop, even on relog.

**Comment by martinjonsson01** [comment]
This has been resolved.
