### ISSUE TITLE
Bugged thrusters

### ISSUE THREAD

**Issue by Mindaugas3** [StarQuestMinecraft/StarQuestPublic#1056]
Once thrusters are used, they cannot be stopped and will just keep going.

Another issue is that thrusters mash blocks up and create a semi-visual glitch, players cannot fall through the corruped blocks that look like "air", but they get stuck and everything gets mashed up. That happens constantly and every second a new block disappears/reappears.

Prime testing has been conducted on Tyder by McD(Littlebro_OM)

**Comment by gregolegomonkey** [comment]
Thrusters also will not automatically turn off like autopilot does, when encountering a point where they cannot go any farther down.

**Comment by martinjonsson01** [comment]
All of these things should be resolved. Please comment if they've not been.
