### ISSUE TITLE
Ship Not Regening

### ISSUE THREAD

**Issue by GamingPlanet** [StarQuestMinecraft/StarQuestPublic#1057]
I had a run in with Jusa and I had to escape Xira so I took my ship and it got damged and it wont regen please fix

**Comment by awangatboo** [comment]
Was it damaged in Xira or in the core?  Was it right at the restart time?  If it was at the restart get a mod to help as there will not be a record as to what was damaged.

**Comment by GamingPlanet** [comment]
It was damaged in the core does it not regen if damaged in the core?

**Comment by GingerWalnut** [comment]
It sounds like you fled before the regen happened, and regen doesn't follow ships.
