### ISSUE TITLE
Erilon Crashes

### ISSUE THREAD

**Issue by JC3371** [StarQuestMinecraft/StarQuestPublic#1058]
I am currently on Erilon and everything seems to be working. The only problem is that whenever someone puts a decimal or types too much in chat at once, everyone in Erilon gets kicked.

**Comment by awangatboo** [comment]
That happens on Jurion as well.  I think that is the chat issue that they mentioned on the front page.

**Comment by JC3371** [comment]
Do you have any idea when this will be fixed?

**Comment by JC3371** [comment]
I honestly think it would be fair to shut down the core till these bugs are resolved. Just as a thought.

**Comment by JC3371** [comment]
I do not think the chat issue occurs when I am chatting, but when other people chat and add a decimal or chat too much at once.

**Comment by JC3371** [comment]
I have seen someone on Erilon try to fly out of the atmosphere and they got stuck. I'm really not sure what is going on in Erilon.

**Comment by ghost** [comment]
Everything is broken on erilon

**Comment by JC3371** [comment]
So, when will this be fixed then? It's been a pretty long time since this happened and there has been no attempt to fix.

**Comment by StarQuestMinecraft** [comment]
Just because there has been no reply here doesn't mean there has been no
attempt to fix. They're working on it. It's a hard one.

**Comment by JC3371** [comment]
Ok. Sorry for the misconception. Good luck guys!

**Comment by GingerWalnut** [comment]
This has been fixed.
