### ISSUE TITLE
Power Armor acting as regular gold armor?

### ISSUE THREAD

**Issue by godeacs1996** [StarQuestMinecraft/StarQuestPublic#1061]
Every so often, my protection IV power armor will glitch out and act as if it's regular gold armor, in that it loses duration as if it were gold armor. This has happened in two ways- fighting creepers that blow up and hurt the armor and also sitting on a cactus to grind repair. 

I will note that if I re-log a few times, it eventually corrects, but it's still something we should fix before the mods have to go around refunding prot 4 gear.

**Comment by BatFC** [comment]
Even after updating the armor? When the armor is losing duration try breaking blocks with them, it should update.

**Comment by GingerWalnut** [comment]
This should be fixed at the next restart, but if it isn't please reopen/ create a new bug
