### ISSUE TITLE
Dutymode wiping inventory

### ISSUE THREAD

**Issue by godeacs1996** [StarQuestMinecraft/StarQuestPublic#1062]
I was refunding a few items to a factionmate who died to a Xira issue a few days ago and when I left dutymode, my inventory wiped. I tried re-logging, re-duty'ing and nothing got it back. I ended up just refunding my items but not my armor because I've been refunding so much stuff lately to everyone. I'll grind the armor back myself, but dutymode is iffy again.

**Comment by martinjonsson01** [comment]
Did you have any potions or banners in your inventory before you went into duty? @godeacs1996

**Comment by GingerWalnut** [comment]
I just tested this again, and I'm not having this issue anymore. If it occurs again, please make another bug report or reopen this one.
