### ISSUE TITLE
Cannon firing offset

### ISSUE THREAD

**Issue by gregolegomonkey** [StarQuestMinecraft/StarQuestPublic#1064]
When fired, the cannon shot traveled straight... until it hit a stonebrick wall, where it destroyed the block to the right of where it's impact should have been.  The cannon was not able to penetrate deeper, although the stonebrick did regenerate.  Keep in mind that stonebrick doesn't usually get destroyed from a single cannon shot.  I was using a yellow cannon, on a freighter, at the Osculo Quillon base, test firing it against a hangar wall at almost point blank range.

**Comment by awangatboo** [comment]
Not sure who to give this one to.  I hear that they might be reworking lots of weapons.  If they do I will assign this one to the person working on that.  That is if I know who it is.

**Comment by Millibyte1** [comment]
Is this still occurring?

**Comment by Millibyte1** [comment]
No longer occurring with the new cannons
