### ISSUE TITLE
Quillon borked?

### ISSUE THREAD

**Issue by gregolegomonkey** [StarQuestMinecraft/StarQuestPublic#1067]
I flew into Quillon in a Warship, carrying Lightning321.  When I entered the atmosphere, I was teleported back into space without an inventory, while Lightning and my ship stayed on Quillon.  When I suffocated in space, I was briefly teleported back to my cryospawn on Quillon (at the Quillon Osculo base), and was then teleported to the Requiem spawnship.  I ended up suffocating myself in space again, only for the exact same thing to happen.
Ginger_Walnut attempted to teleport me back to my ship/Lightning on Quillon, but every time he tried, I was instantly teleported back to my location that I had been teleported from on the spawnship.  Ginger eventually might have restarted the Quillon server (I'm not sure if this happened, or even if the placement in the story is correct), and tried teleporting me again, only to have it fail.
Ginger then built a small 101 block carpet outside of Quillon (in space), and tried to pilot it, with myself on it, into Quillon, but was unable to due to the fact that he was Aratori, and I was Req.  I then tried to take the ship into Quillon, only for the ship and Ginger to enter Quillon, and for myself, inventoryless, to be left in space again to suffocate.
Eventually, Ginger succeeded in getting me on Quill for more then five seconds, at which point I was teleported to my cryopod.  I don't exactly remember what Ginger did to get it to work.

Also- my ship is intact, and all other problems were solved- except that of my inventory loss, which had no items in it that couldn't be ground out in 15 minutes.

**Comment by gregolegomonkey** [comment]
#1073 Seems to be the same issue.

**Comment by awangatboo** [comment]
Giving this one to Ginger as he has already worked with it.
