### ISSUE TITLE
I can't tame Wabbits

### ISSUE THREAD

**Issue by gregolegomonkey** [StarQuestMinecraft/StarQuestPublic#1068]
When right clicking on a rabbit with a carrot, the rabbit is not tamed with any sort of tag over its head, and also disappears upon relogging.

**Comment by awangatboo** [comment]
I think this is handeled not by plugins but by the spigot server itself.  Do you know if this was before or after the move that the server did to 1.10?

**Comment by gregolegomonkey** [comment]
After the move to 1.10.

**Comment by GingerWalnut** [comment]
This should be fixed at the next restart
