### ISSUE TITLE
Pickaxe wiped

### ISSUE THREAD

**Issue by mcdouble** [StarQuestMinecraft/StarQuestPublic#1069]
Sometime within the last hour or 2 I flew to Tyder from Xira. I took the middle gate when looking at core system dynmap. My pickaxe went down to just Efficiency 4, and full durability. I have a screenshot to prove what it used to be, and it includes a name which makes it even more valid.

http://imgur.com/DA1x0KO

**Comment by GingerWalnut** [comment]
Anyone else have any trouble with something like this?

**Comment by Millibyte1** [comment]
Is this still occurring?
