### ISSUE TITLE
Can't Pick Up Items On Yavar

### ISSUE THREAD

**Issue by Hockeyson48** [StarQuestMinecraft/StarQuestPublic#1070]
So aparently on Yavar, I am unable to pick up items that I harvest from farming. When I try to farm them (as shown below) they wont pick up on my inventory. This is seen specifically when I harvest potatoes, wheat, and carrots. 

http://imgur.com/gKLsJo4

I don't think it is client lag because I also had MollyGrue test it, and she is unable to pick up the items either. A few people on Yavar are also having this problem and it is a bit unfair to see other empires that are having no trouble using their farms, while we have to wait for server side issues to fix ours. I don't mean to be rude in the least, and I hope that the issue is resolved whenever possible. Thanks

**Comment by awangatboo** [comment]
Is this still an issue or was something just wrong on that day?

**Comment by Hockeyson48** [comment]
It is still an ongoing problem for me, but I am not sure about others. I have not been on the server as much because I waiting for the glitch to get fixed, so I have not heard about it from any other players.

**Comment by GingerWalnut** [comment]
Just tested this, not having this problem. If it is till happening, please reopen/make a new report.
