### ISSUE TITLE
Entering Radawii makes the ship enter without me.

### ISSUE THREAD

**Issue by ghost** [StarQuestMinecraft/StarQuestPublic#1073]
I tried it 4 times, all with different ships.
It seems like the detection fails, and I end up suffocating in space with nothing on me (e.g. wipes out my inventory or drops items. I dunno). I have absolutely no idea what happens to the items.
I don't have a crypod, so I spawned in the Yavari SpawnShip for about 2 secs, then back to the tutorial.
2 of the times were with atleast one other player - they did enter, I didn't. Specifically in Radawii.
I'll try this on another planet later.
This is **extremely** urgent. I lost my ship, and another fresh ship to get there to get to my ship. I'll update it later.
Thanks.

**Comment by Millibyte1** [comment]
Is this issue still occurring? Were you the pilot of the ship, or a passenger?
