### ISSUE TITLE
[moreusers]

### ISSUE THREAD

**Issue by JC3371** [StarQuestMinecraft/StarQuestPublic#1074]
Today, I noticed that the [moreusers] sign does not work on doors and chests. Has this been removed on purpose or has it not been added back to starquest 4.0?

**Comment by awangatboo** [comment]
I thought there was a space in it.  [more users].  Also, I know from my work on a home server that is part of the locket plugin.

**Comment by JC3371** [comment]
Ok, i will try. I remember it as [moreusers]

**Comment by JC3371** [comment]
Just tried it. There has to be a space. Thanks for your help!
