### ISSUE TITLE
Teleported back into space with nothing

### ISSUE THREAD

**Issue by Creepopolous** [StarQuestMinecraft/StarQuestPublic#1075]
I turned on the thrusters on my ship for the first time on Quillion In seconds, Tardis339 and I were in space. We didn't turn those thrusters off in space(Tardis did when she was back on the freighter on Quillion). Once I moved the ship a block north, it teleported us back to Quillion, as it usually does. But this time, we went back to space! Quillion barely loaded the terrain when we went back! Now we were in space, with no ship and no items. We slowly suffocated. I was back on Erilon, and Tardis was at the ship. Not surprisingly, she had none of her items.

**Comment by Creepopolous** [comment]
Ah, and when Molly tp'd me back to Quillion, I was only there for a flash, and Tardis and I got tp'd back to REQ spawn. Molly denied that she teleported us to the Sunflare.

**Comment by mcdouble** [comment]
There's a server transfer bug that many others have experienced. I'm getting others to write their "stories" here.

**Comment by GamingPlanet** [comment]
Before this bug was announced but was still a thing I was giving somebody a ride and when I entered Quillon I fell out of my ship I don't care about the stuff I would just like my ship back and with at least 4 or 5 droppers full of cobblestone witch was the freighters cargo Thanks for your Help

**Comment by mcdouble** [comment]
Similar to this issue, I am experiencing an issue with server transfers where it doesn't allow me to exit into Arator space. I was going to go to Arator to mine, and my pickaxe actually got wiped to plain :(

**Comment by Creepopolous** [comment]
#1067 seems to be very similar to this.
