### ISSUE TITLE
Private Sign glitch

### ISSUE THREAD

**Issue by Starsword7** [StarQuestMinecraft/StarQuestPublic#1076]
when i add my fried  bluelightning900  to a private sign, he cannot open the chest

on the sign, it only shows bluelightning90  - the last 0 doesn't fit

additionally, when he puts a private sign on something, he cannot access that container.
when i right click on the sign, it says: this container is claimed by bluelightning900

**Comment by awangatboo** [comment]
The server has never used lockette with UUID enabled.  Becasue of that players with long names have this issue.  It is not a bad idea if one of the staff tested lockette with UUID enabled.

**Comment by gregolegomonkey** [comment]
If you are both in a faction, put the faction's full name, including caps, special characters, etc. in brackets.  If you're not in the same faction, and are in a relatively "safe" area, put [Everyone] on the sign instead; either should give him access.

**Comment by Starsword7** [comment]
thank you

**Comment by GingerWalnut** [comment]
This should be fixed at the next restart
