### ISSUE TITLE
Certain block types occasionally disappearing from ships during transfer

### ISSUE THREAD

**Issue by BlockBuster019** [StarQuestMinecraft/StarQuestPublic#1077]
Hi i'm block, and when i left the orbit of mardos yesterday my ships inside got deleted, with that i mean my droppers got deleted with my cargo load in them, my furnaces stairs signs crafting table, everything but wool and slabs. After my realization i was stuck in space i tried to reach another ship for a sign, but because i didn't have a spacesuit i died.. I'm at spawn now without my inventory and without my ship, if a mod or admin would come on and help me with this that would be great!

**Comment by Millibyte1** [comment]
Finally fixed
