### ISSUE TITLE
Getting sucked back to planet when attempting to leave

### ISSUE THREAD

**Issue by AnonymousLemur** [StarQuestMinecraft/StarQuestPublic#1087]
Alright, so on the planet Quillion there is a major bug that prevents everyone on it from leaving. Once you go to y:200 or so, you leave into space. However, moving one block away from the planet and/or autopiloting away just makes it so you warp back to Quillion, and as far as I know, there is no way to avoid this.

**Comment by Millibyte1** [comment]
Closed as duplicate.

You can avoid it by travelling South or having a mod load your ship outside of the planet's hitbox.

**Comment by AnonymousLemur** [comment]
I can't go south when attempting to leave the planet. The planet is south of me, so heading that way just brings me closer to it.
