### ISSUE TITLE
Beavers do weird stuff during autosaves

### ISSUE THREAD

**Issue by TreySoWavvy** [StarQuestMinecraft/StarQuestPublic#1090]
Alright Evan this is a duplication Bug that is VERY specific to a set of events prior. My freighter was in orbit around Jurion Space, and an Auto Save activated. From that i flew to spawn, and accidentally died from fall damage (should fix that :P). Now i waited 20 seconds and clicked Respawn, and when i did something happened. I was teleported to my freighter In Jurion Space as if I NEVER died, like my player data was rolled back to the Auto Save {which it was}. I got suspicious and flew back to spawn yet again, and i found out my ship had been duplicated. with all the items in it perfect condition. When i entered the ship, nothing happened it was almost perfect, as if someone did //copy and //paste. This bug is NOT a normal one, seeing as though you have to have the same timing and events as I did. Im just  letting you know, and for proof the ships are still at spawn screenshots coming soon!

**Comment by mcdouble** [comment]
This MIGHT be related to the bug I experienced in 'Tonight's Beaver Adventure". I don't remember if there was an auto save at the time, but its completely possible. Maybe somebody could poke around and give that a look, since I did give a time in my report.

**Comment by Millibyte1** [comment]
Is this still occurring? Movecraft is significantly more stable now, it's possible whatever weird thing caused this has been resolved

**Comment by Millibyte1** [comment]
No repro
