### ISSUE TITLE
Turrets kicking players

### ISSUE THREAD

**Issue by Mindaugas3** [StarQuestMinecraft/StarQuestPublic#1093]
I was going to test turrets with custom rounds, but apparently they kick you the moment you enter them. Tested them with and without ammunition and custom shots, the program kicks you out of turret the moment you enter them.

Tests have been conducted on Mardos. If that was intentional, please reconsider it - we want to have our own shooting range/training areas.

**Comment by buba141** [comment]
I could not reproduce this bug on Mardos, it was probably fixed when I redesigned part of SQTurrets.
