### ISSUE TITLE
Planet/System transfers not working

### ISSUE THREAD

**Issue by WatchmanPhileo** [StarQuestMinecraft/StarQuestPublic#1094]
Hello, so most of the day July 7th into today July 8th planet/server transfers in the entire Arator system are not working and at this moment are still currently down. Five to six players were trapped in space yesterday and tried multiple times to enter the various planets in the system. The command "Alert: Entering Atmosphere" would appear but then the ship would still be floating in space. This problem was also happening at the warp gates/system transfer points. To give perhaps another helpful detail, people were able to fly out of a planet but the return journey was the issue and was inoperable. Thanks for your time.

**Comment by BatFC** [comment]
Leaving Xira is impossible atm for the same reason.

**Comment by GingerWalnut** [comment]
This should be fixed now.
