### ISSUE TITLE
Dutymode Wipes Inventory

### ISSUE THREAD

**Issue by godeacs1996** [StarQuestMinecraft/StarQuestPublic#1095]
Went to help two guys in Arator space; did /duty, helped out, unduty'd and my inventory on Jurion was gone. Still had my 28 enchanting levels though. From there I tried to duty/un-duty again, tried logging out and back in again, none of it worked.

**Comment by Millibyte1** [comment]
Molly and I both had the same issue yesterday

**Comment by GingerWalnut** [comment]
I just tested, and I'm not having this issue anymore. if it returns, please make another bug report or reopen this one.
