### ISSUE TITLE
Players sometimes not properly teleported during transfer

### ISSUE THREAD

**Issue by WatchmanPhileo** [StarQuestMinecraft/StarQuestPublic#1096]
Hello, When i flew one of my ships out of Tyder a very weird glitch occured. After passing through the atmosphere, I found myself on a different ship of mine in space. I have not moved or piloted another ship since. And was wondering if someone could assist me in making sure that my ship on Tyder was not deleted in the process.

**Comment by Millibyte1** [comment]
Was this at/around the time of the midnight server restart?

**Comment by Millibyte1** [comment]
Should be fixed with the next restart
