### ISSUE TITLE
Colored Docking Tube Perms

### ISSUE THREAD

**Issue by Estenoor** [StarQuestMinecraft/StarQuestPublic#1097]
As of 11:27 AM on 7/9/2016 I do not have the perms to colored docking tubes and I have had them since the end of 2.0. I made an earlier notice of this when 4.0 started up, but eventually I lost the perms again. At the time I merely thought that the plugin was removed entirely, but when I saw the post made by dan14941 about vertical docking tubes and how it looked if you had colored docking tube perms I saw that they were not removed. My ign in SamzFerg.

-Sam Ferguson

**Comment by awangatboo** [comment]
Did you get the perms back?

**Comment by Estenoor** [comment]
Yes I did. Ginger_Walnut helped me out.

Sam Ferguson
NB Blitz Team Member
