### ISSUE TITLE
Tamed animals spawning in wilderness?

### ISSUE THREAD

**Issue by gregolegomonkey** [StarQuestMinecraft/StarQuestPublic#1098]
Found two sheep in group, one sheep in another, and three rabbits in a third.  The two sheep were "pushed together" in the same air space when I found them, the same as how they would normally spawn.  This was on Quillon.

Also...
![2016-07-09_21 44 25](https://cloud.githubusercontent.com/assets/7875618/16711253/9da4f340-461f-11e6-9127-65d5d2a476c3.png)

**Comment by Millibyte1** [comment]
@GingerWalnut guess you did it to all mobs on the world

**Comment by gregolegomonkey** [comment]
#1068

**Comment by GingerWalnut** [comment]
Yeah, this isn't really a bug, its just that I messed something up. You can kill the sheep and rabbits, their just a side effect.

**Comment by gregolegomonkey** [comment]
Also... all my minecarts were changed to Space Beavers, including regular and hopper varieties.
