### ISSUE TITLE
Planet/System transfers not working from tyder into space for larger ships

### ISSUE THREAD

**Issue by WatchmanPhileo** [StarQuestMinecraft/StarQuestPublic#1100]
Hello, I have a rather large ship which flies but has been unable to leave tyder. Every time I try to leave the planet all I get is the alert and nothing happens.

**Comment by Millibyte1** [comment]
It couldn't find a suitable location for your ship to spawn at. I'm going to raise the max attempts at finding an unobstructed location to something insanely high effective next restart, which should fix this
