### ISSUE TITLE
Stargate not working at all

### ISSUE THREAD

**Issue by parrylost** [StarQuestMinecraft/StarQuestPublic#1102]
Hi, not sure if this is the same issue / related to 1091, but since I don't know I figured it's better to start a new thread to be on the safe side: **At present, stargates are not working at all.** To be more specific, flying up to one of the stargates from the Core system to Yavar gives me a message in chat reading "Entering slipgate to YavarSystem!" and "Preparing server jump..." after which _nothing happens_. Well, _actually_, my ship seems to become un-controllable, with no further messages or warnings -- I become unable to turn or move it either with the clock or with AP; to gain the ability to do so again I have to _first _release_ the ship_ (even though I lose the ability to control it, it doesn't actually get _released_ on its own until I do this) and then pilot it again (full re-detection does not seem necessary, it gets re-detected as a previously saved class just fine), after which I can control it again; sometimes I have to do this several times in order to move far enough away from the gate to be able to fly normally, because until I'm far enough away the gate tries (and fails miserably) to teleport my ship to Yavar with every move, with the same results as above.

I've tried this at two of the gates between Core and Yavar so far. Still trapped in the Core system!

**Comment by Millibyte1** [comment]
A potential fix for this should be implemented at the noon restart
