### ISSUE TITLE
Planet/System transfers not working from tyder into space for larger ships

### ISSUE THREAD

**Issue by WatchmanPhileo** [StarQuestMinecraft/StarQuestPublic#1103]
Hello again, I apologize for posting this again but I logged on today after the restart as was suggested in the response to my last ticket. I attempted to fly a larger ship 1742 blocks in total out of tyder's atmosphere. I hit the same problem as before. I received the Alert stating that i was leaving the atmosphere and then nothing. Every time i get the alert though and it doesn't jump me or the ship i find that I am still in control of the ship but the ship will not move. I am however able to pilot my freighter ship that has significantly less blocks. Thanks for you time and assistance with this glitch.

**Comment by Millibyte1** [comment]
Would you mind reattempting this?

**Comment by WatchmanPhileo** [comment]
Hey evan,

I attempted it again today 7/12 at 5:05 pm and got the same result

**Comment by WatchmanPhileo** [comment]
Hey evan, 
As of 7/12 today none of my ships are now able to leave the planet tyder.

**Comment by mcdouble** [comment]
7/12 10:30 EST I've tried entering my freighter into Tyder from all 4 angles and won't let me in. "Preparing server jump..." - no jump

Not to be rude, but I'd really appreciate this bug taking a front seat priority because its literally worse than getting beavered. Getting beavered, you can still walk on the planet and move. But if you can't jump at all its so miserable.

**Comment by WatchmanPhileo** [comment]
Hello,
As of 10;02 today i was able to jump my freighter from tyder into space. I think one of the problems that is occurring with jumps is space debris. I had gingerwalnut delete a number of duplicate ships of mine that had spawned in tyder space near the planet. I made a sugestion to her that if some sort of stained glass ring was placed around the planet it could be used as an indicator of a derelict free zone as in a place where people are not allowed to just leave there ships in order to increase the maximium amount of area for planet entry and planet exiting. I could be wrong but space clutter may be more of a problem to server transfers than is realized.

**Comment by Millibyte1** [comment]
AratorSystem seems to have been operating with an old jar, this should be fixed at the next restart along with the duping bugs. Please PM me and/or open another issue tomorrow if that doesn't fix. Thanks
