### ISSUE TITLE
Cryopods dont work

### ISSUE THREAD

**Issue by GamingPlanet** [StarQuestMinecraft/StarQuestPublic#1104]
Multiple times I have died with an active cryopod and I have ended up at spawn they are bugged and I would like it fixed as soon as you have time Thanks Bye

**Comment by Millibyte1** [comment]
Was your active cryo on your ship? Cryos on ships are notoriously buggy

**Comment by awangatboo** [comment]
always run the /cryocheck command to see where your cryopod is set to.

**Comment by Millibyte1** [comment]
Closing as too ambiguous to repro
