### ISSUE TITLE
Faction Claiming

### ISSUE THREAD

**Issue by QuantumVelocity** [StarQuestMinecraft/StarQuestPublic#1113]
I've just started my own faction, I've put in 20K and I have 10 power.
However, I'm unable to claim any land, the server keeps telling me, "You cannot claim territory of factions in your empire". I'm not near anyone's faction, build or ship shield, even my own ship's. I've asked Ginger, Molly and Deacs, but none of them can tell what's wrong. Therefore, I've considered this to be some kind of perms bug where I can't claim in open wilderness. 

I'm using /f claim o and I'm the leader of my own faction.

**Comment by GingerWalnut** [comment]
This should be fixed
