### ISSUE TITLE
Skeletons

### ISSUE THREAD

**Issue by mcdouble** [StarQuestMinecraft/StarQuestPublic#1114]
Wither skeletons have been replaced by regular skeletons on xira. When readded, please take away the flame bows... regular bows do fine. There's enough fire on Xira

**Comment by awangatboo** [comment]
Someone said they were working today.  Please confirm.  I have not been to Xira in +4 weeks.

**Comment by Denyol** [comment]
Confirmed, these have been reverted to Whither Skeletons.
