### ISSUE TITLE
Torches and ships bug

### ISSUE THREAD

**Issue by ThePieGuy19** [StarQuestMinecraft/StarQuestPublic#1116]
My big freighter wouldn't live the atmosphere but replicas would. The replicas didn't have torches in them so me and molly were sitting there and we discovered that if torches were on the ship, it wouldn't let me leave, but when i removed them i could leave.

**Comment by awangatboo** [comment]
Nice find

**Comment by Millibyte1** [comment]
Is this still occurring? I fixed an issue last night shortly after you opened with large ships being too large for the datatype they were stored in the DB with, so it's possible that it was just the adding/removing of blocks that changed it

**Comment by Millibyte1** [comment]
Going to go ahead and close this for no repro, feel free to reopen if the issue persists.
