### ISSUE TITLE
Ship Duplication 

### ISSUE THREAD

**Issue by JC3371** [StarQuestMinecraft/StarQuestPublic#1119]
My ship got duplicated after leaving Erilon. I have a screenshot attached below.

-JC3371
![2016-07-15_08 49 22](https://cloud.githubusercontent.com/assets/19299597/16880294/6ffaba80-4a69-11e6-92e0-366993706b3a.png)

**Comment by Millibyte1** [comment]
One of those was loaded by me when testing last night, forgot to WE it out.
