### ISSUE TITLE
MachinaDrill not drilling block types

### ISSUE THREAD

**Issue by awangatboo** [StarQuestMinecraft/StarQuestPublic#112]
I think this should be a very low priority on this bug but here it is.

MachinaDrill does not drill through stained clay.  The MachinaDrill does not seam to understand stained clay.  This was most easily seen on Luna Inaris.  Trying to dill there would fail every time you hit stained clay.

**Comment by Thedrew655** [comment]
Very Old Post that should've been closed

**Comment by awangatboo** [comment]
There is a newer version of the plugin that does get new block types.

**Comment by Thedrew655** [comment]
Is there anyway we can fix this?

**Comment by awangatboo** [comment]
All that could be done is get the new plugin and test.

**Comment by Evancooldude** [comment]
Has this been fixed?

**Comment by awangatboo** [comment]
I know the current version of this has not changed on the server.  I also know that it looks like the plugin that handles all the Machinacraft stuff is back to inactive.

**Comment by awangatboo** [comment]
Closing all bugs in preparation for SQ 4.0.
