### ISSUE TITLE
Contents of storage crates being deleted during planet transfers

### ISSUE THREAD

**Issue by WatchmanPhileo** [StarQuestMinecraft/StarQuestPublic#1120]
Hello, just wanted to report that during planet transfers items being stored in crates are deleted. This is problematic as the idea of having a freighter is pretty much pointless if this glitch occurs.

**Comment by Millibyte1** [comment]
Will fix as soon as I can

**Comment by WatchmanPhileo** [comment]
Thanks Evan your the best! I demonstrated the issue to go_deacs. He replaced the lost items but can attest as to the problem.
