### ISSUE TITLE
Sq tech drills

### ISSUE THREAD

**Issue by ghost** [StarQuestMinecraft/StarQuestPublic#1121]
You cant access the gui of a drill once it is activated.

**Comment by mcdouble** [comment]
Testing right now with dev

**Comment by Denyol** [comment]
Ok the issue has been located and will be fixed soon.
It happens on the first time when activating, breaking the lapiz and replacing it seems to fix the issue.

**Comment by mcdouble** [comment]
@dan14941 I did some further testing. Breaking and replacing the lapis block doesn't work 100% of the time. I noticed that the drill sometimes kept going a little bit after the lapis was broken, and then sometimes either carried on from before the lapis was broken, or continued going immediately as it was placed back down.

**Comment by Denyol** [comment]
Hello, has anyone had this issue come up again, since 2 days ago. After my testing of a newer plugin version this bug seems to be non-existant anymore, I will be closing this issue in a week if this bug is not reported here again.

**Comment by Michael-Fragano** [comment]
I just tried out a drill a few minuted ago and It happened to me too.

**Comment by Denyol** [comment]
I believe this has been fixed with the latest SQTech update.
