### ISSUE TITLE
SQ Tech Breaks on server resets

### ISSUE THREAD

**Issue by PatchyFox** [StarQuestMinecraft/StarQuestPublic#1122]
Hi,

I know the plugin is new - just reporting a current pitfall.

After the two daily server resets, the SQ Tech GUI block breaks, and any saved settings are lost. This means that after EVERY reset, we'll have to reconfigure all our machines (not to mention, we'll have to break the lapis and replace it to redetect). 

This also makes mechanics like storing energy in generators overnight impossible. Players MUST expend that energy into drills or tools, or they will lose it at reset.

Thanks,

**Comment by ghost** [comment]
Yup

**Comment by GingerWalnut** [comment]
This should be fixed
