### ISSUE TITLE
SQ Tech - Generators not accepting fuel on main GUI

### ISSUE THREAD

**Issue by PatchyFox** [StarQuestMinecraft/StarQuestPublic#1123]
Hi,

I know it's new. Just reporting things as I find them.

Generators currently do not accept fuel in the main GUI Fuel Slot. They MUST be fed with an import, effectively requiring a full set-up of an Import, a conversion, and an export to work. This makes for a frustrating experience of setting up three machines every time you want to charge a tool, and is also fairly expensive. 

If this is expected and intended, why does the Generator GUI even have a fuel slot at all?

Thanks,

**Comment by GingerWalnut** [comment]
They do except fuel in the main gui fuel slot, its just sometimes that when you put fuel into it it doesn't collect it properly. Theres not a ton I can do about it to make it work every single time, but I can do some work arounds.

**Comment by GingerWalnut** [comment]
I found a way to fix this
