### ISSUE TITLE
SQ Tech - Settings lost if machine set-up broken 

### ISSUE THREAD

**Issue by PatchyFox** [StarQuestMinecraft/StarQuestPublic#1124]
Hi, 

Just reporting things as I discover them.

When using SQ Tech machines - generator, charger - if any block in the actual machine is destroyed (glass from the side of a charger, for example) the entire machine is bricked, and all of its settings are wiped. Obviously, players should avoid breaking the structure of the machine, but because the energy stored in the machine would also be lost with a brick, the margin for accidents could become very costly. This also likely means that if an explosion occurs and destroys structure blocks, all energy in the machine is also lost.

I'm curious to test what happens if a ship flies through a pipe that's also being used as an energy door. The blocks would be deleted/interrupted - would that brick both machines on the ends, or just interrupt the flow?

Thanks,

**Comment by GingerWalnut** [comment]
This is kinda intended as players could store the energy in a 1x1x1 space while it might have been ment to be stored in a 2x2x3 space.
