### ISSUE TITLE
SQ Tech - Fuel Consumption Concerns

### ISSUE THREAD

**Issue by PatchyFox** [StarQuestMinecraft/StarQuestPublic#1125]
Hey there,

Just reporting things as I find them. 

With SQ Tech imports/exports regarding energy sources to a generator, the fuel source is consumed very quickly, rather than at the rate of expenditure. This is incredibly inconvenient, because it means if your UI is wiped (through destruction, server restart, etc.) the fuel, and the energy, are both lost forever. 

Wondering if there's a way for you to make energy imports/exports utilize a single energy source at a time, rather than packets of 16. 

Thanks,

**Comment by GingerWalnut** [comment]
This isn't a bug report, but, I will make the import/export system for generators a bit smarter.
