### ISSUE TITLE
Mob spawning

### ISSUE THREAD

**Issue by ghost** [StarQuestMinecraft/StarQuestPublic#1126]
On my base Quillon, I've noticed that mobs keep spawning in fully lit rooms. Is anyone else seeing this happen?

**Comment by ghost** [comment]
Also mobs are spawning inside blocks.

**Comment by awangatboo** [comment]
I have seen an issue where mobs will spawn in a room that looks fully lit but if you hit F3 and look at the light level it turns out the server thinks it is dark.  If this is the case just re-place your light blocks.  That has always fixed it with me.

**Comment by Millibyte1** [comment]
This is a bug with 1.10 vanilla
