### ISSUE TITLE
New Strategy

### ISSUE THREAD

**Issue by mcdouble** [StarQuestMinecraft/StarQuestPublic#1127]
Beavers are targeting ship signs now ;/

**Comment by BatFC** [comment]
Targeting shipsigns as in after serverjump your shipsign pops off. If you are still inside the protection WG of planet/gate you will not be able to place the sign back and be stuck in your ship.

**Comment by mcdouble** [comment]
Targeting many, many signs now.

**Comment by Mindaugas3** [comment]
Yep. Signs randomly pop off not during transfers, but even when autopiloting.

**Comment by Millibyte1** [comment]
Is this happening only when it's automatically detected your ship? If not, transfer probably isn't the issue. I'm away for the week so @martinjonsson might be able to look into this

**Comment by Mindaugas3** [comment]
It is happenning during the transfers mainly. Sings are "built" before a wall(wool, clay, dropper, whatever could support the sign) and then it just drops off because it doesn't have a supporting block.

**Comment by Millibyte1** [comment]
There's code that's supposed to prevent that already, and this hasn't been happening in the past with it in place, strange. Is this exclusively ship signs?

**Comment by Millibyte1** [comment]
Also see #1083

**Comment by Mindaugas3** [comment]
Update - signs are probably removed prior to transfer to another server.
That's how my ship sign vanished on my way back home.

**Comment by BatFC** [comment]
This bug is petty much exclusive to ship signs and the other signs touching the ship sign if you have any and mainly happens on stargate transfer in my case. All the signs pop off (not disappear).

**Comment by Millibyte1** [comment]
Is this still occurring? Are the signs attached to the adjacent signs, or to other blocks?

**Comment by BatFC** [comment]
Yes, this is still occurring (as of Jul 29th). Sometimes, the signs that are touching the shipsign (they are adjacent and not touching the block that shipsign is on) also pops off. 

P.S. Recently the helm sign is also popping off by itself.

**Comment by Millibyte1** [comment]
Still?
