### ISSUE TITLE
Gold Smelting Multiplier

### ISSUE THREAD

**Issue by Stilettos-anda45** [StarQuestMinecraft/StarQuestPublic#1129]
When I smelted 50 gold ore on Arator, I ended up collecting 70 gold ingots. I had a Fortune II Hammer II Power Tool in my hotbar at the time.  Is this an intended multiplier effect or a bug?

**Comment by martinjonsson01** [comment]
I believe this is because of MCMMO, it can increase the amount of ingots you get from smelting ores.

**Comment by Mindaugas3** [comment]
Definitely MCMMO multiplier. 20 extra ingots is not much anyway.

**Comment by GingerWalnut** [comment]
Mcmmo feature
