### ISSUE TITLE
[SQPT] Only 1 level of looting applicable to a Sabre 3

### ISSUE THREAD

**Issue by Mindaugas3** [StarQuestMinecraft/StarQuestPublic#1130]
/sqpt mods shows that there's 2 levels, however, whenever I try to apply the second level, it says "The max levels of all modifiers on this tool has been reached".

**Comment by GingerWalnut** [comment]
What other modifiers are on the sabre

**Comment by Mindaugas3** [comment]
Damage 2,
Fire aspect 2,
Energy boost 2

**Comment by GingerWalnut** [comment]
Sabre 3s can only have 7 modifiers in total. So with the looting one, it reached 7 and couldn't add another one.
