### ISSUE TITLE
SQ Tech - Fuel 

### ISSUE THREAD

**Issue by PatchyFox** [StarQuestMinecraft/StarQuestPublic#1131]
Hey there,

Three things regarding fuel used in Generators:
- The energy rate for Redstone has been significantly lowered from legacy chargers. Is this intentional, or is there now a loss between the generator and the charger? (I used to be able to charge most of my kit with a single stack of redstone - now i can charge one level 3 shovel and a helmet with that same amount.) 
- Lapis is listed on the main post as an energy source, but doesn't actually work as an import.
- Eyes of ender generate a single unit of energy. If this is intentional, this is incredibly unbalanced. 

Thanks,

**Comment by GingerWalnut** [comment]
1. This is intentional
2. This should be fixed along with charcoal
3. Eyes of enders are meant to be expensive but give you instant energy. A single piece of redstone generates the same amount, but takes more time and is less expensive
