### ISSUE TITLE
SQtech pipe not filling doublechest properly

### ISSUE THREAD

**Issue by BatFC** [StarQuestMinecraft/StarQuestPublic#1135]
SQtech pipe connected to doublechest fills only the chest it is connected and does not transfer items into or out of the other side of the doublechest. So if one wants to use doublechest with pipes one has to put 2 lapis block touching each of the singlechest. Please fix this if it is a bug, if not I will make a suggestion.

**Comment by GingerWalnut** [comment]
This should be fixed at the next restart
