### ISSUE TITLE
Space beavers are back and they are duping ships

### ISSUE THREAD

**Issue by ghost** [StarQuestMinecraft/StarQuestPublic#1136]
Well I was going to the core with 3 others, half of us made it to space in a ship half of us (me included) stayed back on the planet on the same ship, And every time we tried to meet up again our ship was duped and players scattered, we ended up with a mass of ship which we destroyed. Also I just now got spacebeavered and lost my freighter.

**Comment by Michael-Fragano** [comment]
When I went into space a while ago, I noticed when I came back to the planet that the top half of my ship had been duped when I left the atmosphere.

**Comment by Millibyte1** [comment]
This should be fixed as of a few days ago

**Comment by ghost** [comment]
Evan! You're conquest of the beavers is working!
