### ISSUE TITLE
Ship vanished

### ISSUE THREAD

**Issue by CrazyCreeper1o1** [StarQuestMinecraft/StarQuestPublic#1137]
Just a few minutes ago, I was leaving Quillon with my new ship to go to the REQIUEM spawn ship and after leaving the atmosphere, the ship did not respawn in space. I saved myself with /kit spacesuit, but I now have no where to go and I have no idea if my ship is still on the planet. I wish I could give more information, but it might have just been a LAG spike if it wasn't some sort of glitch.

**Comment by ghost** [comment]
Same time same problem

**Comment by mcdouble** [comment]
I had the same problem happen 3 times in the last hour. Space beavers are swallowing hole now.

**Comment by CrazyCreeper1o1** [comment]
Is it Quillon every single time or is it other planets as well?
