### ISSUE TITLE
Multiple problems with claiming faction land

### ISSUE THREAD

**Issue by Michael-Fragano** [StarQuestMinecraft/StarQuestPublic#1138]
My faction, the IFYI, recently merged with SOY, to form UPOY. because my faction wa disbanded, all the territory we had was unclaimed. after joining UPOY, I tried to reclaim the land. When I tried to do so, there were 2 problems.

Problem 1: It seemed to think that the land was still claimed by the IFYI, as it kept saying "you cant claim land owned by another faction in your empire!"
Problem 2: It wouldn't let me claim land because It thinks I can't claim land not connected to the original claim. I don't think this is right, because NovariaEMD has multiple claims not connected to each other on both Radawii and Yavar.

**Comment by Millibyte1** [comment]
On the latter issue, you have to walk claims out from your original and then unclaim the line of claims, you'll be able to claim in both sections

**Comment by Michael-Fragano** [comment]
I know novaria didn't do that, at least on radawii. Also, the place im trying to claim is also almost 1/4 the length of the planet away. Also, If problem 2 isn't a bug, but is an intentional rule, which is most likely put there to keep people from putting claims wherever, why is a dev telling us how to use a loophole to get through the rule?

**Comment by Millibyte1** [comment]
Novaria did do that on Radawii
