### ISSUE TITLE
Problems when entering planets

### ISSUE THREAD

**Issue by specialxport** [StarQuestMinecraft/StarQuestPublic#1139]
I was entering Quillon yesterday with my ship.
When I broke into the atmosphere, I dropped out of my ship, where I fell and died.
Can you please fix this, and also, can I have my ship back, or the materials to build it again (~2 stks yellow wool, ~2 stcks red wool, ~20 Glowstone, ~40 Nether Bricks and Slabs, 6 Pistons, 3 Sponges)

Thank you, 
SpecialxPort

**Comment by Millibyte1** [comment]
Closing as duplicate, ask mod for help in game
