### ISSUE TITLE
Fell to death on Entering Erilon

### ISSUE THREAD

**Issue by WoodenBattleTiger** [StarQuestMinecraft/StarQuestPublic#1146]
I entered the atmosphere of Erilon and immediately fell to my death. I think my ship is still there, though I can't confirm that. I have a screenshot of lost items here:

![2016-07-21_19 26 55](https://cloud.githubusercontent.com/assets/18900865/17042346/e06202cc-4f7a-11e6-9a3c-378f0714da51.png)

**Comment by Millibyte1** [comment]
Closing as duplicate, ask mod for help in game
