### ISSUE TITLE
SQtech pipe deleting items

### ISSUE THREAD

**Issue by BatFC** [StarQuestMinecraft/StarQuestPublic#1147]
SQ tech pipe is eating items in the following scenario:

First the system has one exporting chest, two importing chests. One of the importing chests has to be doublechest.
![2016-07-23_00 17 26](https://cloud.githubusercontent.com/assets/7577409/17063792/05b88286-5074-11e6-99b3-fe5f2bc554c6.png)
![2016-07-23_00 17 38](https://cloud.githubusercontent.com/assets/7577409/17063804/10eedaba-5074-11e6-901c-23a7b6aa543c.png)
![2016-07-23_00 17 44](https://cloud.githubusercontent.com/assets/7577409/17063810/17427066-5074-11e6-8e8c-fd8255e67aed.png)
![2016-07-23_00 17 48](https://cloud.githubusercontent.com/assets/7577409/17063811/18877d2c-5074-11e6-9f2c-3ff5d2abef4b.png)

The doublechest has to be full with the transferring item (in this case cobblestone).
![2016-07-23_00 17 54](https://cloud.githubusercontent.com/assets/7577409/17063834/315de0ca-5074-11e6-911e-9a38586d9938.png)

When you put some of the transferring item in the export chest:
![2016-07-23_00 18 01](https://cloud.githubusercontent.com/assets/7577409/17063856/5a1ab51a-5074-11e6-8dd0-8dcfc4d2bb25.png)

Some part of it will be missing in the import chest
![2016-07-23_00 18 56](https://cloud.githubusercontent.com/assets/7577409/17063872/76bbf918-5074-11e6-9373-ecd2bf739dc8.png)

The doublechest will still be full.
![2016-07-23_00 19 08](https://cloud.githubusercontent.com/assets/7577409/17063879/7fa59d4a-5074-11e6-8ce5-febd79361008.png)

4 of 64 cobblestone was lost in this transfer and this bug occurs only when there is full importing doublechest in the system, so probably it has something to do with the yesterdays doublechest fix.

I lost about DC of ugh ... valuable stuff to this bug, but there is no way to prove this loss so I will not be requesting refund.

**Comment by BatFC** [comment]
Further testing reveals that this bug deletes one item from every transfer, meaning 64 items will be transferred 4 (16+16+16+16) times thus loss of 4 items. If you put 2 items in export chest will have only one item.

**Comment by GingerWalnut** [comment]
This will be fixed at the next restart
