### ISSUE TITLE
Yavar gate 3 and 2 not letting you get home

### ISSUE THREAD

**Issue by Michael-Fragano** [StarQuestMinecraft/StarQuestPublic#1148]
I went to the cor for a little bit yesterday to do some svs for fun, and when I came back in slipgate 2, when i tried to move, i got sent back to the core. I then went to slipgate 3, and he same thing happened. please help.

**Comment by Millibyte1** [comment]
Getting back tomorrow afternoon, will try to figure why everything broke while I was gone. There's code supposed to prevent this and several other bugs that have been reported over the past few days so it's probably an issue with version control that I can clear up quickly.
