### ISSUE TITLE
SQTech and Potions

### ISSUE THREAD

**Issue by NevLo** [StarQuestMinecraft/StarQuestPublic#1151]
Recently Kyorg and I started to create a potions set up with SQ tech. we soon realized that SQ tech and potions do not mix, because when i tried to set imports/exports for potions it gave me this:
![2016-07-23_02 27 58](https://cloud.githubusercontent.com/assets/19544688/17077243/99874a0c-507d-11e6-9eb9-9420301f15b2.png)

**Comment by mcdouble** [comment]
This could be an issue related to mcmmo potions. Was it Haste II?

**Comment by NevLo** [comment]
no, it was a water bottle

**Comment by GingerWalnut** [comment]
This will be fixed at the next restart
