### ISSUE TITLE
problem with /empire join

### ISSUE THREAD

**Issue by Rossgodd** [StarQuestMinecraft/StarQuestPublic#1152]
can not join requiem, tried both /empire join requiem and /empire join requiem confirm within 10 seconds of each other and still noting. Don't even get any text pop up in response.

**Comment by JC3371** [comment]
You might have to captialize REQUIEM. Not completely sure though.

**Comment by mcdouble** [comment]
This has happened to two people who attempted to join Yavari. I instructed them to use the join command, and the join command with the confirm after, and neither worked. Moneybags was able to manually insert the player into the empire, though the person experienced issues regarding the empire commands.

**Comment by finnytom** [comment]
Can confirm.

Me and theclassycake couldn't join, but a dev added us to an empire. But, when going down the green carpets to go to the ship spawns so we can fly to planets, we go on the pressure plate and it teles us back to spawn, even though its supposed to transfer us to the ships. On top of that, when type /empire status finnytom or /empire help, it says my empire is "None", yet i have the correct nametag and access to the empire commands. Same thing happens with TheClassyCake. Me and Cake would like to be arator. My username is finnytom.

**Comment by Rossgodd** [comment]
JC3371, just tried capitalizing REQUIEM, did not work.

**Comment by Rossgodd** [comment]
It is fixed now, I saw the update on the website today that said there where server wide problems.
It is July 24, 2016

**Comment by GingerWalnut** [comment]
This should be fixed
