### ISSUE TITLE
Slipgate regions

### ISSUE THREAD

**Issue by mcdouble** [StarQuestMinecraft/StarQuestPublic#1153]
When entering into the rim systems from the core space, it tp's you to the wrong side of the slipgate (I.E. It tp's you to the south side of the slipgate near Tyder). It ends up tping the player too close to the slipgate and then they're trapped in the endless cycle of being tp'd back and forth unless their ship is 23 or more BPS and they get lucky.

**Comment by NevLo** [comment]
shift fly downwards, then go to the sides. it helps!

**Comment by Millibyte1** [comment]
This should be fixed as of a few days ago
