### ISSUE TITLE
didnt get my saber 3 i bought

### ISSUE THREAD

**Issue by natedawg7900** [StarQuestMinecraft/StarQuestPublic#1155]
![capture](https://cloud.githubusercontent.com/assets/20619999/17085077/c77365be-5194-11e6-8924-4f5e831c062f.PNG)

i payed 8 dollars at around 10:08 pm central america to buy a a saber 3 and didnt get it
my username is natedawg7900

**Comment by lawrencethefrog** [comment]
Could you please provide evidence confirming your purchase? For all we know you're just making it up.

**Comment by natedawg7900** [comment]
ask little he was on when it happened

**Comment by Krayolla** [comment]
Funded and solved.
