### ISSUE TITLE
now everyone got the saber 3 sword except me

### ISSUE THREAD

**Issue by natedawg7900** [StarQuestMinecraft/StarQuestPublic#1156]
please i just want my sword right as they said they got it i got beavered this sucks u can check all my chests even i just want the sword :(

**Comment by lawrencethefrog** [comment]
This isn't even a bug report, it's just you whining about items you lost. We don't have to give you refunds, it's just something nice we do in return for the time it takes you to post a proper in-depth bug report, and even then you have to provide screenshots showing you actually had the item in the first place.
Please don't post any more issues here if this is what they're going to look like.
