### ISSUE TITLE
Unable to enter xira

### ISSUE THREAD

**Issue by ghost** [StarQuestMinecraft/StarQuestPublic#1157]
I was going to xira just to do random things, and It said entering the atmosphere of xira but wouldn't enter. I had to un-pilot and re pilot my ship to move just one time. And all of a sudden Ginger_walnut comes up with his ship, destroys mine, so I run towards xira in the world guard. Except he shoots me with his bow and kills me.

**Comment by Millibyte1** [comment]
This should be fixed now
