### ISSUE TITLE
Dynmap color coordination broken

### ISSUE THREAD

**Issue by LookMomImWalrus** [StarQuestMinecraft/StarQuestPublic#1161]
Onos shores at 3:21 pacific time
arator owns 3/3 points
it still gives mining speed debuff and the territory says yavari

**Comment by LookMomImWalrus** [comment]
edit: it's happening with mount wrath too

**Comment by LookMomImWalrus** [comment]
edit2: it appears only the beacons are bugged.

**Comment by GingerWalnut** [comment]
This should be fixed with a server restart
