### ISSUE TITLE
Bought Sabre 3 Supply Drop from the shop, didn't receive

### ISSUE THREAD

**Issue by TheClassyCake** [StarQuestMinecraft/StarQuestPublic#1165]
Hi. Earlier today I bought a sabre 3 supply drop from the shop, and I didn't get it, nor did any other players. About 5 minutes after I bought it, Jane messaged everyone about it and I got the [I] tag. But, I did not get the sword. My username is TheClassyCake. I asked some moderators, they advised me to create a GitHub issue.

**Comment by GingerWalnut** [comment]
Was your inventory full? Also, did anyone else get the sword?

**Comment by GingerWalnut** [comment]
This should be fixed, please contact a staff member to contact me when you are next online so we can give you the sword
