### ISSUE TITLE
Chunk Glitch

### ISSUE THREAD

**Issue by mcdouble** [StarQuestMinecraft/StarQuestPublic#1168]
Of the two chunks at the Skydogs Xira base, one of them wiped all the chests. Roughly 20-30 doublechests of items were lost. The other chunk had a few chests, all remained. This is exactly what happened on Tyder, when another 20 or so doublechests were wiped back awhile ago.

**Comment by Kyorg** [comment]
Same happened to me, wiped all of my ore chests

**Comment by Millibyte1** [comment]
Closed as duplicate of #1035
