### ISSUE TITLE
Serverjumps to and from previously offline worlds not working

### ISSUE THREAD

**Issue by Millibyte1** [StarQuestMinecraft/StarQuestPublic#1170]
Going to make a new issue here on this previously reported issue, I ask that people not make more duplicates of it. After a server crashes, the plugin dealing with communication between servers breaks and makes two unidirectional connections, causing transfers to break to and from that server until the entire server is fully restarted.

**Comment by mcdouble** [comment]
hi evan

**Comment by samshamrock12** [comment]
My issue isnt the same as what you described becuase mine has been going on for all today and yesterday night plus other people were able to go off and on planets.

**Comment by Millibyte1** [comment]
The fix for this issue will be implemented sometime this afternoon.
