### ISSUE TITLE
Chemical Turrets

### ISSUE THREAD

**Issue by mcdouble** [StarQuestMinecraft/StarQuestPublic#1171]
Chemical turrets will build properly, intake fuel properly, but then I think its upon relog and unloading the chunks that it wiped the GUI and makes it appear as if its an unbuilt turret, despite having the rest of the turret structure on top of it. I tested, and it doesn't fire the splash poison pots in this state.

**Comment by GingerWalnut** [comment]
This should be fixed. If it isn't, please reopen/make a new one
