### ISSUE TITLE
Ship replicator 1 block off

### ISSUE THREAD

**Issue by ghost** [StarQuestMinecraft/StarQuestPublic#1175]
I was copying some ships for my evil plans and the ships spawned 1 block off so I had to keep breaking the replicator blocks next to the ship so the frame wouldn't go with. http://prntscr.com/c18km5

**Comment by BatFC** [comment]
Ah, it is a copy to the other side not mirror image. Move your original ship one right.

**Comment by ghost** [comment]
Also it was copying the middle barrier of brick

**Comment by Denyol** [comment]
This doesn't seem to be an issue.
