### ISSUE TITLE
Cant server jump

### ISSUE THREAD

**Issue by samshamrock12** [StarQuestMinecraft/StarQuestPublic#1181]
So everytime i try entering a planet or anything other than the spawn ship it will say preparing to server jump like normal, but then it just wont sever jump.I've sat there for a good ten minutes and try'd relogging.I've tried asking moderators or admins but everytime theres either none on or they're not answering me.

**Comment by Millibyte1** [comment]
Closed as duplicate of #1170

**Comment by Millibyte1** [comment]
You said other people were able to server jump, were these people in the same system as you?

**Comment by Millibyte1** [comment]
This issue should be resolved
