### ISSUE TITLE
Power Tools Mod Combos

### ISSUE THREAD

**Issue by Laserlance141** [StarQuestMinecraft/StarQuestPublic#1183]
Basically, on Powertools, you can add mods that should not combine to the same Powertool. Example: Fire protection and protection on same armor piece; Attack Damage and Attack Speed on one tool.
I have a few pieces of these broken tools, and will gladly give them up for the items that it took to make them. (Tier 3 Armor Isn't Cheap)

**Comment by GingerWalnut** [comment]
This should be fixed at the next restart
