### ISSUE TITLE
Serverjump Broken For All Planets (Still)

### ISSUE THREAD

**Issue by JC3371** [StarQuestMinecraft/StarQuestPublic#1186]

**Comment by JC3371** [comment]
I tried to leave Erilon today and got the preparing serverjump message. After waiting a good while I wasn't transported into space. I have heard other players complaining about this throughout the day.

**Comment by Millibyte1** [comment]
I put in a fix for one of the last couple major issues with transfer today, but I had to leave before I could fix this one caused by it. I know what's causing the issue, it'll be fixed tonight

**Comment by JC3371** [comment]
:D
