### ISSUE TITLE
beam turret perms and ship stop upon cannon fire

### ISSUE THREAD

**Issue by LookMomImWalrus** [StarQuestMinecraft/StarQuestPublic#1188]
I fired cannons once, my ship wouldnt fly, they wouldnt fire again, and I couldnt do anything ship related
tried in the beam turret, needed perms for it

**Comment by BatFC** [comment]
Yeah, I have this problem too. Moving, firing, turning anything related to ship does not work after firing cannons the first time. I can't unpilot the ship and /release or /stopriding does not work neither is piloting another ship. /shipsize works even when you are outside the ship. I am on planet Tyder.

**Comment by GingerWalnut** [comment]
This should be fixed
