### ISSUE TITLE
Can't mine/build on Grallion. Anywhere

### ISSUE THREAD

**Issue by SirLoser** [StarQuestMinecraft/StarQuestPublic#1198]
I went to grallion, and flew to a floating island in yav claimed territory, and tried breaking blocks. Told me i couldn't. i tried to kill a squid, told me I can't harm it. i tried building something, told me I couldn't place blocks there. Then i flew to an unclaimed territory, and the cap point was in a tree my ship couldn't reach. so once again, I tried building, breaking, and even tried killing something to test, none of which worked. Then i tried the same things on the water's surface, in both a claimed area, and unclaimed one, still didn't work.

**Comment by GingerWalnut** [comment]
This should be fixed
