### ISSUE TITLE
Harvester permission's

### ISSUE THREAD

**Issue by jack0700** [StarQuestMinecraft/StarQuestPublic#1199]
Today when I decided to set up a harvester for my farm I came across a message saying I did not have permission to activate it, I consulted one of the developers on the server at the time (Evan) and he said the required rank is Denizen (or whatever your empires rank two is), this may simply be because it has not been enabled on the planet that I am located on (Yavar). Anyways that is all.

**Comment by Denyol** [comment]
This should be resolved now.
