### ISSUE TITLE
SQ Is Dead

### ISSUE THREAD

**Issue by JC3371** [StarQuestMinecraft/StarQuestPublic#1210]
This is a major issue for many reasons.

**Comment by Millibyte1** [comment]
Other users have not been experiencing this issue, could you give more specific instructions?

**Comment by Millibyte1** [comment]
No repro

**Comment by JC3371** [comment]
:/

**Comment by Millibyte1** [comment]
@JC3371 Is this issue still occurring?

**Comment by Millibyte1** [comment]
Fix pls

**Comment by JC3371** [comment]
💯

**Comment by StarQuestMinecraft** [comment]
This is no longer an issue
