### ISSUE TITLE
Kills not counting(?)

### ISSUE THREAD

**Issue by Mindaugas3** [StarQuestMinecraft/StarQuestPublic#124]
Describe the error.
So I grabbed my invis pot, and flew to Jorcool. I was waiting near him a little, reviewing all maps. I flew around my LRS "Raffica" starfighter. I released it. 

I changed my internet(temporarily) from Wi-Fi to 4G, in order to increase quality of PVP.

I was at 93 r kills then(got no screenshot of that, but if you see logs you can see everything, also I got my screenshot of me having 91 kills)

Jorcool started diggin' up, I came closer and hit him with my [Sharpness V, Embered cutlass II, Unbreaking III] cutlass, I hit him like once or twice and cooked him. 

Then(like always after any kill I've done) I saw that I'm still on 93rd kill to Bucco, when I am supposed to have 99th kill. I flew home, checked if this is some kind of lag, /rankup checked again, still at 93rd.

Note: I was going around the place for about 2-3 minutes.

What steps can I take to reproduce the problem?
1. Go to kel with invisibility potion and hunt someone, 2x kill boost required
2. Wait for someone like 3-4 minutes while flying around a starship
3. Find and kill the target

If it was a permission-related error, what rank are you?

Do I need to check the processing? (Hint: The answer is yes)

If it was a starship related error, what type of ship were you flying, and what were you doing exactly before the error occured? LRS "Raffica"(Light raiding ship), starfighter. I released it and sneaked up to my target.

Please provide any other relevant information here:
X: -823 Z:1318
Screenshots:
Of me killing Jorcool:
http://i.imgur.com/udWXgdz.png
Of me having 91 kills(I killed a settler later(dont have screenshot of this one) so I have 93 kills):
http://i.imgur.com/LQx35be.png

So i still have 93 kills, while I'm supposed to have 99.

**Comment by TheMindaugas** [comment]
WARNING: The issue is present again, yet it literally writes I get 0 infamy. 
http://imgur.com/Kv2CNDR
(Turning off dat jammer, tehehe)
Chewbacca is an affluent meaning 4 infamy to be awarded.
