### ISSUE TITLE
ShapeShifters Bug/Issue

### ISSUE THREAD

**Issue by Unic0rnjunk101** [StarQuestMinecraft/StarQuestPublic#168]
I found when testing with Mastercreeper that the hitboxes of a baby chicken are the size of a baby chicken making it overpowering in pvp which results in it not being a cosmetic perk. I did not get the chance to test a bat or any other baby mobs. It is Extremely important that it is fixed before Friday as the Black Friday sale will make it only 2$ and many people will buy them.

**Comment by Siigillum** [comment]
Still broken. Critical issue i'd say since hitbox appears to be fully missing.
