### ISSUE TITLE
the death bug

### ISSUE THREAD

**Issue by enderdonut** [StarQuestMinecraft/StarQuestPublic#203]
while i was playing starquest, I was in space with a helmet on my head so I could breathe, I was looking for the ship I had gotten lost, when i noticed a sign glitch. so like any minecrafter, I relogged. when I came back, I was suddenly losing health so rapidly I could not even speak before I died. I believe this is a bug that would be rare and I've seen happen before. for example it happened to Stormer too. The only things that i request is starquest fixes this bug and tries to replace the items lost by players who were victims of this monstrosity of a bug. I do not wanting it happening to a new player, who would most likely take it as the server being too buggy. Unfortunately i did not take a screenshot because i was too concentrated on trying to not die.

**Comment by enderdonut** [comment]
It was fast enough to be suffocating even though i was wearing a helmet to breath, in fact it was even faster than that

**Comment by MikeBurk** [comment]
We were unable to work out a way to reproduce the issue.  I would love to fix it - if it happens again or there are any more details you can find and share, please add them and we would be happy to continue investigating.

GIT is for bugs only.  Refund requests are only handled by the moderators.
