### ISSUE TITLE
Easy to duplicate blocks in town

### ISSUE THREAD

**Issue by rudeart** [StarQuestMinecraft/StarQuestPublic#204]
In a town, turn off explosions.
Make a ship with a cannon or more.
Make a second ship with blocks to duplicate.
Shoot cannons at the 2nd ship.
Go pilot the 2nd ship and move it back
Blocks that were hit will respawn and be duplicated

**Comment by Dibujaron** [comment]
Fixed tonight. Thanks for reporting.
