### ISSUE TITLE
Machina Pumps Refuse to Pump

### ISSUE THREAD

**Issue by Oregus** [StarQuestMinecraft/StarQuestPublic#205]
I'm not sure whether I built it incorrectly or not - but the pumps aren't working.

I'm more certain this is a bug, since the pump itself (the wooden planks) extend, while nothing is actually pumped out. 

EDIT: I was trying to pump lava with wooden planks, after I searched around, I had to use Iron blocks. So I used iron blocks, but it says I don't have permission. May I ask why?

**Comment by lawrencethefrog** [comment]
I think I found your problem: The first comment on the MachinaPump bukkit page (http://dev.bukkit.org/bukkit-plugins/machinacraft/pages/machina-pump/) 
 says: "For lava it must be iron blocks. not planks."

**Comment by Oregus** [comment]
No - I used iron blocks. The pipe extended and then the "you do not have permission to pump lava" message appeared.

They worked before - I'm just confused as to why they don't now.

**Comment by Dibujaron** [comment]
Lava pumps created infinite fuel from nothing, so while it's interesting that they broke, I'm not too sad about it. I believe there was some discussion about changing them to only work on ceharram and drakos, maybe one of the other devs changed it.
