### ISSUE TITLE
Active Cryos Reset

### ISSUE THREAD

**Issue by Oregus** [StarQuestMinecraft/StarQuestPublic#208]
So, I decided to do some testing today, with active cryopods.

When toggling active - if you die, it teleports you to the center spawn of the world, rather than your pod. And then, it'll teleport you to the spawn station in Regalis.

I haven't had time to test in-active - mostly because the mod that was going to help me just in-case I went flying somewhere again was too busy with Refugees.

**Comment by lawrencethefrog** [comment]
Active pods are working fine for me on Val. I appeared in mine when I died from a creeper, and I appeared in mine when I re-logged.

**Comment by Dibujaron** [comment]
This is a messy bug that I haven't figured out 100%. Thanks for reporting.

**Comment by Dibujaron** [comment]
This has been fixed recently, thanks for reporting.
