### ISSUE TITLE
quav global chat broken

### ISSUE THREAD

**Issue by TheMindaugas** [StarQuestMinecraft/StarQuestPublic#209]
If you try to /g and speak in quav it appears in brackets, just like if it was broken faction or town chat. You cant tell something to many players at once.

**Comment by GroxTerror** [comment]
Happens sometimes. Usually if you tell a mod they can do something.

**Comment by lawrencethefrog** [comment]
This happened on Val too after the restart yesterday. Planet, global, and local chat were all broken. Nation chat was broken too (I think) but town chat was definetely working.

**Comment by Dibujaron** [comment]
I'm going to assume that this already self-fixed. Our chat plugin is very antiquated, but we have no replacement, so we continue on with it. One of these days we'll get around to fixing it :(
