### ISSUE TITLE
Kills not registering in /rankup

### ISSUE THREAD

**Issue by HiFlyCS** [StarQuestMinecraft/StarQuestPublic#211]
I killed Trollinator (TheBossmanPhil) and the message said I have 48 kills, but when I typed /rankup it showed as if I haven't killed him at all. Here is proof I have killed him. (He is worth 3 kills). 
http://i.imgur.com/woGsPAb.png

**Comment by Dibujaron** [comment]
I'll ask George to look into it, rankup is his child. Thanks for reporting.

**Comment by HiFlyCS** [comment]
Thanks dib

**Comment by Dibujaron** [comment]
This was fixed.
