### ISSUE TITLE
Lag issue still occuring after reset

### ISSUE THREAD

**Issue by bluelimeminer** [StarQuestMinecraft/StarQuestPublic#212]
Lag issue is still occuring after reset at the exact same locations as before.  The full details are in the original ticket.  Can this issue please be investigated further as per Dib's words in previous ticket.

Original Ticket
https://github.com/StarQuestMinecraft/StarQuestPublic/issues/183

**Comment by Dibujaron** [comment]
Really. interesting.  And you're absolutely sure it's tied to that location, and not just the fact that you're in a busy town and lag is common in places like that? Avalon has complained of a similar "ghost area" where this occurs.

**Comment by TheMindaugas** [comment]
Didnt Stealthy fix this? I and finny were there once, i was like moonwalking at 0 fps, asked stealthy to investigate, then he fixed it and said about something with world borded and that it is all messed up somehow. Then he fixed it, is it still lagging?
