### ISSUE TITLE
Mobs disappearing

### ISSUE THREAD

**Issue by XXZELDAFAN** [StarQuestMinecraft/StarQuestPublic#213]
Mobs are randomly disappearing if you get too close or hit them. Not all of them disappear though just some. But it makes it really hard to grind mobs when all of them disappears. So i hope this gets fix.

**Comment by GroxTerror** [comment]
Definite fix needed on this.

**Comment by lawrencethefrog** [comment]
This happens on Val too. I think it might be to do with them crossing chunk borders, or coming within a certain range of the player.
And am I the only one that thinks GroxTerror's image looks like a noobfighter?

**Comment by Dibujaron** [comment]
This was fixed, thanks for reporting.
