### ISSUE TITLE
Compass

### ISSUE THREAD

**Issue by GroxTerror** [StarQuestMinecraft/StarQuestPublic#214]
I was trying to get to quav today and decided to try out the compasses. Upon trying to use /compass live regalisslipgate, it told me no private points were labled 'regalisslipgate'. I tried acu too and got the same result.

**Comment by Dibujaron** [comment]
You have to be in space for those to work, if you're trying them on a planet, they won't show up.

**Comment by GroxTerror** [comment]
Was in space when I did this, I wasn't trying to get off Quav, I was trying to get there invis. (Because Siig)
