### ISSUE TITLE
Shapeshifters Again

### ISSUE THREAD

**Issue by Unic0rnjunk101** [StarQuestMinecraft/StarQuestPublic#215]
Shapeshifters hitboxes for baby chicken are not the size of a player when used in pvp. Another issue is when using invis with shape shifters armor and anything u hold is also invis so making this an Over powering perk which creates an unfair advantage in pvp violating the EULA. I have experienced this first hand and heard the hitboxes were fixed after posted to another ticket about a month ago. Thanks!

**Comment by Dibujaron** [comment]
Fixed at this restart, I hope.
