### ISSUE TITLE
/afk broadcasting bug

### ISSUE THREAD

**Issue by lawrencethefrog** [StarQuestMinecraft/StarQuestPublic#216]
I'm new to GitHub, so please tell me if I am doing something wrong.

The bug:
When a player does /afk, they and other players on the planet hear 'player_whatever went afk', but when the move or somehow come out of afk, the message 'player_whatever is no longer afk' goes out to everyone on the server.

How to reproduce:
Get a friend/fellow dev to type /afk twice on the same planet as you. Then go to another planet and get them to repeat.
I did this with little_liggo to confirm the bug.

Possible cause:
Not having fully set up the afk plugin to work with bungeecord?

**Comment by Dibujaron** [comment]
that's interesting. I will look into this, thanks for reporting.

**Comment by Dibujaron** [comment]
This is still probably possible, but I don't want to spend the time to dig into it and fix it since nobody seems to be abusing it, so I'm going to leave this for now. If it begins to be abused it will be dealt with.

**Comment by awangatboo** [comment]
Closing all bugs in preparation for SQ 4.0.
