### ISSUE TITLE
Problems on planet entry/leaving (Very important)

### ISSUE THREAD

**Issue by TheMindaugas** [StarQuestMinecraft/StarQuestPublic#217]
Yesterday, me and my friend foto3dit0r were chasing bunch of colonists and we accidentally flew to bole. Foto was pilot and I was passenger, both with invis on.Immediately after I entered bole, i died to "fall damage", yet all my items remained(and were picked up by my friend). Foto and little_liggo can confirm.

Same happened during previous raid with GreekAnalyzer and Coolwolf, same death on planet entry, though i believe its some kind of lag, it is very important to look into this glitch. Coolwolf refunded items and XP levels, and both of the companions can confirm

Another case, I've been leaving iffrizar with Crusher48 as my pilot. Though I entered space, I died in iffrizar(Crusher can confirm, once again i fell to my death), and I still respawned in my ship with my inventory and items.(Crusher, and Loart can confirm(he wasnt afk then))

One more case, I was alone flying out of Quav, in Quav I lagged and fell to death, yet respawned at my ship in space, with all my XP and items.

Though I believe 2 last glitches are somewhat harmless, 2 last and 2 first(extremely dangerous) glitches possibly have common cause and should be fixed immediately.

**Comment by TheMindaugas** [comment]
And now my friend krihellion died upon entry to quav.

**Comment by Dibujaron** [comment]
I believe I have fixed this. If I have not, please open this issue again and let me know asap!

Thanks for reporting, as always.
