### ISSUE TITLE
Autopilot jumping through walls

### ISSUE THREAD

**Issue by lawrencethefrog** [StarQuestMinecraft/StarQuestPublic#218]
The problem:
This is an old problem, but still pertinent. Autopilot works by making jumps and copying the ship directly from A to B, a bit like slip-drives on a smaller scale. Autopilot ignores whatever blocks may be between A and B, and will only refuse to jump if the there are blocks at B directly where the ship will go.

This means that I (or anyone else) can use autopilot to jump through walls. However useful it might be for entering my hangar without going to the gate, pirates (or anyone for that matter) could do the same, and this annoys me. This is now easier than ever to do, as autopilot allows you to fine-tune how many blocks you want to jump, making passing through walls as easy as flying up to them and clicking at your autopilot till it goes.

What's more, the only way to stop this is to build walls 20 blocks thick, which is a huge waste of valuable claims, making it impossible for smaller towns and factions to fully protect their hangars form intruders without filling in the actual parking spaces.

Possible fixes:
-Make autopilot check if all the blocks between A and B are air (optimal fix, but most time needed)
-Make autopilot make jumps no bigger than the length of the ship (and change the jump rate) so that it will never go through a wall (optimal fix, maybe less time needed)
-Stop autopilot from jumping into protected areas (partial solution, but fixes most problems of abuse)

**Comment by lawrencethefrog** [comment]
@GroxTerror Autopilot generated a stone wall on its own? That sounds like a pretty major issue all on its own, I suggest you create a separate issue for it if you haven't ready.

**Comment by GroxTerror** [comment]
No, it spawned inside a wall and I nearly suffocated (I was riding an underground train)

**Comment by Dibujaron** [comment]
Unfixable practically, thanks for reporting.
