### ISSUE TITLE
First Glitch With Shields

### ISSUE THREAD

**Issue by GroxTerror** [StarQuestMinecraft/StarQuestPublic#219]
Got my test ship up today, starting shield testing. The first glitch was very unexpected; shields seem to still be loading up when said ship has activated yet again. I encountered this when turning on my ship again and moving it to another location, when it began pelting me with messages from earlier shield startups. No idea if this actually will save the past location, but it might. Guess I'll test that later.

**Comment by Dibujaron** [comment]
Fixed. Thanks for reporting!
