### ISSUE TITLE
Shield issue - shield activates despite breaking sign

### ISSUE THREAD

**Issue by Siigillum** [StarQuestMinecraft/StarQuestPublic#221]
Ok, so today I kiled 2 Ceharram Babylon guys, Looney and Shady. Their ship was equipped with shield systems. I emp the ship, kill the meat inside, break the shield sign. Then i looted and went to Quav for loot dropoff. Went back to colelct the ship and boom, shield is up despite the fact i broke the sign earlier. Towed the ship normally then as the shipsign was emp'd.

**Comment by GroxTerror** [comment]
(No idea how to mention another issue, kinda new to github)

Looks like the issue I mentioned earlier, they may have released the ship or it was released by an EMP. Shield may have then set up, regardless of countering factors.

**Comment by Dibujaron** [comment]
Fixed.
