### ISSUE TITLE
Shields appear to be not working.

### ISSUE THREAD

**Issue by GroxTerror** [StarQuestMinecraft/StarQuestPublic#222]
Not sure what happened here. Left my test satellite out to observe and see if shields are working properly, when I got a message saying that another TUPA guy had found it. He thought it was a stray ship of mine and apparently was able to break blocks on the shield ship and tear off the doors to bring it to Acu for me. I don't know how he got the doors off or how he was able to break the ship itself- but it appears shields aren't working at all. I was on a different server at the time, not sure if that affects anything.

**Comment by lawrencethefrog** [comment]
Maybe he was on the allowed list? I know that towny has a friends system where you can let people build in your plots, and WG might support a similar system.

**Comment by GroxTerror** [comment]
Nope, not on there.

**Comment by TheMindaugas** [comment]
Before being banned, I raided couple of smart settlers who kinda liked experimenting much/red the whole wiki. They had shield on their ships, but it hadnt had created a wg, so i was able to scrap the ship

**Comment by GroxTerror** [comment]
Found the problem. I had boarded another ship afterwards and it apparently deleted my shield.
