### ISSUE TITLE
Cannon damage unpiloting ships.

### ISSUE THREAD

**Issue by Siigillum** [StarQuestMinecraft/StarQuestPublic#224]
Ok. So the damage & unpilot system is almost working and ballanced. Mob, player damage makes the hit guy unpoilot. Same with ap turrets and most likely normal turrets. Cannons are the problem though. They unpilot the ship as well. This leads to one huge problem. Given the cannon rof and explosion radius battles may last till the very first shot. Torpedoes, turrets, blasters unpiloting ships - ok. Cannons - no no in my opinion, way to overpowered now.

By the way, blaster ap turret unpiloting the ship now fixes the flying carpet ship issues :)

**Comment by GroxTerror** [comment]
Not saying I don't agree with this, but shouldn't this be in suggestions on the forums?

**Comment by Dibujaron** [comment]
Done at next restart.
