### ISSUE TITLE
Infinite Iron Door Generator

### ISSUE THREAD

**Issue by Terminus--** [StarQuestMinecraft/StarQuestPublic#225]
On the 11th of Jan 2015 I was testing my tank, and iron door started appearing in my inventory. I soon to discovered how to recreate this, below is the procedure

Step 1
Obtain a ground vehicle with and iron door controlled by a switch

Step 2
Turn the switch "off" so the door closes
![2015-01-11_16 27 27](https://cloud.githubusercontent.com/assets/10490131/5696993/f0ac7110-99b1-11e4-9a8c-17699445981f.png)

Step 3
Pilot the Craft
![2015-01-11_16 27 13](https://cloud.githubusercontent.com/assets/10490131/5696996/001c1f74-99b2-11e4-9017-c78f4ff7df22.png)

Step 4
Open the door via the switch
![2015-01-11_16 53 20](https://cloud.githubusercontent.com/assets/10490131/5697010/590c115c-99b2-11e4-90df-ec4e38b59563.png)

Step 5
Attempt to move the craft down.
![2015-01-11_16 55 38](https://cloud.githubusercontent.com/assets/10490131/5697028/a4931c92-99b2-11e4-8846-c9acb423fdc5.png)

After about 1 second about 3 iron door will appear in you inventory or on the ground, if you continue to move down you can fill up your inventory in 45 seconds.

**Comment by Dibujaron** [comment]
fixed. thanks for reporting :)
