### ISSUE TITLE
Train Issue

### ISSUE THREAD

**Issue by GroxTerror** [StarQuestMinecraft/StarQuestPublic#226]
Tested out the TUPA train system not too long ago. It was lagging pretty hard and the train went off the underground track straight into stone. I had to manually dig myself out. No open blocks were there from what I saw.

**Comment by Siigillum** [comment]
Awesome train you have there.

**Comment by Dibujaron** [comment]
I'm going to call this part of the extreme lag problems of the past couple of days and not worry about it. let me know if it happens again now that the lag problems are gone.
