### ISSUE TITLE
Faction explosion/fire spread flags on dynmap

### ISSUE THREAD

**Issue by TheMindaugas** [StarQuestMinecraft/StarQuestPublic#228]
Factions seem to have explosions on.
A copy-paste from clicking an area in my faction:
sky9faction
Flags

open: false
monsters: false
powerloss: true
pvp: true
friendlyfire: false
explosions: true (!)
offlineexplosions: false
firespread: true (!)
endergrief: false
permanent: false
peaceful: false
infpower: false

**Comment by HiFlyCS** [comment]
Dib said it's ok
