### ISSUE TITLE
21 standard players online

### ISSUE THREAD

**Issue by lawrencethefrog** [StarQuestMinecraft/StarQuestPublic#230]
Just something I saw while I was checking if there were any free spots:

![Image of 21 standard players online in the multiplayer menu]
(http://i.imgur.com/FVud5Bh.png)

I was able to connect to the server even though it was overfull (I haven't got the Jr. Dev rank yet, so I don't think it was that), when about 1 minute before that I couldn't connect (and there were only 20 standard players)
This happened about 10 minutes before the reset.

**Comment by awangatboo** [comment]
I have seen this before and always thought it was a new player that first logged on at a Premium (because of the first 5 days are free) and then while the player is on it goes over the allotted time and they become a Standard player.  This has just been my guess.

**Comment by lawrencethefrog** [comment]
That would make sense, Or it could be someone's priority running out. Not a big issue, either way.

**Comment by GroxTerror** [comment]
i cri very tim
