### ISSUE TITLE
Whaaaacky chat

### ISSUE THREAD

**Issue by brickworm2012** [StarQuestMinecraft/StarQuestPublic#232]
![2015-01-21_08 39 35](https://cloud.githubusercontent.com/assets/9120968/5839101/2853589c-a149-11e4-9995-40d84179b9cf.png)
This is what both town and nation chat looks like. Also global is off. This is on Ceharrem.

**Comment by awangatboo** [comment]
This is what happens when BungeeSuitChat does not initialize correctly.  Most likely a SR. Mod or Manager was able to make this work.  If not it will most likely get fixed after the next restart.
