### ISSUE TITLE
Combat after piloting

### ISSUE THREAD

**Issue by BygoneSamurai** [StarQuestMinecraft/StarQuestPublic#233]
After unpiloting a ship i cannot do pvp for about two minutes and I always get killed because I cannot hit the enemy but they can hit me. I've reported this months ago but still haven't seen a fix, or maybe it's just a problem with me.

**Comment by Oregus** [comment]
This happens quite often - I don't think it has been fixed.

**Comment by BygoneSamurai** [comment]
It's quite annoying, especially when your trying to help a friend out from getting attacked

**Comment by Siigillum** [comment]
Quick relog. And buy priority so the relog IS quick.

**Comment by BygoneSamurai** [comment]
I've got priority but my launcher is slow for some reason, probably my crappy computer

**Comment by lawrencethefrog** [comment]
Have you tried using a bow? I heard that that worked, though I have never tried it myself. If you're trying to help a friend out, I suggest you build an AP turret into your ship as they now dish out decent amounts of damage.
Of course, the quick fix is probably to relog, like Siig said, which would be even more practical if you had SQPriority.

**Comment by Oregus** [comment]
Bow's don't always work either.

**Comment by Dibujaron** [comment]
This is an unfixable bug- it's a mojang problem and they will not fix it. It's possible that 1.8's new smooth relative teleporting may help it, but we'll have to wait and see until we can update the server to 1.8.

**Comment by BygoneSamurai** [comment]
That's too bad, but i will learn to deal with it, thanks everyone for your help!
