### ISSUE TITLE
Slip-drives not consuming fuel

### ISSUE THREAD

**Issue by lawrencethefrog** [StarQuestMinecraft/StarQuestPublic#235]
Today I decided to do a spawn run. I left Valadro in a star-fighter with a slipdrive, and went all the way to starbase_420 without consuming a single eye of ender (it said it consumed catalyst items, but it didn't). I then got in my LF, went through the Digitalia-Regalis slip-gate manually, and used the Slip-Drive to go all the way to spawn without using up any fuel (again, it said it used up catalyst items, but it didn't take them out of the hopper).

**Comment by Dibujaron** [comment]
Stupid inventories have always given problems. Thanks for reporting, I will look into it.

**Comment by Dibujaron** [comment]
fixed, thanks for reporting!
