### ISSUE TITLE
Weird cannon and ship armour behaviour.

### ISSUE THREAD

**Issue by Siigillum** [StarQuestMinecraft/StarQuestPublic#236]
Tested in regalis. Cannons shot firing West or North destroy iron bars and stone slabs. Cannons fired South or East do not break iron bars not stone slabs. (or maybe i secrewed and it's the other way).

This renders ship armour uselss in at least 50% cases. Also can we have some clearifications / list of ship armour blocks (how blast proof they are, cannon proof, or turret proof or torpedo proof levels).

**Comment by GroxTerror** [comment]
Stone brick slabs and stairs are nice looking, but in my testing, iron bars, iron blocks, diamond blocks, and gold blocks are the most effective. (ex. Ship covered in iron bars is very effective)

Otherwise- very interesting. I could help you test this when I get back to Quav.

**Comment by Dibujaron** [comment]
This was fixed. Thanks for reporting.
