### ISSUE TITLE
Ship armour no more exists.

### ISSUE THREAD

**Issue by Siigillum** [StarQuestMinecraft/StarQuestPublic#238]
After the recent explo changes no blocks like slabs, stairs, bars etc act like armnour. They are obliterated like wool when shot with cannons. Also wool burns much faster to cannoonns now.

**Comment by GroxTerror** [comment]
Weird...

**Comment by Siigillum** [comment]
Fixed now. Armour works like it should I think. At least cannonwise. havent tested vs torpedoes yet.
