### ISSUE TITLE
Torpedoes broken, no explosions

### ISSUE THREAD

**Issue by Siigillum** [StarQuestMinecraft/StarQuestPublic#239]
Torpedoes do nto work at defalos, no explosions.

**Comment by Siigillum** [comment]
Torpedoes WORK in digitalia.

**Comment by Siigillum** [comment]
Torpedoes WORK in regalis as well.

**Comment by Siigillum** [comment]
Torpedoes are STILL BROKEN in Defalos.

**Comment by Dibujaron** [comment]
I still don't even know what to do with this one. You appear to have unique skills.

**Comment by awangatboo** [comment]
Old SQ 2.0 Bug.  Closing.  If there are issues like this in SQ 3.0 please re-post.
