### ISSUE TITLE
AFK kick not working?

### ISSUE THREAD

**Issue by awangatboo** [StarQuestMinecraft/StarQuestPublic#240]
I think there might be a problem with the 16 min AFK kick not working.  I like to leave my toon AFK when I am going to to quit the game for the night or when I am going to be gone for a while to let my farms grow for another 16 mins.  The issue that happened yesterday was I was gone for almost 3 hours and I was still logged in.  I was not in any AFK system trying to keep me on.  I should have been logged out.  Today I logged in at ~6:40 local time and when I am creating this ticket I am at work and dynmap shows that I am still logged in.  It is now 8:31 local time.  This looks like I am not being kicked after the 16 mins.  When this issue happened last night krayolla came over to make sure he did not see anything that might have cause my toon not to be kicked.

**Comment by Siigillum** [comment]
I knwo Dib was saying something about this afk-kick bug when one would be kicked on planet entry. He fixed the bug I think, this might have caused this afk kick plugin to malfunction maybe?

**Comment by awangatboo** [comment]
I am going to close this one as the other day I was kicked for being AFK
