### ISSUE TITLE
quav ships bug

### ISSUE THREAD

**Issue by ps3wolvrine14** [StarQuestMinecraft/StarQuestPublic#241]
on quav ships are being a tad buggy. sometimes moving a ship is causing many blocks to be deleted right after detecting the ship. the blocks effected are all blocks that need a block to hang on. (ladders, signs, ect.) and pistons.
noticed on my gunship however not on my light freighter.
i only care abt my 4 pistons.
important note: if you unpilot and repilot the ship will still fly even tho the blocks are missing. 
what happened to me:
when i first tried to move the ship my ship sign disappeared and the ship didn't move. i placed a new sign (after /stopriding) in the same place. no sign was placed but i lost 1 from invo. placed a new sign somewhere else and it placed. redetected and moved and the blocks disappeared apart from the new ship sign. i clicked the sign (unpilot) then clicked again to test if it would. and it let me fly. it ignored the missing saved blocks.
i have a schematic of the ship from b4 this happened.

some1 else also posted abt this on the fourms:  http://www.starquestminecraft.com/starquestforums/m/17078810/viewthread/19022191-ships-bugged-on-quav

**Comment by Dibujaron** [comment]
This was fixed, thanks for reporting.
