### ISSUE TITLE
Miner problems on Quav

### ISSUE THREAD

**Issue by StarquestBaron** [StarQuestMinecraft/StarQuestPublic#242]
Somewhere around 8:00 AM Eastern, January 28, I was trying to operate a miner in my WG on Quav.  When I moved the ship forward one block, it mangled itself into the wall I was mining (poly and iron blocks actually transposed themselves) and the sign disappeared.  Unable to leave the ship because it insisted that I was still riding, I began breaking blocks hoping to find the hidden sign.  Some blocks broke but others behaved as if I did not have permissions.  At some point during this, all of my available inventory slots began filling up with iron blocks.  I gave those to Krayolla when I saw him later.  And if you want it to be a just little bit weirder, :D the poly ship blocks that regenerated when I tried to break them came back white, though they started out red.  

I logged out for awhile and when I logged back in I was able to leave the ship but still couldn't break the rest of the blocks.  I tried again around 10:30 and everything was breakable at that point.

Logging in the same evening, when I attempted to operate a new miner (shortly after Dib had restarted the Quav server, ~~ 6-ish?), I encountered a similar problem.   My ship did not mutilate itself this time and there were no magic iron blocks, but I have logged out once again, trapped on my partly disassembled and partly white miner.

**Comment by GroxTerror** [comment]
Welcome to Quav.

**Comment by Dibujaron** [comment]
This was fixed awhile ago, I forgot to close it.
