### ISSUE TITLE
Existing SQActivators no longer work in 1.8

### ISSUE THREAD

**Issue by Afgncaatp** [StarQuestMinecraft/StarQuestPublic#244]
SQActivators that were in place before the 1.8 upgrade no longer function.

You can break and replace the sign and then it works. I'm sure every one would be super grateful if we didn't have to do that to our multitudes of activators though.

**Comment by GroxTerror** [comment]
What do you mean by "SQActivator"?

**Comment by Afgncaatp** [comment]
I believe SQ Activators was the name Dib gave for his custom redstone bridge replacement.

**Comment by Dibujaron** [comment]
All activators have to be updated in order to work again. Thanks for reporting.
