### ISSUE TITLE
bosk server error

### ISSUE THREAD

**Issue by ironjim92** [StarQuestMinecraft/StarQuestPublic#246]
Describe the error.
bosk was glitching bad, i tried to fly in after it said it was fixed and lost the ship inventory and died then same happened trying to leave bosk twice

What steps can I take to reproduce the problem?
1.leave or enter bosk

If it was a permission-related error, what rank are you?

Do I need to check the processing? (Hint: The answer is yes)

If it was a starship related error, what type of ship were you flying, and what were you doing exactly before the error occured? gunship and 2 starfighters

Please provide any other relevant information here:
inventory isnt the issue id like my ships back though

**Comment by awangatboo** [comment]
I think this was a one day event.  From what I have been told if there are glitches that cause one time issues they should be in the help section on the forums.  If you do not have this issue any more I would recommend closing this ticket.
