### ISSUE TITLE
Chests in WorldGuards

### ISSUE THREAD

**Issue by JUSAPlayer1** [StarQuestMinecraft/StarQuestPublic#247]
So I broke into a WorldGuards this morning to raid it but I was told 

You cannot open something yiu cannot see

When I tried to open the chests. There were no blocks in front if or on top of the chests so I do not know why it would give me this error. Also blocks that used to be explosive, wood planks, dirt, weak blocks, no longer explode via cannons or turrets. Are either of these intended?

**Comment by brickworm2012** [comment]
Yep. Intended. No more WG raiding. :(

**Comment by MikeBurk** [comment]
Correct, WGs have Chest Access off now every where.  Base raiding is discouraged.
