### ISSUE TITLE
Towny Name Change Error

### ISSUE THREAD

**Issue by rubihube99** [StarQuestMinecraft/StarQuestPublic#248]
WHILE YOU READ THIS KEEP IN MIND THAT I DIDN'T READ THE FRONT PAGE BEFORE UPDATING NAMES, I CHANGED MY NAME 3 HOURS BEFORE THAT WENT UP!

So, now onto the issue.
When I changed my name, my name updated (Like it should've) but my town was still under my old username, rubihube99. While I know that there's "nothing you can do about it" StealthyDev confirmed that there may be a solution here. I've got some idea, but I'm not sure how it'd work.
These are the steps I propose might fix the problem:
1) Add me to the town of Jerusalem (my town on Kelakaria)
2) Use your magic perm powers to make me mayor of the town
3) I kick out my old Username, because I don;t have that anymore.
4) Problem Solved?

Again, I'm not sure how you'd go about it, but I think this can be fixed. I'm really scared of losing my town, and I'd have a lot of stress off my head if this was resolved.

**Comment by awangatboo** [comment]
This issue should be closed as Towny is no more on SQ.
