### ISSUE TITLE
[rankup] current money is displayed as 0.0 regardless of actual balance

### ISSUE THREAD

**Issue by emitLLort** [StarQuestMinecraft/StarQuestPublic#249]
Desc: "Current money" that is displayed in /rankup output always shows 0.0. 

Notes:
- While this is occurring, selling items at spawn does not increase "current money" under /rankup.
- Reportedly started occurring after the update to 1.8
- /bal will still show correct balance

Environment: SQ1.8
Steps to reproduce:
1. Type /rankup into chatbox
2. Press enter

Expected:
Chat displays "Current money: <current balance> ..."

Actual:
Chat displays "Current money: 0.0 ..."

**Comment by LittleWolf30510** [comment]
Fixed.
