### ISSUE TITLE
Lost 41 Lead Clusters!

### ISSUE THREAD

**Issue by umutergut1** [StarQuestMinecraft/StarQuestPublic#254]
I left Quavara, then my whole Inventory was rollbacked. I lost 41 lead clusters that I was going to sell. Can I get a rollback please? (I don't have a picture of them, I just have photo of me smelting lead.)
![2015-02-05_18 36 17](https://cloud.githubusercontent.com/assets/10879998/6076959/c68c72e0-adf2-11e4-871a-8f76cd0e6c02.png)

**Comment by GroxTerror** [comment]
Did you change your name?

**Comment by umutergut1** [comment]
Nope, It just happened. I don't  know why, too O.o

**Comment by TheMindaugas** [comment]
Didnt your town member take them? Thats gameplay, not a glitch

**Comment by Dibujaron** [comment]
Thanks for reporting, I know the cause of this and will fix it soon.

**Comment by LittleWolf30510** [comment]
We cannot refund the items (as per the readme of this repository). The reported bug has been assessed and dealt with, thanks for reporting.
