### ISSUE TITLE
Origin Tree farm [Involves precious new players]

### ISSUE THREAD

**Issue by brickworm2012** [StarQuestMinecraft/StarQuestPublic#256]
Each tree farm pod is missing half it's saplings.
Also, albeit unconfirmed, it appears players cannot touch grown trees at all. I have been unable to  break leaves

**Comment by brickworm2012** [comment]
Okay, reidentified the problem. Saplings aren't replanting, and half of the saplings on the side of the pods don't appear to grow.

**Comment by GroxTerror** [comment]
How awful. Looks like Dib's WG update protected more than chests...

I think the way he did it was a big claim and only certain areas could be broken. Or maybe it's something to do with Towny friends? I don't know.

**Comment by brickworm2012** [comment]
Currently it's that one pod I could find where the saplings would respawn, and grow.

**Comment by MikeBurk** [comment]
Fixed!

**Comment by brickworm2012** [comment]
The noobs thank you.
