### ISSUE TITLE
sq priority and old perk from an old player

### ISSUE THREAD

**Issue by ekarlate** [StarQuestMinecraft/StarQuestPublic#257]
Hi ! I am a member of SQ for a long time now, back in the days we could buy lots of perk
way before the new eula.

i heard prior to the new eula that member that had buy those perk will keep them.
hope it still true but today i found out a small problem.

tbh i really think i made a good part i putted in SQ more than a hundred dollar over the time. i did even paid for some of my friend back then (even for AOS i paid for monthly subscription for few).

anyway my problem is today i was not able to log in because it seems i dont have SQ priority.

the first thing i did bought back then was a reseved slot ''for life '' for 20$ back then i guess

i had many problem with other perk i had prior to bungee too i remember having a big talk with dibu after bungee telling me the impossibilities to give me back those perks and told me ill get AFK perk instead to replace all that. then i had it for long. but now i fear i lost this one too since the first thing i bought is lost too.

so all in all. i just want to know clearly what will happen now. should i have to rebuy everything? did i lost my thing? i just want i clear response whatever it is.

Thx btw ill continue to play SQ as i love way too much this server. I am not mad i just want some info cleared up.

thx Eka
( sorry for my english iam a french dude)

**Comment by GroxTerror** [comment]
You've missed a lot. Submit a Support Ticket for this on the forums. And for "Reserved Slot Forever"; the closest thing is a year of priority for $50.

I hope I helped you somehow.

**Comment by Dibujaron** [comment]
Your English is fine, better than many Americans haha.

Unfortunately, most of the perks you purchased are no longer available on the server, so we cannot give them back to you. I will be happy to give you six months of priority to compensate you for your lost value. We're sorry about this, a lot has changed since you were here last :P
