### ISSUE TITLE
Infamy on killing broken?

### ISSUE THREAD

**Issue by TheMindaugas** [StarQuestMinecraft/StarQuestPublic#258]
http://imgur.com/Kv2CNDR
(Turning off dat jammer, tehehe)
Chewbacca is an affluent meaning 4 infamy to be awarded. I got 0 instead. Though I have twice the infamy for warlord, it is pretty fun to shoot things up and request ransom. Failed to pay the ransom ended up like test subject above.

**Comment by Dibujaron** [comment]
This was fixed.
