### ISSUE TITLE
'blockaderunner' and 'heavyfreighter' no longer fit on newly created signs

### ISSUE THREAD

**Issue by russellcampbell** [StarQuestMinecraft/StarQuestPublic#260]
Due to character width limits in 1.8 instead of the 16 char limit in 1.7, at least the two ship labels above can no longer be entered on a sign.  The result is existing ships of these classes will fly and re-detect, but new signs can not be created.

**Comment by russellcampbell** [comment]
Update:  Through extensive testing of variables, It seems that this bug is client dependent, possibly due to font width rendering per OS.  So some user's will have this problem and others will not.  A quick fix I found for my setup is to temporarily turn off the texture pack and the default MC font will fit the labels.  Once the sign is created I can switch back to the SQ pack.

**Comment by Dibujaron** [comment]
Fixed, there was a frontpage post about this, starships now have short names that you can use, thanks for reporting.
