### ISSUE TITLE
Droppers immune to torpedoes/cannons.

### ISSUE THREAD

**Issue by Siigillum** [StarQuestMinecraft/StarQuestPublic#262]
Found out droppers are as resistant as furnaces now. Looking forward to see dropperclads soon. They used to be similar to wool.

**Comment by Siigillum** [comment]
Hoppers are imune too. The new era of hopperclads?

**Comment by Dibujaron** [comment]
This was necessary so that ships didn't lose their stuff when being shot. I haven't seen any hopperclads yet, so I think we're okay.
