### ISSUE TITLE
Locked doors not working with redsotne

### ISSUE THREAD

**Issue by lawrencethefrog** [StarQuestMinecraft/StarQuestPublic#264]
Locked doors will not respond to redstone signals.
This occurs on Iffrizar, but not on Valadro where doors work normally.
It happens with a door in the wild, but I haven't tested it with doors inside WGs, factions, or towns.

Steps for reproduction:
Make a door (iron or oak) on Iffrizar.
Lock it with a [private] sign.
Attempt to open the door with a pressure plate, lever, or other redstone device.

**Comment by Dibujaron** [comment]
Locked doors shouldn't respond to redstone signals, this is intentional. The fact that it is different on two different planets is a bit weird, I will look into it.

**Comment by awangatboo** [comment]
Lawrence this still an issue?  If not can we close this?  If not can you fix it?

**Comment by awangatboo** [comment]
Closing all bugs in preparation for SQ 4.0.
