### ISSUE TITLE
Towny being mean

### ISSUE THREAD

**Issue by Ashen44** [StarQuestMinecraft/StarQuestPublic#265]
so I recently got a few new residents in my town, and one of them claimed a plot in my town. all fine and dandy. problem is, after claiming that plot, he could no longer do anything there. like, nothing. he is very distraught as his house is currently locked down from anyone but mayor and I would like support on this as soon as possible.

**Comment by Siigillum** [comment]
Did he change name recently?

**Comment by Ashen44** [comment]
he did not

**Comment by Dibujaron** [comment]
I'm assuming this was fixed, as nobody else had a problem.
