### ISSUE TITLE
Tree Farm issue

### ISSUE THREAD

**Issue by GamingOverlord** [StarQuestMinecraft/StarQuestPublic#266]
Last night I used the tree farm with charcoal as fuel for about an hour.
I used jungle saplings as they give the most wood per sapling.
I let it self power and i sat there with bonemeal.
However, when I logged on this morning, it would not work.
Now, it will only accept regular coal.
This throws a metaphorical wrench into my plans.
I know this was not intended as I already used it for a large amount of time with charcoal.
I believe it might be related to the reset of Valadro, as lawrencethefrog experienced some elevator issues at the same time.

**Comment by awangatboo** [comment]
I was told this change was intentional.  Running tree-farms on charcoal is very OP.

**Comment by GamingOverlord** [comment]
Well now they are very worthless

**Comment by awangatboo** [comment]
Not worthless but not at OP as before.

**Comment by GamingOverlord** [comment]
They are not powered by a renewable resource, therefore they can be exhausted and are worthless.

**Comment by awangatboo** [comment]
They can also be powered by blase rods.  Anyways if you do not like it take it up with the staff I am just stating what I know.

**Comment by MikeBurk** [comment]
It was a bug that Tree Farms used charcoal earlier.  That bug has since been fixed.
