### ISSUE TITLE
.Pistons / Landing gear disappear

### ISSUE THREAD

**Issue by awangatboo** [StarQuestMinecraft/StarQuestPublic#268]
I have been having an issue with my ships.  For some reason the pistons disappear.  This is really strange as most of my ships are right on the edge of specs.  I have a starfighter that is exactly 200 blocks.  Because it is 200 blocks I have 6 droppers in it.  My Landing gear disappear and if I leave the planet I can not fly my ship because there are to many droppers.

**Comment by GroxTerror** [comment]
Same here. The landing here becomes an invisible, unbreakable block. This has been a long-time issue.

**Comment by Dibujaron** [comment]
This happens if you move your ship while the piston is still retracting or extending. For cannons, this was fixed, but for landing gear I suppose it can still happen. Under review.

**Comment by awangatboo** [comment]
Closing all bugs in preparation for SQ 4.0.
