### ISSUE TITLE
Urgent Ships Glitch

### ISSUE THREAD

**Issue by GroxTerror** [StarQuestMinecraft/StarQuestPublic#271]
Flying any vehicle will result in the driver and passengers to disappear from sight for a certain amount of time. During this time, there is no invisible particles, you can see no armor, no player, or no items they are holding at the time. Same goes for SvS; it becomes tricky when your opponent disappears from sight, as you don't know if they're still in the ship or coming at you.

The time to reappear seems to vary. It can be if the ship has stopped moving for a short time, or it could be if the ship releases. I haven't tested it much, so I'm not sure.

**Comment by lawrencethefrog** [comment]
This isn't new, and I don't see why it is so urgent. In the future could you please refrain from putting 'Urgent' in the name of issues, as it doesn't really help anyone. If the devs find that it is urgent, they can add a label themselves.

**Comment by GroxTerror** [comment]
It's very urgent. It makes SvS very difficult. If the Devs want more SvS, this would be good to fix...

**Comment by Dibujaron** [comment]
This is a duplicate issue, we're working on the other one.
