### ISSUE TITLE
Ship block destruction while in transition.

### ISSUE THREAD

**Issue by Siigillum** [StarQuestMinecraft/StarQuestPublic#272]
Finaly managed to narrow this one.Shooting moving blocks does not destroy them as it should. Much less blocks pop, the remaining just turn white. Tested with turrets and cannons. Not tested with torpedos.

This basically happens when one shoots at the moving ship.

**Comment by Evancooldude** [comment]
Is this still an issue?

**Comment by Siigillum** [comment]
Not really. It adds to ship survivability. Some blocks just turn white instead of being poped straight away. I call a unintended good feature.
