### ISSUE TITLE
Ex-Tr.Mod reverting to creative mode on login

### ISSUE THREAD

**Issue by lawrencethefrog** [StarQuestMinecraft/StarQuestPublic#274]
Today an ex-trial-mod approached me and told me that they were reverting to creative mode each time they logged on to the server. They would prefer to remain anonymous.

**Comment by MikeBurk** [comment]
We can't deal with the bug anonymously... Too much data to sort through trying to check every problem.

**Comment by lawrencethefrog** [comment]
I'll tell you the details in private.

**Comment by Dibujaron** [comment]
Fixed, thanks for reporting.
