### ISSUE TITLE
Hoppers not pulling out of single chests

### ISSUE THREAD

**Issue by Nickmiste** [StarQuestMinecraft/StarQuestPublic#275]
Steps to reproduce:
1) Place a chest
2) Place a hopper under the chest

The hopper doesn't pull out of the chest like it should.

Note: Double chests work the way they're supposed to

**Comment by Cutout1** [comment]
Is this related to the nerds on tree farms? I hear they did something related to hoppers not putting fuel in the furnaces, and maybe they messed something up.

**Comment by cmac17** [comment]
I have also encountered this issue. It is quite annoying, since I am tying to build a machine which requires a hopper drawing from a single chest at one point due to space constraints.

**Comment by greatwazoo** [comment]
hmm interesting Im having this probelm to (the only reason im using it is because hopper realys arent working)

**Comment by awangatboo** [comment]
It just works now for some reason.
