### ISSUE TITLE
Avalon Has No Upkeep?

### ISSUE THREAD

**Issue by cmac17** [StarQuestMinecraft/StarQuestPublic#276]
Describe the error.
I was checking different town for the fun of it, and when I did /t avalon, I noticed that there was no upkeep shown?

What steps can I take to reproduce the problem?
1. Do /t avalon.
2. Check for upkeep
3. Do / t <any town name> to cross-check the issue

Do I need to check the processing? (Hint: The answer is yes)
Yes? I honestly have no idea.

Please provide any other relevant information here:
 To make sure it wasn't something about us not being in the nation that prevented me from viewing it, I also did /t ironloch, and theirs showed. I also checked Mythrea and Paradise, adn htey showed as well.

**Comment by lawrencethefrog** [comment]
I can confirm this has been a bug for a few months now.

**Comment by cmac17** [comment]
So is anything going to be done about it?

**Comment by MikeBurk** [comment]
It should be fixed now and back taxes were paid.
