### ISSUE TITLE
Pilot bouncing in the cockpit.

### ISSUE THREAD

**Issue by Siigillum** [StarQuestMinecraft/StarQuestPublic#278]
Lately there's a lot more of pilot bouncing in the cockpit, especially when multiple ships are flying in the area. Pilot gets message about leaving teh ship and is being teleported inside each few movement ticks. Much less problematic while autopiloting, mostly problematic in manual flight.

**Comment by Dibujaron** [comment]
This was fixed, it was an experimental change to movecraft, thanks for reporting.
