### ISSUE TITLE
Glitches on planet entry and/or exit

### ISSUE THREAD

**Issue by TheMindaugas** [StarQuestMinecraft/StarQuestPublic#282]
Some of my friends had reported numerous ship disappearance and invenotry loss to falling damage upon entries to Quav and Ceh, I had something very different. As I exit atmosphere of Bosk with my interceptor frigate, my XP levels were retained, but my inventory was cleaned. Luckily I took screen shots of inventory before.

http://imgur.com/IgAfmSc,ZRURRxK,sbj9iVm,RwifjFC,BexJ0ca,EvldlXo,u49f4ng,nggikP0,uQqSeXV,P9K5O62#9
After the trip(Ship is intact)
http://imgur.com/jbs4C8d

**Comment by Dibujaron** [comment]
This was fixed. Thanks for reporting!
