### ISSUE TITLE
Autopilot a bit fast...

### ISSUE THREAD

**Issue by brickworm2012** [StarQuestMinecraft/StarQuestPublic#283]
I haven't been able to test this recently, but I was flying in Digi in a starfighter converted into a gunship for trawling purposes. When I checked the debug screen to see where I was (being invis at the time) I realized I seemed to be going more then 10 b/s. I checked the autopilot, which had not converted over to the gunship form, and said 15 b/s. Then I rechecked F3. 
If my counting is correct, I was going 30 b/s. I was NOT using slipspace. Observe the X coordinates.
![](http://i.imgur.com/ZnnBEl3.png)
![](http://i.imgur.com/O5HHNcV.png)

**Comment by brickworm2012** [comment]
It is also 20 b/s in Regalis, in an LightFreighter.

**Comment by Gaming4me** [comment]
-you move every two seconds, so 15bps = 30 blocks and 10bps goes at 20 blocks, no?
