### ISSUE TITLE
Ship Shields Wonkier

### ISSUE THREAD

**Issue by brickworm2012** [StarQuestMinecraft/StarQuestPublic#284]
A pirate left his ship in our town. He left his name off the shield, meaning that until he pilots another ship, it will be stuck there. 
It seems to be a bug that an unnamed ship shield can activate no matter WHERE you are, whether town, faction, or worldguard.

**Comment by awangatboo** [comment]
Dib fixed the code to make it where the users name is put on the sign automatically.  This should resolve the issue.
