### ISSUE TITLE
Lost Miner to Valadro Crash

### ISSUE THREAD

**Issue by cmac17** [StarQuestMinecraft/StarQuestPublic#286]
Valadro crashed about 5-10 minutes ago, and I lost my miner in the crash. I don't remember how to build it, and Beaver tried to automatically recall it, but couldn't. Can a dev help out in getting this miner back?

**Comment by lawrencethefrog** [comment]
Have you got screenshots? The rule of thumb is that without screenshots, and if whatever you lost isn't stored in the system, we don't refund it.

**Comment by cmac17** [comment]
I can try to get screenshots now, I think that the remains are still there. Otherwise, I still have Beaver and minemod who will vouch for me, since they were there.

**Comment by MikeBurk** [comment]
What is the actual bug you ran into?

How did Valadro crash and how did you lose your ship?  Were you piloting during a reboot?

Either way, no refunds are done through the Git system, but we would like to solve the issue so it can't happen again.

**Comment by cmac17** [comment]
I was piloting, when the server for Valadro crashed. I went to Limbo, and about 10 minutes later when Valadro's server came back online, only 20% of the miner was there.

**Comment by LittleWolf30510** [comment]
Please don't post refund requests on github. Thanks

**Comment by cmac17** [comment]
I was told by two mods to post this as a bug report. Since there is a refund involved as well, it was in here too.
