### ISSUE TITLE
OK theres A bunch of signs at spawn In a huge Line 

### ISSUE THREAD

**Issue by hamhamfreak** [StarQuestMinecraft/StarQuestPublic#289]
I have a Screen shot  
![2015-03-04_13 58 39](https://cloud.githubusercontent.com/assets/9193367/6494516/3361956a-c277-11e4-915b-121ca7843ce9.png)

**Comment by brandon11801** [comment]
I believe that is just the trail of a ship moving, I see those quite often with the ship infront, try relogging.

**Comment by brickworm2012** [comment]
Occasionally entire ship hulks will be copied in ghost blocks for hundreds of blocks. Causes a lot of lag, and makes chests fizzle, but eventually they disappear.

**Comment by Dibujaron** [comment]
https://github.com/StarQuestMinecraft/StarQuestPublic/issues/296
