### ISSUE TITLE
Removal and Joining Towns

### ISSUE THREAD

**Issue by thejrusso101** [StarQuestMinecraft/StarQuestPublic#291]
Whenever a player is either removed or leaves the town, this player cannot seems to join another town.  It tells the player that they already belong to a town, even though their previous town's roster says otherwise.

**Comment by thejrusso101** [comment]
Two particular players who are having this issue are Jorcool and wildcman

**Comment by awangatboo** [comment]
I think this was fixed on 3/8/2015.
