### ISSUE TITLE
Deranking over and over

### ISSUE THREAD

**Issue by The1Ulost2** [StarQuestMinecraft/StarQuestPublic#292]
Ok firstly im posting this for a friend who doesn't have github but pretty sure i have all the details.

IGN: Daehtop

First we all applied for white list at the same time and it took daehtop about a week to get a sr mod on who could make him settler in game after it was approved (which is fine people are busy) (paddy was the sr mod). So then he finally does get made settler and it goes away about 15 minutes later... So then he waits another 2 days to find a Sr mod to do it again (general something i think this time). Then i gave him 50k so he could go colonist since we were farming together and i (drubrees) was selling everything. Then 15 minutes after becoming colonist that goes away. So today he talked to a sr mod (paddy) and told him and his response was too bad (which is ridiculous) (then when whispered if he is just going to be out 50k every time he tries to rank up he gets no response and SR Mod is still talking to his friends in chat) so heres our group of 6 is on the verge of leaving ur server which i know you dont care but just letting u know u have a bug and very very bad customer service from your staff.

**Comment by brickworm2012** [comment]
Paddy can be a bit... rough....

**Comment by The1Ulost2** [comment]
ya we gathered that... But any info on why Daehtop keeps getting deranked... its like 15-20 minutes after his rank is increased its dropped back down.

**Comment by Dibujaron** [comment]
Sorry about this. We've been having some issues with our ranking system. Daehtop has been set to Colonist to make up for the lost time, and George will be looking into it.

**Comment by The1Ulost2** [comment]
still says hes a settler colonist but his rankup is that of what a settler would see like you can choose colonist or pirate

**Comment by The1Ulost2** [comment]
to clarify his name has both tags [settler] [colonist] Daehtop and when he does /rankup it says choose between colonist and pirate

**Comment by Will5091** [comment]
The dual rank tag has been a issue for along Time and it even got me when I was citizen so I had 2 tags for nearly a month but once a staff member (paddy) helped me it was ok but if you look around there's always some one with this glitch. Don't worry dude it's so going to be ok :D

**Comment by Dibujaron** [comment]
This was fixed, thanks for reporting.
