### ISSUE TITLE
Rankup issue

### ISSUE THREAD

**Issue by thejrusso101** [StarQuestMinecraft/StarQuestPublic#294]
The player with the issue is ianthecoolkid.  He attempted to rank up Citizen.  However, upon doing his money was deducted from his bank and no rank was given.

**Comment by LittleWolf30510** [comment]
Has this only happened once? Or have you seen it happen to multiple people?

Thanks @thejrusso101

**Comment by thejrusso101** [comment]
This only occurred once in the event of someone actually losing their money.  However, that day, many people were unable to rank up.  Then the following day people were randomly placed back down to refugee.

**Comment by Dibujaron** [comment]
This was fixed, thanks for reporting.
