### ISSUE TITLE
Slip drives malfunction when server resets.  

### ISSUE THREAD

**Issue by thejrusso101** [StarQuestMinecraft/StarQuestPublic#295]
If a player is in slip space during a server restart, they will lose their ship and spawn in the solar system they entered slip space in.  The following issue happened to Unic0rnjunk101.  The player also said that they turned off their ship before the reset.

**Comment by awangatboo** [comment]
This does not make since.  Every time I have turned off my ship while in slip space the ship comes out of slip space.  If the user lost their ship I would think it is because they just stopped moving but did not release their ship.

**Comment by LittleWolf30510** [comment]
@Dibujaron

**Comment by thejrusso101** [comment]
I suppose this really doesn't matter at this moment since slip drives are down and I cannot test it.  Just figured i would throw it out there when they emerge again.

**Comment by Dibujaron** [comment]
Slipspace is dead for now, if I bring it back I will attempt to fix this.
