### ISSUE TITLE
Ship movement visual glitch.

### ISSUE THREAD

**Issue by awangatboo** [StarQuestMinecraft/StarQuestPublic#296]
We have had the issue for quite some time of the visual glitch that will happen when a ship moves.  This is the ship moves and a trail of signs, hoppers, droppers,.... will be left behind.  The items are not really there but can be seen by anyone that was in the system/planet when the ship moved.  For the user you can log out and back in and you will not see them but just because you do not see them does not mean someone else can not.  I have been chased after on more than one occasion by pirates that are using the visual glitch to track someone down even when they are invisible.  This would not be as big of a deal if pirates did not have faster ships that colonist.

**Comment by soronthar** [comment]
I think this is an issue with 1.8. Not long ago I saw a video of a "ghost block generator" in vanilla, that creates blocks that mimics existing blocks, prevent players from moving into them, decrease the durability of the tools if broken but drop nothing.

**Comment by awangatboo** [comment]
I had it happen in 1.7.10.

**Comment by awangatboo** [comment]
Closing all bugs in preparation for SQ 4.0.
