### ISSUE TITLE
Waitroom = Falling to your death

### ISSUE THREAD

**Issue by thejrusso101** [StarQuestMinecraft/StarQuestPublic#300]
Once the wait time is up and it is your turn to enter the server, you do get teleported to your planet as expected.  However, people seem to be falling through the Earth upon arrival to their planet.  Two confirmed case of this is TheMindaugas and TheEnderCow.

**Comment by Dibujaron** [comment]
This does not seem possible with the way the waitroom works, as the waitroom essentially simulates a login to StarQuest when you leave the waitroom and enter the server. I will believe it if it happens to more people, but for now, closed.
