### ISSUE TITLE
Priority Glitch

### ISSUE THREAD

**Issue by StarquestBaron** [StarQuestMinecraft/StarQuestPublic#301]
I found myself in the waiting room because my priority had lapsed.  I went to the store and renewed my priority status but I seem to be permanently stuck in the waiting room, even when there are less than twenty standard players online.  I renewed around six PM Eastern, 3/11.  When I log in I receive the thank you message for using priority but it puts me in the waiting room without adding me to the que.

**Comment by Dibujaron** [comment]
Fixed, thanks for reporting!
