### ISSUE TITLE
Machina pumps not working in towns

### ISSUE THREAD

**Issue by buba141** [StarQuestMinecraft/StarQuestPublic#302]
I built a machina pump to remove some water, but it doesn't work. The planks extend and the cauldron fills with water, but no water is removed. Flipping the lever to retract the planks also does nothing. The troublesome pump is at 46,64,-426 on Krystallos, in the town of Elentizia. I tested a pump outside the town borders, and it worked as expected.

**Comment by Dibujaron** [comment]
This is intentional, as in certain cases pumps could be used to grief towns in the past.
