### ISSUE TITLE
invis disguise 

### ISSUE THREAD

**Issue by thejrusso101** [StarQuestMinecraft/StarQuestPublic#304]
Players have access to /d ocelot setinvisible true.  Not sure what other mobs this works with.  Also, the effect does not go away with shooting an arrow but it does with swords or fists.  Thus, people in disguise can go invisible forever!

**Comment by brickworm2012** [comment]
Sweeet- I mean, BAN THE OFFENDERS

**Comment by Dibujaron** [comment]
This was fixed I believe. Thanks for reporting.
