### ISSUE TITLE
/limbo (First to do this?) Trapped

### ISSUE THREAD

**Issue by K9-Caper** [StarQuestMinecraft/StarQuestPublic#306]
So yeah. I was trapped in the waiting room and I logged out as a fell from the parkour. When I logged back in the next day, I was still falling there but the server WAS NOT full. So it respawned me back into the waiting room. I read the post on forums and I did /limbo. When I did, I was stripped down to the Refugee rank.

EDIT: I did eventually click on the planet I was at and I got my rank and inventory back. But I hope this information can be useful to you developers on for why this happened in the first place.

**Comment by Dibujaron** [comment]
Waitroom is disabled for now and will need a recode before it can work again.
