### ISSUE TITLE
Defalos explosions 0ff, weird cannon behaviour regalis.

### ISSUE THREAD

**Issue by Siigillum** [StarQuestMinecraft/StarQuestPublic#307]
Explosions were not working in defalos system today. Torps, turrets, cannnons. All broken. This situation seems chronic. Fixes itself sometimes.

Moreover some explosions seem to be more powerfull that usual in regalis. (cannons) They do not break armour blocks but break things next to armour (explosion).

**Comment by Mindaugas3** [comment]
Yeah i tested cannons in defalos(or more precisely, 1v2d some colonists) and their cannon shots COULD PENETRATE my iron bars. Also, stone slabs. Cannons could penetrate iron bar with 1 shot, normally they can't. Still EMPed and torpedoed their 2 gunships, still won the fight.

**Comment by Dibujaron** [comment]
This is siig's weird explosion breaking thing that he does that I still haven't figured out.

**Comment by brickworm2012** [comment]
So explosions are still either super powerful, or nonexistent?

**Comment by JUSAPlayer1** [comment]
This happened to me today. Hunting doc and I fired a 1 torp and 1 emp in quick succession. Boarded killed him. Went back to my ship to torpedo the rest but explosions broke. I don't know if it's something related to torpedoes but that's what happened for me today.

**Comment by awangatboo** [comment]
Closing this Old SQ 2.0 Bug.  If this type of problem is still happening in SQ 3.0 please open a new ticket.
