### ISSUE TITLE
Snow Golems without pumpkins

### ISSUE THREAD

**Issue by brickworm2012** [StarQuestMinecraft/StarQuestPublic#308]
Created a mob grinder on Ceh, using snow. However, when 3 snow blocks were placed on each other, it immediately spawned a snow golem. It then took a minute for the server to realize there was a snow entity on a fire planet before killing it. 
This happened twice.

**Comment by brickworm2012** [comment]
Unknown if this works on other planets.

**Comment by awangatboo** [comment]
It does not work on bosk.

**Comment by brickworm2012** [comment]
Thanks for testing... I'll take a guess it probably won't work on any other Reg planets. Can people on Iff or Val confirm it's not Digi?

**Comment by Dibujaron** [comment]
I fixed this, thanks for reporting.
