### ISSUE TITLE
Unable to place blocks and/or break anything.

### ISSUE THREAD

**Issue by Luckyme114** [StarQuestMinecraft/StarQuestPublic#311]
I was trying to see if cannons shoot through iron bars (which I now know they do not), and I made a small starfighter, with a cannon on it, and shot an iron bar. It pushed the iron bar, away, then fired one shot. I kept trying to shoot even with the bar pushed, and saw that it wouldn't fire through. So anyways, after a few shots, i went to move the iron bar back, just to double check that it wouldn't fire, and I couldn't place a block where the iron bar used to be. I found it odd, and relogged a few times and yet still, couldn't place anything. So my friend (brandon11801) came up to investigate himself, and ended up placing a water bucket. The water flowed around the block where the iron bar used to be, but didn't flow through the open area. He told me to see if it was a region I'd somehow claimed, and i tried and didn't find any region i owned. I have no clue how this would happen, but here is a screenshot of it. The glass is below where i can't place any block.
![2015-03-16_21 12 29](https://cloud.githubusercontent.com/assets/11512782/6680122/428c5cf6-cc21-11e4-8969-97d86a8b89c4.png)
(Not sure if the screenshot will go through or not)

**Comment by Dibujaron** [comment]
This is a visual glitch, it will fix after you relog, or possibly after a server restart.
