### ISSUE TITLE
Armor stands not able to be moved / broken once placed

### ISSUE THREAD

**Issue by awangatboo** [StarQuestMinecraft/StarQuestPublic#312]
When you place an armor stand it is placed.  Once you try to break it to move it you can not.  I have tried pushing it with a piston / dirt and the dirt just covered the armor stand.  For now I just buried my armor stand under-grown as I want to use these but I need to be able to control which way they face and such.

Oh yeah this was on Bosk.

**Comment by Dibujaron** [comment]
I believe this was fixed with the mobs overhaul.
