### ISSUE TITLE
Treefarm does not have an overflow

### ISSUE THREAD

**Issue by brickworm2012** [StarQuestMinecraft/StarQuestPublic#313]
As experienced by doctorwhofan92. 
His tree farm chest was full but it still mined down the trees, without drops. His farm block was iron, if that helps. Also was using coal blocks to power it. 
Cannot remember which planet he was on. Kel perhaps.

**Comment by Dibujaron** [comment]
This is intentional; they would cause insane lag if they dropped stuff into the world on overflow.
