### ISSUE TITLE
Slimes, Slimes, and more Slimes

### ISSUE THREAD

**Issue by Luckyme114** [StarQuestMinecraft/StarQuestPublic#315]
I'm on Kelakaria as of right now with my friend brandon11801. We were just going about our town, about to create a cactus farm, when we come up to the surface to realize, there are about... 1000 entities right here? I was lagging like crazy (brandon not so much as he's got a better computer), and he went off to explore the island, looking for slimes. As this exact thing had happened before. he found them, and started to suffocate them with sand. Didn't kill them all. So we're standing there, trying to kill them all, when they just keep spawning, like, they went from 1000 slimes to over 3000 slimes in under 5 minutes. and it's still rising as i'm posting this. No idea why slimes are spawning so rapidly in 1 block areas without light. We're even standing right there as they keep spawning! Help plz...

**Comment by Dibujaron** [comment]
This was fixed, thanks for reporting. Those kela slimes love to get it on. :)
