### ISSUE TITLE
No longer able to create new chest shops.  Only seems to affect me.

### ISSUE THREAD

**Issue by Architect752** [StarQuestMinecraft/StarQuestPublic#317]
About two or three days ago on while on Valadro I decided to change some of my chest shops around and found that I am no longer able to make them for some reason.  I am still ranked as an affluent so it should not be a rank issue.  I checked and rewrote the text on the signs for the chest shops several times in case I got it wrong and it still behaved like it was incorrect or random text.  I asked other players if they were affected by this as well and was told by another player that he had just made a chest shop an hour ago, so to my knowledge I am the only one who has this issue.

**Comment by greatwazoo** [comment]
actually one of the people in my town cant create shops in an area he owns.

**Comment by awangatboo** [comment]
We do not use chestshops in SQ 3.0 old issue should be closed.
