### ISSUE TITLE
/Value no longer works.

### ISSUE THREAD

**Issue by Architect752** [StarQuestMinecraft/StarQuestPublic#318]
The value command no longer works.  When typed in game it tells you there is no command of that name.  I have heard several other players say during in-game chat as well that /value was not working for them.  I am not sure if it is bugged or you guys removed it in preparation for project Willow.

**Comment by JavaInvader** [comment]
I'm not a dev or anything special but i heard mods say it was for project willow

**Comment by brickworm2012** [comment]
/value currently only works in Regalis. Why? Dunno.

**Comment by Dibujaron** [comment]
Fixed, thanks for reporting, sorry about that.
