### ISSUE TITLE
Rankup problem

### ISSUE THREAD

**Issue by CrazyCat0917** [StarQuestMinecraft/StarQuestPublic#319]
Username: CrazyCat0917
Problem: Thanks to bit of generosity, I managed to obtain 50k. I used it to try and rank up. I double checked my balance and did /rankup colonist. It took my money and announced that I had ranked up to colonist. I sent a message in chat and my tag still said settler. After several relogs, I discovered that the rankup failed. 

I apologize if this isnt the place for this type of problem. Also, Fiercefight has the proof if needed.

**Comment by Dibujaron** [comment]
Fixed, thanks for reporting.
