### ISSUE TITLE
Duty mode failing on Bosquevine

### ISSUE THREAD

**Issue by soronthar** [StarQuestMinecraft/StarQuestPublic#320]
I entered duty mode on Kelakaria, Tp'ed to Bosquevine to help a player, and when I tried to leave Duty Mode it got an internal error, leaved duty mode but remained on Bosquevine.

**Comment by Dibujaron** [comment]
George's overhaul of dutymode is due to be fixed soon, he says he will fix this.

**Comment by awangatboo** [comment]
Bosk is no longer in SQ.  Old Bug.  Closing.
