### ISSUE TITLE
Entering Planets Ship Being Eaten

### ISSUE THREAD

**Issue by JavaInvader** [StarQuestMinecraft/StarQuestPublic#322]
So the past week I've entered numerous planets and occasionally my ship gets eaten Tyler refunded me 2 times only half the ship was eaten the first second a front corner. then another ship i flew was eaten  in half no refund needed as it was a pile of flying wool. then Today my whole ship got eaten ...

Ships entering planets have seemed more buggy lately.

**Comment by Dibujaron** [comment]
See the other issue on this, comment there if it happens again, but I believe it to be fixed.
