### ISSUE TITLE
Log-in then Immediate Death from Height Limit Fall

### ISSUE THREAD

**Issue by Hockeyson48** [StarQuestMinecraft/StarQuestPublic#324]
I made a support ticket over a week and a half ago waiting on a response but waiting for an answer. After finding out they were broken I came here. This happened last Saturday so that is when the time stamps for the pictures were taken. 

So during that morning when I was using the skydogs grinder on Ceharram, technical issues with grinder (I don't understand them) made it unable to be used. I took a picture of my inventory before I logged off because it was compiled with armor and I wanted to make sure nothing happened to it. I then logged off because I wanted to finished some stuff up and come back on later today. When I logged back in, I was falling to my death from the top of the skydogs base on Valadro. This happened to me a few days before that Saturday too, but because of the lack of evidence I had I wasn't able to write a support ticket out. Thankfully I was able to write a ticket out this time because my inventory was around 600-700k worth of armor. The following link shows me falling to my death when I logged in today, and the armor I had from this morning (pictures 1 and 2 are the death, and the rest is my inventory).

http://imgur.com/fsRHDXi,jHoTX5C,lBFNrES,aEkzVD1,odsSHjD,9a8pKTu,Egq5AYs,gxi9ii2,dqCSQ0r,evf5E1g,pGVeoVB,L1mme8w,YtW8D91,hahf770,nqbiByc,wxGPucH,3NFgyps,sIHeLjz,2azvPX

I understand how this may seem all coincidental but I promise that this story is 100% legitimate. I was very upset when I saw that my inventory was cleared and I was falling to my death. Please do whatever is possible to fix this bug because many other people have experienced it as well. Thank you very much for reading this! 

I also ask that unless you are a mod/admin that is able to assist. Please don't post.

 -Hockeyson48

**Comment by Dibujaron** [comment]
You may be incorrectly being set for a login. I'll look into it, please let me know if it happens again.

**Comment by mcdouble** [comment]
If this could be looked into please. I timed out today IN my ship then log back in to fall from height limit and die and lose a full set of god tools... Please look into this because somebody else had this happen right after me.

**Comment by Mindaugas3** [comment]
it must have something to do with active cryopods

**Comment by Arjuncraft2001** [comment]
Must have something to do with Valadro. Both of the victims were both on Valadro so that seems to be where the issue resides.

**Comment by Arjuncraft2001** [comment]
Never mind my previous comment it was both Val and ceharram

**Comment by awangatboo** [comment]
Is this still an issue?  

Will close on 8/11/2015 unless @Hockeyson48 says this is still an issue.
