### ISSUE TITLE
Chat toggling broken

### ISSUE THREAD

**Issue by Gaming4me** [StarQuestMinecraft/StarQuestPublic#326]
So apparently you cannot /toggle chats, it guves you an internall error so far I only tested in quavara.

**Comment by brickworm2012** [comment]
Also apparently doesn't work on Ceh.

**Comment by Dibujaron** [comment]
I really hate the chat system.

**Comment by awangatboo** [comment]
The chat system allways has issues and this is a BungeeSuite issue.  ( I think it is seeing that I had the same issue on another server I managed)  Short of BungeeSuite being fixed I would recommend closing this issue.
