### ISSUE TITLE
Random crashing bug

### ISSUE THREAD

**Issue by connorlawrence3** [StarQuestMinecraft/StarQuestPublic#327]
I discovered this bug yesterday upon joining my friend's town. The bug is simply put - I randomly crash with weird errors that disconnect me from the server. It is happening so often that it makes the experience unplayable. Sometimes it happens immediately after I log on, to about 2 minutes. Below are examples of the errors I get when I randomly get booted.
http://gyazo.com/80955adb883e173b59f6781fa99fc064
http://gyazo.com/abcc58ff5b79b3b0595cecb04d388167 (This is the most common one, the values are as high and low as +/- 20 billion as seen here http://gyazo.com/4d13601d9e3ddcd104dc560285f56403)
http://gyazo.com/bb559773df4623b98527f2f03eb8a673
http://gyazo.com/35ddb72d85c88b910b76ee16437a64d2

**Comment by GroxTerror** [comment]
Were you using the modpack?

**Comment by Dibujaron** [comment]
If you're using mods we can't guarantee how they will perform with our server. our server does interesting things that some mods don't like. Try using vanilla minecraft or our modpack.
