### ISSUE TITLE
Planet Time out come back ship messed up

### ISSUE THREAD

**Issue by JavaInvader** [StarQuestMinecraft/StarQuestPublic#328]
So on val was getting ready to take a spawn run just started flying out of the hanger and all of the sudden i freeze come back and only half of my ship flew http://imgur.com/a/xIM3H
I didn't lose cargo but it really messed up the ship.

**Comment by Dibujaron** [comment]
Attempted Solution put into game, please let me know If it persists, thanks for reporting!
