### ISSUE TITLE
Rank Reset Upon Forumban

### ISSUE THREAD

**Issue by TotallyNotSatan** [StarQuestMinecraft/StarQuestPublic#330]
I got forumbanned. I'm now a Refugee. That's about all there is to it. Can I have that rank given back(I was an Affluent)?

I have my inventory and credits, so no problems there.

**Comment by Dibujaron** [comment]
I could fix this but I don't know who you are.

**Comment by TotallyNotSatan** [comment]
...I'm TotallyNotSatan(that's my IGN.) I was thegreensniper. I'm on Krys.

**Comment by TotallyNotSatan** [comment]
As of now, I'm still a refugee.

**Comment by Dibujaron** [comment]
fixed, sorry about the delay.
