### ISSUE TITLE
Proper Infamy

### ISSUE THREAD

**Issue by mcdouble** [StarQuestMinecraft/StarQuestPublic#331]
I was in Avalon. An Affluent player landed their flying carpet roughly a minute before I made it to them and broke the starship sign. I was awarded no infamy for it.  (Sorry if this isn't specific enough, never exactly made one of these before)

**Comment by Dibujaron** [comment]
Thanks for reporting, but just yesterday I finished coding the system that will entirely replace the current kill counting system, so I am not too worried about fixing this one. I would fix it, but it would take awhile to hunt this one down, so I'm just going to let it rest. Sit tight, we're really close with Contracts here.

**Comment by mcdouble** [comment]
Could I get my infamy for it though?
