### ISSUE TITLE
I spawned...

### ISSUE THREAD

**Issue by winecraft-dev** [StarQuestMinecraft/StarQuestPublic#332]
I was flying my ship out of the atmosphere when I realized that my inventory was emptied and that my ship was not anywhere outside of Kel. Before this, I had entered and exited Kel to get something out of my E-Chest

**Comment by winecraft-dev** [comment]
My IGN is J2D2_Crafts

**Comment by Dibujaron** [comment]
Did it tell you ""One of your passengers is not currently online, repilot to proceed without him"?

**Comment by winecraft-dev** [comment]
no

**Comment by winecraft-dev** [comment]
I just left the planet, but a few minutes later, I saw a message that told me that my shields had failed to deploy. I had reentered the planet to get something out of my e-chest, and I unpiloted it then.

**Comment by Dibujaron** [comment]
Okay, thanks, I have resolved this for the next server restart hopefully. Let me know if it happens again.

**Comment by winecraft-dev** [comment]
Wait

**Comment by winecraft-dev** [comment]
am I going to be getting my stuff back?
