### ISSUE TITLE
Boarding Ramps - Ability to use non-ship blocks

### ISSUE THREAD

**Issue by Liggo** [StarQuestMinecraft/StarQuestPublic#333]
The way a boarding ramp works it removes a block when it opens this allows the ship to transport blacks that previously would not be allowed as they are not registered by the ship sign check.

This has recently been used for activities such as the creation of an ender portal , a revision of the plugin advised after this event. perhaps so the boarding ram must be closed in order to fly the ship - This solution also adds realism.

**Comment by Dibujaron** [comment]
Fixed, thanks for reporting. Boarding ramps can now only use stairs and wool.
