### ISSUE TITLE
Forumban Ended, Still Unable to Post

### ISSUE THREAD

**Issue by TotallyNotSatan** [StarQuestMinecraft/StarQuestPublic#335]
This goes for both Groxeron and I. Stealthy banned us for a couple of days, and we're both unbanned now(as of last night.) Neither of us can post on the forums. No red X at our name. Can someone help, or is this an Enjin issue?

**Comment by brickworm2012** [comment]
I still saw a red X next to your name when you got on... but it's gone now...

**Comment by TotallyNotSatan** [comment]
Fixed.
