### ISSUE TITLE
Elevators breaking/not working

### ISSUE THREAD

**Issue by swils24** [StarQuestMinecraft/StarQuestPublic#337]
I don't have too much detail on the "why" but I've dealt with it twice now, quite far apart, timeline wise.

Previously, it was with Jusa at his Kel base.  Elevator (of 2 floors, separated by I think maybe 10 blocks tops) stopped working.  Even after breaking the entire structure down and rebuilding it, the elevator refused to function.  Structure is intact and properly constructed.  Moving 1 block over and rebuilding, it worked as normal

Then, today, evanaesarcaesar's elevator (2x2) stopped working when he tried to bring a sheep up it with him, he reported.  Rebuilding the elevator at any y-value in that 2x2 grid in which it had previously occupied didn't work, but reconstructing it outside of that 2x2 grid did work.

Hopefully other players can chime in with what they have found to break the elevators.

**Comment by Dibujaron** [comment]
This happens occasionally, restarts fix it. The elevator plugin is not one of ours so there isn't much we can do.
