### ISSUE TITLE
Cryopods not breaking properly

### ISSUE THREAD

**Issue by swils24** [StarQuestMinecraft/StarQuestPublic#338]
Had a report earlier today of a player who continued to respawn in their cryopod despite the sign not being there.  Apparently, breaking the block behind the sign will not count as breaking the sign itself, even though the sign breaks off, and the player will continue to respawn there as though they had a functioning Cryopod.

Taking this from a player report, didn't test it/can't attest to it myself.

**Comment by Dibujaron** [comment]
Fixed at next restart, thanks for the report!
