### ISSUE TITLE
Cryopod Glitching

### ISSUE THREAD

**Issue by wildcman** [StarQuestMinecraft/StarQuestPublic#340]
Hey I don't know why but everytime I die my cryopod glitches... how is it fair that if my cryo glitches and I don't go back to it that I just loose my stuff or have to keep wasting money on a noob ship.. I hope this issue gets resolved ASAP

**Comment by Dibujaron** [comment]
I need more information if I'm supposed to be able to try to help you. If it happens to you again, can I have a screenshot of your cryopod build, and can you tell me where you were when you died, and where your pod is (coordinates)? Thanks!
