### ISSUE TITLE
Unknown Cause of Death

### ISSUE THREAD

**Issue by StarquestBaron** [StarQuestMinecraft/StarQuestPublic#342]
At about 7:30 AM Eastern, I had a time-out disconnection on Krystallos.  When I logged back in I received the message that I had died.  I respawned in my cryopod with my inventory wiped. I was safe inside my base, so I was not killed by a mob while I was lagging.  No death message appeared in chat so I have no idea what happened to me.

**Comment by Dibujaron** [comment]
I can't do much with this without some more information. Please post again if it happens to you again. I'm sorry that I can't do more, but there is no way for me to even start to try to investigate this.
