### ISSUE TITLE
Fourm swear filter

### ISSUE THREAD

**Issue by Will5091** [StarQuestMinecraft/StarQuestPublic#346]
Saying f**\* and f***ing do not activate the potato filter

**Comment by Dibujaron** [comment]
@Moneybags118

**Comment by Moneybags118** [comment]
Thank you for reporting. Unfortunately the word filter can't do much about that unless we do every possible combination of letters and *. As long as they are not saying the word openly I'm not going to complain. If they did something like space out the letters (also unable to filter) and have the full word then you should report the post using the support tickets.
