### ISSUE TITLE
Charcoal

### ISSUE THREAD

**Issue by mcdouble** [StarQuestMinecraft/StarQuestPublic#348]
Hey not sure if this is a bug/glitch or not but I place a double chest on the ground, with a hopper on top feeding into it. Then another chest I place on top of the hopper, which as far as I know should feed anything in the top chest down below to the bottom one. Well whenever I have tried using charcoal in hopper contraptions recently, it hasn't worked. Not sure if this is a bug or not but i figured I might as well post incase.

**Comment by mcdouble** [comment]
Also, Dib/Stealthy/Littlewolf, you're free to call me stupid if I am just missing a crucial detail.

**Comment by Dibujaron** [comment]
Get someone else to look at this ingame if you would, to confirm that you're not just missing something. If you're trying to use charcoal with a treefarm it won't work. Otherwise, I'm not sure what's up. I will try to look into it, but please have someone else look at it and comment here.

**Comment by mcdouble** [comment]
Will do. Also, no I was trying to use for a smelter machine but I will get somebody else to look into it thanks.

**Comment by mcdouble** [comment]
I figured out the issue thanks. Closing it for you.
