### ISSUE TITLE
20min kill timer effective after a long period of time.

### ISSUE THREAD

**Issue by TiatLief** [StarQuestMinecraft/StarQuestPublic#349]
I was hitting Ginger_Walnut on Acualis, and a creeper blew up killing him; I went to his ship and broke the sign and it said to lay off. I was awarded no infamy for either. The most recent time I did anything that would trigger this would be a couple days ago when I found a random ship near the Skydogs claim on Acualis (which was his); I got infamy for breaking the ship sign even though way more then 5min probably passed (I think this was a known bug during the time?).

This is the first time I have used github so any advice on how to use it would be nice, oh and ty for taking the time to read this ^^.

**Comment by Dibujaron** [comment]
Fixed, thanks for reporting!
