### ISSUE TITLE
Cannot Connect to Server

### ISSUE THREAD

**Issue by JUSAPlayer1** [StarQuestMinecraft/StarQuestPublic#351]
Ok so I've had this issue for 2-3 days now and I've been posting to the forums with a few staff reply but no dev assistance so I guess it's time to post here....anyways

After the towny crash, and the server instant restart, I could not log back in that night because it game me this error:

Connection Lost
Could not connect to default or fallback server, please try again later: Java.net.ConnectException. 

Naturally, with it being 1am and the server not coming back up I just went to sleep. When the server did come up later the next day, I tried to login and received the same error message. I looked it up and it seems to be something from the server side, from what I can gather. I've tried every fix on my side, including router reset, computer reset, minecraft reinstall, etc with no success. After posting a help request on the server, a few players replied saying that it was showing a message in game that JUSAPlayer1 has left the game but no message saying I joined. This leads me to believe that the server thinks that I am already logged in. I decided to wait till the next restart, thinking that when the server kicked everyone it would reset who was and was not logged in therefore allowing me to rejoin. That was the midnight (EST) restart last night/this morning. I tried again after that restart with no success yet again. After that I went to sleep again and when I woke up this morning i continued to get this message. Swils tried to help me by going to ceharram and trying to /tp here me when I would login and he tried to create a cryopod active for me but that didn't work either. I'm at a loss what to do at this point, and would really like to get on since I just purchased a month of priority and it'd going to waste :P I logged off in the 99thLegion base on ceharram if that info helps at all. I pray that this doesn't reset my inventory/echest....cause that is literally everything I have on me lol. Any help is appreciated. 

Thanks
~JUSA

**Comment by JUSAPlayer1** [comment]
Has any devs seen this? How long should I expect to wait till I can log in...?

**Comment by JUSAPlayer1** [comment]
Not being able to play is killing me...

**Comment by Dibujaron** [comment]
You appear to be able to log in now, seeing as I talked to you recently, so I'm going to assume this is closed? It was probably an issue with your internet, or the server was down for part of it.
