### ISSUE TITLE
Ship turrets firing wrong ammo.

### ISSUE THREAD

**Issue by Kyle98martin** [StarQuestMinecraft/StarQuestPublic#353]
My ship turrets frequently fire the wrong ammunition but I have only tested this with AP and normal turrets. The AP turret fires normal ammo about 70% of the time currently and I have no way to be able to fix it, it just seems to fix itself. The normal turret will occasionally fire AP turret ammo although this is much less common then AP firing normal ammo. I've only had this occur on one of my interceptors and I've seen no one else with this issue.

**Comment by Siigillum** [comment]
That's what you get when 2 turrets are placed clsoe to each other so they actually share a turret sign.

**Comment by brickworm2012** [comment]
Really... interesting.
