### ISSUE TITLE
Ship signs not giving infamy.

### ISSUE THREAD

**Issue by Kyle98martin** [StarQuestMinecraft/StarQuestPublic#354]
Quite a short one but ship signs do not give any infamy if the pilot logs off while piloting the ship. Makes it quite frustrating with combat logging being allowed when you can't even get the infamy from signs currently.

**Comment by Dibujaron** [comment]
Cannot reproduce- more detail please?

**Comment by Kyle98martin** [comment]
The last few who people who have logged off on me when being chased in space have done so without unpiloting the ship. The ship doesn't seem to unpilot itself when they do this so no infamy is awarded for destroying the sign. There is no message or anything in chat and just treats the ship sign like a normal block when broken.

**Comment by Mindaugas3** [comment]
Which system/planet? AFAIK ship signs work in some planets/systems but not in all

**Comment by Dibujaron** [comment]
@TheMindaugas which planets does it seem to work in?

**Comment by LivesParkk** [comment]
This  also happens to me on every planet and space. People who log off without unpiloting don't seem to trigger the sign kill system.

**Comment by Gaming4me** [comment]
Regalis, two days ago, tried to kill Usaid2002 and his ship sign gave me the message that I had already killed him within the past 20 minutes. Not sure about the time it happened though.

**Comment by Gaming4me** [comment]
ah here it is.

[00:12:24] [Client thread/INFO]: [CHAT] You already killed that player in the last 20 minutes! Lay off for a bit...

that was on the 5th, GMT-3

**Comment by Dibujaron** [comment]
@Gaming4me and you hadn't killed him in the last 20 minutes? I guess that goes without saying, I just need to be sure.

**Comment by Dibujaron** [comment]
Fixed, thanks for reporting!
