### ISSUE TITLE
Cryopod Failure

### ISSUE THREAD

**Issue by Moneybags118** [StarQuestMinecraft/StarQuestPublic#355]
Player Involved: RedCanary
Crypod Location: Kel
Place of Death: Kel (literally right next to his cryo heh)
Cause of Death: Fall
Spawned at the spawn station

Pictures:
![2015-04-04_19 59 41](https://cloud.githubusercontent.com/assets/8053437/6995201/9c31b8b0-db07-11e4-8404-1700061613fa.png)
![2015-04-04_19 59 46](https://cloud.githubusercontent.com/assets/8053437/6995200/9c31be8c-db07-11e4-9240-8b6b194841e9.png)
![2015-04-04_19 59 50](https://cloud.githubusercontent.com/assets/8053437/6995202/9c32e014-db07-11e4-91fc-e32de7af6021.png)

**Comment by Dibujaron** [comment]
See frontpage post; I believe this just needs to be updated twice to work.
