### ISSUE TITLE
My door wont let me in.

### ISSUE THREAD

**Issue by larppoolius12345** [StarQuestMinecraft/StarQuestPublic#356]
![2015-04-05_09 04 46](https://cloud.githubusercontent.com/assets/11803780/6995962/fbdd6a1e-db72-11e4-8ffb-5bec165e58e5.png)

**Comment by Dibujaron** [comment]
I'm fairly certain this is a case of something having been done wrong. Make sure you typed your name right, or let it auto-fill your name for you. We have people with long names that have functional doors, so I'm pretty sure that's not the problem.
