### ISSUE TITLE
Time out + entry point

### ISSUE THREAD

**Issue by mcdouble** [StarQuestMinecraft/StarQuestPublic#357]
So randomly everybody timed out. I timed out standing on a pathway in Trinity Gardens, Avalon. I timed out, managed to get back in, and now all of the sudden I'm spawned in underneath the pathways in a hole and drowning. I spent an hour gathering all that stuff on the spot and I'm upset so this is all I really can say on the matter. This is all I think that really happened if that helps you recreate it or something.

**Comment by Dibujaron** [comment]
Thanks for reporting, did you get a chat message when you got spawned underneath that stuff? If you did happen to get a chat message it would help me out a lot in figuring out what broke.

**Comment by mcdouble** [comment]
I don't believe I got any abnormal chat messages sorry. I have been at times randomly getting an error message in chat though. Next time I receive it I will mark it down on paper

**Comment by MasterChiefMC** [comment]
I fell out of my friends ship when i timed out last week.

**Comment by awangatboo** [comment]
This was one of those strange events on the server that will never be tracked down correctly.Much code has changed since SQ 3.0.  Closing this ticket
