### ISSUE TITLE
Locked door does not let me in

### ISSUE THREAD

**Issue by larppoolius12345** [StarQuestMinecraft/StarQuestPublic#358]
The bug: After locking my base door with [private] the door does not let me in. It says I don't have permission even though it is MY door.

How to reproduce: Have a player with 14+ character name lock a door by writing [private] on a sign

Possible causes: Having a too long name that does not fit in a sign

Edit: It says that this container (door) is claimed by larppoolius12345 (me) but it still does not let me open it.

**Comment by brickworm2012** [comment]
Another possible cause is... well... did you manually right your name down? If so, it might have been misspelled.

**Comment by larppoolius12345** [comment]
No i wrote only [private] on the sign.

**Comment by dphfox** [comment]
I think your name exceeded the character limit on a sign. What's on the sign?

**Comment by larppoolius12345** [comment]
1st line: [private]
2nd line: larppoolius123

**Comment by larppoolius12345** [comment]
funny thing is that this worked 6 months ago (then I took a break blah blah)

**Comment by Dibujaron** [comment]
@larppoolius12345 if this is still a problem, where is your base? (planet and coords) I'd like to look at this door and see if I can see anything wrong with it.

**Comment by larppoolius12345** [comment]
-75 65 395 Boskevine example door in basement

**Comment by Nickmiste** [comment]
Possibly related to this bug:

xLordHerobrinex2 can't open private doors (even ones that he makes) because they are locked by xLordHerobrinex. Happens with longer names sometimes. I THINK it only happens if someone with a similar name logs into the server. That probably isn't the case, but it's still worth mentioning.

**Comment by larppoolius12345** [comment]
It says that this door is claimed by larppoolius12345 (me) when I right click on it.

**Comment by awangatboo** [comment]
This bug was most likely on an old version of Lockett.  The newest versions support open and closing by UUID and you do not even need to put your name on it.  If we have updated Lockett in SQ 3.0 I would recommend closing this bug.

**Comment by awangatboo** [comment]
Closing all bugs in preparation for SQ 4.0.
