### ISSUE TITLE
Co-Mayor bugged?

### ISSUE THREAD

**Issue by mcdouble** [StarQuestMinecraft/StarQuestPublic#359]
Hey so when I was in the town of Ironloch, the mayor and I agreed we would set ally perms on so I could use Ironloch's facilities while I left and joined Avalon for something. As assistant and co-mayor I did the command /t set perm ally on. It marks it down as ally perms on in /t, but didn't ACTUALLY give the perms I needed. I talked to lawrencethefrog about it and he mentioned co-mayor being bugged. He also said one of the main/sr. devs (Dib, Stealthy, LilWolf) would be allowed to set my perms straight. I am sorry that this isn't detailed enough but that's all that I did honestly.

**Comment by lawrencethefrog** [comment]
I had problems with co-mayor too a long time ago. These problems included not being able to claim plots for the town (though I was able to unclaim plots the town owned) and various other problems which I can't remember right now.
When the mayor (fiercefight) set me as assistant as well as co-mayor, the problems went away.

**Comment by mcdouble** [comment]
I was both when I tried turning ally perms on though.
Update: Ally perms are on in random plots in the town, just of course, not the ones I need.

**Comment by Dibujaron** [comment]
This is a Towny bug and so I'm not sure it's within our capacity to fix. Towny is an old plugin and it has a lot of issues that are still unresolved by its team. I will look into this, but definitely no promises.

**Comment by awangatboo** [comment]
No Towny in SQ 3.0 please close
