### ISSUE TITLE
Ship "Turned Off"

### ISSUE THREAD

**Issue by WillisDoering** [StarQuestMinecraft/StarQuestPublic#360]
While flying on autopilot, my ship disengaged autopilot and died in mid-space. No harm was done for I just started it back up and continued my marry way. This may just be a glitch (or I need to call a mechanic) , but thought I would post it in case it becomes dangerous.

**Comment by brickworm2012** [comment]
This sometimes happens if there is space junk in the way. I've often thought I was being jammed, only to find a sign or a wool block in my path.

**Comment by Dibujaron** [comment]
^ brickworm is right. if this happens to someone else I will worry, but for now, I'm going to chalk it up to space dust. Thanks for reporting though!
