### ISSUE TITLE
Krystallos dying?

### ISSUE THREAD

**Issue by LivesParkk** [StarQuestMinecraft/StarQuestPublic#361]
I was on Krystallos mining when chat exploded with error messages. I tried /who and got an internal server error, checking ttrough the dynmap showed I was the only person online. I got about 30 unable to create sign at coordinates. Chest fix messages started appearing in chat every 5 seconds. I got messages that I was joining and leaving dutymode. After a flurry of internal server errors and various other errors Krystallos went offline. It soon came back but I spawned  at krys spawn without my inv and nOT at my cryo. Krystallos then went on to crash nin a similar manner 6 more times.

**Comment by Dibujaron** [comment]
This crashing was fixed, sorry about that.
