### ISSUE TITLE
Enderpearls re-enabled

### ISSUE THREAD

**Issue by swils24** [StarQuestMinecraft/StarQuestPublic#367]
It's been said in a few locations, but thought I'd put it here anyway.  Centralization and all that.

Enderpearls are functional again, not sure if that's intended.

**Comment by Dibujaron** [comment]
We're discussing it, thanks for reporting.

**Comment by GroxTerror** [comment]
To be honest they'd be a cool addition.

**Comment by awangatboo** [comment]
This is still the case.  Dib was the decision made to keep this in the game?

**Comment by awangatboo** [comment]
Last thing I was told by SQ management was they are still trying to decide if they think this is OK or not.

**Comment by Evancooldude** [comment]
Has this issue been resolved?

**Comment by awangatboo** [comment]
Last I heard was they are going to disable them but I think they have not gotten around to doing that yet.
