### ISSUE TITLE
cryopod error

### ISSUE THREAD

**Issue by greatwazoo** [StarQuestMinecraft/StarQuestPublic#368]
at my town on kelkaria I have a cryopod even after redetection it still didnt spawn me at my cryo 
paddycraft verified i had built it correctly I can supply pictures if i need to

**Comment by Dibujaron** [comment]
Was your cryopod active? Where is it (coordinates)? When you died, what planet were you on? Where did you go when you were respawned? Do you know about what time this happened?

Thanks for reporting, this could be a useful test case.

**Comment by greatwazoo** [comment]
okay so no it wasnt active i dont know its coords cause im still at spawn BUT its at starenterprises in the building with the skeleton head by the door on floor 7 , when respawned i went to spawn , and I have know idea when this happened

**Comment by awangatboo** [comment]
Closing this bug in order to obtain better details in current Cryopod issues.  If you have another Cryopod iss please see this forum thread before opening a new issue.

http://www.starquestminecraft.com/starquestforums/m/17078810/viewthread/23552021-great-cryopod-bug-closing/post/last#last
