### ISSUE TITLE
Cannot place blocks in certain areas.

### ISSUE THREAD

**Issue by Arjuncraft2001** [StarQuestMinecraft/StarQuestPublic#369]
Ok so i have a big mix of factories in one area and I can't place blocks in some areas. Nick confirmed in creative that he can't either. I am not sure whether this is vanilla, but I am pretty sure this has to do with Machina Factory since it doesn't happen anywhere else. The coords are (-1562, 85, 205) on Valadro.

**Comment by brickworm2012** [comment]
Glitchy towny?

**Comment by Dibujaron** [comment]
@Arjuncraft2001 I went to the place and could not reproduce the error. I guess it went away on restart. Let me know if it happens again and thanks for reporting!

**Comment by Dibujaron** [comment]
believed to be duplicate of #375
