### ISSUE TITLE
Elevators make you fly! when your not in them!

### ISSUE THREAD

**Issue by RedCanary123** [StarQuestMinecraft/StarQuestPublic#371]
Today my friend killed me a few times while going up a elevator and I logged out with my cryopod activated. When i logged on I was jumping and realized i could fly. There is not much more i can say about this issue. Sorry if i disobeyed a rule on posting i am new to github.

**Comment by brickworm2012** [comment]
Cryopods have been connected to of a lot of whacky bugs lately. This is simply the latest.

And yes, this is definitely where you post, and how you post it.

**Comment by Dibujaron** [comment]
That's an interesting situation. Your flight should go away after you try to pilot a ship or anything, so I'm not too concerned about that, but I will implement something so that this doesn't happen again. Thanks for reporting!
