### ISSUE TITLE
Kills giving 20 minute cooldown error

### ISSUE THREAD

**Issue by Gaming4me** [StarQuestMinecraft/StarQuestPublic#373]
Alright so I went to kill BigHit5 on Valadro yesterday at about 22h - 1am EST, and when I got the kill (he's a colonist), it gave me the message saying I had already killed said player within 20 minutes.

**Comment by Dibujaron** [comment]
With kills, the 20 minute kill timer is still enabled. This is intended. Unless you hadn't killed him in the last 20 minutes?

**Comment by JavaInvader** [comment]
Yeah Same has happened to me Haven't killed them with in weeks possible maybe even never and it says You killed them in the last 20 minutes.

**Comment by Kyle98martin** [comment]
I also experience this bug today when I killed Usaid2002 who I last killed 2 days ago.

**Comment by Arjuncraft2001** [comment]
Same happened to me. Killed AlanDragon, but no kills. (On Valadro)

**Comment by GroxTerror** [comment]
No kills for Seamonster or MasonTheGame... or just anyone for that matter

**Comment by Nickmiste** [comment]
This bug seems to happen whenever I kill Usaid. I can't get kills from him anymore. He's not the only one, but he's the only one who comes to mind.

**Comment by JavaInvader** [comment]
Same for Usaid2002 Cant get kills when i kill him i think he is broken.

**Comment by awangatboo** [comment]
Kills like this do not matter in SQ 3.0 please close
