### ISSUE TITLE
Block 36

### ISSUE THREAD

**Issue by Nickmiste** [StarQuestMinecraft/StarQuestPublic#375]
There have been a number of occurances of locations where no blocks can be placed. After much investigation, I have found out that these blocks are id 36, piston extension. I have no idea what causes them, though they seem to appear by redstone. A few properties to note:

-No blocks can be placed at this blocks location
-Players can walk through the block
-Water doesn't flow through the block
-You can remove this block by flying through it with a ship

**Comment by Dibujaron** [comment]
Ah, that would explain it. I believe these can be removed by right clicking them. It'll probably fix when we update our spigot version, those have a way of appearing as bugs a lot.

**Comment by brickworm2012** [comment]
This has been around for a while. Occasionally I saw these on Quav from a dogfight. 

Also, if the pistons are extended and the piston block itself is deleted, it will drop a full piston. I've seen this happen at Origin station when the ship is cleared.

**Comment by awangatboo** [comment]
Is this still an issue?  I remember seeing this a lot in SQ 2.0 but I have not seen it at all in SQ 3.0

**Comment by awangatboo** [comment]
Will close this ticket on 8/11 if no other comment.
