### ISSUE TITLE
Ship Signs Not breaking

### ISSUE THREAD

**Issue by JavaInvader** [StarQuestMinecraft/StarQuestPublic#378]
Ok so the new feature, I just tried making a ship didn't have enough wool needed to change ship sign said I could not break it because I flew it in the past 5 minutes (not true didn't have enough wool to even fly) so i had my faction mate try to break it he could not even break it and his name isn't on the sign.

**Comment by JavaInvader** [comment]
Also the 5 minute timer doesn't seem to be working

**Comment by Kyle98martin** [comment]
I can also confirm that ship signs are currently impossible to break but they still give infamy when you attempt to break them if the ship has been piloted.

**Comment by brickworm2012** [comment]
Repeatedly?

**Comment by Dibujaron** [comment]
This was fixed, thanks for reporting.
