### ISSUE TITLE
Ship Signs

### ISSUE THREAD

**Issue by GroxTerror** [StarQuestMinecraft/StarQuestPublic#379]
Recently Uni and I were attacking Seamonster and MasontheGame. I noticed a large iron ship (Seamonster's)  and went over invisible to check it out. I tried breaking the ship sign but was prompted with, "You can't break your ship sign (insert other text here)" I was flying my ship a minute earlier, so it may have made it so I couldn't break theirs. Also, I had killed Seamonster a minute earlier and the kill didn't register saying I had killed him previously, which I hadn't. It also seems to affect all surrounding blocks, so I couldn't rip off the sign area to tow away the loot. After a lot of risky breaking, it was a large chunk of raidable material just in the middle. I tried to register it as a new ship but it said there were forbidden blocks on the craft (couldn't find any)

Note: I was playing under Xeronne at the time.

**Comment by Dibujaron** [comment]
This was fixed, thanks for reporting.
