### ISSUE TITLE
Fall into void

### ISSUE THREAD

**Issue by Nixx59** [StarQuestMinecraft/StarQuestPublic#382]
I was fly to Kelakaria when The server gave me a error message and kicked me off. I immediately rejoined, but spawned in Regalis with no items and then I fell into the void and died.

**Comment by Arjuncraft2001** [comment]
Just to make the dev'a life easier: what was the actual error message? 

Without the specifics they can't find out what happened.

**Comment by Mindaugas3** [comment]
something similiar had happened to me just the day after no refund policy. Internet started lagging(usually it has pretty low ping, around 130 ms) and i was salvaging things(like quartz slabs) and fell into the void. With my new p4u3 and god bow.

**Comment by Dibujaron** [comment]
I'm going to mark this unfixable because I'm pretty sure it can't be fixed. I can't test it because I can't force my internet to lag like that. I'm thinking of a couple of ways to redesign the communication protocol to not rely on the player, but we'll have to see.

**Comment by liv4ths** [comment]
Okay so about 20mins ago, Matthew385 was traversing reg when he tried space walking back to his ship and fell into the void and died when his computer lagged. Idk whats eles to say other than that.

**Comment by oreomium** [comment]
<Matthew385> : I was walking back to my ship from spawn, still have about 1mil of melons left on that freighter. I was suffering extensive internet lag. Had to restart my computer several times.

**Comment by awangatboo** [comment]
Old issue please mark as closed
