### ISSUE TITLE
Ship Sign

### ISSUE THREAD

**Issue by WillisDoering** [StarQuestMinecraft/StarQuestPublic#383]
I had just logged on for the first time since the latest update came into effect and couldn't break my ship sign. I tried an half hour later and still it gave me the message that I need to wait 5 min. after starting my ship. I couldn't start it due to pieces are missing and I don't know from where. I was in my world guard at the time and go under the username WillisDoering.

EDIT: I broke it, it may have just been a glitch.

**Comment by Dibujaron** [comment]
This was fixed, thanks for reporting.
