### ISSUE TITLE
Ship sign breaking

### ISSUE THREAD

**Issue by MEHcommonsensebroken** [StarQuestMinecraft/StarQuestPublic#384]
logged in tonight to try and scrap what was left of my old ship cause i was informed a fix was coming at the next restart aka 1hour ago 

now onto the subject i am reporting about 

 on the subject of ship signs, you are now blocked from breaking your own ship sign within 5 minutes of having flown it. This includes the block behind the ship sign. This is because people, in one of the most stunning displays of butthurtness that I have ever seen, seem to have been breaking their ship signs and then combat logging in order to deny pirates their kill. At that point they've already lost everything that they're going to lose- they gain nothing from breaking the sign themselves- but they nevertheless break it just to screw the pirate. So now, thanks to them, all of you are inconvenienced. I really don't like the way I had to fix this, it's going to be a pain for good-intentioned users, so if anyone has a better idea for solving it let me know.

this section is from the front page aka the feature about the 5min sign breakage it is still causing players problems 

and as i was informed this was not enough

i was on krystallos 
trying to break my own sign from 2 hours ago 
as well as a friends from a month ago 
is that enough?, if not meh i tried

**Comment by Dibujaron** [comment]
This was fixed, thanks for reporting.
