### ISSUE TITLE
Cryopod's glitched in krystallos

### ISSUE THREAD

**Issue by MEHcommonsensebroken** [StarQuestMinecraft/StarQuestPublic#385]
early today i tested my activepod/cyropod spawn
and both seem to be not working 
later checking with another person on krystallos they spawned at the spawn of the planet instead of thier cryopod

Steps to reproduce this issue 
1. make a pod on krystallos 
2. set to active 
3. relog and appear in the same place

steps to reproduce spawn bug
1. set up pod 
2. die

**Comment by Dibujaron** [comment]
Thanks for reporting. Stupid cryopod. I will figure this out someday... :(

**Comment by awangatboo** [comment]
There are many cryopod issues and Dib is working on them.  I am going to leave one of them open but it will be a bug made in SQ 3.0 as so much code has changed since SQ 2.0
