### ISSUE TITLE
Are the Beavers Back?

### ISSUE THREAD

**Issue by Hockeyson48** [StarQuestMinecraft/StarQuestPublic#386]
So I experienced a very large ship bug lately. Just a while back I was doing  a bit of hunting, and after a successful kill I went outside the atmosphere of Iffrizar to store the loot I received during the kill. Right after, my ship split in half right outside Iffrizar. A moment later I was sucked back into Iffrizar and my ship laid below me split in two. I recieved help from Coolwolf later on and decided to report the bug here. I'm not sure what happened, but I want to try to prevent this from happening again. I will provide a picture of my ship after the wreckage. Thanks for taking the time to read this!

-Hockeyson48

http://imgur.com/923jrO4

**Comment by Dibujaron** [comment]
This was fixed, thanks for reporting.
