### ISSUE TITLE
Random Release

### ISSUE THREAD

**Issue by GroxTerror** [StarQuestMinecraft/StarQuestPublic#387]
I was flying over Seamonster's place just flying about trying to grab my ship that he got earlier. I decided it was time to head home so I began to fly up to head into orbit. Around 200y, suddenly my ship released out of the blue and I went plummeting to the ground.

This is the second time this has happened. The first time jrusso refunded my stuff and ship. It's gotten annoying, because he just got a well armed ship and my god set and loot cargo, with no effort.

**Comment by Dibujaron** [comment]
This was fixed, thanks for reporting.
