### ISSUE TITLE
Ships giving Ability to fly (for 7 seconds tops)

### ISSUE THREAD

**Issue by JavaInvader** [StarQuestMinecraft/StarQuestPublic#389]
Title says it all sometime while flying on the planet ship stops moving and i'm gliding around my ship. Might be the issue to Random releasing because you take damage when u stop gliding which only lasts for about 3-7 seconds and is within the ship boundaries, giving fall damage hence the ship releasing

**Comment by Dibujaron** [comment]
This is due to lag between you and the server; as soon as the server sees that you moved you're put out of flymode. Because it's lag, you actually can't do anything with it, so it's not a problem. Thanks for reporting though! :)
