### ISSUE TITLE
Parts of ship disappearing when flying.

### ISSUE THREAD

**Issue by Kyle98martin** [StarQuestMinecraft/StarQuestPublic#390]
I was flying on bosk today at about 16:10PM GMT when I relogged after my autopilot stopped, upon logging in I discovered about 70% of my ship was gone. It was just gone. JUSA went back and looked for the remains but they wouldn't be found. The ship was in one piece when I logged out so I don't understand what could have happened to it.

**Comment by Hockeyson48** [comment]
I had a similar problem with my ship. I made a report but got no feedback on it just yet.

**Comment by Dibujaron** [comment]
This was fixed, thanks for reporting.
