### ISSUE TITLE
lost plot

### ISSUE THREAD

**Issue by fghhjbbv** [StarQuestMinecraft/StarQuestPublic#393]
my plot was nissing  when i was in the town after i broughtt it on 11 april saturday 2015.

**Comment by fghhjbbv** [comment]
my username is Marsman _120.

**Comment by fghhjbbv** [comment]
My town is on quavera called fusionlands

**Comment by GroxTerror** [comment]
This probably wasn't a bug, but a town owner deleting your plot.
