### ISSUE TITLE
Falling in space.

### ISSUE THREAD

**Issue by Kyle98martin** [StarQuestMinecraft/StarQuestPublic#394]
Sometimes when floating about in space you will begin to fall and will not be able to stop yourself from falling. This has happened to me about 3 times in the last 2 days but I was able to fix it 2 of those times by quickly relogging. The 3rd time I haven't been so lucky so I'm not logged out at layer -60 at spawn.

**Comment by Dibujaron** [comment]
This is not a bug. This is the gravity detection system working as intended, and it happens when you fly between something above you and also something close below you. It could also be due to lag. Unfortunately, in both cases, it can't be fixed. Sorry, thanks for reporting.
