### ISSUE TITLE
Idle Kicking in Ships

### ISSUE THREAD

**Issue by AlternatePFG** [StarQuestMinecraft/StarQuestPublic#395]
This might not do it for the captain (I kept moving, AlternatePFG) but my friend got idle kicked (Alex3341) on our way to Acualis. Either way I want to point out that bug, but I'm also wondering if he could get tped to me? Or is that refund.

**Comment by greatwazoo** [comment]
hmm thats happened to me too, interesting that it doesnt do that for driver just passengers

**Comment by Dibujaron** [comment]
The pilot is marked as active because they are sneaking and repositioning. If the player is perfectly still while flying (like AFK) they're going to fall out. This is not really something that I can fix unfortunately.
