### ISSUE TITLE
Ship eaten, Lost inventory

### ISSUE THREAD

**Issue by Generaltyler1** [StarQuestMinecraft/StarQuestPublic#396]
GhostNova was unable to make an account so I'm making this for her

She says she was flying to bosk in a slightly modified gen 3 noobfighter from the northwest side, around y = 80 when she entered the planet she found herself on the ground with no ship and no inventory

**Comment by Dibujaron** [comment]
This was fixed, thanks for reporting. We were having communications issues at the time.
