### ISSUE TITLE
Lifts

### ISSUE THREAD

**Issue by Liggo** [StarQuestMinecraft/StarQuestPublic#398]
The lift was built correctly however on the pressing of the stone button nothing happened. The player did not go up , as was expected , the player just stayed there.  It was inside the town fusionlands on quav .

**Comment by Kyle98martin** [comment]
If someone has shot the lift with a bow in the last restart it can sometimes break them until the next server restart.

**Comment by fghhjbbv** [comment]
they shut it on purpose to prevent pirates getting in like jusa.
