### ISSUE TITLE
Chuck still loaded when  I am gone.

### ISSUE THREAD

**Issue by awangatboo** [StarQuestMinecraft/StarQuestPublic#400]
I live on bosk and even though I have not played as much as I used to it seams like my chunk is not unloading.  I have Mellon towers that work as long as the chunk is loaded but each time I have been logging in recently it seams as if there is loads more melons than when I have left.  It is just Me and TheBeaver99 in the town and he has not been on much as well.  I want to report this in case this is a bug.  Oh yeah one last thing this is in a town and I don't see any W/G that close that would keep my chunks loaded.

**Comment by awangatboo** [comment]
The more I think about it the amount of melons I get might be constant with the chunk staying loaded until the next planet restart.

**Comment by Dibujaron** [comment]
People do fly over and load the chunks, so I'm going to chalk this up to that. I will look into it though.

**Comment by awangatboo** [comment]
Just as a note our town goes all the way up to Y=254   I am sure if people come close the chunk will load but I know they cannot fly over.  :)
