### ISSUE TITLE
Ship cut in half when exiting bosk

### ISSUE THREAD

**Issue by JUSAPlayer1** [StarQuestMinecraft/StarQuestPublic#402]
Right so basically this morning I was leaving bosk in my interceptor, I flew up to workd height and when I went to exit it said that I depiloted it then it sent me into space. When I looked around in space I was inside my ship, only there was a problem. The bottom half of my ship was gone. And I was stuck with just the tip half. I grabbed a sign and made the top of my ship a star fighter and flew it back to bosk. When I got to where I ebtered space there was my ship. But only the bottom half. But it was at y lvl 224. When I tried to reattach the ships by redetecting I was given an error saying "That ship is already being piloted" so I waited for a restart but that didn't help. Paddy is helping me right now by flying the too half after doing something (I don't know what lol) so no refunds requested or anything like that just wanted to let you know about the glitch.

**Comment by Dibujaron** [comment]
I wish I had seen this when it had happened. Thanks for reporting, I will look into it.

**Comment by Dibujaron** [comment]
Figured out why this happened, it's fixed. Thanks for reporting.
