### ISSUE TITLE
block placeing

### ISSUE THREAD

**Issue by MEHcommonsensebroken** [StarQuestMinecraft/StarQuestPublic#403]
player named hamtaro21 called me to aid him in a glitch today and apon tping i attempted to place pistons myself in a global region (aka free placement) after 5mins we discovered we cannot place blocks on this ship at all 

steps to replicate problem 
step 1 have a ship pre deected 
step 2 try to add pistons to the sponges or any blocks to the front of the sponge 
step 3 go mad cause you can;t :P

**Comment by Dibujaron** [comment]
If you want to add blocks to a predetected ship, you need to detect the ship again. you can't add to a ship that is already detected without redetecting it.

I appreciate the report but I'm not sure what you're saying.
