### ISSUE TITLE
Ceh( and other planets) have broken spawn rates

### ISSUE THREAD

**Issue by Consue** [StarQuestMinecraft/StarQuestPublic#404]
I have lately herd complaints, and have complaints myself that the spawn rates on Ceh (and some other planets Im not sure witch ones) are too low
to give proof to this phenomenon I have prepared a spawn platform
In vallina minecraft above the nether in normal mode you get this:
![2015-04-20_20 29 08](https://cloud.githubusercontent.com/assets/12021889/7239449/3d90c648-e7aa-11e4-9798-2c5db9aef293.png)

and in SQ, at block limit, at hard dfficulty were the surface of Ceh is WAY lower than that of the Nether:
![2015-04-20_20 37 55](https://cloud.githubusercontent.com/assets/12021889/7239486/7a453f24-e7aa-11e4-89d8-2e46cc831110.png)

Is what is happening here,is this related to the kel slime or the selective spawning?
O and if you do fix this, please only increase the pig men count, the on fire sharp shooters have a very good population as of now

**Comment by Dibujaron** [comment]
Ceharram is not the normal nether, we have a custom mob spawning engine that works slightly differently than vanilla. Behavior will not be the same. I feel like the spawn rates are about where we want them.
