### ISSUE TITLE
MachinaFactory activator/brewing relay/sorter bugs

### ISSUE THREAD

**Issue by Millibyte1** [StarQuestMinecraft/StarQuestPublic#405]
Three issues that I have encountered:

When the player who has created an activator logs in, the activator does not immediately work (you have to reset the signal). I have been bypassing this bug by creating simple redstone repeater clocks to reset the signal every few seconds, but it is annoying.

Brewing relays cannot use glowstone dust as an ingredient (or at least cannot brew speed II potions; I haven't tested it on any other kinds).

This isn't necessarily a bug, but splitters cannot directly feed into other splitters or into brewing relays.

**Comment by Dibujaron** [comment]
Activators work from a state change, from a redstone signal going from "off" to "on". The old machina redstone bridge that it replaced worked in the same way. The redstone clock seems like a bit of a wasteful way to do it, though, can't you just have a button or something to start them all?

Regarding the brewing relays, someday I will fix machinacraft, but that time is not now. It is an extremely old plugin and I'm surprised it still works at all.

**Comment by Evancooldude** [comment]
Unsure of how progress on fixing this is going. I know that splitters are still very buggy. Any new information?

**Comment by awangatboo** [comment]
Someone would need to get the Machinacraft code and fix it.

**Comment by awangatboo** [comment]
Closing all bugs in preparation for SQ 4.0.
