### ISSUE TITLE
Turrets not Regenerating properly in Regalis

### ISSUE THREAD

**Issue by JavaInvader** [StarQuestMinecraft/StarQuestPublic#406]
title says it all.

**Comment by Dibujaron** [comment]
But it really doesn't. What is happening, and what did you expect to happen instead?

**Comment by JavaInvader** [comment]
I got shot by someone in a spawn fighter and no all of my ship regened might have something to do with fire it leaves...? I don't know? Its not common but when it happens it's really annoying. Didn't move the ship so it didn't regen over the ship or anything just didn't come back.

**Comment by awangatboo** [comment]
Is this still and issue in SQ 3.0 if not you should close the bug.

**Comment by awangatboo** [comment]
Closing Bug as there is no Regalis any more
