### ISSUE TITLE
Cryopod issure

### ISSUE THREAD

**Issue by Consue** [StarQuestMinecraft/StarQuestPublic#407]
Dyed in Ceh and ended up in Reg and updated my cryospawn 2 days ago
this just happened

**Comment by Dibujaron** [comment]
Thanks for the report. This is proving to be so elusive...

**Comment by awangatboo** [comment]
Closing this bug in order to obtain better details in current Cryopod issues.  If you have another Cryopod iss please see this forum thread before opening a new issue.

http://www.starquestminecraft.com/starquestforums/m/17078810/viewthread/23552021-great-cryopod-bug-closing/post/last#last
