### ISSUE TITLE
Krystallian Cryopod

### ISSUE THREAD

**Issue by StarquestBaron** [StarQuestMinecraft/StarQuestPublic#410]
I was maliciously knocked into a lava wall by  native of Krystallos.  Having just had words with two of his fellows, this was enough to kill me.  Unfortunately, my cryopod failed to respawn me back into my base and I went to Regalis spawn instead.  First shot is seconds after the incident
![2015-04-23_09 33 39](https://cloud.githubusercontent.com/assets/10749070/7299207/7f3556a0-e9a2-11e4-9792-38ba1de98536.png)

These two shots show me setting my cryopod yesterday.
![2015-04-22_06 12 07](https://cloud.githubusercontent.com/assets/10749070/7299241/b168c026-e9a2-11e4-8f33-a99f0ca785d3.png)
![2015-04-22_06 12 09](https://cloud.githubusercontent.com/assets/10749070/7299242/b3107586-e9a2-11e4-94d2-8bcb850cbc28.png)

If this is important, I DID use a bedspawn yesterday.  I mention it because when Paddy was doing some testing the other day on Krys, I respawned at my bedspawn at one point during the experiment.

(In case you are considering refunds, this is the second time I've lost nicely enchanted gear to this glitch.  In fact, I had just finished re-enchanting some of it.  :(  )

**Comment by Dibujaron** [comment]
I believe you. Still trying to find this bug, it's a murderous one for sure. Thanks for reporting.

**Comment by TotallyNotSatan** [comment]
Same thing happened with sethlibra on Krys, but he's back. Just marking this as reproduced.
