### ISSUE TITLE
Inventory lost upon exiting Bosk.

### ISSUE THREAD

**Issue by Kyle98martin** [StarQuestMinecraft/StarQuestPublic#412]
I left Bosk today at approx 5pm GMT and my inventory was wiped but my ship was fine. I don't know if this is a still happening since I'm now stuck in space but if it is the steps to replicate are: 
1. Have an inv with something in and a ship.
2. Fly out of Bosk and into space.
3. Be sad before your gear is gone again.

I don't have any screenshots of my stuff since I didn't take any today. I have some from 3 days ago though and I haven't died since then so I don't know if you'll allow them to be used for a refund request. Normally I wouldn't ask for a refund but I've lost so much stuff to bugs recently I can't affording to not get refunds.
Edit: Screenshots of inv from a few days ago: http://imgur.com/WG7tLx2,JoOMvea,bLUjIn5,3bD0ImU,Z0OcZX8,O7bMesZ
Granademan also seen me about outside his base about 5 mins before this happened if you need to verify I still had the gear with someone.
Edit 2: The server restart appeared to fix this issue.

**Comment by MEHcommonsensebroken** [comment]
gonna acceptthe screenshots next time please make sure you have a timestamp and a fresher picture
