### ISSUE TITLE
ship glitch

### ISSUE THREAD

**Issue by MEHcommonsensebroken** [StarQuestMinecraft/StarQuestPublic#413]
tonight i was called to help with a player who has glitched through their ship on bole

after getting the story of what happened this is what i can give for steps to reproduce

step one fly up
step 2 keep flying up
step 3 glitch and fall through your floor 

seems to be a issue when flying straight up

**Comment by awangatboo** [comment]
I saw this issue a lot in SQ 2.0 but have not seen it in SQ 3.0  closing.  If it happens again in 3.0 please open another ticker
