### ISSUE TITLE
Ship Fall

### ISSUE THREAD

**Issue by GroxTerror** [StarQuestMinecraft/StarQuestPublic#415]
Recently when I've been entering planets, I'll sometimes just fall out the bottom of my ship and die. Luckily, the first two times Paddy and Tyler were on so I was luckily able to recover my gear. But, today, it happened again and no one was there to help. It happened differently, as I was flying a ship then it suddenly froze, and I was then dead. No one was nearby and I'm irritated to have lost my good gear, as most of my gear is lost via bugs anymore.

**Comment by Kyle98martin** [comment]
It's not a fix to the bug but always carry feathers. Sounds like they could have saved you the first 2 times.
