### ISSUE TITLE
Beavers after slipgate exit

### ISSUE THREAD

**Issue by Liggo** [StarQuestMinecraft/StarQuestPublic#418]
The player went to the portal and then as soon as the player went through the portal he received a message saying his ship was depiloted. When he attempted to repilot  , he then received a message stating he did not have enough polymer. On further investigation he found a hole on the west facing side (the side facing the portal). 

The player was checkmate101 and he used nearby wool to fix his ship and piloted home :)

**Comment by JUSAPlayer1** [comment]
Tried to get home ;)

**Comment by awangatboo** [comment]
The movecraft code has changed so much since then we need a newer case to try to figure out if this is still and issue.  Please have someone open a case when / if this happens again.
