### ISSUE TITLE
Contract Redo

### ISSUE THREAD

**Issue by HiFlyCS** [StarQuestMinecraft/StarQuestPublic#420]
I already completed a philanthropy contract (3) and it didn't replace it. Instead, it gave me the same contract for the same reason "helping children in Drakos" and was to the same station.

**Comment by HiFlyCS** [comment]
Irrelevant Note: You can also give yourself data cores by breaking your own ship sign

**Comment by awangatboo** [comment]
This does not seam to be an issue in SQ 3.0
