### ISSUE TITLE
URGENT: All towns have lost their money.  

### ISSUE THREAD

**Issue by bluelimeminer** [StarQuestMinecraft/StarQuestPublic#425]
Bank account balance for all towns is at zero.  Player, faction, and nation bank balances appear to be fine.

Check /money top credit 1 or /money top credit 2 and see for yourself.

This is urgent.  If this issue is not resolved by tommorow at 2:00pm EST or 3:00pm EST (Can not remember which one is tax time)  then all the towns on the server will fall and we will have a serious issue on our hands.

**Comment by brickworm2012** [comment]
Doesn't seem to be affecting Ignis_Pyrgos.... All the stuff is in there... Have you updated it with a withdrawl or something similar recently?

**Comment by Dibujaron** [comment]
Fixed, see frontpage. Thanks for the report :)
