### ISSUE TITLE
Starheights, VerstecktStadt, Arcturus, Rocklobsters, Altair still has 0 balance

### ISSUE THREAD

**Issue by bluelimeminer** [StarQuestMinecraft/StarQuestPublic#426]
StarHeights still has a balance of 0.

As per Wildcman mayor of StarHeights the town had 1.7 million in it.

**Comment by bluelimeminer** [comment]
VerstecktStadt, Arcturus, Rocklobsters, and Altair also still have a 0 balance

-- I only checked all the towns on Bole and Bosk

**Comment by soronthar** [comment]
Emerald Isle had 0 credits, I added 100k of my own to keep it alive just in case. It had around 6.4 millions or so (around 1000 days of unkeep)

**Comment by soronthar** [comment]
After adding 100k to prevent Emerald Isle from disappearing, today I have 43500. The unkeep should be 6500.

**Comment by Dibujaron** [comment]
This was fixed, as well as it can be. Thanks for reporting.
