### ISSUE TITLE
Data cores don't drop correctly

### ISSUE THREAD

**Issue by Kyle98martin** [StarQuestMinecraft/StarQuestPublic#428]
I've shoot a few people down since the new contract system came out and broken 3 signs I think and my friend broke the rest. None of these ships have dropped data cores so I don't know if this is a bug or there's something you have to do to make them drop. I know you can get them since JUSAPlayer1 managed to get a data core from his own ship which is now stored away in a chest. I also have piracy contracts active so I know they're not a requirement for getting data cores.
Steps to replicate:
1. Kill someone flying a ship
2. Break ship
3. Gain infamy as usual but no data core.

**Comment by Siigillum** [comment]
Confirming, no datacores drop. Test subject ROBOLE's starfighter.

**Comment by Dibujaron** [comment]
This was fixed, thanks for reporting.
