### ISSUE TITLE
/p doesn't work on bole

### ISSUE THREAD

**Issue by grimreeper132** [StarQuestMinecraft/StarQuestPublic#429]
pretty self explanatory /p works everywhere but on bole, I have talked to a few others and it doesn't work for them as well.

**Comment by Dibujaron** [comment]
Chat is an ancient and very broken system. Thanks for reporting, not sure when I'll be able to fix this.

**Comment by awangatboo** [comment]
/p is not a command in SQ 3.0 please close Ticket.
