### ISSUE TITLE
Cannot Re-Claim Town

### ISSUE THREAD

**Issue by HowlingCrusader** [StarQuestMinecraft/StarQuestPublic#433]
My town, Culpatus, went down down when there was all that trouble with Towny, and after receiving the refund for it, it is not letting me re-claim.

When I log in it gives me the town name and offers to let me set the MOTD, but the town isn't actually there, It will not let me claim the land saying that I am already a member of a town, and when i try to delete the town it says I don't have permission, I don't know if it's important, but when I do /t it says "Towny: null"

The town is currently protected by a dev WG that Paddy set up for me.

**Comment by awangatboo** [comment]
Towny is gone in SQ 3.0 please close ticket.
