### ISSUE TITLE
Data core issues.

### ISSUE THREAD

**Issue by Kyle98martin** [StarQuestMinecraft/StarQuestPublic#436]
So I've done some further testing on data cores today. Data cores do not appear to drop on people whose kill timers are not broken. I've tested this on targets with no contract and targets with a contract and none dropped a data core. You can get bugged data cores like the ones Java reported and I discovered how they drop. Any player who is giving you the 20 minute timer bug will drop a glitched data core that can't be used to complete contracts.

**Comment by Kyle98martin** [comment]
After more testing I also discovered that destroying a sign from a ship that hasn't be flown in the last 5 minutes also yields a glitched data core.

**Comment by brickworm2012** [comment]
Yes. I've gotten several "pending" cores several minutes after destroying signs of ships that haven't been flown in days, or even weeks.
