### ISSUE TITLE
Town name changing issue

### ISSUE THREAD

**Issue by icekoob** [StarQuestMinecraft/StarQuestPublic#437]
Today I attempted to change my town's name and I got a message saying: "You cannot rename towns" even through I'm mayor.

**Comment by JavaInvader** [comment]
You cannot rename towns. last time Dragoth accidently di /t rename instead of /p rename and renamed Avalon Elevator. Planet crash towny safe mode kicked in and the town started unclaiming itself ...

**Comment by icekoob** [comment]
how was I able to rename my town last week...

**Comment by Generaltyler1** [comment]
it was becuase you somehow were able to, but that was how the one player managed to crash towny last week so we disabled town name changing now

**Comment by icekoob** [comment]
Oh ok, thank you tyler

**Comment by awangatboo** [comment]
Towny is gone in SQ 3.0 please close ticket
