### ISSUE TITLE
Elavator + Massive ping lag = death

### ISSUE THREAD

**Issue by APnaptime** [StarQuestMinecraft/StarQuestPublic#438]
At the sheep farm in suido I get ping lagg, its okay but I afked at the elavator thinking that it would get me there eventually, when I checked back in, I was dead.

**Comment by GroxTerror** [comment]
Try a elevator that's 150 blocks high. Pretty sure this is unfixable.

**Comment by awangatboo** [comment]
There are many reasons for LAG and the Dev's can not fix issues that are caused by LAG as it might be something with each users internet connection.
