### ISSUE TITLE
Chickens not Spawning from Eggs on Krystallos

### ISSUE THREAD

**Issue by TotallyNotSatan** [StarQuestMinecraft/StarQuestPublic#442]
Chickens aren't spawning from eggs on Krystallos. From what I've heard, they work on Kel. I detonated over 100 chicken eggs, so the odds of not getting a single chicken are next to none(0.0000000000021%.) Should they spawn here?

**Comment by Dibujaron** [comment]
Chickens don't spawn from eggs anywhere since some jokers made a fully automated chicken farm that nearly lagged kela to death. Breed them with seeds.
