### ISSUE TITLE
Missing Ship

### ISSUE THREAD

**Issue by freethecheese** [StarQuestMinecraft/StarQuestPublic#443]
I left Starquest for a few months, and I came back inside my former town, owned by MathMan (arjuncraft). I found myself stripped of my rank and trapped inside the Melon facility I helped create. Nickmiste assisted me in escaping this situation, but I could not find my ship, which was protected with a ship shield before I left. After further investigation, we found that my ship had somehow been destroyed. Nickmiste informed me that it could have either been a moderator-assisted shield break or something to do with a map reset on Valdaro. I think it is ridiculous that I should log on and find that my shielded ship was destroyed, and now that the town owner is inactive I have no idea what to do. Please, if you can, refund my ship. It took me a long time to build, and it means so much to me.

Attached is an image of my ship. I am sorry that I can provide nothing more.
![2015-02-16_16 55 23](https://cloud.githubusercontent.com/assets/12386768/7557167/7d9e7e50-f741-11e4-921e-edf4e5819ee2.png)

**Comment by Nickmiste** [comment]
AlanDragon admitted to taking the ship due to a ship shields glitch. He is willing to return it, however the doors have been locketted by Arjun. I reccomend you close this bug report and have a senior moderator assess this issue ingame.

**Comment by freethecheese** [comment]
Thank you for your assistance
