### ISSUE TITLE
"killed a player in the last 20 minutes" even though I never killed them before

### ISSUE THREAD

**Issue by Generaltyler1** [StarQuestMinecraft/StarQuestPublic#444]
GhostNova reported this, Posting for her.

She killed pvpbruh and TangoLikesSugar on Valadro  and for both of them she got the message saying that she killed them in the last 20 minutes, but she never killed them but when she killed Flammeer she got the infamy point

here are some pictures she sent me
![2015-05-11_20 25 19](https://cloud.githubusercontent.com/assets/7715853/7579002/cf3acb2e-f822-11e4-8e1d-4397b72055a1.png)
![2015-05-11_20 01 02](https://cloud.githubusercontent.com/assets/7715853/7579009/d8da4916-f822-11e4-9647-b41cc419c2bf.png)

**Comment by JUSAPlayer1** [comment]
It has been "fixed" times but everyone still gets this error.  It used to happen only part of the time with me but everyone I kill I now receive this message.

Conspiracy Theory: Devs leave broken to discourage pvp since it's now useless from an infant standpoint :P

**Comment by JUSAPlayer1** [comment]
*infamy

**Comment by JUSAPlayer1** [comment]
Still broken fyi
