### ISSUE TITLE
Active Cryopod issues

### ISSUE THREAD

**Issue by JavaInvader** [StarQuestMinecraft/StarQuestPublic#446]
I was on bosk active podded to quav flew back to quav when i enter quav. teleports me and restores my inv from when i active podded back to bosk

**Comment by Dibujaron** [comment]
I'm not sure I fully understand what you're saying here. Can you try to make this clearer here? It looks like to me:
-  logged in on bosk
- active pod on Quav teleported you back to it
- flew back to quavara (?)
- when you entered quav you were sent to bosk by an active pod (?)

**Comment by JavaInvader** [comment]
i flew back to bosk, when i entered bosk it restored my inventory and
position(At skydog base) i had when i active poded from bosk to quav about
10 minutes before
