### ISSUE TITLE
Ship Shield Issue

### ISSUE THREAD

**Issue by Nixx59** [StarQuestMinecraft/StarQuestPublic#447]
When I left the server and came back on, I tried to enter my ship but it wouldn't let me. It seems I was removed in some way from my own ship shield.

**Comment by Nixx59** [comment]
![2015-05-14_18 59 12](https://cloud.githubusercontent.com/assets/11953469/7645546/91a8ec82-fa6b-11e4-90bf-aa6a078f054e.png) Here's a screenshot of the message the server gave me.

**Comment by JavaInvader** [comment]
once you put [Shield] on the sign you must put your User name under it
for example
[Shield]
JavaInvader

**Comment by awangatboo** [comment]
This has been fixed as ship Shields will automatically put your name on the sign.
