### ISSUE TITLE
Inventory lost when entering Digi.

### ISSUE THREAD

**Issue by Kyle98martin** [StarQuestMinecraft/StarQuestPublic#448]
I entered Digi at around 2:15am GMT just before a manual server restart and upon entering the system I lost all items in my inventory. The ship remained intact as they usually do when this bug occurs and the restart usually temporarily fixes the bug but doesn't restore the inventory. 

Screenshots of inv for refund: http://imgur.com/Lbw0PwQ,zLdSdIS,TRqyTqt,lIBQpu3,q4WdByh,AkwoghP,lDhmsI4
The screenshots were taken about 15 minutes before the incident occurred and the screenshots do give a time and date of when they were taken.

**Comment by TheBeaver99** [comment]
Refunded, thank you for posting to github.
