### ISSUE TITLE
Cryopod... 

### ISSUE THREAD

**Issue by mcdouble** [StarQuestMinecraft/StarQuestPublic#450]
2 times now I've fallen and taken enough damage to kill me. Both of those times I immediately spawned at Valadro spawn for half a second, then spawned at Origin Station. Both times were fall damage, and both times I lost A LOT of stuff. Please fix, if at all possible.

**Comment by flaammeer** [comment]
Ive also experienced the same problem but with creepers i end up spawing in my cryo for a split second then get teleported into the origin station this time i lost over 36 sponges which is a lot for me and its happend 3 other times but an admin or a mod has been on to help me except this last time so could you guys plz fix it

**Comment by retonlage** [comment]
Same thing here. It's quite annoying.

**Comment by awangatboo** [comment]
Is this still an issue or an SQ 2.0 issue that can not be fixed?

**Comment by awangatboo** [comment]
Closing this bug in order to obtain better details in current Cryopod issues.  If you have another Cryopod iss please see this forum thread before opening a new issue.

http://www.starquestminecraft.com/starquestforums/m/17078810/viewthread/23552021-great-cryopod-bug-closing/post/last#last
