### ISSUE TITLE
Ship Got Eaten

### ISSUE THREAD

**Issue by Moneybags118** [StarQuestMinecraft/StarQuestPublic#451]
Player Adyro says he "flew to Quav after the restart, logged off, and 'this' happened [when he came back]"
![2015-05-16_22 14 27](https://cloud.githubusercontent.com/assets/8053437/7668786/ff01ca16-fc18-11e4-943d-61a4973dfad2.png)
![2015-05-16_22 14 33](https://cloud.githubusercontent.com/assets/8053437/7668787/ff02b5f2-fc18-11e4-9b0e-d45fac94a654.png)
![2015-05-16_22 14 37](https://cloud.githubusercontent.com/assets/8053437/7668788/ff034fe4-fc18-11e4-965b-74dcb2b8d6af.png)

**Comment by lawrencethefrog** [comment]
Can confirm similar event happening when entering atmosphere of Avaquo for the first time. Half of the ship simply disappeared. No restart involved.

Also, the regular 'cut' and the intact corner suggest that this may be related to loading/updating chunks. If something similar happens again it would be helpful to use `/f seechunk` to confirm this.

**Comment by awangatboo** [comment]
Seeing that this was on Quav and we are now in SQ 3.0 we should look at this when we find this bug in SQ3.0.
