### ISSUE TITLE
Hangliders Unwanted Behavior

### ISSUE THREAD

**Issue by GroxTerror** [StarQuestMinecraft/StarQuestPublic#452]
Recently while hangliding off the Easle Tower, the hanglider hit the water and kept going at full speed. I was underwater going at an insane pace. This could easily be abused while fighting a player in an ocean, because you could easily jump up and move quickly away from your attacker, or to your target. They also do not stop until they hit the bottom, so this is pretty dangerous in a deep ocean.

**Comment by JavaInvader** [comment]
I told nick about this
