### ISSUE TITLE
-2 standard players online

### ISSUE THREAD

**Issue by RabbitCarrot** [StarQuestMinecraft/StarQuestPublic#453]
This happens when there are no players online.
![temp](https://cloud.githubusercontent.com/assets/10271880/7702674/e6c3e004-fdff-11e4-9323-81c9aadb8e4b.png)

**Comment by brickworm2012** [comment]
Jane.

**Comment by awangatboo** [comment]
not really a bug an I have not see this since the new Bukkit version was put in place.
