### ISSUE TITLE
Players losing inventory during server trainsition

### ISSUE THREAD

**Issue by Generaltyler1** [StarQuestMinecraft/StarQuestPublic#454]
I have reports of GhostNova losing her inventory going from Regalis to Quav and Bonzer1uk lost his going from Digi to Def. I'm think it happened around 3:30 pm EST

**Comment by JavaInvader** [comment]
Yup Just happened to me. Entered Krystallos from Defalos ships here inventory is wiped. Around 5:08 EST

Update: tried leaving the planet Chat said i left the atmosphere, then left me and ship on planet ate my inventory. then ship derped and threw me out fell to my death and then my cryopod decided to break so now I'm stuck at spawn (btw i lost kit starter this time so 2 inventories were eaten)

**Comment by brickworm2012** [comment]
Were there books or whatnot involved?

**Comment by JavaInvader** [comment]
did not have a book
