### ISSUE TITLE
Unable to unpilot Ships on Krys

### ISSUE THREAD

**Issue by Will5091** [StarQuestMinecraft/StarQuestPublic#455]
so i landed on Krys yesterday and tried to unpilot my ship but it wouldn't let me so i did /stopriding and i get spammed with this "You have left the craft you have 15 seconds to return to the craft before it auto releases" which i suffered with for 20 minutes while trading with doctorwhofan it and when i loggred on it was still happening today and now i cant repilot. my ship is at Pax_republic at x=1590 y151 z=-428

**Comment by awangatboo** [comment]
This was a SQ 2.0 bug.  Closing as SQ 3.0 is now running.
