### ISSUE TITLE
Quavara glitched

### ISSUE THREAD

**Issue by jmr123456** [StarQuestMinecraft/StarQuestPublic#456]
Earlier today I tried to go to Quav. As I enterd the atmoshphere, I was teleported to space,  ended up getting my inventory wiped and lost my ship. The same happened to Amishortyiam.

When you get teleported to space it says: Could not connect to default or fallback server, please try again later: java.net.ConnectException

UPDATE: It's the same with Kel and possibly other planets

**Comment by awangatboo** [comment]
This happens when a system is down.  This was fixed but can still happen from time to time when a server crashes.
