### ISSUE TITLE
Cryopod

### ISSUE THREAD

**Issue by xxb0nkersxx** [StarQuestMinecraft/StarQuestPublic#457]
I've died several times on Bol and keep spawning in the spawn station my active cryo doesn't work either

**Comment by retonlage** [comment]
I've had the same issue.

**Comment by awangatboo** [comment]
Closing this bug in order to obtain better details in current Cryopod issues.  If you have another Cryopod iss please see this forum thread before opening a new issue.

http://www.starquestminecraft.com/starquestforums/m/17078810/viewthread/23552021-great-cryopod-bug-closing/post/last#last
