### ISSUE TITLE
Leaving atmosphere of Krys 

### ISSUE THREAD

**Issue by Will5091** [StarQuestMinecraft/StarQuestPublic#458]
so i got back to Krys after i died and my cryo didnt set _Sigh_ and i got my ship to pilot and i took it up to leave the planet and it just says leaving atmosphere and doesn't tp me so i move my ship down to try again and it tped me out of the atmosphere to space and now im stuck there but ik the ship is still on krys near the town of Pax_Republic.

p.s.- could i get my location reset to krys in my ship or get my ship moved to space arround me?

**Comment by awangatboo** [comment]
Closing as an old SQ 2.0 issue.
