### ISSUE TITLE
enchanting gone wrong pvpbruh

### ISSUE THREAD

**Issue by pvpbruh** [StarQuestMinecraft/StarQuestPublic#460]
I was on kel and i enchanting with anvil and i had sharp 4 book and i think smite 4 book and knockback 2 and fire aspect and i enchanting sharp 4 and then when i look in my inventory and the 2nd book was gone the happen around 6:08

**Comment by pvpbruh** [comment]
i found out want happen XD

**Comment by brickworm2012** [comment]
So... case closed.

**Comment by awangatboo** [comment]
Since you found out what the issue was I am closing the ticket.

**Comment by pvpbruh** [comment]
Sent by Outlook for Android

On Wed, Aug 5, 2015 at 6:52 AM -0700, "awangatboo" notifications@github.com wrote:
Since you found out what the issue was I am closing the ticket.

---
