### ISSUE TITLE
Leaving Atmosphere Glitch

### ISSUE THREAD

**Issue by Spateeter** [StarQuestMinecraft/StarQuestPublic#464]
So today I left Boskevine at around 1:12 with 2.5 double chests of melons in my droppers and a chest of melons in my inventory to do a spawn run, then this happens.

http://imgur.com/8qhtF0D,gWDQaJp,jW1DzlZ,cic5ye5

This isnt the first time that this occured. It has happened twice but the first time was during the no-refund policy. All my droppers and my ship that I built are gone. Not only did I waste several credits purchasing this from a dealer, but I also wasted a ship that I maintained for a long time, and truly liked. I have been spending more time making up the deaths from the gliches that occur rather than actually playing and enjoying the server.

I just ask that hopefully a mod or admin will be able to help. Thanks.

**Comment by Afgncaatp** [comment]
I think Spateeter meant single chests, I've got screenshots of the empty chest shops as requested by him: http://imgur.com/a/cP8Va

**Comment by Spateeter** [comment]
Yes I apologize, I meant 5 single chests or 2.5 double chests.

**Comment by awangatboo** [comment]
This can happen when a system is down.  This still might happen in SQ 3.0 but as this was in SQ 2.0 I am closing this ticket.
