### ISSUE TITLE
Spawning at the origin station instead of cryopod

### ISSUE THREAD

**Issue by retonlage** [StarQuestMinecraft/StarQuestPublic#467]
Recently i have died two times where i respawned in spawn instead of at my cryopod. Right after i respawned, both times it teleported me to the cryopod, but teleported me to the origin station immediatly afterwards. Both times were on Kelakaria where my cryopod also is.

**Comment by retonlage** [comment]
Just to inform you, i have also encountered this bug twice today.

**Comment by awangatboo** [comment]
Closing this bug in order to obtain better details in current Cryopod issues.  If you have another Cryopod iss please see this forum thread before opening a new issue.

http://www.starquestminecraft.com/starquestforums/m/17078810/viewthread/23552021-great-cryopod-bug-closing/post/last#last
