### ISSUE TITLE
Towny Breeding

### ISSUE THREAD

**Issue by mcdouble** [StarQuestMinecraft/StarQuestPublic#469]
Ok so Mr. Dib. The last issue in breeding that Zorecknor and I posted, you seemed to solve a different issue. This isn't your fault, because we didn't do enough testing to figure out what the true bug was. However what you fixed was handy anyways. The new issue, that Tyler and I discovered, is that they won't breed in Towny. I don't think its just Avalon, but then again, not positive. I know that both cows and pigs gave me babies outside of towny, haven't tested with ponies yet though. But yes, that's it. I get xp from them, but not little cows/pigs.

**Comment by mcdouble** [comment]
DIB! Nevermind, I'm stupid. Tyler, in his brilliance, realized that it was a dev protect issue. When Avalon fell, liggo was kind enough to toggle mobs off for me, since the amount of creepers and skeletons lurking my town was unbelievable. It ended up killing mobs and such. So in that, that we believe prevented the cows too.

**Comment by awangatboo** [comment]
Please close Ticket as issue was resolved.
