### ISSUE TITLE
Atmosphere glitch for the 7 billionth time.

### ISSUE THREAD

**Issue by amishortyiam** [StarQuestMinecraft/StarQuestPublic#470]
I've lost 4 ships, 4 sets of diamond gear, tools, various building supplies, various ship and other supplies.
Today I got dc'd while leaving Bosk, when I logged back on, my light freighter with 16 droppers full of stacks of melon blocks (worth approx 600k I might add) and all my gear was gone and I fell to the ground.
If you're not going to offer refunds then fix this issue. I'm sick of losing gear that I work hard for because of random chance. I lost 600k worth of melons today that I had spent days collecting.
I'll rebuild my ship, make more armor and get more melons but it will take over a week and I'm certainly not happy about it.

I want to enjoy Starquest but things like this make it really hard, especially without the chance of a refund, which I'm still ticked off about.

**Comment by pvpbruh** [comment]
this same thing happen to me

**Comment by pvpbruh** [comment]
but 2 times

**Comment by awangatboo** [comment]
This was in SQ 2.0 and code has been changed a lot since then.  Closing the issue as most people do not have this issue right now unless one of the server is down.
