### ISSUE TITLE
EMP'd Ship Signs

### ISSUE THREAD

**Issue by JUSAPlayer1** [StarQuestMinecraft/StarQuestPublic#471]
Plain and simple. When EMP'd, breaking ship signs no longer gives you the infamy nor does it drop the data core.

**Comment by awangatboo** [comment]
Infamy does not matter.  Does this still not give a ship core?

**Comment by awangatboo** [comment]
Did EMPS ever drop ship core's if not this would be a suggestion.

**Comment by awangatboo** [comment]
JUSA when you get back to SQ on Friday could you please confirm that EMPs still do not drop ship cores

**Comment by Evancooldude** [comment]
Has this issue been resolved?

**Comment by awangatboo** [comment]
The last thing I head from someone on the server the data-cores still do not drop.

**Comment by GingerWalnut** [comment]
I think that I have fixed this bug and I am waiting for it to be put in production.
