### ISSUE TITLE
planet issue this happen to me more than once

### ISSUE THREAD

**Issue by pvpbruh** [StarQuestMinecraft/StarQuestPublic#472]
I keep dieng every now and then form when i enter the planet i fall out my ship and die i this happen yesterday at ceh and today at quav

**Comment by JUSAPlayer1** [comment]
It's a server wide glitch. It's happened 9 times to myself/my fac members on bosk it's happened once to me also on Quav, bole, Kel, and krys. Only thing that's saved me is having leather in my inventory.

**Comment by greatwazoo** [comment]
happened to me coming in to bosk, was piloting gunship FYI

**Comment by JUSAPlayer1** [comment]
Happened again to me this morning on Quav.

**Comment by awangatboo** [comment]
Closing as a SQ 2.0 bug.  I have not seen this exact issue in SQ 3.0 yet.
