### ISSUE TITLE
Fell out of Ship while entering Krystallos

### ISSUE THREAD

**Issue by LilWoofy** [StarQuestMinecraft/StarQuestPublic#473]
When i entered Krystallos, i fell out off my ship and died hitting the ground. 
I contacted Nickmiste who was on the server if he could help me out with what just happened. When he went to see where i died, there was no ship to be found or no items. He says they must of been eaten by the bug. 
What i'm asking for is a refund possibly if i could. I lost of a lot of good items while entering Krystallos. And i would really love to have them back.

**Comment by brickworm2012** [comment]
I've heard the space beavers have been favoring that area.

**Comment by awangatboo** [comment]
SQ 2.0 issue closing as a very old issue,
