### ISSUE TITLE
Contract Fraud

### ISSUE THREAD

**Issue by StarquestBaron** [StarQuestMinecraft/StarQuestPublic#474]
I recently came up on the wanted list which surprised me greatly.  When I checked my contracts, I found this:
![2015-05-29_20 00 15](https://cloud.githubusercontent.com/assets/10749070/7894773/146c77cc-063f-11e5-8ccd-c0b8b4ef9b18.png)

The second contract was actually a philanthropy contract to deliver 9 thousand some credits to north Regalis eco station.  I was EXTREMELY careful about getting the correct number when I accepted, Unfortunately I was not so conscientious about taking a screen shot :derp:

I realize that with no proof you may not be able to change this, and I will deal with it if this is the case.  But I'm hoping, being a mostly upstanding citizen, that you can remove me from the wanted list.

**Comment by greatwazoo** [comment]
this has happened to me as well, sadly dibs big thread o refunds didnt land me a refund

**Comment by Dibujaron** [comment]
Was the yellow wool contract one that you intended to receive?

**Comment by StarquestBaron** [comment]
Yes, that one I accepted.  I had the same issue again today, I accepted two contracts, one came through correctly but the other, a philanthropy contract again, turned into a privateering contract.  

There is a further issue on the original unwanted contract.  I attempted to fulfill it today and received the message that I did not have the correct material for this contract.  I was given the data core and did not collect it myself if this has any bearing on the issue.

I have screen shots of all these if you need them.  (And I'll try to watch github more closely.  Sorry for the tardiness in responding.)

**Comment by StarquestBaron** [comment]
Just letting you know that the issues are all resolved on my side.  The problem with the contract not fulfilling was a major derp on my part.  (I somehow missed that the contract item had to be in a dropper in order to be unloaded.)  Now that I know what I'm doing (and with a little help from friends), I have all my current contracts filled.
