### ISSUE TITLE
Movecraft issue: pilot behaving like a ragdoll tossed inside the ship.

### ISSUE THREAD

**Issue by Siigillum** [StarQuestMinecraft/StarQuestPublic#475]
Happened to me today. Was chasing a freighter, while i move it keeps teleporting me back to shipsign facing it. Chasing something like that is pretty HARD. It was not an issue earlier.

Freighter was about 600 blocks big, Wolf IV i used is around 400. System was Regalis.

Chased a starfighter under 200 blocks in digitalia earlier, no issues.

Also reminding such difficulties (pilot ragdolling in the cockpit) happened earlier when there were some kind of doubleteleportation fixes applied to movecraft.

Finally, invisible pilots still happening i think. Not completely confirmed though.

**Comment by JUSAPlayer1** [comment]
The rag doll when chasing a ship happens everywhere just not all the time. It's extremely annoying when hunting. The invis pilots and ship blocks does still happen , tested in both regalis, and various planets including bole, quav, bosk, and ceh. 

On a seperate note...another thing that gets really annoying is not being able to move a ship while in a turret. Autopilot ing works fine, but I'm talking about manual. If you get in a turret and try to shift to move, you move a few blocks but you end up being glitches out of your ship resulting in a tp back to the ship sign resulting in your turret saying active by [playername] and not being usable until sign broken and replaced.

**Comment by Dibujaron** [comment]
I'll fix the turrets thing. I still can't get the ragdoll as you talk about it to happen to me.

You wouldn't happen to be flying a ship where your head is getting shoved into a block when you move, would you?

**Comment by Dibujaron** [comment]
Fixed the turrets thing, and hopefully the other issue too. I will close this in a few days if nobody says anything else.

**Comment by brickworm2012** [comment]
It might do with the phasing out of the ship issue that is ever prevalent.

**Comment by brickworm2012** [comment]
It seems to happen most often in Reg, if this rears its head again. I have never had this problem in Digi or Def.

**Comment by Consue** [comment]
it happened to me too, ship was moving too fast and I was being shoved in the wall behind, then tped facing the sign

I also noted that according to the direction you initiated the ship that will be the same spot and oritaion you will end up in when this happens

**Comment by greatwazoo** [comment]
it happens to me when there is an extensive amount of people online

**Comment by awangatboo** [comment]
Was this in SQ 3.0?  Is this still happening?

**Comment by awangatboo** [comment]
Please update or I will mark this as closed and assume that it was fixed in SQ 3.0

**Comment by awangatboo** [comment]
I think this has been fixed.  Please open another ticket if it happens in SQ 3.0
