### ISSUE TITLE
Ship Pilots Invisible

### ISSUE THREAD

**Issue by ConnorXConnor** [StarQuestMinecraft/StarQuestPublic#476]
It seems that some people are seeing people currently flying ships as invisible. I noticed a player that it was happening to. Then I asked everyone if they've had similar issues and several confirmed it. Probably could be a very damaging bug.
-EnderTizzy

**Comment by Dibujaron** [comment]
That's been a problem for awhile. It's a spigot bug and there's not a lot we can do about it unfortunately.

**Comment by Siigillum** [comment]
Quick relog is the temporary fix for this. Till ship moves again...

**Comment by GroxTerror** [comment]
It affects everything around the ship as well, including you, if you aren't even piloting it. Kyra got a taste of this the other night while trying to smash me against a wall with a gunship.

**Comment by awangatboo** [comment]
Duplicate of #259
