### ISSUE TITLE
Items despawning too fast

### ISSUE THREAD

**Issue by cloudtail** [StarQuestMinecraft/StarQuestPublic#478]
After I died to cryopod glitches my items had despawned by the time I got back to my base even though noone was on the planet (Valadro). This happened twice.

**Comment by mcdouble** [comment]
Wait... If you don't keep the chunks loaded with stuff on the ground in them, they're not supposed to disappear?
.......ARE YOU KIDDING ME!?!? I've lost so much stuff to this happening omg lol and I just find this out now.

**Comment by brickworm2012** [comment]
I have had items despawn within seconds of losing them, but it only happened once. Might have been fire.

**Comment by awangatboo** [comment]
SQ 2.0 issue.  Please comment if still an issue on SQ 3.0 and I will re-open the ticket.
