### ISSUE TITLE
Regalis NOM NOM NOM

### ISSUE THREAD

**Issue by mcdouble** [StarQuestMinecraft/StarQuestPublic#480]
So looney tunes, aka lOOney20 was leaving Quavara yesterday when he was attacked by this guy named Regalis. Regalis ate up his ship and looney tunes was stuck in space, until his good pal JUSAPlayer1 came to the rescue and flew him to bosk.

Notes:
Quav --> Regais
Brand new ship
Got chewed up by Regalis solar system

Posted by McDouble, for looney20

**Comment by lawrencethefrog** [comment]
Jane warned you not to fly into the sun. I can't see how a solar apocalypse would make it safe all of a sudden.

**Comment by awangatboo** [comment]
I think this was an issue of a Server being down when going from planet to system.  This can happen as it is minecraft.  Please close ticket.
