### ISSUE TITLE
Enderman Disguise Crash

### ISSUE THREAD

**Issue by Nickmiste** [StarQuestMinecraft/StarQuestPublic#481]
NOTE: This bug has only been tested with the enderman morph on Kelakaria

When a player disguises into an enderman, all players nearby crash with the following crash report:

---- Minecraft Crash Report ----
// You're mean.

Time: 6/4/15 10:22 PM
Description: Ticking entity

java.lang.ClassCastException: java.lang.Integer cannot be cast to java.lang.Byte
    at pz.a(SourceFile:92)
    at vo.co(SourceFile:347)
    at vo.z(SourceFile:263)
    at ps.x(SourceFile:149)
    at ps.K(SourceFile:162)
    at pk.t_(SourceFile:266)
    at pr.t_(SourceFile:1265)
    at ps.t_(SourceFile:211)
    at vv.t_(SourceFile:32)
    at adm.a(SourceFile:1408)
    at adm.g(SourceFile:1386)
    at adm.i(SourceFile:1279)
    at ave.s(SourceFile:1849)
    at ave.av(SourceFile:888)
    at ave.a(SourceFile:325)
    at net.minecraft.client.main.Main.main(SourceFile:124)
## A detailed walkthrough of the error, its code path and all known details is as follows:

-- Head --
Stacktrace:
    at pz.a(SourceFile:92)
    at vo.co(SourceFile:347)
    at vo.z(SourceFile:263)
    at ps.x(SourceFile:149)
    at ps.K(SourceFile:162)
    at pk.t_(SourceFile:266)
    at pr.t_(SourceFile:1265)
    at ps.t_(SourceFile:211)
    at vv.t_(SourceFile:32)
    at adm.a(SourceFile:1408)
    at adm.g(SourceFile:1386)

-- Entity being ticked --
Details:
    Entity Type: Enderman (vo)
    Entity ID: 4740663
    Entity Name: Enderman
    Entity's Exact location: 1770.13, 73.00, -171.75
    Entity's Block location: 1770.00,73.00,-172.00 - World: (1770,73,-172), Chunk: (at 10,4,4 in 110,-11; contains blocks 1760,0,-176 to 1775,255,-161), Region: (3,-1; contains chunks 96,-32 to 127,-1, blocks 1536,0,-512 to 2047,255,-1)
    Entity's Momentum: 0.00, -0.06, 0.00
    Entity's Rider: ~~ERROR~~ NullPointerException: null
    Entity's Vehicle: ~~ERROR~~ NullPointerException: null
Stacktrace:
    at adm.i(SourceFile:1279)

-- Affected level --
Details:
    Level name: MpServer
    All players: 3 total; [bew['Nickmiste'/4729645, l='MpServer', x=1773.30, y=74.00, z=-165.80], bex['EnderTizzy'/4734929, l='MpServer', x=1778.16, y=73.00, z=-170.47], bex['xLordHerobrinex2'/4751213, l='MpServer', x=1775.81, y=74.00, z=-166.13]]
    Chunk stats: MultiplayerChunkCache: 442, 442
    Level seed: 0
    Level generator: ID 01 - flat, ver 0. Features enabled: false
    Level generator options: 
    Level spawn location: 0.00,62.00,0.00 - World: (0,62,0), Chunk: (at 0,3,0 in 0,0; contains blocks 0,0,0 to 15,255,15), Region: (0,0; contains chunks 0,0 to 31,31, blocks 0,0,0 to 511,255,511)
    Level time: 905554714 game time, 908406462 day time
    Level dimension: 0
    Level storage version: 0x00000 - Unknown?
    Level weather: Rain time: 0 (now: false), thunder time: 0 (now: false)
    Level game mode: Game mode: creative (ID 1). Hardcore: false. Cheats: false
    Forced entities: 165 total; [tn['chicken'/4190180, l='MpServer', x=1814.97, y=57.06, z=-211.72], tn['Emu'/4189943, l='MpServer', x=1816.22, y=57.06, z=-211.78], bew['Nickmiste'/4729645, l='MpServer', x=1773.30, y=74.00, z=-165.80], tn['chicken'/4190246, l='MpServer', x=1811.88, y=57.06, z=-212.81], tn['chicken'/4190247, l='MpServer', x=1805.84, y=57.06, z=-211.22], bex[' §?GroxTerror'/4674255, l='MpServer', x=1771.69, y=72.91, z=-167.22], tn['chicken'/4190181, l='MpServer', x=1806.78, y=57.06, z=-211.22], tn['chicken'/4189940, l='MpServer', x=1814.49, y=57.06, z=-212.92], tn['Emu'/4190245, l='MpServer', x=1810.50, y=57.06, z=-212.22], tn['chicken'/4190176, l='MpServer', x=1806.72, y=57.06, z=-211.22], tn['chicken'/4189939, l='MpServer', x=1806.97, y=57.06, z=-215.41], tn['chicken'/4190177, l='MpServer', x=1812.84, y=57.06, z=-212.31], tn['chicken'/4190241, l='MpServer', x=1816.22, y=57.06, z=-212.97], tn['chicken'/4189951, l='MpServer', x=1805.19, y=57.06, z=-211.22], tn['chicken'/4190254, l='MpServer', x=1813.50, y=57.06, z=-211.84], tn['chicken'/4190189, l='MpServer', x=1814.31, y=57.06, z=-211.72], tn['chicken'/4190190, l='MpServer', x=1813.03, y=57.06, z=-212.28], tn['chicken'/4190253, l='MpServer', x=1814.47, y=57.06, z=-211.22], tn['chicken'/4189947, l='MpServer', x=1811.34, y=57.06, z=-212.81], tn['chicken'/4190184, l='MpServer', x=1806.94, y=57.06, z=-212.81], tn['chicken'/4189946, l='MpServer', x=1810.73, y=57.06, z=-214.25], tn['chicken'/4190185, l='MpServer', x=1805.19, y=57.06, z=-211.69], tn['chicken'/4190251, l='MpServer', x=1810.56, y=57.06, z=-212.81], tn['chicken'/4190186, l='MpServer', x=1811.22, y=57.06, z=-212.22], tn['chicken'/4189945, l='MpServer', x=1807.42, y=57.06, z=-212.11], tn['chicken'/4190187, l='MpServer', x=1812.44, y=57.06, z=-213.56], tn['chicken'/4189926, l='MpServer', x=1813.72, y=57.06, z=-213.41], tn['chicken'/4190199, l='MpServer', x=1807.03, y=57.06, z=-212.78], tn['chicken'/4190261, l='MpServer', x=1815.31, y=57.06, z=-213.22], uz['item.item.melon'/4738993, l='MpServer', x=1743.91, y=22.00, z=-160.31], tn['chicken'/4189922, l='MpServer', x=1809.33, y=57.06, z=-211.27], tn['chicken'/4189935, l='MpServer', x=1806.03, y=57.06, z=-211.94], tn['Emu'/4189933, l='MpServer', x=1815.63, y=57.06, z=-212.36], tn['Emu'/4190268, l='MpServer', x=1806.53, y=57.06, z=-213.38], tn['chicken'/4189928, l='MpServer', x=1814.14, y=57.06, z=-211.22], tn['chicken'/4190265, l='MpServer', x=1809.06, y=57.06, z=-211.22], tn['chicken'/4190202, l='MpServer', x=1805.19, y=57.06, z=-211.75], uz['item.item.melon'/4743956, l='MpServer', x=1760.13, y=30.00, z=-145.53], uz['item.item.melon'/4764874, l='MpServer', x=1745.65, y=11.76, z=-172.75], tn['Emu'/4189911, l='MpServer', x=1809.28, y=57.06, z=-211.81], tn['chicken'/4189910, l='MpServer', x=1815.08, y=57.06, z=-211.22], tn['chicken'/4190215, l='MpServer', x=1816.78, y=57.06, z=-211.88], tn['chicken'/4189917, l='MpServer', x=1812.81, y=57.06, z=-211.81], tn['chicken'/4190156, l='MpServer', x=1816.06, y=57.06, z=-211.22], tn['chicken'/4190155, l='MpServer', x=1813.03, y=57.06, z=-212.00], tn['chicken'/4190167, l='MpServer', x=1809.38, y=57.06, z=-214.94], tn['Emu'/4189893, l='MpServer', x=1816.78, y=57.06, z=-212.56], tn['chicken'/4190166, l='MpServer', x=1806.00, y=57.06, z=-213.38], tn['chicken'/4190165, l='MpServer', x=1816.13, y=57.06, z=-211.22], tn['chicken'/4189894, l='MpServer', x=1812.21, y=57.06, z=-212.33], tn['chicken'/4190231, l='MpServer', x=1809.22, y=57.06, z=-213.91], tn['chicken'/4189895, l='MpServer', x=1807.49, y=57.06, z=-211.22], tn['chicken'/4190164, l='MpServer', x=1805.69, y=57.06, z=-214.03], tn['Emu'/4190163, l='MpServer', x=1806.19, y=57.06, z=-213.44], tn['chicken'/4190225, l='MpServer', x=1812.19, y=57.06, z=-211.22], tn['chicken'/4190224, l='MpServer', x=1809.78, y=57.06, z=-213.50], tn['chicken'/4190161, l='MpServer', x=1812.84, y=57.06, z=-211.22], tn['chicken'/4190227, l='MpServer', x=1806.03, y=57.06, z=-211.22], vo['Enderman'/4740663, l='MpServer', x=1770.13, y=73.00, z=-171.75], tn['chicken'/4190237, l='MpServer', x=1809.81, y=57.06, z=-211.91], tn['chicken'/4190233, l='MpServer', x=1806.41, y=57.06, z=-211.84], tn['Emu'/4190170, l='MpServer', x=1815.94, y=57.06, z=-211.28], tn['chicken'/4190168, l='MpServer', x=1814.81, y=57.06, z=-212.47], tn['chicken'/4190234, l='MpServer', x=1816.28, y=57.06, z=-211.25], tn['Emu'/4190112, l='MpServer', x=1810.69, y=57.06, z=-212.19], tn['Emu'/4190304, l='MpServer', x=1814.81, y=57.06, z=-212.41], tn['chicken'/4189872, l='MpServer', x=1808.34, y=57.06, z=-213.41], tn['chicken'/4190117, l='MpServer', x=1807.22, y=57.06, z=-211.71], tn['chicken'/4190314, l='MpServer', x=1808.22, y=57.06, z=-211.22], tn['Emu'/4190313, l='MpServer', x=1815.69, y=57.06, z=-215.16], tn['chicken'/4189887, l='MpServer', x=1809.22, y=57.06, z=-211.22], tn['Emu'/4190318, l='MpServer', x=1805.81, y=57.06, z=-214.63], tn['Emu'/4190319, l='MpServer', x=1808.47, y=57.06, z=-213.31], tn['Emu'/4190320, l='MpServer', x=1814.19, y=57.06, z=-212.41], tn['chicken'/4190326, l='MpServer', x=1806.16, y=57.06, z=-212.66], tn['chicken'/4190325, l='MpServer', x=1814.72, y=57.06, z=-212.53], tn['chicken'/4189867, l='MpServer', x=1815.55, y=57.06, z=-212.65], tn['chicken'/4189864, l='MpServer', x=1810.73, y=57.06, z=-212.84], tn['chicken'/4189865, l='MpServer', x=1805.93, y=57.06, z=-211.22], tn['Emu'/4190328, l='MpServer', x=1808.19, y=57.06, z=-212.47], tn['Emu'/4190335, l='MpServer', x=1808.22, y=57.06, z=-211.22], tn['chicken'/4189869, l='MpServer', x=1805.19, y=57.06, z=-211.22], tn['chicken'/4190082, l='MpServer', x=1814.75, y=57.06, z=-212.44], tn['chicken'/4190083, l='MpServer', x=1808.96, y=57.06, z=-213.27], tn['Emu'/4190274, l='MpServer', x=1812.81, y=57.06, z=-215.16], tn['chicken'/4190275, l='MpServer', x=1812.19, y=57.06, z=-213.53], tn['chicken'/4190085, l='MpServer', x=1810.07, y=57.06, z=-212.81], tn['chicken'/4190279, l='MpServer', x=1813.09, y=57.06, z=-213.66], uz['item.item.melon'/4741507, l='MpServer', x=1743.75, y=30.00, z=-180.72], tn['Emu'/4190090, l='MpServer', x=1812.83, y=57.06, z=-211.22], tn['chicken'/4190281, l='MpServer', x=1816.78, y=57.06, z=-212.81], tn['chicken'/4190282, l='MpServer', x=1806.34, y=57.06, z=-214.13], bex['GroxTerror'/4740663, l='MpServer', x=1770.09, y=73.00, z=-171.66], tn['chicken'/4190287, l='MpServer', x=1809.72, y=57.06, z=-213.25], tn['chicken'/4190098, l='MpServer', x=1812.19, y=57.06, z=-211.78], tn['chicken'/4190290, l='MpServer', x=1809.16, y=57.06, z=-212.00], tn['chicken'/4190103, l='MpServer', x=1805.19, y=57.06, z=-211.22], tn['chicken'/4190292, l='MpServer', x=1812.97, y=57.06, z=-212.22], tn['chicken'/4190100, l='MpServer', x=1805.89, y=57.06, z=-214.93], uz['item.item.melon'/4731638, l='MpServer', x=1744.72, y=10.00, z=-192.59], tn['chicken'/4190303, l='MpServer', x=1806.25, y=57.06, z=-211.25], tn['Emu'/4190058, l='MpServer', x=1816.78, y=57.06, z=-211.25], tn['chicken'/4190052, l='MpServer', x=1814.13, y=57.06, z=-214.78], tn['chicken'/4190055, l='MpServer', x=1805.13, y=57.06, z=-215.43], tn['Emu'/4190054, l='MpServer', x=1807.91, y=57.06, z=-211.78], tu['Rabbit'/4684227, l='MpServer', x=1775.66, y=74.00, z=-167.72], tn['chicken'/4190398, l='MpServer', x=1813.56, y=57.06, z=-212.47], uz['item.item.melon'/4747688, l='MpServer', x=1794.19, y=42.00, z=-146.06], bex['EnderTizzy'/4734929, l='MpServer', x=1778.16, y=73.00, z=-170.47], tn['chicken'/4190073, l='MpServer', x=1812.99, y=57.06, z=-212.25], tn['chicken'/4190074, l='MpServer', x=1805.19, y=57.06, z=-211.81], tn['chicken'/4190070, l='MpServer', x=1805.19, y=57.06, z=-214.22], tn['Emu'/4190066, l='MpServer', x=1809.78, y=57.06, z=-211.22], tn['chicken'/4190384, l='MpServer', x=1813.06, y=57.06, z=-211.84], tn['chicken'/4190029, l='MpServer', x=1812.61, y=57.06, z=-213.73], tn['chicken'/4190351, l='MpServer', x=1816.19, y=57.06, z=-211.22], tn['chicken'/4190028, l='MpServer', x=1815.49, y=57.06, z=-211.22], tn['chicken'/4190350, l='MpServer', x=1809.41, y=57.06, z=-214.53], tn['chicken'/4190027, l='MpServer', x=1813.75, y=57.06, z=-213.00], tn['chicken'/4190345, l='MpServer', x=1808.53, y=57.06, z=-212.66], bex['xLordHerobrinex2'/4751213, l='MpServer', x=1775.81, y=74.00, z=-166.13], tn['chicken'/4190021, l='MpServer', x=1808.59, y=57.06, z=-211.36], tn['chicken'/4190343, l='MpServer', x=1816.16, y=57.06, z=-211.22], tn['Emu'/4190342, l='MpServer', x=1816.78, y=57.06, z=-211.81], bex['EnderTizzy'/4734929, l='MpServer', x=1778.16, y=73.00, z=-170.47], tn['chicken'/4190364, l='MpServer', x=1805.19, y=57.06, z=-215.38], tn['chicken'/4190044, l='MpServer', x=1806.54, y=57.06, z=-214.68], tn['Emu'/4190045, l='MpServer', x=1809.88, y=57.06, z=-212.06], tn['chicken'/4190367, l='MpServer', x=1806.69, y=57.06, z=-211.88], tn['Emu'/4190042, l='MpServer', x=1805.19, y=57.06, z=-211.22], tn['chicken'/4190361, l='MpServer', x=1815.42, y=57.06, z=-211.78], tn['Emu'/4190363, l='MpServer', x=1805.53, y=57.06, z=-211.91], tn['chicken'/4190356, l='MpServer', x=1808.41, y=57.06, z=-211.97], uz['item.item.melon'/4747648, l='MpServer', x=1749.75, y=54.00, z=-145.97], tn['chicken'/4190357, l='MpServer', x=1805.19, y=57.06, z=-211.88], tn['chicken'/4190035, l='MpServer', x=1805.19, y=57.06, z=-213.53], tn['chicken'/4190353, l='MpServer', x=1807.09, y=57.06, z=-212.78], tn['chicken'/4190354, l='MpServer', x=1805.69, y=57.06, z=-211.84], tn['Emu'/4190355, l='MpServer', x=1816.78, y=57.06, z=-212.91], tn['Emu'/4189992, l='MpServer', x=1811.38, y=57.06, z=-212.25], uz['item.item.melon'/4729293, l='MpServer', x=1792.88, y=28.00, z=-155.63], ux['Boat'/4684454, l='MpServer', x=1774.69, y=77.00, z=-166.50], tn['chicken'/4189999, l='MpServer', x=1812.22, y=57.06, z=-214.46], bex['xLordHerobrinex2'/4751213, l='MpServer', x=1775.81, y=74.00, z=-166.13], tn['Emu'/4189984, l='MpServer', x=1809.78, y=57.06, z=-213.51], tn['chicken'/4189987, l='MpServer', x=1811.72, y=57.06, z=-212.34], uz['item.item.melon'/4739989, l='MpServer', x=1744.13, y=9.00, z=-195.72], tn['chicken'/4189990, l='MpServer', x=1807.00, y=57.06, z=-213.56], tn['chicken'/4190008, l='MpServer', x=1806.50, y=57.06, z=-213.97], tn['chicken'/4190002, l='MpServer', x=1805.84, y=57.06, z=-215.00], tn['Emu'/4190005, l='MpServer', x=1806.71, y=57.06, z=-211.89], tn['chicken'/4189963, l='MpServer', x=1805.19, y=57.06, z=-211.22], tn['chicken'/4190411, l='MpServer', x=1813.44, y=57.06, z=-211.22], tn['Emu'/4190413, l='MpServer', x=1812.19, y=57.06, z=-215.19], tn['Emu'/4190412, l='MpServer', x=1805.66, y=57.06, z=-211.75], tn['chicken'/4189966, l='MpServer', x=1805.19, y=57.06, z=-211.80], tn['chicken'/4189965, l='MpServer', x=1805.19, y=57.06, z=-211.22], tn['chicken'/4190414, l='MpServer', x=1806.50, y=57.06, z=-212.65], tn['chicken'/4189955, l='MpServer', x=1808.72, y=57.06, z=-211.22], tn['chicken'/4189959, l='MpServer', x=1811.21, y=57.06, z=-212.81], tn['chicken'/4190405, l='MpServer', x=1809.03, y=57.06, z=-213.28], tn['chicken'/4190404, l='MpServer', x=1807.84, y=57.06, z=-211.22], tn['Emu'/4189957, l='MpServer', x=1816.78, y=57.06, z=-211.22], tn['chicken'/4190407, l='MpServer', x=1816.13, y=57.06, z=-212.88], tn['chicken'/4189980, l='MpServer', x=1813.47, y=57.06, z=-211.22]]
    Retry entities: 0 total; []
    Server brand: BungeeCord (git:BungeeCord-Bootstrap:1.8-SNAPSHOT:"e6da9cb":1040) <- PaperSpigot
    Server type: Non-integrated multiplayer server
Stacktrace:
    at bdb.a(SourceFile:309)
    at ave.b(SourceFile:2296)
    at ave.a(SourceFile:334)
    at net.minecraft.client.main.Main.main(SourceFile:124)

-- System Details --
Details:
    Minecraft Version: 1.8.6
    Operating System: Mac OS X (x86_64) version 10.9.5
    CPU: 4x Intel(R) Core(TM) i5-4570R CPU @ 2.70GHz
    Java Version: 1.6.0_65, Apple Inc.
    Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Apple Inc.
    Memory: 184963744 bytes (176 MB) / 365592576 bytes (348 MB) up to 1060372480 bytes (1011 MB)
    JVM Flags: 5 total; -Xmx1G -XX:+UseConcMarkSweepGC -XX:+CMSIncrementalMode -XX:-UseAdaptiveSizePolicy -Xmn128M
    IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
    Launched Version: 1.8.6
    LWJGL: 2.9.2
    OpenGL: Intel Iris Pro OpenGL Engine GL version 2.1 INTEL-8.28.33, Intel Inc.
    GL Caps: Using GL 1.3 multitexturing.
Using GL 1.3 texture combiners.
Using framebuffer objects because ARB_framebuffer_object is supported and separate blending is supported.
Shaders are available because OpenGL 2.1 is supported.
VBOs are available because OpenGL 1.5 is supported.

```
Using VBOs: Yes
Is Modded: Probably not. Jar signature remains and client brand is untouched.
Type: Client (map_client.txt)
Resource Packs: [faithful32pack.zip, SQBasic.zip]
Current Language: English (US)
Profiler Position: N/A (disabled)
```

**Comment by mcdouble** [comment]
This is like reading the alphabet for Dib isn't it?

**Comment by liv4ths** [comment]
I had that issue of mc crashing when paddy would tp to me as an enderman on iff

**Comment by awangatboo** [comment]
It just started working.
