### ISSUE TITLE
Missing 6 months of priority

### ISSUE THREAD

**Issue by Afgncaatp** [StarQuestMinecraft/StarQuestPublic#484]
I just bough 6 months of priority. When I flew to Regalis got notice that my buy craft purchases had been credited, but my subscription balance remains at 0. I can provide receipts if needed.

I think this happened earlier when another player bought priority for me, but I was hesitant to push it as I couldn't tell for sure if he had made the purchase. Now I believe he did and that would put me as missing 8 months of priority.

I'd very much like to get this resolved soon so I can participate in the solar apocalypse

**Comment by Kyle98martin** [comment]
I just purchased a 3 month priority and also received the buycraft notification but received no priority subscription. Can provide proof if needed.

**Comment by Afgncaatp** [comment]
Issue fixed for both of us, thanks to the mysterious mod/dev who handled it.
