### ISSUE TITLE
Data Cores

### ISSUE THREAD

**Issue by Nickmiste** [StarQuestMinecraft/StarQuestPublic#487]
Data Cores turn into normal paper upon duty and undutying

**Comment by Evancooldude** [comment]
I looked into this, Ginger looked at the code too, and neither of us could make heads or tails of why it isn't working. The only logical problem with the system at this point is that either the database, or the database system, isn't properly set up for this usage, or that the duty program isn't linking into it properly, and neither of us know the first thing about accessing the databases. If LittleWolf were here, he could solve it, but as it is it may be a while before somebody figures out what's going on here.

**Comment by awangatboo** [comment]
Closing all bugs in preparation for SQ 4.0.
