### ISSUE TITLE
Trap doors

### ISSUE THREAD

**Issue by liv4ths** [StarQuestMinecraft/StarQuestPublic#489]
Okay so got told this isnt intended so here i go, for as long as ive played sq when you put a trap door on the top part of a block then fly with your ship it drops to the lower part of the block. happens everytime. idk whats causing it though.

to repeat bug do the following: place a wooden trap door on the top part of a block, save ship then try to fly, then stop piloting go look a trap door, it falls down the block.

**Comment by awangatboo** [comment]
I think this should be a low priority if not just accepted as the design of the game.

**Comment by awangatboo** [comment]
Closing all bugs in preparation for SQ 4.0.
