### ISSUE TITLE
planet logout bug

### ISSUE THREAD

**Issue by WERTRUS** [StarQuestMinecraft/StarQuestPublic#490]
I was just having a look around at the sights on bosk but when I logged out to have lunch, when I came back I was in the middle of nowhere suffocating in space. 3 days later I was on kel when it happened again. Also when I teleported I had nothing on me like it was all taken away. I am not sure what happened but hopefully you might be able to figure it out. 

P.S. Love the server. Its so cool.

-**WERTY**

**Comment by awangatboo** [comment]
This most likely was a Bungge issue.  These happen from time to time and for the most part you need Mod help to get your stuff back.  As this is a know issue could you please close your ticket
