### ISSUE TITLE
Nether brick stairs and slabs not a ship block

### ISSUE THREAD

**Issue by Consue** [StarQuestMinecraft/StarQuestPublic#491]
I was playing around in the shinatagins server and I noticed that my ships with nether brick armor dont count it as a ship block
is this intended or a bug cause if it is a feature then I have a lot or remodeling to do XD

**Comment by awangatboo** [comment]
schenanigans server has been shut down to normal users and SQ 3.0 has been out for a while.  I just tested on SQ 3.0 and Nether brick slabs work but stairs do not.  This might be by design.

@Dibujaron 

Are Nether Brick stairs meant to not be ship blocks?

**Comment by awangatboo** [comment]
I have been told by SQ Management that this was planned in SQ 3.0.  Closing Ticket
