### ISSUE TITLE
Cannons Can Be Covered

### ISSUE THREAD

**Issue by brickworm2012** [StarQuestMinecraft/StarQuestPublic#494]
Cannons that have non-pushable blocks in front of them, like furnaces, simply push the cannon fire right through. I have no idea how long this has been going on, and is in effect both on the regular and Shenanigans servers.

**Comment by awangatboo** [comment]
I think this is an issue but it is up to the SQ management to state if this is allowed or not.

**Comment by lawrencethefrog** [comment]
I would assume that this is not allowed as cannons are meant to be destroyable by blasting (with turrets or other cannons) so if this bug allows you to make the cannons indestructible by covering them with blast proof materials it is (by virtue of the common sense rule) illegal.

**Comment by awangatboo** [comment]
Closing all bugs in preparation for SQ 4.0.
