### ISSUE TITLE
Shenanigans server

### ISSUE THREAD

**Issue by ghost** [StarQuestMinecraft/StarQuestPublic#495]
Well this has been a day in the making.
So long story short I was building a ship and finished it. It was all fine, until I tried to fly it and it worked for a bit. Suddenly I cant stop riding it. I broke the ship sign and nothing happened. /stopriding doesn't work /releaseallships doesn't work noting works. I got the idea to use schematica to copy my ship and use a alt to fly it. It worked! I went on placing all the signs for torpedoes and turrets and it was fine. It was all fine until I placed the ship shield. As soon as I placed it it broke. I got the exact same bug

I hope this will help find a way to fix it. What I was thinking was removing the usernames _UltimateV and UltimateVillager (my main and alt) from the shield database and the ship database and the "ghost ship" it thinks i'm piloting (but i'm not) will be removed.

**Comment by ghost** [comment]
[edit] This is the sq 3.0 plugin and the same bug may be on the main server when it opens many others may get this bug with ship shields.

**Comment by awangatboo** [comment]
SQ 3.0 has been open for a while and I know I have not seen this bug and have played a Very long time.
