### ISSUE TITLE
SkyWatch

### ISSUE THREAD

**Issue by GoldPikachuSpark** [StarQuestMinecraft/StarQuestPublic#496]
I am in a faction with xLordHerobrinex and I happened to "accidently" punch him and skywatch appeared and then the server restarted and Skywatch was no longer tracking me.

**Comment by awangatboo** [comment]
I do not think this is a Bug but just the way the system works.  SkyWatch will not carry over a system restart.  

@Dibujaron 

Could please confirm this is the way it works?
