### ISSUE TITLE
Cryopod Not Functional

### ISSUE THREAD

**Issue by Pairjax** [StarQuestMinecraft/StarQuestPublic#499]
So, I travel all the way to Ava in order to remain there, and I forget my food when I'm at the bottom of the world. I decide, since I already activated my pod, to just die and store the items in a chest I can retrieve later. Now, I die and I return back to spawn. I now am at Rakuria, gathering wool to travel back to Ava. If this bug could be fixed, and I returned to the planet, I would greatly appreciate it. However, I would be fine with you only fixing the bug, because I can make it to the Gamma sector by my own. I also already know the coords to Ava.

**Comment by awangatboo** [comment]
Closing this bug in order to obtain better details in current Cryopod issues.  If you have another Cryopod iss please see this forum thread before opening a new issue.

http://www.starquestminecraft.com/starquestforums/m/17078810/viewthread/23552021-great-cryopod-bug-closing/post/last#last
