### ISSUE TITLE
Time Out

### ISSUE THREAD

**Issue by mcdouble** [StarQuestMinecraft/StarQuestPublic#503]
3:54 EST I timed out randomly. Screen says: java.net.ConnectException: Connection timed out: no further information:

Second timeout like this in last half hour. First one recovered in a minute for me, as did the second one. Also, dynmap appears to not be loading for me. This might crappy internet on my side, but I figured I'd report because I remember AWHILE ago you'd ask for timeouts to be reported.

**Comment by mcdouble** [comment]
30 seconds after logging in I had the "Existing connection forcibly closed by a remote host". Not sure if this means anything to you.

**Comment by GoldPikachuSpark** [comment]
It's dynmap, me and LH are getting the same problem. When we're on any starquest server and go to the dynmap website we time out of both and can't reconnect to any SQ server for like 3-5 minutes (any as in Teamspeak, shenanigans, and regular SQ.

**Comment by awangatboo** [comment]
Many of the issues that happened day one have been resolved.  If this is still not an issue please close this github ticket so Dib can get to the important ones that cause issues for the whole server.
