### ISSUE TITLE
Contracts wiped

### ISSUE THREAD

**Issue by immensityofkaiq** [StarQuestMinecraft/StarQuestPublic#504]
Thankfully, my (OreNinja's) old smuggling contract from 2.0 is gone, but so are all of my 3.0 contracts from yesterday (around 3 AM EST today actually), including a Merchanting contract for five stacks and twelve green wool for eight thousand something credits and one merchanting point. I did not drop them, nor do I know how to. Please help.

**Comment by Dibujaron** [comment]
I dropped all of them for everyone. Sorry that I wiped your good one.
