### ISSUE TITLE
Ships

### ISSUE THREAD

**Issue by mcdouble** [StarQuestMinecraft/StarQuestPublic#505]
This isn't a bug, but I know this is the sort of place where you want issues. 

Currently, ships are spawning into each other at spawn station when you spawn your ship in. This is a big issue. There's few people who dig themselves out, and even if they do, their ship leaves debris behind. Everybody's getting stuck. 

Is it possible to have a system like the speeder spawners where it will first notify you there's a ship in the way and ask you to inform the owner. If owner is offline click button again to remove ship.

**Comment by awangatboo** [comment]
This sounds more like a suggestion.  Suggestions should be put in the forums.  There are 6 pages of Bugs and I think lots of them are not bugs.  I would request that you close this issue seeing that most people have lost there legacy ships at this point and no refunds are going to happen.
