### ISSUE TITLE
Dynmap Kicks Us from All SQ Servers

### ISSUE THREAD

**Issue by GoldPikachuSpark** [StarQuestMinecraft/StarQuestPublic#506]
Whenever xLordHerobrinex and I (Goldieh) are on any SQ server (Teamspeak, shenanigans, regular SQ, etc.) and open dynmap we time out from all SQ servers and cannot reconnect to any SQ server for a while. This only happens when we open dynmap.

**Comment by GroxTerror** [comment]
This is because of the current DDoS attack that has passed.
