### ISSUE TITLE
Lockette only works on oak doors.

### ISSUE THREAD

**Issue by Goldham89** [StarQuestMinecraft/StarQuestPublic#507]
Jungle, Birch and Pine doors do not work with lockette

**Comment by awangatboo** [comment]
I need to make sure this is still the case.

**Comment by Evancooldude** [comment]
As far as I know, this is still an issue. I'll look into adding that to lockette, but it's a surprisingly complex plugin...

**Comment by GingerWalnut** [comment]
This has been fixed.
