### ISSUE TITLE
Mobs Not Spawning on Uru

### ISSUE THREAD

**Issue by Cutout1** [StarQuestMinecraft/StarQuestPublic#511]
I have yet to see a single creeper or bat on Uru, and I've been there for a while. I talked to a few other people, and they haven't seen any either. I haven't played today yet, so I don't know if it isn't fixed already, but it makes mining there a bit too easy.

**Comment by awangatboo** [comment]
Mobs on Uru now spawn.  The spawn rate is low but they do spawn.

Please close ticket.  If you want to open another ticket about spawn rates please make sure someone else have not done so already.
