### ISSUE TITLE
Bought Priority Got 4 months instead of 1

### ISSUE THREAD

**Issue by Cutout1** [StarQuestMinecraft/StarQuestPublic#512]
So today I decided I would buy priority. The server was hard to join, and the server does need money so I decided to buy a month. I checked /subscription, and it said I had 120 days. Anyone know why? I am 95% sure I only bought the one 5$ pack.

**Comment by Dibujaron** [comment]
Thanks for reporting, fixing this haha, it was doing that for everyone... I appreciate your honesty :)
