### ISSUE TITLE
Skywatch on Uru and potentially other planets + ryopods

### ISSUE THREAD

**Issue by Kyle98martin** [StarQuestMinecraft/StarQuestPublic#513]
I logged in before to being instantly being swarmed by a ridiculous amounts ghasts and skeletons with punch bows which swiftly lead to my death and loss of a lot of gear. I have reports of 2 incidents of skywatch showing up when playing have taken damage from falling or a cactus. They are also not only coming in 1 wave. I killed someone before and I had to fight 2 separate waves of skywatch rather than just 1. Cryopods are also not saving on Uru.

**Comment by Dibujaron** [comment]
Fixed skywatch. Cryopods are working for my testing, can you provide step-by-step of how it's not working? Remember that active cryopods no longer work in the way they used to.

**Comment by Kyle98martin** [comment]
I had a cryopod set up on Uru and when skywatch killed me the cryopod failed to spawn me at it. This has happened to 1 other person that I know about. I'm fairly certain this issue only occurs when you're killed by skywatch.
