### ISSUE TITLE
Ship loading problem

### ISSUE THREAD

**Issue by mastermagi00** [StarQuestMinecraft/StarQuestPublic#514]
I tried to load in my Dreadnought today, but it just teleported me to some other guy's ship. I checked the dynmap to make sure the ship didn't spawn in somewhere else, but it was nowhere to be found.
but here's the kicker. I went back inside the spawn station, and pressed the button AGAIN and it TPed me to where that other guy's ship was before he moved it.

In conclusion:
-You can press the button more than once,
-upon pressing the button, your ship does not spawn
-and finally, upon pressing the button you TP into the middle of nowhere
-and just to clear things up, my ship has not spawned anywhere

Also, this is not a refund request. this is just to help you guys fix the problem

**Comment by awangatboo** [comment]
I think 0 work will be done on Legacy ships.  If they worked then great if not "Oh Well".

Please close ticket
