### ISSUE TITLE
Negative Credits from Contract

### ISSUE THREAD

**Issue by GoldPikachuSpark** [StarQuestMinecraft/StarQuestPublic#516]
I did ./contract new to view my available contracts and saw that a smuggling contract required 74 sugar cane to be turned into Eco Station Alpha-West but the reward was one smuggling point and -196 credits.

Screenshot:
http://gyazo.com/ee648316e455b169fd14d2e702d6d010

--Goldieh :smile:

**Comment by Siigillum** [comment]
Sounds liek a good deal.

**Comment by Generaltyler1** [comment]
dib did say that there will be some bad deals that come out, not sure if this it one or not

**Comment by awangatboo** [comment]
This issue has bee resolved please close Ticket
