### ISSUE TITLE
Ships Not Dropping Datacores

### ISSUE THREAD

**Issue by GoldPikachuSpark** [StarQuestMinecraft/StarQuestPublic#517]
I broke RoyalSoda114's fighter ship sign when he logged on me and I didn't get a datacore. We were on Xylos I don't know if I have to do something before ships drop datacores but I'm not getting any from any ship sign i break and I don't get a message that says the ship has been parked for more than five minutes.

**Comment by Siigillum** [comment]
Get a piracy contract so they drop.

**Comment by awangatboo** [comment]
Please close ticket if Siig's solutions works.

**Comment by awangatboo** [comment]
Is this still an Issue?

**Comment by awangatboo** [comment]
Data cores are dropping right now.
