### ISSUE TITLE
Lag/Rollback Death

### ISSUE THREAD

**Issue by ConnorXConnor** [StarQuestMinecraft/StarQuestPublic#521]
Minutes before the most recent restart I was rollbacked into the air while constructing my base. I entered my ship to fly it, but noticed that I was lagging because the lapis block anchoring it did not drop. Then I was teleported into the air a bit above my base where I'd jumped down before, and survived, and fell to my death. If the next staff member who can could get online to validate and restore this, that would be great.

**Comment by awangatboo** [comment]
This is a refund request please talk to a Mod about this and close the GitHub Ticket as GitHub is for repeatable bugs.
