### ISSUE TITLE
Contracts not working right.

### ISSUE THREAD

**Issue by AlinaFicalton** [StarQuestMinecraft/StarQuestPublic#525]
I tryed to accept a contract and it gave me a different contract then the one i picked (i checked the list and contract number and it was the right one). Also when I try to get a ship core I cant. I have tryed sneaking onto someones ship and braking there sign (yes within 5 min) and nothing. I have also tryed hurting and killing someone then braking there sign and STILL no ship core!

**Comment by Dibujaron** [comment]
I'm investigating. FYI you can /contract delete within an hour of accepting it if you end up with a contract you don't like.

**Comment by AlinaFicalton** [comment]
yes but that costs me 1/2 the reward or so i was told by everyone.

**Comment by awangatboo** [comment]
Contract system has been re-worked.  Please close and re-report if the issue returns.
