### ISSUE TITLE
Skywatch is Still on in Gamma planet's and System

### ISSUE THREAD

**Issue by JavaInvader** [StarQuestMinecraft/StarQuestPublic#526]
Hit someone on Avaquo (Avacado) and got skywatch warning then troops showed up as expected after the warning. logged off and now heading to bed so haven't died (yet) and sure hope that i don't! XD

**Comment by Dibujaron** [comment]
Dangit. Will fix. Thanks for reporting.

**Comment by Dibujaron** [comment]
fixed at next restart
