### ISSUE TITLE
relogging from one pc to another

### ISSUE THREAD

**Issue by mulleeh** [StarQuestMinecraft/StarQuestPublic#528]
at first i was playing on a secondary computer. I started on grun and went to complete a contract and afterwards to otavo. after i got to otavo i wanted switch back to my primary computer, and when i logged in it put me back to grun where i started. maybe the server didn't save my progress but i guess you have a better chance to see that than me. Thank you for the help.

Mulleeh

**Comment by awangatboo** [comment]
make sure you are using play.starquestminecraft.com as your server address on both computers.  From time to time Bungee can get mixed up if you use the IP and then use the DNS name.  

Known issue please close ticket.
