### ISSUE TITLE
Docking tube wont retract

### ISSUE THREAD

**Issue by mrtopsyt** [StarQuestMinecraft/StarQuestPublic#531]
I docked to ecostation alpha north, not realising that it was an iron door I was trying to dock to. However when I try to release my docking tube it says "Docking tube does not end in wool - error". My ship is now stuck at the ecostation and it would be great if a staff member could undock it.

**Comment by awangatboo** [comment]
was someone able to help you?

**Comment by mrtopsyt** [comment]
Yes.

 Tuesday, August 4, 2015, awangatboo notifications@github.com wrote:

> was someone able to help you?
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/StarQuestMinecraft/StarQuestPublic/issues/531#issuecomment-127611620
> .

## 

From Jonah

**Comment by awangatboo** [comment]
Closing ticket as you were helped.
