### ISSUE TITLE
Cryo not working

### ISSUE THREAD

**Issue by Tonlage** [StarQuestMinecraft/StarQuestPublic#532]
My friend Kridec recently used /suicide on Sampetra.  Instead of respawning at his cryopod, he respawned in the middle of space, we do not know where, and suffocated to death. Then he respawned after this he spawned Spawn instead of his cryo.

**Comment by awangatboo** [comment]
Closing this bug in order to obtain better details in current Cryopod issues.  If you have another Cryopod iss please see this forum thread before opening a new issue.

http://www.starquestminecraft.com/starquestforums/m/17078810/viewthread/23552021-great-cryopod-bug-closing/post/last#last
