### ISSUE TITLE
Bouncy Ship Bug

### ISSUE THREAD

**Issue by oreomium** [StarQuestMinecraft/StarQuestPublic#534]
I dont know if there is already an issue for this, but I just got killed exiting Uru. I exited the atmosphere, and I kept bouncing in my ship, and it was spamming me /stopriding. I could not move, and so I did /stopriding, but it dismounted me outside of my ship, and I tried to get back in, but the ship went into the atmosphere of Uru, so I was stranded in space without a helmet and I died. -Matthew385

**Comment by awangatboo** [comment]
Dib updated movecraft.  i have not seen this in a while so I will close this ticket.  Please open another ticket if it happens again.
