### ISSUE TITLE
Mob Spawning

### ISSUE THREAD

**Issue by JavaInvader** [StarQuestMinecraft/StarQuestPublic#535]
Mob spawning is Great on Avaquo now but Still seems to be 0 mobs on xylos

**Comment by Kyle98martin** [comment]
Uru is also having weird spawning issues. The creepers spawn as usual but the old krys skeles are spawning everywhere.

**Comment by mcdouble** [comment]
Tallimar as well.

**Comment by mcdouble** [comment]
Issue is relevant on Xylos as well. (reporting for somebody who asked  me to on xylos)

**Comment by mcdouble** [comment]
bump

**Comment by awangatboo** [comment]
mobs are working well.
