### ISSUE TITLE
Can't delete tradepost buy order

### ISSUE THREAD

**Issue by Tonlage** [StarQuestMinecraft/StarQuestPublic#536]
As the title suggests i am unable to delete a buy order i made. When i type /tradepost manage it shows up as it should and then i click it it asks for confirmation, but when i click confirm nothing happens and it still shows up in /tradepost manage.

**Comment by Nickmiste** [comment]
Under review

**Comment by awangatboo** [comment]
Closing ticket as tradepost are going away for a new system Niick is working on.
