### ISSUE TITLE
Netherwart dissapears

### ISSUE THREAD

**Issue by cloudtail** [StarQuestMinecraft/StarQuestPublic#537]
When right clicking with netherwart on avaquo I got the restricted item message and the whole stack dissapeared from my inventory.

**Comment by Nickmiste** [comment]
Netherwart is only able to be grown on Xylos.

**Comment by GroxTerror** [comment]
I think he's saying he was just trying to transport it back not plant it, and it disappeared.

**Comment by cloudtail** [comment]
no, literaly, if you hold and right click, it dissapears

**Comment by awangatboo** [comment]
I can not reproduce.  Is this still an issue?

**Comment by awangatboo** [comment]
Cloudtail please comment or I will assume that this is no longer an issue.

**Comment by awangatboo** [comment]
Seeing that I cannot reproduce and Cloudtail has not responded I am closing this ticket
