### ISSUE TITLE
Faction Chat

### ISSUE THREAD

**Issue by mcdouble** [StarQuestMinecraft/StarQuestPublic#538]
faction chat hasn't worked the whole time. idk what thats about... but yeah

**Comment by Kyle98martin** [comment]
Get used to it. It won't work 95% of the time.

**Comment by mcdouble** [comment]
Neither did Town Chat :/

**Comment by awangatboo** [comment]
The BungeeSuite chat plugin is not a great one and has loads of issues.  I am not sure if this will be fixed by our Dev's,
