### ISSUE TITLE
Treefarm not working

### ISSUE THREAD

**Issue by Scooter5131** [StarQuestMinecraft/StarQuestPublic#539]
I unlocked the treefarm but can't get it to work. Tried with both Iron and Diamond Blocks in multiple areas and never got the sign to change after I entered [treefarm] and clicked it.

I doubled checked the forum to make sure everything was set up correctly and didn't see any issues.

FYI,
I am on Rakuria

Scooter5131
![2015-06-28_16 17 27](https://cloud.githubusercontent.com/assets/13090706/8398425/6fdd5e9c-1db3-11e5-9852-93dad44d877a.png)

**Comment by awangatboo** [comment]
This is Nick's Plugin.  I think I remember hearing something about tree-farm and permissions.  Hopefully Nick can fill us in.

**Comment by BatFC** [comment]
Tree farms still don't work, tested on 24th Jul.

**Comment by Scooter5131** [comment]
I can also confirm that they do not work on Eratoss as I moved there a couple of weeks ago and have been trying to activate it every day that I am on.

There is additional information from awangatboo in issue #606, and Nickmiste was assigned to that one a little over a week ago.

**Comment by Scooter5131** [comment]
Have there been any updates on this yet, still not working on August 3rd.

**Comment by awangatboo** [comment]
This is a duplicate of issue #606.  Issue #606 is assigned to @Nickmiste so we should keep up with that ticket.  I am marking as duplicate and closing this one.
