### ISSUE TITLE
uru lag death

### ISSUE THREAD

**Issue by Laserlance141** [StarQuestMinecraft/StarQuestPublic#540]
So, i was mining on uru and all of a sudden i started lagging, so when i got kicked form the server, i thought it was no big deal. I immediately logged back on (priority :sick: ) and found my self back on Eratoss, right where my ship had left the planet (in the sky), with no items on me at all. I promtly fell to my death, and then re spawned on Eratross, not in my cryo. I had 2 freshly enchanted tools on me, a dia pick with silk touch, and a dia pick with efficiency 4, a unenchanted dia sword, a set of full iron armor and 28 levels(was enchanting). I think if i just get sent to limbo and then choose to go to uru, ill get all the stuff back, so i probably won't need to get it all refunded. I have i large amount of client log data showing the death, then how i would keep respawning on eratoss.

**Comment by mcdouble** [comment]
pics or it didn't happen

**Comment by Laserlance141** [comment]
only evidence is the continued re spawning on eratoss and a large client side log, which i can't put inhere for some reason

**Comment by awangatboo** [comment]
Take up any refund requests with Mods.  The real issue is why did Bungee forget where you were.  I think unless we can reproduce this issue it is a bug that can not be fixed.  

Close this Ticket please.
