### ISSUE TITLE
Glitched out of my ship and fell to death on Octavo

### ISSUE THREAD

**Issue by jamesmc1209** [StarQuestMinecraft/StarQuestPublic#541]
Hello, I was flying a ship I bought after i was too trusting and lost all my items. I was flying to Octavo to gather leather to trade to a faction who was stocked on supplies. Upon entering the atmosphere in Octavo when as soon as it loaded the terrain i was falling to my death. I'm looking on the dynamap to find my stuff but by now it's gone. My only hope is to find my ship. I had 15 iron ore, 8 diamonds, 30 gold poly, aprox 50 steaks, and my powerdrill. that is the only items i really care about. I already got robbed when trading to a stranger of 50 copper, & 3 stacks of leather. This is getting annoying that i have to now start all over for a third time....

**Comment by mcdouble** [comment]
This isn't a ticket.... Remember, you were told to file a ticket asking for help? This is github.

**Comment by awangatboo** [comment]
For refund request please contact a Mod.  

Please close this Ticket
