### ISSUE TITLE
Unable to leave athmosphere

### ISSUE THREAD

**Issue by Draconoc** [StarQuestMinecraft/StarQuestPublic#544]
I was trying to leave the athmosphere of Cetallion with my makeshift shuttle. But the moment the message of "leaving the athmosphere" appeared, I glitched out of the ship fell to the ground (without damage somehow) and my inventory was wiped. Also it seems that my shuttle did leave the athmosphere, sadly I did not, and I don't have any means (that I know of) of recovering it.
I didn't manage to catch a screenshot of my fall, but I did get one of the error message.
![2015-06-29_15 52 09](https://cloud.githubusercontent.com/assets/13104847/8411660/7986b6dc-1e85-11e5-92be-af3aa462f772.png)

**Comment by Tonlage** [comment]
Same thing happened to me, but on Rakuria

**Comment by Scooter5131** [comment]
Same thing just happened to me on Rakuria also

![2015-07-01_06 14 32](https://cloud.githubusercontent.com/assets/13090706/8453808/c2a18f02-1fbd-11e5-91ff-0975e79bc1f5.png)

**Comment by awangatboo** [comment]
This is an issue that happens if the Server that you are going to is down.  Hopefully you contacted Mod's about a refund and have not flown any ships or gone into the Alpha system since this bug otherwise you can not be refunded.  

Known issues -

Please close Ticket.
