### ISSUE TITLE
Priority reset again.

### ISSUE THREAD

**Issue by ShinySurskit** [StarQuestMinecraft/StarQuestPublic#546]
Last I checked I had about 27 days remaining, and it is gone again just after the most recent reset :/

HAALP

:P

**Comment by TacoLink** [comment]
Happened to me too. Had about 160 days remaining, cannot get on server.

**Comment by icekoob** [comment]
Happened to me 2

**Comment by Dibujaron** [comment]
This was fixed. Sorry guys.
