### ISSUE TITLE
Some issues with cert unlocking and ship stats

### ISSUE THREAD

**Issue by Gaming4me** [StarQuestMinecraft/StarQuestPublic#547]
1- When you unlock a cert, it still shows at /certs available

2-If you try to unlock it again, it'll take your money and give you the same tag again

![tags](https://cloud.githubusercontent.com/assets/11284568/8421637/1d3d5c78-1ea8-11e5-9c1f-add2d5dd6b25.png)

3- doing /shipclass gunship returns an error.

**Comment by Kyle98martin** [comment]
/stats was disabled or never added. I believe Dib said he was going to try and add it back today.

**Comment by Dibujaron** [comment]
Fixed this issue.

/shipclass is meant to be used with a player, not an actual shipclass. It's to see who is flying what.
