### ISSUE TITLE
Priority still not working

### ISSUE THREAD

**Issue by ssninja** [StarQuestMinecraft/StarQuestPublic#548]
I purchased my priority on 6-29-15 and today (6-30-15) it still doesn't work, after purchasing priority I tried going on to the server and it was in "maintenance mode" I was later told that the priority users were being manually re-entered, I believe that my username was missed when re-entering the users. My buycraft transaction ID was: 7NM63794LL623980T and I purchased priority for 1 month.
Thank you!

**Comment by Dibujaron** [comment]
Sorry about that! You bought it right during the transition and it didn't go through. Fixed, and some bonus time added for your troubles!
