### ISSUE TITLE
Wool drops on Uru

### ISSUE THREAD

**Issue by GamingOverlord** [StarQuestMinecraft/StarQuestPublic#552]
I did not see a post so far on this, so I just wanted to make sure that it has been reported that wool on Uru does not drop from leaves
If it has, what place in the queue does fixing this have?

**Comment by awangatboo** [comment]
Uru is a desert planet.  There should not be trees to get wool from.  Have you tried to see if you can get any from cactus like on Grun?  If so then it is just the Wiki that is stating it wrong.  Please test.

**Comment by GamingOverlord** [comment]
I've checked
Dib himself(or whoever typed the description in the news) stated it drops from leaves.
I checked and it does not drop from cactus
Trees grow in the oasis
Lots of them

**Comment by awangatboo** [comment]
I just got word from the SQ management that they changed their mind on having wool on every planet.  Wool source on Uru is not planed.  Closing Ticket.
