### ISSUE TITLE
Weird ship beaviour in gamma

### ISSUE THREAD

**Issue by Siigillum** [StarQuestMinecraft/StarQuestPublic#554]
So i chased one guy in gamma, shot him with turret and aparently this weird glitch appeared when i was moving ship around without moving myself. Hold shift - ship moves, i stay in place. It was like moving it remotely.

dying and comming back helped. reloging temporarily helps.

**Comment by Siigillum** [comment]
This is caused by PVP manager plugin. Causes ships to behave like that as soon as it's triggered.

**Comment by Siigillum** [comment]
PVP manager most likely breaks shipcombat that way. :( 

I heared old had a good idea of /logoff plugin. Might be better.

**Comment by GroxTerror** [comment]
This is a very old glitch I've found, usually occurring with carpets in 2.0 (ship flies without me)

**Comment by Siigillum** [comment]
PVP manager bug. Issue solved. Closing. Thanks Dib.
