### ISSUE TITLE
Change of Contract terms

### ISSUE THREAD

**Issue by Architect752** [StarQuestMinecraft/StarQuestPublic#556]
Last night around 8:00 to 9;00 PM EST, while on Eartoss, I accepted two new contracts one after the other just before getting off for the night.

The first was a Merchant contract for 39 cyan wool taken to Alpha north.  The second and the problem one, was a Smuggling contract for around 59 brown wool taken to Alpha north.  As I recall, I even brought up contract list to ensure I had the right one, before logging off.

When I logged on today around 6:00 PM EST I brought up contract list to ensure I had the amount of wool needed before flying off and found that my Smuggling contract had changed it's terms.  Now it wants 2175 Thin_glass (Glass panes I assume) taken to Beta east {Photo below}.  I know I did not chose this one by mistake because it was not in even in my list of contracts open to take last night.

http://i.imgur.com/D12wKcD.png

I think what may have caused this, is the fact that I took two contracts at just about the same time.

If possible I request this contract removed from my list, If that is not possible I don't mind.

**Comment by Nickmiste** [comment]
Typing "/contract new <#>" to accept a contract will give you 5 new contracts. Don't accept 2 comtracts right away.

**Comment by Architect752** [comment]
Ah I see.  I did not know that, so I thought it was a glitch.  Oh well, I guess I have a lot of glass panes to acquire or 2054.5 credits to pay to remove it.
