### ISSUE TITLE
Legacy ship didnt spawn in right

### ISSUE THREAD

**Issue by AlinaFicalton** [StarQuestMinecraft/StarQuestPublic#558]
I just spawned in my legasy ship and i cant fly it. why

**Comment by mcdouble** [comment]
You're one of like 100 others who lost their favorite ship in the legacy spawn in area. Apparently we were supposed to know whether or not the area was clear to spawn in or not.

**Comment by AlinaFicalton** [comment]
it was clear. my legasy ship didnt spawn with a legasy sign, just a normal one.

**Comment by awangatboo** [comment]
Dib stated legacy ships are use at your own risk.  Mine did not work and was destroyed by someone else.  TheBeaver99 lost his as someone spawned their ship inside of his.  In short I think this is a know issue and you will not get a refund please just build up all your resources from the great SQ 3.0 planets.  

Please close this Ticket.
