### ISSUE TITLE
PvP manager not trigerred by cannon explosions

### ISSUE THREAD

**Issue by Siigillum** [StarQuestMinecraft/StarQuestPublic#559]
As in the topic. Pvp manager plugin is not being triggered by cannons' explosions, very likely it wont be trigerred by torpedoes too. 

Since skywatch IS triggered by cannons' explosions I believe the fix to this is possible.

On a side note, Pvp manager works well now while doing shipcombat. Though the /logoff plugin old mentioned may be a better idea at some point. Reloging usually helps o get rid of movecraft bugs and glitches, PvP manager makes this impossible in many cases.

**Comment by awangatboo** [comment]
Closing all bugs in preparation for SQ 4.0.
