### ISSUE TITLE
Lost Ship and Inventory on Arrival to Trinitos Gamma

### ISSUE THREAD

**Issue by Hockeyson48** [StarQuestMinecraft/StarQuestPublic#560]
So I lost ship and inventory on my arrival to Trinitos Gamma as soon as I went through the slipgate (screenshots provided below). All I am asking for is a small refund for inventory and my ship, as well as a warning to players to make sure to be careful when going through slipgates.

http://imgur.com/X57wpeP,UIg3pVo,DjQIZ4O

**Comment by Dibujaron** [comment]
Um, according to my logs, Your serverjump came from Trinitos Beta to Avaquo, and then I don't see one of you leaving Avaquo to go somewhere else. You shouldn't be able to jump directly from Trinitos Beta to Avaquo, so I'm a bit confused here... any light you could shed on that?

**Comment by Hockeyson48** [comment]
Well that is proabaly the issue, I died in Gamma and never went to Avaquo. After I got refunded by Generaltyler, THEN I went to avaquo. Not sure why the logs say something else.

**Comment by awangatboo** [comment]
I think this is an old issue.  Closing Ticket.  Will re-open if this is still a problem.
