### ISSUE TITLE
planter dont work 

### ISSUE THREAD

**Issue by ekarlate** [StarQuestMinecraft/StarQuestPublic#561]
Actually the problem is when i try to switch the lever it says i dont have perms.

But i actually do have the ressource engineer certs unlocked as iam using drills for some times now.
my farm is well built as i followed machina website way to built it.

anyway i can fix that? other player told me they where able to use the planter w/o any problem so.

dont know what else now XD

**Comment by JavaInvader** [comment]
Same problem except i unlocked it 2 times opps XD doesn't work, still says I do not have permission to use this.

**Comment by awangatboo** [comment]
I have the same issue.  I think something is wrong wen you unlock the cert because I think it does not add

 machinaplanter.*:
        children:
            machinaplanter.all: true

to your permissions on your account.  It does this for the drill.

**Comment by awangatboo** [comment]
As noted in another post the Tag is also missing.

**Comment by AlinaFicalton** [comment]
i am also having this problem

**Comment by PatchyFox** [comment]
Issue still withstanding

**Comment by Dibujaron** [comment]
@Moneybags118

**Comment by awangatboo** [comment]
It looks like if you buy the new resource one it will work now.  

Please close ticket as the bug has been fixed.

**Comment by awangatboo** [comment]
This was a permissions issue that has been fixed now but you will need to re-purchase the cert
