### ISSUE TITLE
Contract Completed Didn't Give me points or credits

### ISSUE THREAD

**Issue by ConnorXConnor** [StarQuestMinecraft/StarQuestPublic#564]
Title says the most. I had a contract to Gamma west and flew over to it.
It was a smuggling one for 59 copper blocks.  I completed the contract but it didn't give me any smuggling points or credits.

**Comment by awangatboo** [comment]
Issue resolved also a duplicate issue.  I think the other was the duplicate but it really does not matter.  Please close your ticket.
