### ISSUE TITLE
Contracts not giving rewards

### ISSUE THREAD

**Issue by AlinaFicalton** [StarQuestMinecraft/StarQuestPublic#565]
so i finished 2 contracts today (one worth 33060c and the other i have no idea) and i didnt get any rewards, not money not rep, nothing.

**Comment by AlinaFicalton** [comment]
also i think contracts are broken. I have a contract to turn in 1399 stone to gamma west and its saying i dont have any materials. Ive tryed cobble stone, stone, and stone bricks, and nothings working

**Comment by JavaInvader** [comment]
I had a contract for Dark oak. I chopped 12 stacks of logs go to complete says i dont have the materials. then I convert a stack into planks and it worked so contracts aren't very clear with the names.

**Comment by awangatboo** [comment]
From what I have heard the contracts not paying out was a problem for a day or so.  This issue has been fixed I think as I completed a smuggling and a merchanting contract today and they payed out.  As the specific of your GitHub ticket has been completed please close your ticket.  If you want to start another one about contract items names then that should reflect it in the title.
