### ISSUE TITLE
World Boarders do not work with ships

### ISSUE THREAD

**Issue by awangatboo** [StarQuestMinecraft/StarQuestPublic#567]
Priority : low

In SQ 2.0 Dib had gotten the ships to see world boarders and stop before the boarder.  This function appears to be broken.  I was on Loyavas auto piloting south over the water.  I was not watching the map and my ship kept going but I kept being teleported outside the ship and pushed back into the map.  After 15 seconds of this I was release from my ship.  My ship was outside the world boarder but I was in the world boarder.

**Comment by Siigillum** [comment]
Confirming. Still an issue. Lost a ship this way a few minutes ago on Ava (hit border due to HUGE lag from Ava). This is also my reimbursement ticket thing.

**Comment by awangatboo** [comment]
Dib put some code in to see if the errors can be found.

**Comment by lawrencethefrog** [comment]
Only happens during periods of intense lag. This makes it very hard to fix and forcing it to check when the server is under big strain might not be good for other things.
