### ISSUE TITLE
Glostone trees on Xylos

### ISSUE THREAD

**Issue by awangatboo** [StarQuestMinecraft/StarQuestPublic#570]
If you take a Birch sapling and plant it on Xylos and use bone meal you get a glowstone tree.  I am reporting this but I would love it if you kept this in there as I think the trees were cool.  If you are Ok with keeping it please let me know and I will close the ticket.

**Comment by Siigillum** [comment]
This should be a feature in my opinion! Awesome.

**Comment by Siigillum** [comment]
Project - Xylos alive! Aparently Cehar trees can grow there. Yay!

**Comment by TacoLink** [comment]
*Dib fixes trees on xylos, they now explode*

**Comment by awangatboo** [comment]
I will verify and then close.

**Comment by awangatboo** [comment]
Tree did not explode.  I would love to see this stay and Just close the ticket.

**Comment by Dibujaron** [comment]
Yeah this was an intentional secret feature.
