### ISSUE TITLE
Items not floating in space, Skywatch failing.

### ISSUE THREAD

**Issue by TacoLink** [StarQuestMinecraft/StarQuestPublic#571]
When doing some Pirate-y things, killing people in space, I noticed Nick's space items plugin is missing. 
Along with this, skywatch troopers fall into void when not in a ship, thus rendering ghasts the last line of defence. Not sure if intentional.

**Comment by awangatboo** [comment]
I was talking with Nick on TS the other night and he said that gravity in space needed to be completely reworked before his plugin would work again.

**Comment by awangatboo** [comment]
Nick you want to comment on this?  Is this fixable under our current system?

**Comment by awangatboo** [comment]
Closing all bugs in preparation for SQ 4.0.
