### ISSUE TITLE
Eratoss has every ore

### ISSUE THREAD

**Issue by lucon1** [StarQuestMinecraft/StarQuestPublic#572]
all ores are found on eratoss in vanilla levels, not sure if coal levels are high or not.seem to be only vanilla
![2015-07-09_01 48 20](https://cloud.githubusercontent.com/assets/7586854/8591202/40edfeca-25ec-11e5-9761-b7a275aee0fc.png)  (didn't find gold, but didn't look realy hard either)

**Comment by awangatboo** [comment]
The only thing that should be High is Diamonds and Coal.  As reworking this planet is not going to happen without a complete planet reset I think the Wiki should be changed the say all ores are vanilla.

**Comment by awangatboo** [comment]
Have updated the Wiki.  Please close this Ticket

**Comment by lucon1** [comment]
not closing it. it may be nice, but it is way over-overpowered. i do forsee a planet reset coming

**Comment by icekoob** [comment]
Can confirm

**Comment by Dibujaron** [comment]
Will be fixed by reset at the end of beta.
