### ISSUE TITLE
faction powerboost doesn't add on top

### ISSUE THREAD

**Issue by lucon1** [StarQuestMinecraft/StarQuestPublic#573]
buying 2 powerboosts of equal amount for a faction don't add. still takes away money though.

also i think that it doesn't tax you properly, haven't been charged for a powerboost bought a while ago.

**Comment by icekoob** [comment]
can confirm

**Comment by ekarlate** [comment]
same tried to bough additional 10 got 1k removed. but no powerboost added.

**Comment by Dibujaron** [comment]
Will fix tonight.

**Comment by awangatboo** [comment]
@lucon1 

Does this work correctly now?

**Comment by awangatboo** [comment]
Seeing that dib said he fixed it and @lucon1 has not responded I am closing this ticket
