### ISSUE TITLE
Skywatch beta system STILL BROKEN

### ISSUE THREAD

**Issue by Siigillum** [StarQuestMinecraft/StarQuestPublic#574]
Defeating skywatch in beta does not keep them from respawning after you relog. Ghast fireballs break shielded and pvp/explosion protected blocks. Ship gets EMP'd at some point too. Skywatch appears after about 20-30 s. 

THIS IS AS BROKEN AS IT WAS BEFORE, nothing changed. Also impossible to defeat those ghasts using a ship. Tried, they just blow you out of the sky.

**Comment by Siigillum** [comment]
Spawning results, about 9-12 fighters - 3 shocktroopers. Cant those fighters shoot normal freaking slow travelling firebals ghasts normally do?

**Comment by awangatboo** [comment]
Is this a duplicate of #557 ?

**Comment by Siigillum** [comment]
This is the new test after skywatch fixing. Also defeating skywatch and leaving system stops respawns.

**Comment by Dibujaron** [comment]
Tried another fix, let me know if it works @next restart @Siigillum
