### ISSUE TITLE
Gunship Cert Fail

### ISSUE THREAD

**Issue by HiFlyCS** [StarQuestMinecraft/StarQuestPublic#577]
I have the gunship cert, tag, but I can't fly the gunship. It gives "You do not have permission for this craft!"

**Comment by Dibujaron** [comment]
@Moneybags118

**Comment by awangatboo** [comment]
Is this still an issue?  Many bug like this seamed to be fixed when the ship upgrades happened.

**Comment by awangatboo** [comment]
I just got conformation that the gunship cert works not and that the person with the cert can fly it.

Closing ticket.
