### ISSUE TITLE
Drills can't mine new blocks

### ISSUE THREAD

**Issue by martinjonsson01** [StarQuestMinecraft/StarQuestPublic#578]
The drills from machina can't mine blocks such as Sea lanterns, Prismarine blocks and stained clay. They don't recognize them as a block they can stand on either. (they need a block under them to be able to move forward) Either this can be fixed by updating the plugin(if there is an update) or by just changing it. I use drills with diamond heads. The drills were created on Avaquo, that is filled with these blocks and since they stop whenever they encounter one of these blocks it's extremely annoying.

**Comment by awangatboo** [comment]
This is an issue with that plugin that is not maintained by any of our Dev's.  This is a duplicate of #112 please close and follow #112.

**Comment by martinjonsson01** [comment]
Will do.
