### ISSUE TITLE
Skywatch not working in Alpha

### ISSUE THREAD

**Issue by Tonlage** [StarQuestMinecraft/StarQuestPublic#579]
I was recently attacked by Siig in alpha.  I was not wanted, but Skywatch didn't trigger when Siig shot me with cannons and turrets.

-Aksel_Mads

**Comment by Siigillum** [comment]
You were wanted according to /contract wanted.

**Comment by Tonlage** [comment]
According to my /contract wanted i wasn't.

**Comment by Siigillum** [comment]
According to my lawyer, maybe a mistake. So many people are dropping contracts nowadays...
