### ISSUE TITLE
Faction chat

### ISSUE THREAD

**Issue by flashgnash** [StarQuestMinecraft/StarQuestPublic#581]
If I am in faction chat and the server restarts it glitches me so I cant talk in any chat whilst on that planet. You fixed this before for me, could you do so again please? Thank you.

(flashgnash)

**Comment by awangatboo** [comment]
This is a know issue that happens about 65% of the time.  The best thing to do is find a mod and ask them to reload faction chat.  I am not sure there is a long term solution that can be provided by our Developers.

**Comment by Dibujaron** [comment]
I am well aware that chat is extremely broken. I will attempt to fix it at some point, but don't bet on it anytime soon. I recommend Skype for faction chats for the time being.
