### ISSUE TITLE
Contract not completing 

### ISSUE THREAD

**Issue by LilWoofy** [StarQuestMinecraft/StarQuestPublic#584]
I am trying to complete my 2nd contract in my list. 
I followed it's instructions, I went to Gamma_West and got a Shuttle data core. But it said I didn't have the required materials. I had the Shuttle data core in the dropper, the ship was piloted. And I typed /contract complete 2. Oldskoolish also helped me out with this bug, He told me to come report it here.

Here is a screenshot:

http://i.imgur.com/c39cRVN.png?1

**Comment by awangatboo** [comment]
There have been several reports since 7/13/2015 midnight restart that this is not working.  I think it is everyone.

**Comment by Siigillum** [comment]
Confirming. Privateering contracts do not complete. Tested right now (timestamp). Gamma West station.

Text says no required materials.

**Comment by Steffbeard** [comment]
Same thing for Beta_East

**Comment by Tonlage** [comment]
I have done a bit of testing and to me it seems that this bug is only affecting piracy and privateering.

**Comment by Dibujaron** [comment]
This was fixed, I believe. Can someone confirm?

**Comment by wildcman** [comment]
no they still arent working

**Comment by Siigillum** [comment]
Tested yesterday, it worked. Used NEW datacore though.

**Comment by wildcman** [comment]
hmm someone tested it today and said that it wasnt working

**Comment by Steffbeard** [comment]
I did it today with a data core that wasn't even an hour old. I litterly got it right at the slippage then I went to beta_east and it didn't work

**Comment by Siigillum** [comment]
Tested privateering contracts in Gamma west, used old datacores. Works for that station.

**Comment by wildcman** [comment]
contracts at alpha west using an old data core still isnt working

**Comment by swils24** [comment]
Just now, couldn't complete a piracy contract at Gamma West using a datacore that was acquired after this issue cropped up.

**Comment by LilWoofy** [comment]
Contracts for piracy don't work at Gamma_West or Beta_East. 
Haven't tested others, but those are the one I just tested.

**Comment by Siigillum** [comment]
Maybe privateeringcontracts work and piracy contracts dont now?

**Comment by Siigillum** [comment]
I found out what is broken. Normal non-wanted datacores do not count as datacores. Wanted datacores work JUST FINE. Finished privateering and piracy contracts in Alpha north. Could not finish the contract - piracy with normal datacore so i used wanted one, it worked.

**Comment by Siigillum** [comment]
Another thing found out yesterday. Normal datacores which does not work for piracy contracts WORK for privateering contracts.

**Comment by Dibujaron** [comment]
Fixing tonight. bleh.

**Comment by wildcman** [comment]
so what your saying is wanted data cores work for piracy contracts siig?

**Comment by Siigillum** [comment]
Yes. They work for privateering contracts too.

**Comment by awangatboo** [comment]
Is this still an issue?

**Comment by awangatboo** [comment]
I am marking as fixed and closing.

Thanks @Dibujaron
