### ISSUE TITLE
Glitch kills me.

### ISSUE THREAD

**Issue by forgefan** [StarQuestMinecraft/StarQuestPublic#585]
Well so i was flying to eratoss making  a delivery(5 stacks of coal) but then i suddendly get disconected for no apparent reason. So i log back in but i am spawned 10 blocks from my ship. 
Please fix this glitch.My in game anme is pylonmaster.

**Comment by Phoenix49** [comment]
I was flying my ship to the star in Trinitos Alpha when my ship suddenly disappeared. I am stuck in space with my helmet on yet I'm still sufficating.  Please fix this glitch. Minecraft username is Jetfire49

**Comment by Dibujaron** [comment]
forgefan, unfortunately this is a minecraft bug that we can't really fix. We have several mechanisms in place to attempt to stop your ship as soon as you disconnect and to teleport you back to the ship when you log back in, but sometimes even with those you disconnect in such a way that you cannot be saved. There's nothing we can do about it. 

Phoenix, if you were flying to the star, your ship vaporized. As Jane is so fond of saying, don't fly into the sun, you will surely die. We used to have warnings posted about that but I guess we didn't add them back in 3.0, sorry :(
