### ISSUE TITLE
/kit spacesuite not working

### ISSUE THREAD

**Issue by awangatboo** [StarQuestMinecraft/StarQuestPublic#586]
I have tried this in TA as well as Loy and /kit spacesuite is not valid.  When I run the command /kits I do not see spacesuite or the seeds one that has been talked about.  Only starter, clock, controller.

Good for me that my respiration III still works in space but I think this will be an issue if I loose this helmet

**Comment by Siigillum** [comment]
Just adding this here. Respiration III and pumpkins were supposed not to give the "breathing in space" ability after we get kits.

**Comment by lawrencethefrog** [comment]
It might also be that it's spelt spacesuit and not spacesuite
