### ISSUE TITLE
Contracts Not Completing

### ISSUE THREAD

**Issue by Steffbeard** [StarQuestMinecraft/StarQuestPublic#587]
When i travelled to Beta_East eco station, I had the contract open for both Privateering and Piracy. I wanted to finish the pirate one first, so i put only one data core in my dropper, and landed my ship. When i ran the command /contract complete 0 it said: "You do not have any of the required materials on your ship." So, i tried it with the Privateering one and switched the data cores, and i got the same message. I tried leaving the eco station, switching around the data cores, that didnt work. Then i tried removing both contracts and accepting new ones... THAT didnt work. So now im stuck on Beta_East penniless and irritated. Please fix this!

**Comment by awangatboo** [comment]
This is a duplicate issue of #584.  Please close this issue and follow #584.
