### ISSUE TITLE
Rakuria Tree Farming 

### ISSUE THREAD

**Issue by gregolegomonkey** [StarQuestMinecraft/StarQuestPublic#588]
THIS DOES NOT INVOLVE THE [TREEFARM] PLUGIN.

When planting birch saplings on Rakuria, 4/4 which grew into "wool trees" were yellow, instead of being all colors for that wood (orange, dark green, etc.).

**Comment by awangatboo** [comment]
This is a known bug.  At least that is what Beaver has told me.  Even thought it is known thanks for documenting it.  I think it is with all the trees.  They only grow like they did on Kel back in the SQ 2 days.

**Comment by Dibujaron** [comment]
This is intentional; I haven't bothered to make the other kinds regrowable yet. I may get to it sometime soon.
