### ISSUE TITLE
Cryopod glitch

### ISSUE THREAD

**Issue by Starsword7** [StarQuestMinecraft/StarQuestPublic#590]
My brother (bluelightning900) died with a fully functioning cryopod, but was still teleported back to spawn.

**Comment by awangatboo** [comment]
Cryopods have been having issues since 3.0.  Is the cryopod set in active mode?  If so i would recommend turning that off.  I have heard lots of people say there are issues with that.  Also if the cryopod is on a ship I have been told by Siig that there are issues with that.

**Comment by Siigillum** [comment]
If cryopod is on a ship and gets damaged by some random pirates this causes huge issues and requires one to do /removehome usually (you end up spawnign in space where the cryopod was before it got damaged).

**Comment by Starsword7** [comment]
This cryopod was built on a planet and never moved, and was in passive mode.

**Comment by icekoob** [comment]
Can confirm this

**Comment by awangatboo** [comment]
Closing this bug in order to obtain better details in current Cryopod issues.  If you have another Cryopod iss please see this forum thread before opening a new issue.

http://www.starquestminecraft.com/starquestforums/m/17078810/viewthread/23552021-great-cryopod-bug-closing/post/last#last
