### ISSUE TITLE
Lockette Protected door Max Name size issue

### ISSUE THREAD

**Issue by Starsword7** [StarQuestMinecraft/StarQuestPublic#591]
when i create a protected sign with my name on it, I cant open the door, edit the sign or break it. when trying to break the sign it says: you cannot break a container claimed by (username)

**Comment by awangatboo** [comment]
This is a strange one.  Is the name on the [private] sign just like yours?  Any caps difference?  Did you fill in the name or did you let Locket add the name on the door?  Which planet?  If on a ship does it do this in space?

**Comment by Starsword7** [comment]
i let lockette add the name, and the cryopod was on Uru.

**Comment by Starsword7** [comment]
I figured out the issue: my brother posted the original topic logged in as my github, and his IGN is bluelightning900, since lockette can't fit the entire name on the sign, so it writes "bluelightning90".
Still an issue that needs to be fixed

**Comment by awangatboo** [comment]
The Max name issue has been reported as a Bug to the people who make lockette.  I assume that SQ will use the updated / fixed version when the people that make Lockette update for a fix.

**Comment by awangatboo** [comment]
I have been told we are on the newest version of Lockett.  We need for this to be updated by the creators to get a fix.

**Comment by Evancooldude** [comment]
Perhaps if we changed over to using UUID? That fits on one line... How lockette would handle that, I don't know. I might look into fixing this once I become a little more learned in the ways of lockette and UUID names.

**Comment by awangatboo** [comment]
Closing all bugs in preparation for SQ 4.0.
