### ISSUE TITLE
Vanilla Ore Generation on eratoss

### ISSUE THREAD

**Issue by icekoob** [StarQuestMinecraft/StarQuestPublic#592]
After doing some coal mining on Eratoss, I had gotten non native eratoss ores. There's a possibility that there's dungeons on Eratoss too. 
![2015-07-13_17 16 37](https://cloud.githubusercontent.com/assets/12261784/8662281/b9059a7c-2983-11e5-8c64-b3b7267d7aa9.png)
![2015-07-13_17 16 18](https://cloud.githubusercontent.com/assets/12261784/8662283/bdfb5260-2983-11e5-944d-3d286666d57d.png)
![2015-07-13_17 14 22](https://cloud.githubusercontent.com/assets/12261784/8662287/c2fd727a-2983-11e5-9ecd-481f5bec0f0f.png)
![2015-07-13_17 11 10](https://cloud.githubusercontent.com/assets/12261784/8662294/cb32ab40-2983-11e5-8e81-f9815c24c2ab.png)

**Comment by awangatboo** [comment]
This is a duplicate bug of #572.  Please close this ticket and add any needed information to Ticket #572

**Comment by icekoob** [comment]
how do I close this XD

**Comment by awangatboo** [comment]
you should see a comment and close button at the bottom of the page.
