### ISSUE TITLE
Turrets Do Not Activate Skywatch.

### ISSUE THREAD

**Issue by JavaInvader** [StarQuestMinecraft/StarQuestPublic#593]
As the title says turrets do not activate skywatch.

**Comment by TotallyNotSatan** [comment]
Can confirm.

**Comment by AlinaFicalton** [comment]
i can confirm also

**Comment by Dibujaron** [comment]
All turrets? Which types specifically?

**Comment by JavaInvader** [comment]
I believe all types

**Comment by icekoob** [comment]
I can confirm too

**Comment by Siigillum** [comment]
[turret] turrets do not activate Skywatch. Havent test other.

**Comment by Kyle98martin** [comment]
Normal turrets still do not activate skywatch but APturrets do.

**Comment by Dibujaron** [comment]
Fixed.
