### ISSUE TITLE
detection.

### ISSUE THREAD

**Issue by forgefan** [StarQuestMinecraft/StarQuestPublic#594]
Well so i build a ship and pilot it it works fine and everything but after the 3rd piloting it suddendly says i have to detect it even if i did not change anything. And when i detect that ship it says it is to large and after i remove half of the ship it still says it. This has pretty much ruined my whole fleet. pls fix this.My in game name is pylonmaster.

**Comment by awangatboo** [comment]
you might want to make sure you are not building it on a block that sticks to ships.  

I would make sure you build on coblestone, stone bricks, or dirt.  If your ship is on grun or Uru you might be attaching to the harden clay.

Also from time to time it does seam like you have to redetect even if nothing has changed.  I am not sure why what is.

**Comment by forgefan** [comment]
no some of the ships that this has happened too are floating.

**Comment by Dibujaron** [comment]
Can I get a secondary confirmation for this? If anyone else has had this issue let me know. I'm concerned about this, but I think it may be something that you're doing, as our ship detection system has not changed in the past 6 months.

**Comment by forgefan** [comment]
No i have checked all thing that could go wrong first time i pilot the ship it is ok but the second or third time i detect it says the ship is too big even if i remove half the ship.

**Comment by Tonlage** [comment]
I've also had the problem where i randomly need to redetect an already detected ship.

**Comment by JavaInvader** [comment]
Check diagonal blocks

**Comment by awangatboo** [comment]
I do not have any issue with this.  

@forgefan 

What planet are you having issue on?  What cords.  I would like to fly over to that planet and see if I can re-create the issue for myself.

**Comment by forgefan** [comment]
I have checked and all the ships are not atatched to anything some are even 10 blocks of the ground and regarding the cordinates i would like to not share them since it may endager my ships but it has happened on cetallion and rakuria.

**Comment by forgefan** [comment]
by the way i destoryed one of the mentioned ships to have 50 blocks(i counted) but it still said it had more than 200 blocks.

**Comment by forgefan** [comment]
issue fixed.

**Comment by forgefan** [comment]
Thanks to thebeaver.
