### ISSUE TITLE
Skywatched for killing yourself.

### ISSUE THREAD

**Issue by Kyle98martin** [StarQuestMinecraft/StarQuestPublic#596]
Reporting this bug for Yargon_Kerman who I was in TS with at the time of this incident. He shot himself off a tower with an arrow and died which triggered skywatch. After he flew back to collect his stuff skywatch killed him for killing himself.

**Comment by Siigillum** [comment]
Solid logic there.

**Comment by Dibujaron** [comment]
Fixed at next restart. Sorry about that.
