### ISSUE TITLE
/stats [shipname] command 

### ISSUE THREAD

**Issue by gregolegomonkey** [StarQuestMinecraft/StarQuestPublic#597]
"I'm sorry, but you do not have permission to perform this command. etc..." comes up when trying to use command.

**Comment by awangatboo** [comment]
I can confirm this issue.

**Comment by icekoob** [comment]
I can too

**Comment by awangatboo** [comment]
this might be that the data has not been put in on the /stats as this is Beta SQ 3.0 and they have changed the stats and do not want to put them in until they are final.
