### ISSUE TITLE
/kit spacesuit is broken.

### ISSUE THREAD

**Issue by AlinaFicalton** [StarQuestMinecraft/StarQuestPublic#598]
/kit spacesuit is broken. when you use the kit it reads that the kit is not set up correct. so one i used my /kit spacesuit and i cant get it agen, 2 the kit is broken. Other people are saying they have not used the kit yet and when they go to they have a week long cooldown already

**Comment by awangatboo** [comment]
/kit spacesuit now works please close this Ticket.  Also feel free to put anything about the spacesuite not working in Ticket #602 that you opened.
