### ISSUE TITLE
Cryopod Issues

### ISSUE THREAD

**Issue by winecraft-dev** [StarQuestMinecraft/StarQuestPublic#599]
Every time I have died, I have ended up spawning in TA. I have set up a cryopod on Eratoss, but it isn't working. Please help me
-Jurgmania

**Comment by awangatboo** [comment]
There are lots of people saying there are cryopod issues.  I would not really know as I have only died once in SQ 3.0 and that due to a bug.

My recommendation is rebuild the cryopod ( my guess is again ) and when this happens next please report the day you build the cryopod and the date / time it failed.  I hope this will make it easier for someone to track it down in the logs.

**Comment by awangatboo** [comment]
OK I have now died twice in SQ 3.0 and my cryopod worked.  Is your cryopod on a ship?

**Comment by Dibujaron** [comment]
Cryopods, and bedspawns before them, have been broken since time immemorial. Nobody can quite figure out why. It's extremely frustrating. It works for me every time I try it, and I can't figure out what makes it break for other people occasionally.

**Comment by Dibujaron** [comment]
Is it working for you at the moment? You have a cryopod in the database, and in past cases when cryos weren't working it was null in the database. http://prntscr.com/7t8edk

**Comment by Dibujaron** [comment]
#590

**Comment by winecraft-dev** [comment]
It is working for me now. However, I believe it has something to do with Skywatch, because I died the first time to skywatch and was TPed to TA, as normal, but after dying a second time, to random reasons, my cryopod didn't work.

**Comment by awangatboo** [comment]
Closing this bug in order to obtain better details in current Cryopod issues.  If you have another Cryopod iss please see this forum thread before opening a new issue.

http://www.starquestminecraft.com/starquestforums/m/17078810/viewthread/23552021-great-cryopod-bug-closing/post/last#last
