### ISSUE TITLE
Planters Not Working

### ISSUE THREAD

**Issue by PatchyFox** [StarQuestMinecraft/StarQuestPublic#600]
Hi there,

I'm sure you're aware of the issue already, but just in case nobody's reported it formally... I have the cert for planterdrill (twice, in fact) and can use Machina Drills just fine. Unfortunately though, when I tried to set up a planter, I received an "insufficient permissions" error. 

I'd love to be able to start farming soon - any idea when this will be fixed?

Thanks, 
-PatchworkFox

**Comment by awangatboo** [comment]
This is a duplicate of #561.  Please close this ticket and follow what the issue is on Ticket #561.
