### ISSUE TITLE
Missing priority

### ISSUE THREAD

**Issue by buba141** [StarQuestMinecraft/StarQuestPublic#601]
I purchased 6 months of priority during the 4th of July sale, but it was never credited to my account. /subscription still shows 0 days remaining, and I still get the "Starquest is too full right now" message if I try to join when 20 standard players are on. Proof of purchase:
http://i1372.photobucket.com/albums/ag335/buba141/buycraft_7-7-15_zpsjggps3h0.png

**Comment by Dibujaron** [comment]
Hi there,

You show as having 4392 hours of priority on my console, which is in accordance with your purchase history. Are you sure you were logging in with the correct account?

**Comment by buba141** [comment]
/subscription shows the right amount now, just checked
