### ISSUE TITLE
Space helmets still dont work.

### ISSUE THREAD

**Issue by AlinaFicalton** [StarQuestMinecraft/StarQuestPublic#602]
So the kit spacesuit works now but the helmet it self does not. I have the helmet and im trying to fly in space and i am still sufficating in space.

**Comment by awangatboo** [comment]
I had stranger issues with this in TA.  Here is my test 7/15/2015 at about 10:30 am server time.

Au-qua infinity III - It says I am suffocating but take no damage.

Next 

Full space suite - It works!  no damage. I then take off one piece still not damage. Then I take it all off and still no damage.  I then go put it in a dropper just in case the check is that you have it on you. 

Next

Go into space with no armor of any type on my toon and fly around and take no damage.

**Comment by Dibujaron** [comment]
Installed a fix for your problems, awangatboo. Let me know if it's fixed.

**Comment by AlinaFicalton** [comment]
you have to ware the FULL set of armor in order to be able to breath in space

**Comment by awangatboo** [comment]
Test done in TA at ~ 9:30 am server time.

Test 1
- Go into space with respiration 3.  I get the error that you are suffocating but take no damage.
- Then take off suit - No damage.
- Put on space suite - No damage.

( Between tests.  I go back to Loy and then back out to TA )

Test 2 
- go into space with nothing on.  Take damage
- put spacesuite on.  I stop taking damage
- put on respiration 3.  No damage
- take off armor.  No damage

To me it is like there is a check and when it finds the respiration 3 helmet it stops checking.
