### ISSUE TITLE
Removing Contracts

### ISSUE THREAD

**Issue by JavaInvader** [StarQuestMinecraft/StarQuestPublic#604]
When you remove a contract (longer then an hour) and you do not have the funds in your bank, It will remove it anyways.

**Comment by awangatboo** [comment]
Why is this a bug?  Do you not want people to remove contracts if they do not have any money?  If someone does not have any money then I would think it would not matter.

**Comment by Dibujaron** [comment]
The problem is people can offload cash to their faction bank and then grab it back as soon as they delete the contract.

**Comment by awangatboo** [comment]
Great point.  I guess I just do not think this way.

**Comment by Dibujaron** [comment]
Fixed.
