### ISSUE TITLE
certs available not updating.

### ISSUE THREAD

**Issue by AlinaFicalton** [StarQuestMinecraft/StarQuestPublic#607]
so i have unlocked a few certs (like LF and autofarms/miners) but the certs page wont update... It does not remove the certs i have already unlocked OR the next tear of ship i sould be able to access (ie the next tear of freighter).

**Comment by awangatboo** [comment]
I can confirm this is an issue.

**Comment by mcdouble** [comment]
I think the machina planter perms are derped as well. Drill perms work though.

**Comment by Siigillum** [comment]
Yacht perms are broken. Miner perms are broken. No such ships as lightyacht and lightminer in database, cant create a shipsign.

**Comment by awangatboo** [comment]
Cert page now updates so you do not see what you have already purchased.
