### ISSUE TITLE
CRAZY skywatch

### ISSUE THREAD

**Issue by winecraft-dev** [StarQuestMinecraft/StarQuestPublic#608]
Earlier today, I accidentally hit someone, and set Skywatch on myself. Later on, I leave the planet, then decide to enter the planet again. I instantly recieve a Skywatch Warning and am forced to fight off skywatch again. Please fix this
-Jurgmania

**Comment by Siigillum** [comment]
What planet. Did you fight off skywatch? Or did you just leave planet when attacked?

**Comment by winecraft-dev** [comment]
I was on Eratoss. I did fight off skywatch and defeated all of the troops. However, when I left the planet to travel somewhere, I reentered the atmosphere of Eratoss to escape pirates and recieved a message about Skywatch immediately after entering the atmosphere.

**Comment by Dibujaron** [comment]
The solution for this was discovered in another issue, will fix today.
