### ISSUE TITLE
Killed by Skywatch AFTER Defeating Skywatch + Glitched Cryo

### ISSUE THREAD

**Issue by Spateeter** [StarQuestMinecraft/StarQuestPublic#610]
After I beat skywatch I went into my faction base and logged off. I recently just logged on and I came on to see that skywatch was still active. I died in my faction base and was hoping to retrieve my stuff, but my cryopod glitched me into the middle of space in trintos_alpha so I currently have nothing. Was hoping someone can look into this and help me out because this has happened quite a lot.

**Comment by awangatboo** [comment]
The Dev's are looking into the Cryopod issues as well as the skywatch issues.  If you need a refund ask a mod.

**Comment by Dibujaron** [comment]
Skywatch issues fixed. Cryo issues still being worked on, sigh.
