### ISSUE TITLE
Broken ship sign at alpha west

### ISSUE THREAD

**Issue by vtarcher** [StarQuestMinecraft/StarQuestPublic#612]
So we logged onto find that we cant fly our ship because we get this error
http://gyazo.com/551f3b7534ff01e6a43da3ef51d013b2
It's numskull34's ship but he also had me on the pilot sign. Our ship is at Alpha west on platform 6 and this is our ship
http://gyazo.com/f277b4cac86735311d7ef2d7c881e3c3

**Comment by awangatboo** [comment]
I am not sure if the devs will have the same issue I am having but I can not read any of the signs.  The image is to dark.  

What is the error you are getting?

**Comment by vtarcher** [comment]
Fighter
<Invalid name>
<ask a mod for help>

**Comment by vtarcher** [comment]
Fighter
< Invalid name >
< ask a mod for help >

**Comment by vtarcher** [comment]
its been fixed thanks!
