### ISSUE TITLE
Name Changes do not affect access to WG's, or piloting ships

### ISSUE THREAD

**Issue by TacoLink** [StarQuestMinecraft/StarQuestPublic#613]
I changed my name around 6:00pm EST (7/17/2015), and logged on where I was supposed to be
Then, I tried piloting my ship, which did *not* work, after that, tried breaking the sign, but strangely, it said I could not break my sign within 5 minutes of piloting. My ship shield then activated, and I am unable to break my own ship sign, on Sampetra @Coords(789, 226). If the WG could be removed or if I could pilot my ship somehow, I will be very greatful. Strange to not this phenomonon.

~TheNotsure, formally know as TacoLink, and before that Notsure45

**Comment by awangatboo** [comment]
Notsure , Sorry to say this but this is not a bug.  Dib stated a long time ago on the front page if you change your name lots of things will not work and you do this at your own risk.

There is a chance that the W/G might update after a server reset.  

If you find a really nice mod they might break the sign but I do not think they will.

**Comment by TacoLink** [comment]
He said he would fix that up with ship shield's; as there is a reason he used UUIDS

**Comment by TacoLink** [comment]
Issued solved, but I'm leaving this so dib can see it.
