### ISSUE TITLE
Skywatch keeps coming if not killed by a player.

### ISSUE THREAD

**Issue by LilWoofy** [StarQuestMinecraft/StarQuestPublic#614]
When a ghast or trooper suffocate somehow, It doesn't count as it died.
Therefor after you kill all of them, You don't get the message that you're safe. So they come again when you re-log.
I think same goes with fire, if you let them die with a fire aspect sword. It won't count as a kill either (I think)

**Comment by TacoLink** [comment]
Do they despawn, and if you log back in, do they come back at full force?

**Comment by Dibujaron** [comment]
Ah, that's why. Will fix, thanks.
