### ISSUE TITLE
cryopods

### ISSUE THREAD

**Issue by forgefan** [StarQuestMinecraft/StarQuestPublic#615]
well so i was derping around in space trying to find ships to tow away to my base and destory them for polymer and i accidentaly fell in space and died but I didnt respawn in the cryopod and my mom got scared
She said 'You're movin' with your auntie and uncle in Bel Air'. I begged and pleaded with her day after day.But she packed my suit case and sent me on my way
She gave me a kiss and then she gave me my ticket.
I put my Walkman on and said, 'I might as well kick it'.

**Comment by awangatboo** [comment]
There are random bugs with cryopods and the amount of bugs go up if you are using one on a ship.  If you have details of what time and system this happened in then a Dev could look at that systems log but without this info I am not sure anything can be done.

**Comment by mcdouble** [comment]
Points for how he reported it xD

**Comment by awangatboo** [comment]
Closing this bug in order to obtain better details in current Cryopod issues.  If you have another Cryopod iss please see this forum thread before opening a new issue.

http://www.starquestminecraft.com/starquestforums/m/17078810/viewthread/23552021-great-cryopod-bug-closing/post/last#last
