### ISSUE TITLE
Cannot filter tradepost browser by planet

### ISSUE THREAD

**Issue by buba141** [StarQuestMinecraft/StarQuestPublic#619]
The command /tradepost browse planet=Eratoss  displays "An internal error occurred while attempting to perform this command". I tested this while on Grun, but /tradepost browse planet=Grun had the same issue.

**Comment by awangatboo** [comment]
I have never seen "planet=" as part of /tradepost.  Is there a document somewhere that says it should do this?  If not this is a new feature for Nick to consider.

**Comment by TotallyNotSatan** [comment]
Can replicate issue on Grun. planet= is a part of tradepost, or at least should be.

**Comment by Scooter5131** [comment]
This was originally listed in the Tradepost instructions, and looks like it is still an issue on Eratoss as of 8/7/2015 when I tried to use it.

<url>http://starquestminecraft.com/starquesthome/m/17590832/article/3328799/keyword/tradepost</url>

Scooter5131

**Comment by awangatboo** [comment]
I have been told By Nick that he will re-building this system.

**Comment by awangatboo** [comment]
Closing bug as trade posts will be replaced soon.
