### ISSUE TITLE
Freighter and Heavy freighter

### ISSUE THREAD

**Issue by forgefan** [StarQuestMinecraft/StarQuestPublic#620]
Well so i have the light freighter certification but i cannot buy the freighter cert.

**Comment by awangatboo** [comment]
I think seeing that SQ 3.0 is in Beta they have not rolled out the next line of ships.  I am not sure on this but it seams to be the case for all the ship classes.

**Comment by Gaming4me** [comment]
well I got cruiser cert to unlock, so I'm not that sure. have you browsed through all your certs?

**Comment by awangatboo** [comment]
Is this still an issue?

**Comment by Thedrew655** [comment]
Certs have been modified greatly since the date of this post, if anymore issue arise please create another support ticket.
