### ISSUE TITLE
Contract Stack size wrong for snowballs

### ISSUE THREAD

**Issue by Tonlage** [StarQuestMinecraft/StarQuestPublic#622]
Then looking the number of snowballs that is required to complete a contract the number of stacks shows as if snowballs can be stacked up to 64 and not 16.

**Comment by awangatboo** [comment]
There are many contracts that think items can be stacked with stack size 64.  This does not change functionality of the game and should be a low priority.

BTW - Same for mushroom stew.

**Comment by awangatboo** [comment]
Would be nice to have fixed but does not stop gameplay

**Comment by Evancooldude** [comment]
This bug has been fixed. Since I evidently don't have the ability to close this, I'll ask that Awang or Dib do so.

**Comment by awangatboo** [comment]
Has anyone got a snowball contract on the server and confirmed this?
