### ISSUE TITLE
Skywatch testing - 21.07.15

### ISSUE THREAD

**Issue by Siigillum** [StarQuestMinecraft/StarQuestPublic#624]
Tested Skywatch in beta. Normall turrets did not trigger skywatch in Beta twice. Normal turrets trigered skywatch in Beta once (when i hit myself witha turret while hitting a guy). Skywatch was then dispatched by Kyra while i was busy avoiding their projectiles. After leaving thesystem and comming back skywatch properly did not reapear (so constant skywatch respawning seems fixed).

Skywatch spawns consisted of 3 ghast waves and one skele wave of around 2-4 skeles.

I sugest removing skellies from space maybe, they are the issue which basically prevents any combat there.

**Comment by Siigillum** [comment]
Ghasts are already supperstrong concerning their accuracy.

**Comment by Siigillum** [comment]
Tested again, Beta, skywatch properly triggered after direct 3 turret hits. Spawned normally. Got rid of skelles by falling them into space. After reloging (30 min break) the skywatch does not respawn.

**Comment by awangatboo** [comment]
Dib has re-balance skywatch in Beta.  I think you should close this ticket and test again and open another one if there are still more issues.

**Comment by awangatboo** [comment]
Closing ticket.  Siig it would be nice to see you back in game testing SvS like you used to.
