### ISSUE TITLE
Can autopilot through iron bars

### ISSUE THREAD

**Issue by Metr0n0me** [StarQuestMinecraft/StarQuestPublic#626]
I can autopilot through iron bars--I discovered this issue when I autopiloted straight into another faction's base through the portcullis.

**Comment by awangatboo** [comment]
This is a know issue / feature.  When you fly in space you make jumps with your ship.  I had heard Dib looked into "Fixing" this but it would make loads more LAG if this was done.  Expect ships to go really slow if he "fixes" this.

**Comment by brickworm2012** [comment]
Well, it has been nerfed slightly with fighters being 50 blocks, but yes, this has been an problem.

**Comment by awangatboo** [comment]
This is a current game play function and all though it might not be what is desired that is the way it is.  Please put this in the suggestions under the forums but realize if this does happen we are looking at way more LAG.
