### ISSUE TITLE
Everything is broken.

### ISSUE THREAD

**Issue by forgefan** [StarQuestMinecraft/StarQuestPublic#628]
Flying,chat,local and travel thorugh and into palnets all of these features are broken.

**Comment by awangatboo** [comment]
Chat does seam to be down but I could pilot a ship.  I did not have much time so I could not go from planet to space.

**Comment by forgefan** [comment]
still i cannot leave the tallimar atmosphere

**Comment by awangatboo** [comment]
That probably means Gama is down or the server that is Tallimar is having issues.

**Comment by forgefan** [comment]
kk but still i would appreciate if gamma could come up again.

**Comment by awangatboo** [comment]
They were working for me latter this day.  Please check and if it works please close this ticket
