### ISSUE TITLE
Alpha System Down Again

### ISSUE THREAD

**Issue by StarquestBaron** [StarQuestMinecraft/StarQuestPublic#631]
So sorry, Dib.  I don't know about the other systems but we aren't able to leave planet in Alpha.

**Comment by brickworm2012** [comment]
Yep. This message pops up:
And we tend to fall quite a distance, without being harmed. But with loss of inventory.
![2015-07-25_06 40 42](https://cloud.githubusercontent.com/assets/9120968/8889454/56cd73f2-3298-11e5-947f-9cd132f038b3.png)

**Comment by brickworm2012** [comment]
Wait, turns out I didn't get fall damage because I can now fly. Not sure how to fix that.

**Comment by LookMomImWalrus** [comment]
I lost everything i had because of this..... how do i get back...

**Comment by awangatboo** [comment]
Contact a Mod for a refund.  Closing this ticket as Alpha was up since then.
