### ISSUE TITLE
Turret Glowstone to Sponges glitch

### ISSUE THREAD

**Issue by DarthOcto** [StarQuestMinecraft/StarQuestPublic#633]
I found a glitch were you can build a turret with a glowstone block instead of a sponge and then enter the turret and when you exit the turret the glowstone block turns into a sponge

**Comment by Kyle98martin** [comment]
Known issue but there doesn't seem to be a fix for it. It's the same as using landing gear to turn redstone into sponge

**Comment by brickworm2012** [comment]
Had enough to make a spongeclad in 2.0 because of it. Good times.

**Comment by awangatboo** [comment]
players can receive bans for abuse of bugs.  Just an FYI

**Comment by awangatboo** [comment]
Closing all bugs in preparation for SQ 4.0.
