### ISSUE TITLE
I'm not even sure what happened

### ISSUE THREAD

**Issue by shadyninja21** [StarQuestMinecraft/StarQuestPublic#634]
Yesterday I logged back on to work with Mitch and I was in Trinitos Beta at the north station. I flew from there to Xylos, and at some point along the way I lost 3 pieces of armor in my inventory (not sure why only 3), and the stuff in one of my droppers. The stuff I don't care about really, it was just some blaze rods and wood, but the armor was Protection IV. I have screenshots of all my stuff incase its decided I get a refund. 

Secondly, today, I was fighting blazes on Xylos when I hit a lag spike BAD. When it passed over I was dead and respawned on avaquo. I have screenshots of the items I lost in that one too.

I am sorry I can't really explain what happened because I'm not even sure.

**Comment by shadyninja21** [comment]
I believe the inv wipe might've happened with one of the 2 server jumps.

**Comment by awangatboo** [comment]
I think the Dev's will not be able to help with this as it can not be reproduced.  If you need a refund please contact a Mod.

**Comment by awangatboo** [comment]
Closing as there is no way to reproduce this bug.
