### ISSUE TITLE
certs not working right after the update.

### ISSUE THREAD

**Issue by AlinaFicalton** [StarQuestMinecraft/StarQuestPublic#635]
So the update/fix came out for certifications tonight and some things... don't work. i went into my /certs available and i only had upgrades for basic ships, not my unlocked ones. Also when i do /certs tag it does not have the resource eng, but i have it in /certs list.  Also i can only upgrade my ships 4 times.... not 5.

**Comment by Siigillum** [comment]
Speed II upgrade for fighter does not work.

**Comment by awangatboo** [comment]
Was this on 7/26?  On 7/27 they seam to work.  Please recheck.

**Comment by AlinaFicalton** [comment]
its was happening during both.

**Comment by awangatboo** [comment]
I think this has been resolved.  Closing ticket but will re-open if this is still an issue.
