### ISSUE TITLE
Weird Contract Thing

### ISSUE THREAD

**Issue by Tongonto** [StarQuestMinecraft/StarQuestPublic#636]
I was doing some contracts, and noticed something strange : 
After taking contracts repeatedly until I had 5, I decided to delete one - when I do /contract available, the list of contracts was the exact same one as I had seen before. I took a contract, and then deleted another one; I was taken right back to the same "page" of contracts.
It's sort of like this : 
I have five contracts. Contracts A, B, and C now appear when I do /contract available.
I delete one contract. Now contracts D, E, and F (which I have already seen before), now appear - I take contract F, and now see contracts A, B, and C again. I delete a contract again; now i'm back at contracts D, E, and F.
I then went to an eco station, and completed three contracts; my available contracts seemed to stay the same, except get larger; Contract F, for 36 purple wool, became 39 purple wool, then 42, and then 44 with the reward increasing each time.

**Comment by awangatboo** [comment]
I am not sure but I do not think this is a bug.  This is just how it works.

**Comment by shadyninja21** [comment]
That's like that incase you accept the wrong number. You can delete it and go back to the old page to get the one you meant to get. 
You can close this

**Comment by Gaming4me** [comment]
Its what shadyninja said, its for when you accept a contract that you didnt want to, so you remove it and accept the one you should have accepted in the first place. I believe its intentional.

**Comment by Siigillum** [comment]
It's how it works. To get new contracts you have to actually complete some.

**Comment by Tongonto** [comment]
Ah, okay. I just thought it was a bug because of the contract duplication that could be done there.
