### ISSUE TITLE
Voting takes too much VTs

### ISSUE THREAD

**Issue by Creepopolous** [StarQuestMinecraft/StarQuestPublic#637]
I got 6 sponges from /redeemvote then I tried to get steak. It told me I didn't have enough credits, despite the fact I had 35 VTs before getting the sponges. When I checked my balance, I found that I only had 5 VTs.

**Comment by awangatboo** [comment]
@Nickmiste

**Comment by Evancooldude** [comment]
Has this issue been solved?

**Comment by awangatboo** [comment]
Ask Nick

**Comment by awangatboo** [comment]
Closing all bugs in preparation for SQ 4.0.
