### ISSUE TITLE
Flying ship, Random Death

### ISSUE THREAD

**Issue by danielbkantor** [StarQuestMinecraft/StarQuestPublic#639]
I was flying my ship on Uru and then I randomly die. It said my ship was released when I never clicked the sign and then I fell to my death. Also my cryopod failed and I was spawned at spawn and not at my cryo at eratoss

**Comment by awangatboo** [comment]
Do you know where you were on the map?  If the world boarder is not working and you were not watching your ship while on autopilot your ship can keep going outside the world boarder and you keep getting TP back in the boarder and after a small amount of time movecraft will release you from your ship and if you are at Y=205 you fall to your death.  Could this have been the issue you had?

**Comment by awangatboo** [comment]
As you have not responded to this ticket in 11 days I am closing this ticket.
