### ISSUE TITLE
Hoppers broken

### ISSUE THREAD

**Issue by cloudtail** [StarQuestMinecraft/StarQuestPublic#640]
Hoppers randomly stop sending/accepting items. Really annoying when you have a few hundred of them in one place.

**Comment by awangatboo** [comment]
This is an issue that I saw on SQ 2.0.  My hunch is it is something in the spigot server causing the issue and it might be there trying to reduce lag.

**Comment by Gaming4me** [comment]
yeah I had a dispenser/hopper pipeline and the hoppers would ALWAYS jam every couple days at least. I'd have to redo the whole hopper part of the pipeline or it'd just stop on the hopper before the one that jammed.

**Comment by awangatboo** [comment]
Closing all bugs in preparation for SQ 4.0.
