### ISSUE TITLE
Fix the Restart System!

### ISSUE THREAD

**Issue by JavaInvader** [StarQuestMinecraft/StarQuestPublic#641]
alpha was the only system to restart  and did not come back up. Midnight Restart

**Comment by awangatboo** [comment]
Was this just this one time or has the restart constantly failed to bring up so many systems?

**Comment by JavaInvader** [comment]
its been happening in the past 2 weeks alot

**Comment by awangatboo** [comment]
the last couple of days it has started well.  Closing ticket.  If I need to re-open it let me know.
