### ISSUE TITLE
Skywatch in Beta persists even if you survive the trip to a planet.

### ISSUE THREAD

**Issue by HiFlyCS** [StarQuestMinecraft/StarQuestPublic#642]
I whacked someone and Skywatch attacked. I survived the trip to Otavo, but when I went back into space, Skywatch gave me a warning again and tried to attack. I thought if you lived to see a planet, they would stop.

**Comment by Kyle98martin** [comment]
Changing planets does not cause skywatch to stop attacking you. They won't follow you into the new system but they will still go after you in the system you are wanted in

**Comment by HiFlyCS** [comment]
So how do you shake them off completely?

**Comment by Siigillum** [comment]
Kill them. Or maybe wait after restart. Or die to skywatch.

**Comment by awangatboo** [comment]
@HiFlyCS I do not think this is a Bug but more a game play issue.  Please close this ticket.

**Comment by awangatboo** [comment]
@Dibujaron changed Skywatch in Beta today so I do not think this is a bug any more.  Closing the ticket.  If you still think this is an issue on 8/6/2014 please open a new ticket or get me to re-open this ticket.
