### ISSUE TITLE
Glitched out of ship. Ship eaten by atmosphere.

### ISSUE THREAD

**Issue by HiFlyCS** [StarQuestMinecraft/StarQuestPublic#646]
On Eratoss: http://imgur.com/GpjY19p

Unrelated note: Oreninja couldn't help me because he's not a full-full mod... :(

**Comment by Siigillum** [comment]
Ore should get skype.....

**Comment by HiFlyCS** [comment]
I know right!

**Comment by awangatboo** [comment]
This looks like the issue you get when you fly outside the world border.  If so I think there is another issue open on this.

**Comment by awangatboo** [comment]
I assume that this was taken care of.  I saw you flying around today.  Closing ticket.
