### ISSUE TITLE
Redeemvote error

### ISSUE THREAD

**Issue by CleverDan** [StarQuestMinecraft/StarQuestPublic#648]
My ign is LagothZanta.

I made a redeemvote purchase of a diamond tool and enchant kit, but got the message "One parachest can't fit all of that!" I didn't get any parachests, and my VT count was reduced.
![2015-08-02_22 44 46](https://cloud.githubusercontent.com/assets/8528456/9031624/2ab740bc-396a-11e5-9226-3c6255aca6b6.png)

**Comment by awangatboo** [comment]
@Nickmiste

**Comment by awangatboo** [comment]
Closing all bugs in preparation for SQ 4.0.
