### ISSUE TITLE
MachinaPlanter Not Working

### ISSUE THREAD

**Issue by Scooter5131** [StarQuestMinecraft/StarQuestPublic#650]
I just built my Planter and I can't get it to start.

![2015-08-03_19 22 37](https://cloud.githubusercontent.com/assets/13090706/9050611/233efbee-3a15-11e5-8070-bdd6e6319ebb.png)

I did repurchase the Cert when it was reset, and can use Drills, but nothing happens with I flip the switch for the Planter.

Scooter5131

**Comment by awangatboo** [comment]
What time did this happen?  Based on when the Ticker was created the server was having issue during that time.  Does it still not work?

**Comment by Scooter5131** [comment]
I've been trying for a couple of days now, and just tried it again and was not able to get it to work.

Scooter5131

**Comment by awangatboo** [comment]
Wait.  Does it give you any error?  Also I thought the switch had to be over the furnace.

**Comment by Scooter5131** [comment]
I'm not getting any errors, it just doesn't do anything (tried again earlier this morning).

As far as I know, the only critical configuration is that the furnace has to align with the top rail, and the chest aligns with the bottom. I did move the switch to test though, and it still didn't work.

FYI,
Not sure if it makes any difference, but I am on Eratoss.

Scooter5131

**Comment by awangatboo** [comment]
I will make one Eratoss and try it.  It works for me on Loy.

**Comment by awangatboo** [comment]
I agree there is something wrong.  Mine did not work as well.  I have have TheBeaver double check my design but if it looks good I will assign this bug to Dib.

**Comment by awangatboo** [comment]
Never mind.  My planter was not made from oak planks and oak fences and that is why it did not work.  I changed out with oak and it worked.  Is yours all Oak?

**Comment by Scooter5131** [comment]
No, it's all Birch as that's all I've ever used for building.

I'll try swapping out the fences tonight to see if that resolves the issue (assuming it will based on your testing).

Thanks for the help!
Scooter5131

**Comment by Scooter5131** [comment]
Oak was the issue, thanks for the help.

Scooter5131
