### ISSUE TITLE
Ship Eaten, Crew dead.

### ISSUE THREAD

**Issue by TacoLink** [StarQuestMinecraft/StarQuestPublic#651]
Coming from Trinitos Gamma to Trinitos Alpha, my ship was eating in the process of switching the servers. In this specific time frame I was teaching my friend how contracts and certs work, and both him and I are fairly mad about the whole ordeal. We spawned in Trinitos Alpha with no ship, no items, and no spacesuit, suffocated, and died. I only have once screenshot of the events, here it is:
![2015-08-03_20 28 30](https://cloud.githubusercontent.com/assets/13079905/9050810/6ca11d3e-3a20-11e5-95ff-89c0eae0d9cd.png)Edit: This happened about 8:30pm EST, 8/3/15
EditPart2:This happened at the same time as the beta crash, maybe there is a connection?

**Comment by awangatboo** [comment]
Something went way wrong on 8/3/15.  Russo was able to stop and restart the server and things started working correctly but in my case he was unable to get my ship or gear back.  He tried 4 different places to pull my ship back and it did not work.  You can ask a mod in-game for a refund but I think you will most likely need to mark this up to SQ 3.0 being in Beta stage and rebuild.  Sorry

Will close this bug on 8/11 unless some other resolution it made.

**Comment by TacoLink** [comment]
Partially fixed thanks to money, Still without a ship (Or a friend, ;-;) but I'm fine with that.

**Comment by TacoLink** [comment]
Not relevant anymore, cl00singg
