### ISSUE TITLE
Fighter Armor % Bug

### ISSUE THREAD

**Issue by StarWarden** [StarQuestMinecraft/StarQuestPublic#653]
I have been building a fighter and there seems to be a bug that only let's the Fighter class have 19 armor blocks. I talked to one other person having the same problem. My fighter is 200 blocks total, and I have 24 armor blocks on it as is. But when I try to save it in the database, it says that there are too many armor blocks of blast resistance 19 or greater. This should not be because when you multiply 200 total blocks by 15% or .15 (the armor % for fighters) then you get 30. So I have under the maximum amount of armor blocks but the ship thinks I have more than 30. Please help, I don't want to be stuck with insufficient fighters.

**Comment by awangatboo** [comment]
I am not sure but this might be correct if you have other blocks on your ship like stairs, more than one furnace.  When you try to build is it only wool and then the armor and 1 sign?  Just trying to make sure something else that is not on it has a blast resistance of +19.

**Comment by StarWarden** [comment]
No I double checked all other blocks, and the armor is the only stuff with blast resistance of over 19. It's all stone brick stairs.

**Comment by awangatboo** [comment]
Would you mind showing pics or if not please tell were your ship is so I can look at it.

**Comment by awangatboo** [comment]
If you will not show pics or let someone see the ship I going to close this bug.
