### ISSUE TITLE
Trinitos Alpha

### ISSUE THREAD

**Issue by HollywoodSun** [StarQuestMinecraft/StarQuestPublic#654]
Trinitos Alpha is down and I need a ship refund. My inventory was mostly empty but I really need the ship back. Thanks.

**Comment by awangatboo** [comment]
on 8/3 there was a major issue that cause many people to loose their ships and stuff.  ( I was one of them )  I am not sure if this was part of the same case but Please contact a mod in game and reference Github ticket #654.  Hopefully they can help but in my case a manager could not find my ship in the ship database and my stuff I had was just gone.

**Comment by awangatboo** [comment]
8/4 ~8:44 Server time TA still down confirmed by users.

**Comment by HollywoodSun** [comment]
Lawrence fixed it for me, and Trinitos Alpha is back up. Case closed.
