### ISSUE TITLE
Flew Myself into my own Cannons

### ISSUE THREAD

**Issue by HollywoodSun** [StarQuestMinecraft/StarQuestPublic#655]
Yeah.. had no idea you could make yourself explode with your own cannons if you flew fast enough. So I did that on accident, and quite a large bit of my ship was blown up, enough that I can't fly. It is supposed to slowly regen (In Gamma), but the restart stopped that process. Is there anyway I can get a ship reload?

**Comment by HollywoodSun** [comment]
Oh, I also suicided and my cryopod decided not to work, so I am at Spawn Station. The Cryopod was at Paladins base on Otavo, Coords are 1221, 65, -285

**Comment by awangatboo** [comment]
You need to talk to a mod about the ship.  I am not sure they will refund you on this.  It is up to the MOD.  As for the Cryopod issue this should be in a different ticket.  Give as much details as you can as the cryopod issues are really being a pain.
