### ISSUE TITLE
Skywatch is "chicken" to fight you if you trigger them on a wanted person.

### ISSUE THREAD

**Issue by HiFlyCS** [StarQuestMinecraft/StarQuestPublic#656]
I attacked a wanted person in Beta, but Skywatch gave a warning. Then Skywatch Emp'd my ship but didn't show up. What?

**Comment by awangatboo** [comment]
What did you expect to happen?  Should you not have even been warned as this was a wanted person?  Or do you think this is a bug on the part of the re-balance of Sjywatch in the beta system?

**Comment by shadyninja21** [comment]
I attacked hollister it said they were coming and I was resistig but nothing came.

**Comment by Generaltyler1** [comment]
were you a privateer?

**Comment by Thedrew655** [comment]
Thread appears to have become dormant, if an issue like this occurs again please create another thread.
