### ISSUE TITLE
:/       ( Ship is stuck to eco station )

### ISSUE THREAD

**Issue by GirlArcher** [StarQuestMinecraft/StarQuestPublic#657]
my ship landed on the eco station and now its stuck to it and I cant leave

**Comment by awangatboo** [comment]
Are you right clicking to start your ship or left clicking to re-detect your ship?  It should not work if you are left clicking but right clicking should work.  If not you will need a mod to help you out.

**Comment by awangatboo** [comment]
I will ask you about this in-game but I do not think this is a real bug so I am closing it.  If I find out more in-game I will re-open.
