### ISSUE TITLE
Docking port Bug

### ISSUE THREAD

**Issue by ghost** [StarQuestMinecraft/StarQuestPublic#658]
ON my ship, I have an entrance/exit that is also a docking port, and when I left my ship, I couldn't get back in because the buttons below and above the door acted as a floor and a ceiling. Eventually, my friend helped me get back to my ship, but is there a way you could fix this?

**Comment by awangatboo** [comment]
This is the way space works.  It has always been this way.  I will assign to Dib but do not expect this to be changed.

**Comment by gregolegomonkey** [comment]
If you are having difficulties getting in, fly above the buttons, then shift down while walking into the door/wall.  Also the way space works: air that is sandwiched between two blocks on different y levels will have gravity, depending on the distance between the two blocks.

**Comment by awangatboo** [comment]
Also another idea is to put a hatch on your ship.

**Comment by Thedrew655** [comment]
Since this is an aspect of space that cannot be currently changed I'm going to go ahead and close this one.
