### ISSUE TITLE
driving into a mountain

### ISSUE THREAD

**Issue by fghhjbbv** [StarQuestMinecraft/StarQuestPublic#660]
My ships autopilot drove me into a mountain!
it is somewhere in -184 65 496.
its shield is active, and i died with my loot including a stack of diamonds stolen from a grun faction.
it is happened  22:00  )8/)8/2015

**Comment by fghhjbbv** [comment]
im marsman

**Comment by awangatboo** [comment]
I do not think autopilot should fly you into a mountain.

**Comment by fghhjbbv** [comment]
go look at the coordinates, you will find a fighter with two cannons, mostly white with some blue,red and orange parts and may have a pile of loot nearby.

**Comment by awangatboo** [comment]
I think this is a movecrat issue or it just be a issue that happens when the server LAG's.

**Comment by Evancooldude** [comment]
Has been reported multiple times. Seems to be an extreme-lag situation. This has been classified as one of "Those bugs", the variety that takes forever to find / write a fix for. Once I start getting my hands dirty with movecraft I'll look into this.

**Comment by awangatboo** [comment]
Closing all bugs in preparation for SQ 4.0.
