### ISSUE TITLE
Machina

### ISSUE THREAD

**Issue by HollywoodSun** [StarQuestMinecraft/StarQuestPublic#662]
Though I have not personally tested it, I have heard lots of Machina certs are either broken or Machina itself is broken. Like I said, this is a report for someone else, masafu2000. Someone else verified they are having problems as well. He also had the cert unlocked, but it still wouldn't work (Planter).

**Comment by awangatboo** [comment]
May people think that planter is broken when you get the cert but I have found that most of the time people build it wrong because they do not use oak for all the pieces.  If you use any other wood it does not work but all oak planks and fences do the trick.

**Comment by HollywoodSun** [comment]
Okay, I will tell them that and see if they can get it to work. Case temporary closed.

**Comment by HollywoodSun** [comment]
He said it is properly built with oak wood, and he has the cert, but he does not have permission to use it.

**Comment by awangatboo** [comment]
When did he get the Cert?  If the cert was purchased in the first month of SQ 3.0 it will not work.  He has to buy the one with 11 philanthropy pints in it.  If he bought the first one he must re-buy the second one.

**Comment by HollywoodSun** [comment]
Yeah, we slowly figured that out. I completely forgot that the certs were revamped a bit. I told him he will have to purchase it again, so case closed. Sorry for this, should have figured that out quicker Lol.

**Comment by awangatboo** [comment]
That's OK have fun getting 11 philanthropy.
