### ISSUE TITLE
Vote redeem lost when it hit world height

### ISSUE THREAD

**Issue by freethecheese** [StarQuestMinecraft/StarQuestPublic#663]
I redeemed 8vt for a stack of steak inside the Echo Era base inside of a mountain, and the parachute chest failed to land on top of the base, likely because it was at the world height limit. Can there be a way to just get the items if it hits the world height? Also, can I have the steak I earned?

**Comment by awangatboo** [comment]
This is a strange one.  Nickmiste will need to look at this as it is his plugin.  Talk to a Mod about getting the steak.  They should give it to you due to this bug.

**Comment by awangatboo** [comment]
Closing all bugs in preparation for SQ 4.0.
