### ISSUE TITLE
Cryopod Glitch

### ISSUE THREAD

**Issue by HollywoodSun** [StarQuestMinecraft/StarQuestPublic#664]
I am reporting for Usaid2002, with a Cryopod Glitch. He was on Avaquo and apparently died, where his Cryopod glitched.

**Comment by AlinaFicalton** [comment]
can confirm the glitch but not the cryopod. was in a privet and unassailable by outsiders

**Comment by shadyninja21** [comment]
The floor of his base isn't protected, so should you break through you can reach his cryopods quite easily. If somebody cared enough, had the time, and the resources, they could've flown his cryopod out of there. I don't know if that helps with your search for the bug though.

**Comment by awangatboo** [comment]
is a 7 day ticket and you did not put in the required info for this ticket.  

http://www.starquestminecraft.com/starquestforums/m/17078810/viewthread/23552021-great-cryopod-bug-closing

Closing bug as the devs need full info to fix bug.
