### ISSUE TITLE
Skywatch didn't come

### ISSUE THREAD

**Issue by shadyninja21** [StarQuestMinecraft/StarQuestPublic#665]
I killed Alina in TUPA base. After I grabbed her gear I high tailed it out of there for fear of skywatch. I got the messages that said:
"Prepare to be boarded"
"Skywatch is coming"
"Your resistance is admirable"
etc.
I got those, but no actual fighters or shock troppers. It happened on Otavo at like 1:15ish EST on Otavo. I'm wanted and she isn't. (I think that means something with skywatch).

If it is a bug can you deactivate the messages for me becasue it freaks me out! 
Thanks

**Comment by AlinaFicalton** [comment]
I can confirm this. battle was at lease a min long and i hear no skywatch. I also re-spawned near by and never heard anything. I actually forgot about skywatch will shady said something.

**Comment by AlinaFicalton** [comment]
this happoned agen. i killed some dude and i was greated by these messages: 
sorry, i will post the images tomorrow. the websight i use to upload images is down.
Basicaly it said skywatch was summoned, 2 seconds later wave 2, 10 seconds later wave 3, 30 seconds later wave 4, than nothing. skywatch never spawned and it just went about it like i killed them all and won.

**Comment by awangatboo** [comment]
@AlinaFicalton did you ever upload the images?

**Comment by awangatboo** [comment]
Closing this bug as I have heard that Dib re-worked skywatch in beta.  if this issue happens again please create a new ticket.
