### ISSUE TITLE
Ship slowly disappearing?

### ISSUE THREAD

**Issue by TheLazyGriffin** [StarQuestMinecraft/StarQuestPublic#666]
Just as I was about to enter the slipgate from beta to alpha, the back of my ship disappeared and about a dozen blocks suddenly were gone, along with a few signs. My ship was rendered un-flyable and I had to rebuild it. (I was not shot, nobody was even in the area at the time it happened) then later about 5 minutes after I had entered alpha, more of my ship disappeared. I have no idea why this is happening and now I'm stuck in space. I don't know what do to. Hollywood tried to help me and in the end just told me to report it here and hope for a compensation.

**Comment by awangatboo** [comment]
Sounds like Space Beavers

**Comment by GirlArcher** [comment]
The same thing happened to but It would not let me rebuild my ship because how close I was to the slipgate.

**Comment by awangatboo** [comment]
This is a low priority issue as it does not happen all the time and is not repeatable.

**Comment by awangatboo** [comment]
Closing all bugs in preparation for SQ 4.0.
