### ISSUE TITLE
No Mobs spawn on Xylos ?

### ISSUE THREAD

**Issue by Youri013** [StarQuestMinecraft/StarQuestPublic#667]
I have been walking for hours now but I still can't find any blazes on Xylos. Is this a bug or am I wrong?
Pleas could someone fix this???

**Comment by Youri013** [comment]
Ow and does anyone else have this too?

**Comment by awangatboo** [comment]
I have found blazes on Xylos.  I heard that Dib was looking into the code on this yesterday so at some point today I will go check again.  Oh yeah the way I found blazes was auto-piloting close to the ground and from time to time I would find them.

**Comment by awangatboo** [comment]
Stayed on Xylos for about an hour and tried my trick and could not find a single mob.  I think this is an issue again.

**Comment by awangatboo** [comment]
I was told Nick was going to look into this.

**Comment by awangatboo** [comment]
I think this might have been fixed could you please check?

**Comment by awangatboo** [comment]
I went there today and loads of mobs are there.  Watch out.  Closing Ticket.
