### ISSUE TITLE
I died to a Random glitch

### ISSUE THREAD

**Issue by Usaid2002** [StarQuestMinecraft/StarQuestPublic#669]
Okay so I know this is weird and hard to believe but I was walking in my worldguard... and I died.. RANDOMLY... I don't even know what the heck happen it just randomly said I died and made me go to spawn.. My cryo was on TUPAS Avaquo base and I want a refund for my items please. 

Thank you dibby and managers for your work! 

Thanks, Usaid!

**Comment by awangatboo** [comment]
You need way more info than this.  What planet were you on.  Was anyone else around you?  What flags are set on your W/G.  Where should you have gone.  What was the death message (look in your logs if you restarted) what time (server time).  I think this would be a good start to see how you died and if a Mod should give you a refund.

**Comment by Usaid2002** [comment]
Alright dude thanks.

What planet was I on: Avaquo

My Death Message: "You died!"

What Time: Around the restart last night.. Like 11:30 PM Central Time USA

Where should I have gone: I should have gone to  NewAureumsTUPA Avaquo base because after the skydogs raided me I moved my cryo from my worldguard to the TUPAN base. So I should have have gone to NewAureumsTUPAN Avaquo base 2nd floor going up from the elevator. The first cryo you see after you go up is mine. 

Thank you, Usaid2002!

**Comment by awangatboo** [comment]
Someone with console access will need to go look at the logs.  At least we have the info now.

**Comment by Usaid2002** [comment]
Okay, BUT THAT IS what is said on my screen and logs.

**Comment by shadyninja21** [comment]
I feel like he got shot by a skelie

**Comment by awangatboo** [comment]
I have asked and it sounds like no one has looked at or responded to my request to have someone look at the logs.  Try to get a manager and talk to them.  Seeing this was a glytch and not e repeatable bug I am closing the ticket.
