### ISSUE TITLE
my cryospawn glitched

### ISSUE THREAD

**Issue by rocky0121** [StarQuestMinecraft/StarQuestPublic#672]
i flew to rak, and there i updated my spawn by double right clicking the cryo sign. a few minutes later i fell down a hole and died. Then i was warped back to spawn 8

**Comment by AlinaFicalton** [comment]
can confirm this was a glitch and not a broken or messed up pod

**Comment by awangatboo** [comment]
Please see this forum thread.

http://www.starquestminecraft.com/starquestforums/m/17078810/viewthread/23552021-great-cryopod-bug-closing

Update in a couple of days or this ticket will be closed.

**Comment by awangatboo** [comment]
not proper info on Cryopod issue closing ticket
