### ISSUE TITLE
Wanted status not staying

### ISSUE THREAD

**Issue by BatFC** [StarQuestMinecraft/StarQuestPublic#673]
When I get any black market contracts and cancel them within the hour the wanted status does not stay with me.

According to this post: http://starquestminecraft.com/starquesthome/m/17590832/article/3407496/page/2
the wanted status should persist for an hour. 

Couple this with the ability to remove contracts in space and it is impossible to hunt wanted people in Alpha or Beta.

**Comment by Thedrew655** [comment]
I notified the developers and they will look into the issue, thank you for reporting it.

**Comment by awangatboo** [comment]
I think this is fixed as I know I was talking to Yargon yesterday and someone saw his name on the wanted list even though he had no contracts.  Closing ticket.  Please open another one if this happens again.
