### ISSUE TITLE
Cows not Spawning on Otavo

### ISSUE THREAD

**Issue by LilWoofy** [StarQuestMinecraft/StarQuestPublic#674]
I logged in Today 8/11/15
And all my cows were gone. When I went to go find more, I realized there were no more cows in sight. No cows were spawning anywhere anymore. I've manage to find one cow out far in the wild with a name tag but that's about it. I asked JavaInvader also, and he said some of his cows disappeared too. I think at the moment cows are broken.

**Comment by AlinaFicalton** [comment]
i think all mobs are broken ATM because alot of people are saying they cant find mobs.

**Comment by awangatboo** [comment]
I though that mobs were completely broken but then i found if I went to the spawn of the planet I found some.  if I have a chance I will sty to swing by and double check again.

**Comment by awangatboo** [comment]
I just went to Otavo and went to spawn.  Found 1 cow right away.  I killed it and then tried to find another one.  Looked for 10 - 15 mins.  Looked in the day and in the night.  I only found that one cow.  Sorry I killed :(

**Comment by LilWoofy** [comment]
You monster!
And cows were fine before, they spawned a lot. But now they don't spawn at all...

**Comment by Siigillum** [comment]
Good job awan, you made cows extinct on Otavo....

**Comment by awangatboo** [comment]
Dib worked on the code and got this working.
