### ISSUE TITLE
WG Issues

### ISSUE THREAD

**Issue by winecraft-dev** [StarQuestMinecraft/StarQuestPublic#675]
I was in BatFC's worldguard and at first wasn't able to pvp him. A few minutes later, I started hitting him, and he was taking damage. I did /rg info and there wasn't a flag for PvP.

-Jurgmania

**Comment by awangatboo** [comment]
Not 100% sure this is the issue but I have heard for issues where people that are mods have strange things happen to them when they come out of duty mode.  I wonder if you had been in duty mode earlier and this was one of the strange things.

**Comment by BatFC** [comment]
PVP deny flag was definitely there before the incident, I checked the WG to make sure shield was up before Jurg came.
After the fight even destroying and replacing the shield sign wouldnt turn on the PVP deny.

**Comment by Kyle98martin** [comment]
Shields and WGs have 1 way pvp in favour of the owner by default. The combat manager plugin seems to disable the 1 way PvP though making PvP enabled in the WG.

**Comment by awangatboo** [comment]
Jurgmania- 

is there a chance you had gone into duty as a tr mod?  I know that mods have overrides on WGs and from talking to TheBeaver sometimes mod perms do not clear up as soon as you unduty.   Is there a chance that you hit him some time after coming out of duty?

**Comment by awangatboo** [comment]
-Jurgmania 

Any comment on this?  If not I am going to assume you had just gotten out of duty mode and that was the case and close this ticket.
