### ISSUE TITLE
my ship issues

### ISSUE THREAD

**Issue by rocky0121** [StarQuestMinecraft/StarQuestPublic#676]
ok so i was flying to the skydogs xylos base in my fighter, and i autopiloted on the way. then some weird glitch happened and my ship was mixed in with a bunch if different blox like netheract and other things. then i had hollywood and notsure help me, but i suffocated and was tped back to otavo

**Comment by awangatboo** [comment]
We have had a lot of issues like this since SQ 3.0.  We might have had the issues before but most planets did not have any high mountains so it was not really seen.

**Comment by awangatboo** [comment]
Closing all bugs in preparation for SQ 4.0.
