### ISSUE TITLE
Falling to death at Eco-stations 

### ISSUE THREAD

**Issue by Thedrew655** [StarQuestMinecraft/StarQuestPublic#677]
Over the past few days a few players have experienced falling to his or her death while exiting a ship while stopped at an eco-station, myself included. My best guess is it has something to do with leaving a ship and it thinking you are still in a place where gravity should exists. So far this incident has only occurred at eco-stations, if you have any other questions let me know.

**Comment by awangatboo** [comment]
The space plugin does not work at ECO stations?  I know space only works well as long as there is nothing below you and above you.  The space plugin makes it where you can fly in space as long as there is no floor or ceiling at the same time.  If the ECO station acts as a floor and part of a persons ship acts as a ceiling then they will be subject to gravity.  Is there a chance this is what happened or something different?  Needless to say I know NICK stated that we need a whole re-write of the space plugin.

**Comment by Thedrew655** [comment]
I believe when each person left his ship either wool on the ship (boarding ramp) or buttons (docking door) acted as the roof and then the eco station acted as the floor causing the players to fall to their death.

**Comment by awangatboo** [comment]
Should we leave this ticket open as a request to re-write the space plugin?

**Comment by TacoLink** [comment]
*This is a small lil idea, but how about disable "gravity" in space, and replace it with the old creative free-flying?*

**Comment by Thedrew655** [comment]
It's a rare glitch, I'll go ahead and close it for now.
