### ISSUE TITLE
create fac bug

### ISSUE THREAD

**Issue by liv4ths** [StarQuestMinecraft/StarQuestPublic#679]
I created a fac called NavCorp and it took my money and said it was created but didnt put me as the leader. The fac has no leader listed and when i do /f f it says im in the fac wilderness.

**Comment by TacoLink** [comment]
Happened to me before. Can confirm.

**Comment by awangatboo** [comment]
I do not think the bug fixers will be able to get good info from the logs that are old.  We need to have someone else report this when the logs are new and someone can see the issue.  I am closing this bug  and waiting for the next one like it to see if we can get fresh logs to see what happened.
