### ISSUE TITLE
Ship Regenerated into Other Ship

### ISSUE THREAD

**Issue by HollywoodSun** [StarQuestMinecraft/StarQuestPublic#680]
Reporting for Will_Hamilton, someone else's ship regenerated in Gamma, presumably his target, but it regenerated into his cockpit overwriting his blocks. Hopefully someone can help him.

**Comment by awangatboo** [comment]
This is a risk that pirates take when they fly too close to their targets.  I will ask management but I think nothing should be done about this.

**Comment by HollywoodSun** [comment]
It's more of just a "perhaps we could get a fix for this" instead of a refund request.

**Comment by awangatboo** [comment]
Oh Ok.  I will put it on the list for Dib to look at but it will most likely be a long time before he looks at this.

**Comment by Siigillum** [comment]
I call this "damaged by debris". It's always been around. Unintended feature. Just stay clear of possible debris.

**Comment by awangatboo** [comment]
Closing all bugs in preparation for SQ 4.0.
