### ISSUE TITLE
/stats (shipclass) broken

### ISSUE THREAD

**Issue by buba141** [StarQuestMinecraft/StarQuestPublic#681]
I don't have permission to use the /stats command. The exact error message is "I'm sorry, but you do not have permission to perform this command. Please contact the server administrators if you believe that this is in error." I tried checking several different ship classes, but got the same error every time.
Also, /stats in not listed in the tab complete menu.

**Comment by AlinaFicalton** [comment]
this is know and has been reported

**Comment by awangatboo** [comment]
I have talked with staff and this is not going to be fixed any time soon.  It looks like there is another command called /stats that overrides /stats for ships.  That is why it does not work.

**Comment by Siigillum** [comment]
The very simple soultion would be to change this command to something that not gets overrided.... But that's just me.

**Comment by awangatboo** [comment]
I agree with @Siigillum.

**Comment by AlinaFicalton** [comment]
new command sigestion. /shipstats

**Comment by awangatboo** [comment]
I have talked to the Devs more and the new command will be /shipinfo and it should be in game in the up coming weeks.

**Comment by awangatboo** [comment]
The new command is on the server use /shipinfo {shipname} to see the info you seek.
