### ISSUE TITLE
Cryopod

### ISSUE THREAD

**Issue by starquestbugs** [StarQuestMinecraft/StarQuestPublic#684]
I recently made it to avaquo after numerous attempts and set up my cryopod within my factions base. However, a pirate dug all the way down to near-bedrock and killed me, but offered to return my stuff. However.... I'm at spawn station in alpha. My cryopod didn't work. I'd send you the cords but I don't I don't know the exact area, just that it's In heavens cryopod area. I never got a message that said "cryopod broken" and I have been killed many times by wither skeletons. Please help as I don't want to fly through TG again.

**Comment by starquestbugs** [comment]
Oh sorry forgot. Username key0fdestiny

**Comment by awangatboo** [comment]
Talk to a MOD and they "might" help you. If you want to try to help with the issues we have with cryopods please follow this format.

http://www.starquestminecraft.com/starquestforums/m/17078810/viewthread/23552021-great-cryopod-bug-closing

If not giving all the correct info we will close this bug in a few days.

**Comment by awangatboo** [comment]
Closing this one as well make sure to use /cryocheck
