### ISSUE TITLE
Unlocking Gunship cert with privateering gives you piracy verison

### ISSUE THREAD

**Issue by icekoob** [StarQuestMinecraft/StarQuestPublic#685]
I unlocked gunship when I had 6 infamy and 13 privateering and it gave me the pirate version. I would like to have the privateer version.

**Comment by awangatboo** [comment]
Not sure how to fix this.  I can ask if anyone knows.

**Comment by awangatboo** [comment]
Oh yeah by the way what color is which?  Pirate is color "?" and privateering is color "?"

**Comment by JavaInvader** [comment]
Pirate is Red Privateer is Blue

**Comment by awangatboo** [comment]
Can you remove the cert and then repurchase it?  If so will the color be correct?

**Comment by Evancooldude** [comment]
Has this issue been resolved?

**Comment by icekoob** [comment]
Yep
