### ISSUE TITLE
Lost my stuff, told to post here

### ISSUE THREAD

**Issue by NommaBoy** [StarQuestMinecraft/StarQuestPublic#687]
Basically, I went to alpha space, it was down, I lost my inv and ship, reported on forums (with proof), and told to post refunds here, so here is what I lost (this is what you meant by refunds right). Also, link to forum post just in case: http://www.starquestminecraft.com/starquestforums/m/17078810/viewthread/23858771-lost-my-stuff/post/104519967#p104519967
In my inventory:
1 stack of grey wool
1 stack of blue wool
1 stack of light blue wool
1 stack of red wool
stone tools (not important, I can easily re-make)
15 cooked pork
Ship controller
Full Space suit
1 blaster (Power III and Unbreaking III enchants)
23 blaster ammo
full set iron armor (enchanted chest piece with prot I)

In storage containers:
another stack of red wool
another stack of grey wool
2 stacks + 41 magenta wool
1 stack + 14 white wool

Ship itself (not sure how this works, if i am given materials i can easily re-create):
(I don't have any proof/pics of the ship, but I'm being as accurate as possible. If you want pics, I can do my best to look for some)
1 sponge
1 piston
at least 1.5 stacks of purple wool
14 storage containers
9 glass

I read that we aren't supposed to post refunds here, but idk if this is an exception, since I was told on the forums to do so.

**Comment by awangatboo** [comment]
Github is for bugs and not really refund requests.  The Bug was that Alpha was down.  Dib has updated the code so Alpha should not crash as much.  Please see a mod in-game for a refund and you can reference this bug as there was a crash of Alpha_space about the time you had your issue.
