### ISSUE TITLE
Mob spawning broken!

### ISSUE THREAD

**Issue by LilWoofy** [StarQuestMinecraft/StarQuestPublic#688]
I logged on to Uru, and saw all kind of animals that aren't suppose to be on uru. 
Chickens, Cows, pigs, and sheep.

Proof: http://imgur.com/j8KLk1Y,QkCuSOj

**Comment by awangatboo** [comment]
Thanks for reporting.  This has been reported on TS due to this issue.  You can fix it for now.  please Turn mob spawn to off in your factions.  Dib knows about this and Nick thinks he has found a fix to the code but Dib needs to install it.

**Comment by awangatboo** [comment]
It is only in factions that this happens.

**Comment by brickworm2012** [comment]
Saw pigs and chickens on Rakuria, in the Spark faction land.

**Comment by shadyninja21** [comment]
This is happening on Otavo as well. Creepers, Skeletons, cave spiders (those belong though) a few enderman

**Comment by awangatboo** [comment]
I have been told by Dib this was fixed.  Closing issue.
