### ISSUE TITLE
/contract wanted <playername> not working

### ISSUE THREAD

**Issue by Tonlage** [StarQuestMinecraft/StarQuestPublic#690]
Then writing /contract wanted <playername> returns:
"This player is not wanted
This player is not a privateer"
even if the player is wanted or privateer.

**Comment by awangatboo** [comment]
could you please give more details and I just ran this command today in Alpha and it returned Kyle as a wanted player.

**Comment by awangatboo** [comment]
Also where did you see you were to put the player name after the command?  I thought it was just /contract wanted

**Comment by gregolegomonkey** [comment]
The command is just /contract wanted.

**Comment by awangatboo** [comment]
Closing this ticket as a misunderstanding of the command.  As @gregolegomonkey said it is just /contract wanted.
