### ISSUE TITLE
Elevators glass dissapearing

### ISSUE THREAD

**Issue by lucon1** [StarQuestMinecraft/StarQuestPublic#691]
not sure of the exact cause, but the other day, i tried to activate a 3x3 elevator, which had some dropped items on it. I got sent up to the top level(my destination), but got stuck there hovering and locking view and movement in place. 

I'm guessing it was because the items were glitching the elevator (didn't like being told when/where to stop), but unconfirmed

I tried to move, out of it, break stuff around it to block update, jumping, etc. no help  I tried to "/duty" out of it, but was considered "flying" so no help.  I finally ended up relogging.

when i logged back on, all the glass had disappeared from the elevator, and i fell to my death. glass was still missing.

**Comment by awangatboo** [comment]
The plugin Lift is flaky when the server has a heavy load.  I do not see enough info to recreate and put a bug against the lift plugin.

**Comment by awangatboo** [comment]
I have asked SQ management and at this point they do not see a good alternative to the lift plugin.  They do not code the lift plugin so I have been told there is nothing that can be done.
