### ISSUE TITLE
Contract Glitch

### ISSUE THREAD

**Issue by Liggo** [StarQuestMinecraft/StarQuestPublic#692]
When completing a contract which asked for 20 stacks of oak logs and 25  , and also pretty much 2 stacks of birch logs , it took the birch logs and gave me the contract points but it didnt remove the oak logs from my droppers

**Comment by awangatboo** [comment]
Seeing that this is in the favor of the player I am marking this as a low Priority.

**Comment by Evancooldude** [comment]
This issue is on the agenda for bug fixes for the Jr. Developers. It should be cleared up within a week.

**Comment by Millibyte1** [comment]
I fixed the bug yesterday afternoon, forgot to make a post about it. 

The fix is currently waiting to be implemented.

**Comment by Millibyte1** [comment]
The fix has been implemented and tested.

**Comment by awangatboo** [comment]
Case closed :)
