### ISSUE TITLE
cryopod #2

### ISSUE THREAD

**Issue by starquestbugs** [StarQuestMinecraft/StarQuestPublic#693]
Well cryopod 1 got fixed, a mod toed me to avaquo and set my spawn. However a few hours later I got ambushed by androids and fell and died. I re spawned in trintos alpha again. Please help me. Same cryopod location as he first.
Keyofdestiny
Heaven miner

**Comment by awangatboo** [comment]
Talk to a MOD and they "might" help you.  If you want to try to help with the issues we have with cryopods please follow this format.  

http://www.starquestminecraft.com/starquestforums/m/17078810/viewthread/23552021-great-cryopod-bug-closing

If not giving all the correct info we will close this bug in a few days.

**Comment by starquestbugs** [comment]
Thanks. I can't seem to make this elevator without getting killed.

**Comment by starquestbugs** [comment]
Uhh... It says invalid ip address.

**Comment by awangatboo** [comment]
The forums are changing and the link is bad right now.

**Comment by awangatboo** [comment]
I am closing this as Dib has worked on cryopods.  Use the new command /cryocheck to make sure your cryopod is set correctly.

**Comment by starquestbugs** [comment]
Uhhhhhhh so now that that command was added after the bug I can't get a mod to help as it was never set up correctly (even though I now stranded on two and the cryopod that the mod had was set up and I re spawned once, then it just stops working?) great. Just great.
