### ISSUE TITLE
Friendly mob spawns don't work

### ISSUE THREAD

**Issue by PandoraKid102** [StarQuestMinecraft/StarQuestPublic#695]
Breeding friendly mobs does not produce a baby animal. The animation is there, its just the baby that does not appear. This only occurs in faction land, as I tested it and it works just fine. So far I tried on Nal and Era but I am pretty sure its serverwide, due to the recent changes.

**Comment by awangatboo** [comment]
I heard someone say something about that,  I guess that the fix that Dib put in to stop all the different mobs from spawning in faction land also stopped the passives.

**Comment by StarQuestMinecraft** [comment]
Finally got around to fixing this. Installed at next restart. ~dib
