### ISSUE TITLE
Piracy Contracts

### ISSUE THREAD

**Issue by JavaInvader** [StarQuestMinecraft/StarQuestPublic#697]
You can't partially complete piracy contracts. It will just take the items and not deduct them.

**Comment by awangatboo** [comment]
Is this at every ECO station or just Gama South?  I ask this as Liggo has seen some strange stuff at Gama South.

**Comment by JavaInvader** [comment]
Every eco station

**Comment by shadyninja21** [comment]
Happened at gamma south for me one time

**Comment by Siigillum** [comment]
Bump. The issue still exists.

**Comment by awangatboo** [comment]
Closing all bugs in preparation for SQ 4.0.
