### ISSUE TITLE
Trmods don't suffocate in Space

### ISSUE THREAD

**Issue by JavaInvader** [StarQuestMinecraft/StarQuestPublic#698]
for whatever reason Trmods don't suffocate in space. Idk if its just trmods or all other staff ranks.

**Comment by awangatboo** [comment]
I will ask beaver about mods.

**Comment by awangatboo** [comment]
Beaver suffocated in Beta.  Is this all space worlds for Trmods?

**Comment by JavaInvader** [comment]
I have no idea i will have to ask some to test

**Comment by brickworm2012** [comment]
Trial mods seem to have a lot of duty overlap, don't they.

**Comment by awangatboo** [comment]
Giving this a low priority as we should be trusting Tr. Mod not to abuse bugs

**Comment by Beachguyryan** [comment]
Add being able to open faction doors that are "locked" to the list that overlaps from duty, i made a report about it.

**Comment by awangatboo** [comment]
Closing all bugs in preparation for SQ 4.0.
