### ISSUE TITLE
Resource Pack Texture Missing

### ISSUE THREAD

**Issue by Laserlance141** [StarQuestMinecraft/StarQuestPublic#701]
There is no on state for the redstone lamp.
![2015-08-30_10 42 53](https://cloud.githubusercontent.com/assets/13091148/9568638/2290717e-4f04-11e5-9b51-28f610bf936f.png)
![2015-08-30_10 42 47](https://cloud.githubusercontent.com/assets/13091148/9568640/248afe68-4f04-11e5-9295-3fb95e7ed1be.png)

**Comment by awangatboo** [comment]
I know this has been mentioned to money.

**Comment by awangatboo** [comment]
Closing all bugs in preparation for SQ 4.0.
