### ISSUE TITLE
Try to claim with /rg create or /rg define and both come don't work.

### ISSUE THREAD

**Issue by Crazan21** [StarQuestMinecraft/StarQuestPublic#703]
So I unclaimed my region in my fac area as soon as I found out that wasn't allowed, then I went to go make a claim 150 blocks away so I could have a safe home and I get "You don't have permission" error message every time I type /rg create or /rg define. I'm really confused as to why I don't and can this be fixed?

**Comment by awangatboo** [comment]
Try ' /rg claim (rgname) ' That should work.

**Comment by Crazan21** [comment]
thank you haha, I musta just been being stupid.
