### ISSUE TITLE
faction chat problems, fix soon please.

### ISSUE THREAD

**Issue by Crazan21** [StarQuestMinecraft/StarQuestPublic#704]
so I did /f title for me and my member herobrine, now our names come up white on faction chat for ourselves plus the rest of the faction no longer sees our chatting and we can't see eachothers. Is there a way to fix this or undo this?

edit- I tried removing titles and the issue persists.

**Comment by awangatboo** [comment]
I  am pretty sure all that happened is the faction part of chat crashed.  When this happens get a mod and ask them to reload.

**Comment by Crazan21** [comment]
ahh alright
