### ISSUE TITLE
Furnaces do not count as armour.

### ISSUE THREAD

**Issue by Siigillum** [StarQuestMinecraft/StarQuestPublic#706]
Furnaces do count as "other" block type for ships, do not count as armour.

Furnaces are superb armour block resistant to everything btw.

**Comment by awangatboo** [comment]
Quiethelper reported this to management.  They are considering what they want to do about it.

**Comment by Siigillum** [comment]
Furnaceclad in the works anyway, just in case. Hehehe.

**Comment by awangatboo** [comment]
I have been told they still do not count as armor but have been limited to 1% of the ship so I am closing this bug.
