### ISSUE TITLE
Ship Size not available on some servers

### ISSUE THREAD

**Issue by Liggo** [StarQuestMinecraft/StarQuestPublic#707]
Siig reported earlier that when he attempted to use /shipsize  in both beta space and eratoss it did not work and i can also confirm that it did not work on xylos when i tried , it simply gave me the unknown command line. I don't know how widespread this is but it seems like it simply isn't installed on some servers :-1:

**Comment by Siigillum** [comment]
Does not work in Beta, Eratoss, Alpha...

**Comment by Siigillum** [comment]
Worked on Grun a few days ago.

**Comment by Siigillum** [comment]
Does not work on Grun too now...

**Comment by awangatboo** [comment]
I was just told the code is gone.  It should not work on any planet / system.  Nick thinks this is a mistake .  They are working on it.

**Comment by Siigillum** [comment]
Where did the code go.... Ugh?!

**Comment by awangatboo** [comment]
As of 9/3/2015 this command is back and working.
