### ISSUE TITLE
Torpedoes not breaking clay armour blocks.

### ISSUE THREAD

**Issue by Siigillum** [StarQuestMinecraft/StarQuestPublic#708]
As said. Clay blocks are immune to torpedoes.

Torpedoes are now officially useless completely....

**Comment by awangatboo** [comment]
I Talked to Dib about this and he said he will be making some code that QuietHelper will test and tweak values and hopefully fix this issue.

**Comment by Siigillum** [comment]
Issue still exists. Stained clay blocks are basically unbreakable like obsidian...

**Comment by GingerWalnut** [comment]
This has been fixed.
