### ISSUE TITLE
Contract Unresponsive Issue

### ISSUE THREAD

**Issue by motopilot** [StarQuestMinecraft/StarQuestPublic#709]
Contract isn't giving money or taking items out of dropper. It does not give any message whatsoever no matter what number is given with the " /contract complete # " command.  IGN: Opticswagger

**Comment by Siigillum** [comment]
Do you have your ship active (are you piloting it)?

**Comment by awangatboo** [comment]
I have had this issue before and it typicality clears up after I logout and then back in.  Please try this and report back.

**Comment by motopilot** [comment]
Thanks for your help, I did have my ship active at the time. The contract I had yesterday expired so I guess I'll just have to try another one.

**Comment by Siigillum** [comment]
If contract expired that means you have not accepted it That's my guess.

**Comment by awangatboo** [comment]
Wait did you take the contract?  "/contract new (type) #"  After this you can make sure you have the contract with "/contract list"  after this go try to complete it.

**Comment by motopilot** [comment]
Still is not working for me. I am now at beta east trying to complete a contract involving red wool. I have the wool in a dropper, and I am piloting the ship. I enter /contract complete 1 and nothing happens.

**Comment by Siigillum** [comment]
do /contract list, tell me what you have there.

**Comment by awangatboo** [comment]
if you do /contract list what # is the contract?

**Comment by awangatboo** [comment]
lol siig me and you have the same idea.

**Comment by Siigillum** [comment]
lolz

**Comment by motopilot** [comment]
You guys are funny. I believe I solved it. My contract accept commands were not going through.
Works now. Thanks for the quick responses.
