### ISSUE TITLE
ArmorStands not Placeable

### ISSUE THREAD

**Issue by brickworm2012** [StarQuestMinecraft/StarQuestPublic#710]
I was unable to place armorstands in faction land on Rakuria. I tried multiple places, and the result was a loss of the armorstand without anything appearing.

**Comment by awangatboo** [comment]
Did you try it on non-faction land?

**Comment by Kyle98martin** [comment]
Armour stands are counted as mobs for some reason. If you enable mobspawns in faction land then you'll be able to place them

**Comment by awangatboo** [comment]
This is resolved now as Dib fixed the issued of entities in faction land.
