### ISSUE TITLE
Completing Contracts issue

### ISSUE THREAD

**Issue by Littlecritter** [StarQuestMinecraft/StarQuestPublic#711]
I see a smuggling contract that says get 47 slime balls and go to Alpha North: Eco station right, and I  get 210Credits and 1 Smuggling Point to complete so I go to sampetra to get the slime balls and after I get them I go to Alpha North Station straight after that because I had thought I accepted the contract so then Siig told me I had to be in a planet to accept a contract so I quickly go to Loyavas to accept it and then go to Alpha North Station and do "/contact complete 1" right, and it says "completing contract"
and so I don't get anything from it and I do /contract stats and it says nothing I didn't get any points from it nor any money I'm not sure why can you please fix

**Comment by awangatboo** [comment]
I am putting this to Priority low as it is only one person affected.  Have you done other contracts before?  have they worked?

**Comment by Siigillum** [comment]
always check with /contract list    if you actually accepted the contract, sometimes spelling error causes this...

**Comment by Littlecritter** [comment]
no this is my first one

**Comment by awangatboo** [comment]
Have you been able to complete another contract?  I have been told from time to time the database that the contract system talks to can stop taking connections from a Server like Tinitos Alpha.  I am not sure but maybe this was what was happening when you tried to complete your contract.  I can bug some Manager to give you a contract point but I do not know if there is a way to do that.  Please try another contract and report back.

**Comment by awangatboo** [comment]
From what I have been told the code that handles contracts has been updated a lot.  Closing this one for now.  Please re-open if this is still and issue.
