### ISSUE TITLE
Power boost

### ISSUE THREAD

**Issue by PandoraKid102** [StarQuestMinecraft/StarQuestPublic#712]
Isn't power boost supposed to drain money from the bank? That is what I've heard but haven't seen it happening

**Comment by awangatboo** [comment]
I can ask about this but as there are still loads of bugs it might take a while before someone get to it.  Thanks for reporting it.

**Comment by PandoraKid102** [comment]
It would create a money sink and maybe send people to actually get money to sustain factions ^^. Just my bit of thought

**Comment by Siigillum** [comment]
Powerboost was supposed to drain money daily I remember.

**Comment by awangatboo** [comment]
It does.  I added 10 powerboost to my faction and that was yesterday and it took off money yesterday and today.  I will check tomorrow.  If it take out money tomorrow I am going to close the ticket.

**Comment by awangatboo** [comment]
It does take money away but it is strange as to when it does. Closing ticket.
