### ISSUE TITLE
Crash When join

### ISSUE THREAD

**Issue by Codex66** [StarQuestMinecraft/StarQuestPublic#713]
Every time I join I crash. I'm on Sampetra.

**Comment by awangatboo** [comment]
I will go to Sanpetra to see if is is something with the server.

**Comment by Codex66** [comment]
ok

**Comment by awangatboo** [comment]
Another idea is to also delete / rename your %appdata%/.mincraft folder and let it re-download

**Comment by Codex66** [comment]
oh im using technic

**Comment by awangatboo** [comment]
Try normal minecraft and see if that helps.

**Comment by awangatboo** [comment]
I am not sanpetra and no issues.  I will go to my W/G and logout to make sure it is not a login issue.

**Comment by Codex66** [comment]
ok. can for some reson i cant inatll normal minecraft... it says unable to update launcher when i try to install.

**Comment by Codex66** [comment]
ok i can log on without mods

**Comment by awangatboo** [comment]
OK good deal.

**Comment by Codex66** [comment]
ya its just the mods that crash me for some reson
