### ISSUE TITLE
Powerboosts

### ISSUE THREAD

**Issue by Laserlance141** [StarQuestMinecraft/StarQuestPublic#714]
Whenever i try to boost power, I get the message that money was removed from my faction's bank, but no power is added, and then if i try to remove existing power boosts, the boosts do not get removed. This really is concerning me because i have buildings outside of faction land, and with this weekend's update they would get deleted.

**Comment by starquestbugs** [comment]
I have no idea. Faction land is buggy. I can't build in fac land, but I could place a Cryopod sign there and I could I interact with it, but It didn't count as a sign and I kept respawning in alpha. What have mods said about this?

**Comment by Laserlance141** [comment]
How does that involve powerboosts?

**Comment by awangatboo** [comment]
It takes money from the faction make sure the faction back has enough money when you purchase.  This is if you are " /powerboost faction # "

**Comment by Laserlance141** [comment]
My fac has a bank of around 80k, the problem is that the powerboosts are not applied to the faction, I can cancel more boost than I have, and buy without gaining any power.

**Comment by lucon1** [comment]
similar problem (same as my previous one) I can't "add" powerboosts. if i buy 30,one time, then i buy another 20, it still takes the money, but i go down to 20 extra power, instead of 50.  Also i noticed, that bonus power is not removed fully when you can't pay taxes, (it's only been 1 day)

**Comment by awangatboo** [comment]
@Laserlance141 did you use the personal power boost or the faction one?  /powerboost faction (ammount)?  I talked with someone else was trying to put there faction name in as the first argument after /powerboost and it was giving issues.  I just want to make sure this can re re-created as when I have tried it I can not re-create the bug.

**Comment by Laserlance141** [comment]
I figured out what the problem was, I just was selecting the same boost amount each time, and since consecutive boosts don't stack, nothing happend.
