### ISSUE TITLE
Powerboost Broken

### ISSUE THREAD

**Issue by Evancooldude** [StarQuestMinecraft/StarQuestPublic#715]
The issue here is simple, yet hard to explain

The problem: When one purchases a powerboost (tested using faction powerboosts) It overwrites your current powerboost number instead of adding to it. If I have 2 powerboosts, and I say /powerboost faction purchase 1       , It sets my faction powerboost level to 1 instead of three,

Unclear if this is intentional or accidental, but it does take your money regardless

**Comment by awangatboo** [comment]
I am not really sure this is a bug or just bad documentation about powerbost.

**Comment by awangatboo** [comment]
The staff needs to come up with better documentation on how powerboost works.

**Comment by awangatboo** [comment]
Evan can you update the wiki with info about powerboost?

**Comment by Evancooldude** [comment]
Sure, I'll look into making the wiki page clearer about how it works. Did we change how this works at all, or is it still on the "whatever you buy sets your powerboost to that" system?

**Comment by awangatboo** [comment]
Closing all bugs in preparation for SQ 4.0.
