### ISSUE TITLE
Fighter Updgrade Not Activating

### ISSUE THREAD

**Issue by brickworm2012** [StarQuestMinecraft/StarQuestPublic#716]
I bought the fighter_guns1, and could not add another cannon to my ship, which already had two. Either I'm missing something, or the money should have been spent on philanthropy.

**Comment by awangatboo** [comment]
What is your in-game name?  Have you made sure you bought it?  /cert list to make sure you bought it.

**Comment by starquestbugs** [comment]
Hmm. Odd. Have you tried upgrading then again (if you can, only have storage upgrade)

**Comment by awangatboo** [comment]
I know others have guns +1 and it works.  Could you try again?

**Comment by brickworm2012** [comment]
Terribly sorry for the delay, but any way I put it, it seems functional now.
