### ISSUE TITLE
Powerboost Glitch - This is different than my previous post - Urgent

### ISSUE THREAD

**Issue by Evancooldude** [StarQuestMinecraft/StarQuestPublic#717]
In a previous post about powerboost, I mentioned that powerboost's purchasing was either broken or simply designed in a way that wasn't intuitive. This is an entirely seperate, and extremely urgent, post.

Several days ago, I attemped to get more powerboosts. My base had 4, and I wanted to up it to 8 so that, if I died, my base couldn't be claimed over, and I could expand more. I did /powerboost faction purchase 8, since powerboosts currently overwrite instead of adding when purchased, and I then had 8 powerboost, for a total of 18 faction power (I checked using /f f, I had 18 power, 8 powerboost), for my 14 land. I planned to add more ship parking space to my base. I logged on the next day later that night since I was busy with homework until then. I tried to buy another chunk of land, and discovered that I couldn't because I didn't have enough power. I did /f f Gallifrey (My faction) and discovered I was back to 4 powerboost! How this happened, I don't know, but I can only speculate that at some point my powerboost quantity reset (Possibly due to the reset of several worlds? This was during that time)

Now, I purchased 8 powerboost again, but didn't expand my land just yet, afraid that the glitch would repeat itself and I'd be stuck with too little power to support my land. I completed a contract or two, checked my faction power again, and it was still 18 with 8 powerboost. I logged off for the night.

Next day, today, I logged on since I didn't have too much homework. My powerboost was still working fine at 8, and so I assumed it was just a temporary glitch caused by the worlds resetting or something along those lines (My base wasn't on a planet that was reset (I'm on Loyavas), but I figured perhaps during the server restart and file transfer something got screwed up)

I went ahead and flew around, completed contracts, when low and behold the phone rings and I find out my dad got into a car accident and he's going to hospital to get xrays to see if anything is broken. I'm sitting in space during this, and so to avoid having anything stolen while I was on the phone, I quickly broke apart the shipsign block, destroying the shipsign, or so I thought. I talked on the phone with my mom, who was already with my dad, and when I came back I was under attack by JUSA. I came back too late, and was quickly killed. Now, this was my fault, and I'm not asking for a refund on the ship or my stuff because I was stupid enough to stop in space, even if it was because my dad was in an accident.

I respawn, and everything is dandy, until JUSA shows up at my base. I tell him to go away, figuring he is here to try and shoot at me to make his point. I check my faction power just to confirm that there's no way he could get me... and I find my powerboost is back at 4. Before I can do anything, JUSA digs through the ceiling. I tell him to stop, that there's been a glitch, and he just makes smily faces in chat and begins to destroy my farms before my eyes. He  enemies my faction, kills me, locks me in my cryo before overclaiming it, and that's where I just logged out and posted on the forums for help. I am posting a more detailed account here, in the hopes that my base could be restored.

As for why exactly this glitch occured, I don't know. I thought the first time that it was simply an issue with the world resets, and it the issue as a whole might've started there. I'm not an expert in how this system works like you Devs are, and so that's the only thing I can think of. As for why it would've messed up my attempts to purchase powerboost after the reset, I don't know.

I know the above is a lot to read, and so thank you for reading it. As for what I am requesting:
First and foremost, a fix for the bug, if one exists. I don't want what happened to me to happen to anybody else.
Second, I beg of you to restore my base to how it was. Is there any way this can be done? Is there any sort of backup from the world resets, or backup files in general, that would allow my base and it's contents to be put back to the way they were?

I don't want JUSA to be banned for this. As much as I think he should've heard me about before destroying my base, he wasn't breaking the rules by raiding me, and so there is really no reason to punish him. If it isn't possible to restore my base to it's completion, then I'm afraid I don't know what to do. I don't have pictures of all of my stuff, and there's no way to prove that I actually had what I told you I had. I had two rooms of chests, containing stuff like almost a stack of diamonds, boat loads of iron, building materials, diamond tools, tons of crops. I had a piston vault door, a max size machina farm, an automatic melon farm of my own design, not to mention my ship parked on top (Unclear whether that has been damaged) my ship replicator, emerald tree farm, elevator system, and so much more that has most likely been damaged or stolen entirely.

As you can see, I had a lot of stuff. I simply don't want to start over and try to regain everything I had. If there's no way to restore my base, and if you won't refund my stuff, which I can understand, then I'm most likely going to quit. That's not a threat, and it's not supposed to mean anything to you. I'm simply saying that if I can't get this glitch's damaged restored, I don't want to continue playing.

Thank you for reading this monster. Please, help me Dibujaron, You're my only hope!

**Comment by awangatboo** [comment]
Thanks for the info.  This is great detail.  I am not sure if you know this but I am the first line of defense in bugs before they go up the chain.  This was a great deal of info but if you can remember what dates these things happened it would be great as the Dev's or the Helper can go through the logs.  I will bug one of them to take a look at this but the dates would be good.

**Comment by Evancooldude** [comment]
hmmm. I know that the first issue was noticed on the day after the Planets were reset, whenever that was.... Also, the base overclaiming occured today, 9-17. I'll think and see if I can come up with any more info for you. Thank you for assisting.

**Comment by awangatboo** [comment]
I bugged the Helper.  He is looking into it but said that it is really unlikely there is any way to get  your base back the way it was.  But depending on how things work out some help might be able to be provided.

**Comment by Evancooldude** [comment]
Okay, thank you! I really hope I can get back at least some of my things

**Comment by Evancooldude** [comment]
I understand the difficulty in getting my things restored, but since they were lost to a glitch, I'm really hoping that we can work out some work of way to, if not instantly, then perhaps have me assist a mod in putting my base back in order via the mod's assistance or some other solution. I just hope we can work out a solution that puts me back to where I was.

If it would help, I can compile a list of the things I lost, once a mod can remove all the claims covering my base so I can reclaim it and begin an inventory

**Comment by JUSAPlayer1** [comment]
Please tag me on this for future posts. I don't think it is a glitch, however if this proves to be, come by my place on uru and I'll get you some gear to get back on your feet. I don't want to have raided a base due to a glitch, and everything that I didn't take is already sorted and put away. As for your base, I unclaimed it all and I believe Yargon may have claimed it for himself. Regardless please keep me posted on this.

**Comment by Evancooldude** [comment]
Okay, thanks. If a mod could at least message me and help me to get my base claims back, that would be great

**Comment by awangatboo** [comment]
It will all be up to what QuietHelper finds.  Still waiting to here back from him.

**Comment by Evancooldude** [comment]
Okay, thank you. I might not be around for much longer tonight, but please, if it's decided that I can have my stuff back, or at least my base claims, could you or somebody remove the claims over my base and reclaim it for me? If i'm around, I'll reclaim it myself, but I don't want people to come back and claim over it after you unclaim it, if you do decide to do so.

**Comment by Evancooldude** [comment]
In addition, it seems like getting my faction magically restored is unrealistic. However, I obviously know what my faction looked like, and I have no problem completely the repairs and rebuilding myself, assuming that a mod will unclaim the claims on top of my land. However, I suspect that I will have lost a fair amount of my stuff. The bad news is, I don't have photo evidence. Now, I can completely understand if you are therefore unwilling to give me anything back. The good news is, I know almost every item in my base down to the last piece of cobblestone. This is due to the work I've been doing lately. I had a large bank of random chests filled with random stuff, so I began to create a chest room. I stuck all of my stuff into that, but then I decided that I wanted to make it automatically sorting via machina. I created a different room (My main vault), and constructed and moved all my items into it. However, I discovered that my assumption of how machina pipeline worked was flawed, and that that base design wouldn't work. So I switched to hoppers. I rearranged the chests, only to discover that the amount of hoppers necessary would be too many. I then went to a manual sorting system. The end result is, I've hauled every item in my base 4 times in the past 3 days, so I can tell you exactly what I had. If you agree to restore my claims, I can write up a full list.

**Comment by awangatboo** [comment]
From QuietHelper - “I talked to Dib and we both could not find anything in the logs. The issue is that the /powerboost command does not log like we would like it to.  There could have been a bug but we can not find it.  Because of this I can come on and help him some but seeing that we are not 100% sure any faction overclaims will not be undone.  In addition any armor unless screenshots are provided will not be restored but some Iron and Diamonds will be helped out with.   In addition timelord should delete his faction and recreate it just in case there is something wrong with it in the DB.”

**Comment by Evancooldude** [comment]
Okay, if I understand this correctly, I'm not getting my base back... I'll delete my faction and recreate it I guess... Don't suppose I could get a 5k refund for that? Also, some supplies will be given to me? I understand that you can't give me back my base, but could I request that, once i get a new base going (hopefully tomorrow) I be given some supplies to compensate for the huge quantity of stuff I lost.

Thank you for all you help. I accept the decision you've reached, and I appreciate you looking into it.

**Comment by awangatboo** [comment]
You can ask QuietHelper when you see him about the 5K.

**Comment by awangatboo** [comment]
I am going to leave this open until you or QuietHelper Tell me to close the ticket.

**Comment by awangatboo** [comment]
I have been told to mark this case closed.

**Comment by Evancooldude** [comment]
Thanks to the amazing staff, I have been able to begin rebuilding from this bug. Thanks to all of you for your hard work and great help!
