### ISSUE TITLE
Ship fused to landing pad on Eco Station: Alpha North

### ISSUE THREAD

**Issue by Stilettos-anda45** [StarQuestMinecraft/StarQuestPublic#718]
It seems my ship is fused to the World Guard-protected landing pad...and I am trapped in the ship since I can't break blocks.

When I try to control my ship, it says there are too many blocks.  Also says block at  -104, 66, -3504 should be air (that wool was always part of my ship).  So when I try to remove the block, "Hey!  Sorry, but you can't break that block here."  

Now I am trapped and can't even play, but just stare out the window of my ship, like a jail cell, and read the chat.  That's all I can do now.

-Stilettos_anda45

**Comment by awangatboo** [comment]
what planet?

**Comment by Stilettos-anda45** [comment]
It's Eco Station: Alpha North

**Comment by Stilettos-anda45** [comment]
Thanks for the fix.  I appreciate it.
