### ISSUE TITLE
World reset bug

### ISSUE THREAD

**Issue by Millibyte1** [StarQuestMinecraft/StarQuestPublic#719]
I just logged in for the first time in about a week, and my sheep farm that was in claimed territory on Eratoss has disappeared; I assume this was due to the world reset on Tuesday. It had pretty much everything that I owned on the server, and that was quite a lot. Is there any way that the four chunks the sheep tower consisted of could be world-edited back in from the old map? The farm was located around x:1800 z:100

It also contained about 500 sheep. They long to return to their 32x32m segregated pens; do it for the sheeple!

**Comment by awangatboo** [comment]
All Sheep were deleted during the world reset.  You will need to figure that out on your own.  Ass for your base I know everyone else has their base transfer.  when you logged in where were you?  In rock?

**Comment by Millibyte1** [comment]
I was right outside of where my claimed land was, but there was no tower in front of me.

Also, I was just joking about the sheep, I already knew that all of them were gone.

**Comment by awangatboo** [comment]
Was part of your base there but just not the sheep tower?

**Comment by Millibyte1** [comment]
The only thing that was there was the ladder that lead down to the underground entrance. Here's a screenshot:
![2015-09-18_22 55 40](https://cloud.githubusercontent.com/assets/12040916/9974340/83e888e0-5e58-11e5-9a60-0f43cd6a6e0d.png)

**Comment by awangatboo** [comment]
Is there a chance that yous ran low on power and those 4 chunks got unclaimed?

**Comment by Millibyte1** [comment]
No; I had a powerboost, and they were still claimed when I logged on

**Comment by awangatboo** [comment]
what faction was it?

**Comment by Millibyte1** [comment]
Lantean

**Comment by awangatboo** [comment]
Are you the only one in the faction?

**Comment by awangatboo** [comment]
How much powerboost do you have and how much should it be?

**Comment by Millibyte1** [comment]
Yes; the last other member in it, Exrage0, was auto-kicked two weeks ago, and so I bought the powerboost to prevent overclaiming

**Comment by Millibyte1** [comment]
I have a powerboost of 10 points, which is the correct amount

**Comment by awangatboo** [comment]
how much power is used right now?

**Comment by Millibyte1** [comment]
15 claims out of 20 power

**Comment by awangatboo** [comment]
so you were at 19 of 20 before the reset?

**Comment by Millibyte1** [comment]
I was at 15 before the reset; I still have the 4 chunks the sheep farm consisted of claimed, they just didn't carry over for some reason

**Comment by awangatboo** [comment]
So the location where the sheep farm was is still in your current faction land?

**Comment by Millibyte1** [comment]
Yes

**Comment by awangatboo** [comment]
I can ask Dib about this but seeing that everyone else had no issues I am not sure how this will go over.

**Comment by Millibyte1** [comment]
Alright, thanks.

**Comment by Siigillum** [comment]
Base was unclaimed by me about 1 hr before reset i think. Power level allowed of unclaiminig that ugly tower.

**Comment by Siigillum** [comment]
If that was built properly like BosaTergur i would have overclaimed myself and removed claims after reset. But it basically looked like crap.

**Comment by Siigillum** [comment]
I hope this helps.

**Comment by Siigillum** [comment]
As far as i remember the power level shortage allowed just for unclaiming the tower and nothing else. 4 chunks i think. 

Build proper bases please so people can consider saving that from things liek that.

If not the reset i'd massdrive that myself.

**Comment by awangatboo** [comment]
OK so this was not a bug.  Thanks Siig for clearing things up.

**Comment by Millibyte1** [comment]
I'm confused as to why the chunks were still claimed when I came back, but okay then. Thanks for the info.
