### ISSUE TITLE
Glitch on entry

### ISSUE THREAD

**Issue by greatwazoo** [StarQuestMinecraft/StarQuestPublic#723]
Today entering nal at ~10:00pm EST My ship a fighter carrying one other person began glitching. I was standing in my ship and continuosly falling out, then staying in and moving around spazzmatically. Eventually the me and my partner fell out of the ship, to our deaths.

**Comment by awangatboo** [comment]
We have seen this issue.  It happens from time to time.  See a Gm for a refund.
