### ISSUE TITLE
Ship phasing problems

### ISSUE THREAD

**Issue by Mindaugas3** [StarQuestMinecraft/StarQuestPublic#724]
Today I had 2 cases of bad autopilot, accompanied with massive (probably server side, because in 1st pic a player was trying to use boarding ramp) lag.
1. The ship autopilots and phases through stone, then it replaces any stone from the mountain it had phased in. (It is accompanied with "kissed the wall" spam)(Occourence in images 2,3)
   Image 2 shows head slot covered with stone which wasn't replaced by sign/ship block.
   Image 3(take it with grain of salt, ANOTHER bug occours when ship blocks are invisible), but where's supposed to be clay armor/wool the blocks were invisible, revealing stone.
2. The ship autopilots and phases through world border without even stopping(happened in Avaquo north of RazeTaskForce base, shown in images 4 and 5). In image 4, Siigillum is talking how he ALSO lost a ship due to this bug. interesting interaction - after 5 minutes, ship shield activated BEHIND a world border.

The fighter is in first image, flying through Avaquo.

All sources: http://imgur.com/a/yEotG

**Comment by awangatboo** [comment]
Do you have an idea as to what time this might have happened?  I have a hunch this is one of these strange issues that will take forever to find.

**Comment by Siigillum** [comment]
Worldborder not stopping the autopilot most likely, then ship flying further while pilot stays at the border. That's what is happenign there usually.

**Comment by awangatboo** [comment]
Closing all bugs in preparation for SQ 4.0.

**Comment by awangatboo** [comment]
Closing all bugs in preparation for SQ 4.0.
