### ISSUE TITLE
Unique Block Drop - Protected Regions

### ISSUE THREAD

**Issue by Evancooldude** [StarQuestMinecraft/StarQuestPublic#726]
Whilst scrapping a fallen faction, I came across a room that was protected by a worldguard. I noticed it when I tried to break a hedge in the room, and I got the usual message of "You can't break this block here." I checked the region info, confirmed it was a WG, and was about to leave when I noticed a gray wool item on the ground. This was on Loyavas, where spruce leaves drop gray wool. I tried breaking the block again, and after several times "breaking" it, it dropped another piece of gray wool. The unique block drops system that causes gray wool to drop is evidentally not taking into account whether the block was actually broken. It's simply detecting when the block is "Broken", regardless of if the player is able to break it. This bug could be abused to farm large amount of wool - Grab a friend, have them make a wg with a block of spruce leaves in it, and sit there breaking it over and over for gray wool.

**Comment by awangatboo** [comment]
I know this was fixed for mudrooms on Cet.

**Comment by awangatboo** [comment]
Closing all bugs in preparation for SQ 4.0.
