### ISSUE TITLE
How to Pilot Leight_Freighter?

### ISSUE THREAD

**Issue by lachie07** [StarQuestMinecraft/StarQuestPublic#727]
So I just got Leight_Freighter_Pilot (thingy), and I have no idea how to place the main core sign. On fighters you put "Fighter", and on Shuttles you put "Shuttle", but what is it for Leight_Freighter??

**Comment by awangatboo** [comment]
This is not a Bug.  GitHub is for bugs.  Please ask people in game or check on the WIKI.  

http://starquestmc.wikia.com/wiki/StarQuestMC_Wiki

In addition you can look at this spreadsheet with the list of abbreviations.  

https://docs.google.com/spreadsheets/d/1TZr1UZaBFxGqv0SWCOhyp7zoPy2bI9EVVExHYZsWUaw/edit
