### ISSUE TITLE
Info Outdated

### ISSUE THREAD

**Issue by brickworm2012** [StarQuestMinecraft/StarQuestPublic#728]
This isn't exactly a bug, but the info talks about outdated elements, such as refugees signing up.

We've been complaining for a while, it's only now I realized we should probably tell someone who can do something.

**Comment by awangatboo** [comment]
Refugees still have to sign up.  The sign up to get from guest [g] to player [p].  What needs to be changed?

**Comment by awangatboo** [comment]
I need more data before I can Bug a dev / jr, dev about this.  Please put more info in or this will be closed.

**Comment by Mindaugas3** [comment]
Worldguard is supposed to have no PVP while info tells users to set no PVP up.

**Comment by awangatboo** [comment]
World guards can have no PVP or PVP it is up to the user.

**Comment by awangatboo** [comment]
Anything else so I can bug the staff about or should I just close this issue.

**Comment by lawrencethefrog** [comment]
Please could you produce a comprehensive list of outdated info to fix so that we know what you mean.

**Comment by awangatboo** [comment]
If we do not hear back any specifics in a day or so I will close this bug.
