### ISSUE TITLE
Tallimar - Improper ore distribution

### ISSUE THREAD

**Issue by Mindaugas3** [StarQuestMinecraft/StarQuestPublic#730]
Talimar is supposed to have no coal. I find that there is vanilla coal, and its very easy to find.
Also it is supposed to have high lapis. I find very low lapis there. Please fix.

**Comment by awangatboo** [comment]
Many planets have not have the resources 100% they way the Wiki says.  We can change the Wiki but I think that is all that will happen.

**Comment by awangatboo** [comment]
There are not current plans to reset and change planet ore distribution.  If you want to help out update the Wiki please.
