### ISSUE TITLE
Trapdoors changing halves upon planet entry/exit

### ISSUE THREAD

**Issue by Mindaugas3** [StarQuestMinecraft/StarQuestPublic#731]
Wooden Trapdoors always change half to bottom, regardless if it was top or bottom. This bug makes ships less attractive to look at. 

Pending test with iron trapdoors.

**Comment by awangatboo** [comment]
I think it is the same with Iron trap doors.

**Comment by awangatboo** [comment]
Oh and I assume you are talking about when you use them on a ship as I do not think this is an issue if it is not flying.

**Comment by Evancooldude** [comment]
Already been reported. Once I get acquainted with our good friend movecraft I'll look into this

**Comment by Millibyte1** [comment]
Has this been fixed?

**Comment by awangatboo** [comment]
Closing all bugs in preparation for SQ 4.0.
