### ISSUE TITLE
Too Many Ores

### ISSUE THREAD

**Issue by brickworm2012** [StarQuestMinecraft/StarQuestPublic#733]
I have found diamond and emerald on Eratoss at the lowest possible level. They spawned in similar amounts to vanilla.

**Comment by awangatboo** [comment]
i will check with Dib but I do not think they will reset the planet again.

**Comment by brickworm2012** [comment]
I actually wouldn't mind. _grins_

**Comment by awangatboo** [comment]
Currently no plans to reset any planets.
