### ISSUE TITLE
Piracy / privateeringrewards reballance.

### ISSUE THREAD

**Issue by Siigillum** [StarQuestMinecraft/StarQuestPublic#735]
Suggested reballance.

1-2k c / datacore in alpha contract.

5k max / datacore in beta.

10k max / datacore in gamma.

Or even half those numbers. Or instead of c add some rewards like diamonds, sponges etc.

Current rewards are a bit broken. 100k c for4 fighter datacores.

And i have almost 2 doublechests of those random cores... So just saying, i am nerfing myself actually too. 

Money should come from trading and smuggling primarily.

**Comment by awangatboo** [comment]
I know management are looking into changing the rewards from the system.

**Comment by awangatboo** [comment]
Closing all bugs in preparation for SQ 4.0.
