### ISSUE TITLE
World reset, cryopod bug

### ISSUE THREAD

**Issue by Architect752** [StarQuestMinecraft/StarQuestPublic#736]
Around 8:00-8:20 PM EST RC3371 died and was sent to an empty spot around -520 -80 on Grun despite not having any cryo set.  I teleported over at his request and spoke with him.  It seems that he had a Wg at or nearby the spot but had not been there for more than a month and as such it was wiped with the reset.  Even after using /removehome the spawn point persisted, verified by RC3371 using /cryocheck.

The only thing I can surmise that could have caused this is that he had a cryopod at his Grun Wg and the reset of Grun wiped the structure but not the spawn point and somehow rendered it unable to be removed via /removehome.

**Comment by awangatboo** [comment]
He at least needs to have his re-spawn location removed.

**Comment by awangatboo** [comment]
Did this get resolved?  Can we close the bug?

**Comment by awangatboo** [comment]
Closing this bug as no one has responded to it in a long time.
