### ISSUE TITLE
Regen enabled in Gamma

### ISSUE THREAD

**Issue by Kyle98martin** [StarQuestMinecraft/StarQuestPublic#737]
Gamma has normal ship regeneration rather than the no regeneration that it's supposed to have. Have not tested beta regen but I've heard it is working fine

**Comment by awangatboo** [comment]
@Quithelper

**Comment by QuietHelper** [comment]
Someone overwrote the config file.  It has been fixed.

**Comment by Siigillum** [comment]
Must have been an insider job. Heh

**Comment by awangatboo** [comment]
Seeing that Quiet said he/she/it fixed it I will close this ticket.  Please contact me if it needs to be reopened.
