### ISSUE TITLE
Ship Shields Useless For Me

### ISSUE THREAD

**Issue by Stilettos-anda45** [StarQuestMinecraft/StarQuestPublic#738]
My ship shields tell me , "Your starship's shield is fully warmed up and is providing full protection," and after waiting for this message to appear in chat, I happily go about my business.  Yet, my ships get griefed and stolen continuously.  This has happened numerous times and it's a bit much to have to keep running into this problem.  I'd like to have the same basic tools everyone else has at their disposal to protect their gear.  

Please also see my post entitled "Cannot Use Lockette."

**Comment by awangatboo** [comment]
SQ is not friendly to players with long names the best solution is to go change your name to get it to be smaller.  For your private signs see a mod and see a manager for W/G

**Comment by PandoraKid102** [comment]
Do shields not kick in because of the long name or because you are piloting another ship and the shield goes away?

**Comment by awangatboo** [comment]
Is this still an issue or can we close the bug?

**Comment by Millibyte1** [comment]
This is not an issue, this is user error. My name is too long to fit on a sign, and it autofills.

Also, you don't have to write your name on the sign. If you are the owner of the craft, you're automatically added to the shield.

**Comment by Evancooldude** [comment]
Ship shields use UUIDs, which are separate of your username and it's size. There is no reason that comes to mind why your ship shields wouldn't be working and others would. Please remember that if you edit your ship in any way it can interrupt the process, including opening/closing docking tubes, boarding ramps, doors, etc. Also, if you pilot any other ship at any point, this can disrupt the ship shield, even if the newly piloted ship doesn't have a shield.

**Comment by awangatboo** [comment]
Closing as no input has been given back by the user that created this bug.
