### ISSUE TITLE
Cannot Use Lockette

### ISSUE THREAD

**Issue by Stilettos-anda45** [StarQuestMinecraft/StarQuestPublic#739]
The standard player has the ability to use Lockette signs to guard against access to their doors and possessions.  I do not have that same luxury.  When I place a simple [private] lockette sign, I am locked out.  I have had to seek GeneralTyler's help in removing my lockette signs.  

I cannot lock my ship doors, my chests, or anything else with Lockette...unless I don't want it anymore because I won't be able to access it from that moment onward.  

It gives me the following message: "This container has been claimed by Stilettos_anda45.  You don't have permission to use this door."  

Is SQ using the most recent version of Lockette?  Version 1.8.20 was released on July 29, 2015 and offers UUID support.  It also checks for past names used (although I have never changed my name).  

I'd like to be able to use the same simple tools that other SQ players use to protect items and ships.  Please see my other post entitled "Ship Shields Useless For Me." 
These two issues combined leave me a vulnerable, disadvantaged, and regularly taken advantage of, so it's starting to kill the fun for me.

**Comment by awangatboo** [comment]
SQ is not friendly to players with long names the best solution is to go change your name to get it to be smaller.  For your private signs see a mod and see a manager for W/G

**Comment by Evancooldude** [comment]
As far as I know, the process of changing all plugins to support longer usernames is, at best, impractical. Perhaps some plugins will get support, but your best bet is a username change.

**Comment by Millibyte1** [comment]
As a player whose username is too long to fit on a sign, I can say that this is not actually an issue. If I type "evanaesarcaes" on a sign, which is the maximum length of a line of text on one, it will let me use the sign. I believe this is caused by user error.

**Comment by awangatboo** [comment]
I am closing this one as I know that this user has changed their name to a shorter name.
