### ISSUE TITLE
Courier weapon cert

### ISSUE THREAD

**Issue by PandoraKid102** [StarQuestMinecraft/StarQuestPublic#740]
This is pretty much a low priority but I have two of my courier certs on guns (courier_guns1 and courier_guns2). I cannot remove them from the current certs as they return an error (Error: cert not found.) and cannot buy 2 new ones.

**Comment by awangatboo** [comment]
This is an issue.  I have the same problem.

**Comment by Siigillum** [comment]
Should have removed earlier, teheheheh ehehe hehe haha hehe.

**Comment by awangatboo** [comment]
Dib told me he fixed this and it should go into place after 10/15 restart.  After that try removing the cert.

**Comment by Millibyte1** [comment]
Can anyone confirm that this has been fixed?

**Comment by PandoraKid102** [comment]
It is fixed. "This cert no longer exists so you were not penalized for it's removal. Cert removed."
Closing issue.
