### ISSUE TITLE
Worldguards not disappearing after the owner hasn't came on in a month.

### ISSUE THREAD

**Issue by icekoob** [StarQuestMinecraft/StarQuestPublic#741]
So I had a clean up and I found 3 wgs near Astrakane. One was a ship shield and the other 2 were illegal wgs. The ship shield and one of the illegal wgs aren't disappearing even through the owners haven't logged on in months.

**Comment by awangatboo** [comment]
W/G do not work like that.  You will need to get a RM-Mod or higher to remove the ship shield and if it was an old town that fell then ask the same RM-mod or higher to remove the other W/G's.  The 30 day window is only when a planet is going to be reset.
