### ISSUE TITLE
Protection 4 enchantment decreasing/preventing suffocation in space.

### ISSUE THREAD

**Issue by Siigillum** [StarQuestMinecraft/StarQuestPublic#742]
Protection 4 enchantment reduces the suffocation damage as any other damage. Other enchantments or unenchanted armour does not reduce suffocation damage.

I suggest either fixing the suffocation damage type or changing it so only useless enchantments like blast protection reduce it. 

Right now prot 4 efectively allows for very long space-floating rendering spacesuits somehow not very usefull compared to diamond prot 4 gear.

**Comment by GingerWalnut** [comment]
I think that I have fixed this bug and I am waiting for it to be put in production.

**Comment by Siigillum** [comment]
ETA on that so i know when to test?

**Comment by Evancooldude** [comment]
We junior devs don't have the ability to put things into use, and the Dev team has different time zones, so things like this can take a few days before the line of communication finally gets through and things get added. Things like this will generally be put on the server within two days of a post on here, so try it then.

**Comment by awangatboo** [comment]
From what I have been told the changes that were made have it where proc 4 with respiration take no damage.  I think this is the wrong way so they will need to fix it again.

**Comment by Siigillum** [comment]
I was refering to plain protection 4 without respiration enchantment.

The respiration 3 was fixed earlier and i assume it was fixed the way that now respiration 3 does nto work but the damage is soaked up by protection...

**Comment by awangatboo** [comment]
Ginger has thins one been fixed?

**Comment by Siigillum** [comment]
Possibly it has been fixed. Need to compare the regular vs prot 4 damage.

**Comment by GingerWalnut** [comment]
This has been fixed.

**Comment by Siigillum** [comment]
Fixed, works awesome. We love you.
