### ISSUE TITLE
Cryopod glitched

### ISSUE THREAD

**Issue by Travja** [StarQuestMinecraft/StarQuestPublic#743]
I recently was in a space fight, my cryopod on my ship was destroyed. Since then, I have gone back to base and set up a new cryopod on a new ship. Sadly, this cryopod doesn't work. When I do /cryocheck it says that I don't have a cryopod even though I just got a message saying that it has been updated. So I'm pretty sure all that needs to be done is a quick column clear for my player on the SQL database ;) Thanks guys!

**Comment by Evancooldude** [comment]
I can't remember what command it is, but it's one of these three:
/removehome
/removespawn
/removecryo
One of those should remove your spawn, allowing you to set a new one. Have you tried this, and if so, did it do anything?

**Comment by Travja** [comment]
I didn't try those, but I did get it resolved. Turns out, all I had to do
was remove a current cryopod sign and place it again. xD So go ahead and
mark this as solved!

On Tue, Oct 20, 2015 at 3:07 PM, Evancooldude notifications@github.com
wrote:

> I can't remember what command it is, but it's one of these three:
> /removehome
> /removespawn
> /removecryo
> One of those should remove your spawn, allowing you to set a new one. Have
> you tried this, and if so, did it do anything?
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/StarQuestMinecraft/StarQuestPublic/issues/743#issuecomment-149703451
> .

## 

There is a difference between existence and sentience.

**Comment by Evancooldude** [comment]
I don't currently have the ability to mark it as solved... I'll ask a manager to mark it. Thanks!!
