### ISSUE TITLE
Problems with world guard plugin

### ISSUE THREAD

**Issue by conkleon** [StarQuestMinecraft/StarQuestPublic#744]
I just built a house on a planet and then a full diamond guy came in and killed me. I am sure that i had all my world guard perimeter working pls look into it because it is a real problem. You can check it out my username is conkleon and my world guard base its named ctmobase.

thanks for hearing me out 
--conkleon--

P.S. 1)sorry for my english if i messed up anything
        2)very nice server

**Comment by awangatboo** [comment]
What planet is this W/G on?

**Comment by Evancooldude** [comment]
Does world guards list command not automatically search bungees worlds?
Thought it did... If it doesn't, then we'll need the world it's on

**Comment by Siigillum** [comment]
Do not forget to set pvp flag to OFF/DENY. By default pvp is on in worldguards, needs to be manually changed to no pvp.

**Comment by conkleon** [comment]
well it is on nalavor

**Comment by QuietHelper** [comment]
I TP'ed to the location where your ship was and can not find any other world guard around that location.  What is the name of the region?

**Comment by conkleon** [comment]
sorry I just found out what happened my friend (that was also an owner of it) deleted the region so he could add some more space but he didnt re-activated it so our bad sorry that i wasted your time pls delete this post

**Comment by awangatboo** [comment]
case closed
