### ISSUE TITLE
Contracts cancelling in space possible.

### ISSUE THREAD

**Issue by Siigillum** [StarQuestMinecraft/StarQuestPublic#746]
I was chasing Goldie today. In Gamma he was wanted. In alpha he was not suddenly. I expect contracts can be cancelled in space again.

**Comment by awangatboo** [comment]
I thought they could be canceled in space but if you were wanted and canceled one you would say wanted for an hour.

**Comment by Siigillum** [comment]
Might have been an issue then. Needs further testing in case of server/system switch.

**Comment by Evancooldude** [comment]
If you would test this out, it would be greatly appreciated. It's possible that the 1-hour tag doesn't carry over yet, in which case we'll need to fix that. Any more information or testing you can give us is appreciated.

**Comment by Siigillum** [comment]
1 hr tag does not carry over through systems.

**Comment by awangatboo** [comment]
Oh wow that is a big bug.

**Comment by GroxTerror** [comment]
Another interesting thing is nearly making yourself invincible in base sieges in alpha against wanted guys. Just accept the contract, shoot a bit, delete it. Repeat till satisfied.

**Comment by awangatboo** [comment]
Closing all bugs in preparation for SQ 4.0.
