### ISSUE TITLE
Charcoal Not Fueling Treefarms

### ISSUE THREAD

**Issue by PatchyFox** [StarQuestMinecraft/StarQuestPublic#747]
Unsure if intentional, but charcoal is not able to be used as fuel in tree farms. As coal is a non-renewable resource, it seems odd that it's the only fuel that can be used.

**Comment by Siigillum** [comment]
Intentional. Only normal coal works.

Solved? Close?

And coal is renewable. Skeles on Avaquo.

**Comment by awangatboo** [comment]
Siig is correct
