### ISSUE TITLE
Entering Rakuria's Atmosphere

### ISSUE THREAD

**Issue by QuantumVelocity** [StarQuestMinecraft/StarQuestPublic#748]
There is a glitch when entering Rakuria's atmosphere where the player is thrown out of his/her ship and drops to their death. Their ship is left hanging in the air, fused with many other ships that have already been abandoned by their doomed owners. I myself have lost two ships, both with cargo in them and I have also lost my inventory items. 
The area of where this occurs is at coordinates:
x: -1660
y: 191
z: 99

On the dynmap, you can clearly see the several fused and destroyed ships. This should be considered a serious threat as players will be unable to return to Rakuria after a contract or a visit to another planet, without dying and having to relocate what's left of their destroyed ships.

**Comment by awangatboo** [comment]
This can happen on any planet at any time.  It is not just Rakuria.  Ask a mod about getting a refund.  Reference this ticket.

**Comment by QuantumVelocity** [comment]
Oh wow, this is terrible! Is it going to get fixed at any point in time? It happened twice in a row for me and a friend.
