### ISSUE TITLE
Blasters "Duping" Visual Glitch

### ISSUE THREAD

**Issue by GroxTerror** [StarQuestMinecraft/StarQuestPublic#750]
So while toying with the new automatic blasters, I found some cool stuff.

Leaving the blaster in its auto-fire mode, then opening your inventory and moving the blaster, creates an interesting effect. The blaster will move back into its original spot once you close your inventory. Opening your inventory again will show the blaster where you moved it. However these copies disappear after opening a chest or dropping one of them. Possible fix: make it so they stop shooting when you open inventory.

I also experienced a different effect. After firing my automatic blaster, then turning it off and moving it into my inventory, it did something strange. When right-clicking in the slot (slot 6) where it previously was, the blaster jumped back into the sixth slot and began to fire. Opening my inventory while this was going on made the dupe thing happen again.

**Comment by GroxTerror** [comment]
Also, this makes my sixth slot unusable.

**Comment by GingerWalnut** [comment]
I have tested this bug, but I cannot recreate it. If you relog does this fix the bug? Is there anything else that might have triggered it? What planet/system where you on?

edit - Nevermind, I managed to recreate it with a sniper. I am looking into fixing it

**Comment by awangatboo** [comment]
Closing all bugs in preparation for SQ 4.0.
