### ISSUE TITLE
Lag Autopilot Death

### ISSUE THREAD

**Issue by GroxTerror** [StarQuestMinecraft/StarQuestPublic#751]
Experienced a problem while autopiloting on Grun. Was averaging 300 ping, and I fell out the bottom of the ship after a jump as it was autopiloting. I hit the ground, died, and then got the respawn screen under my ship.

**Comment by awangatboo** [comment]
See a mod for a refund and do not fly when your ping is so high.  I would say get better internet but I know that is not an option.
