### ISSUE TITLE
Armour blocks technically unbreakable

### ISSUE THREAD

**Issue by Siigillum** [StarQuestMinecraft/StarQuestPublic#752]
Torpedoes cant break armour blocks. That way people just turtle up in their cobble/stoneslab/clay/bars boxes in space and you cant do a thing to them (they leave a small window and shoot you if you try to board. I suppose this is not how svs should look like. Get shot and box up!

Torpedo explosion strenght needs to be fixed so they actually work.... Now they dont.

**Comment by Siigillum** [comment]
Not to mention clay rmoved as it's unbreakable.

**Comment by GingerWalnut** [comment]
This has been fixed.
