### ISSUE TITLE
New blasters ballance issues.

### ISSUE THREAD

**Issue by Siigillum** [StarQuestMinecraft/StarQuestPublic#753]
Sniper blaster (power 5) does about 2.5 heart  max damage to prot 4 diamond gear guy. Usually it's around 1,5 - 2 hearts.

Normal blasters (power 5) seem almost ballanced. Base damage increase to 5 instead of 4 may help those as the damage received by prot 4 guy is laughable.

Automatic blasters are a waste of serwer resources. Power 5 auto blasted does no damage to prot 4 armoured guy.

**Comment by awangatboo** [comment]
I think the Automatic blaster is a way to destroy someones armor.

**Comment by Siigillum** [comment]
Destroying an unbreaking 3 diamond armour takes about 30 min of shooting. Or more. Tested with Pika and LH.

**Comment by awangatboo** [comment]
Closing all bugs in preparation for SQ 4.0.
