### ISSUE TITLE
Lag and falling

### ISSUE THREAD

**Issue by Mindaugas3** [StarQuestMinecraft/StarQuestPublic#754]
I was being chased by Goldieh, but when he came closer(he couldnt fire anything and didnt fire anything nor we saw each others ships) i fell to death because of movecraft glitch. When movecraft lags, you fall down but dont nessecarily die. I died. Fix this already.
I lost my 36 levels, core, and some inventory contents(bits of wool clocks etc)

**Comment by Mindaugas3** [comment]
The issue has been refunded, and Ive tested stuff and noticed that this bug only happens when you autopilot.

**Comment by awangatboo** [comment]
Closing all bugs in preparation for SQ 4.0.
