### ISSUE TITLE
Contract Points for W-Freighter Wrong Type

### ISSUE THREAD

**Issue by PatchyFox** [StarQuestMinecraft/StarQuestPublic#756]
The contract points required for Warp Freighter have been set as Reputation/Infamy instead of Smuggling/Trading. Though the ship class is functionally useless, this makes it impossible to complete the normal progression of smuggling certifications.

**Comment by awangatboo** [comment]
lol - I ran into the same problem tonight.  I already messaged a staff member and they said it will be fixed on next reboot.

**Comment by awangatboo** [comment]
Fixed as I now have it.
