### ISSUE TITLE
Missing Nick

### ISSUE THREAD

**Issue by icekoob** [StarQuestMinecraft/StarQuestPublic#757]
My friend(EnderProphet) had recently bought me a nick. It's been 22-ish hours and I haven't gotten my nick. I've went to Trinitos Alpha and I've gotten the buycraft message.
![2015-11-12_20 06 31](https://cloud.githubusercontent.com/assets/12261784/11159062/16f76dc8-8a22-11e5-9dd0-6f717e1a32d3.png)
My IGN is IceCube_ btw and I believe the nick is IceCube in cyan

**Comment by icekoob** [comment]
It's been fixed.. Idk how to close issues XD

**Comment by awangatboo** [comment]
I checked with Dib and he said this happned.

**Comment by awangatboo** [comment]
Beaver said this is fixed.
