### ISSUE TITLE
SQShipPainter message bug

### ISSUE THREAD

**Issue by icekoob** [StarQuestMinecraft/StarQuestPublic#758]
After a restart, I've logged on and I was trying to break some gravel and I've been getting these msgs.
![2015-11-14_11 16 48](https://cloud.githubusercontent.com/assets/12261784/11164831/8c040adc-8ac1-11e5-8e29-f6289733d2c1.png)
Yargon stated that Loy isn't affected. Atm it appears that Samp, Rak and Otavo has been affected

**Comment by icekoob** [comment]
Ava, Eratoss are affected too

**Comment by awangatboo** [comment]
The server restarted and I was told that this was not an issue any more.  Is it?  Can this be closed?
