### ISSUE TITLE
Everything is gone

### ISSUE THREAD

**Issue by lachie07** [StarQuestMinecraft/StarQuestPublic#760]
So Tank invaded me. That's not a problem, I flew up and out of his reach, but then glitches happened. Jane kicked me for absolutely no reason. I didnt say anything, I didnt do anything, I was just flying up. So I was kicked, and then when I log back on, I am dead. I wasn't suffocating, I was just immediately dead. So then I found out that Tank has stolen EVERYTHING I OWN. Now awangatboo, I know you will probably read this first, so make this high-priority please. Because I am EXTREMELY agitated right now. Because of jane, I have lost everything I own. A ship (around 500 blocks, light_freighter), over 20 diamonds, a second (small ship, 60 blocks), 16 wood logs, diamond armour, diamond tools, and alot of iron / coal. Please give me back all my stuff.

**Comment by awangatboo** [comment]
Lachie - I will make it Medium priority.  Only server wide issue get high priority.  Having said all this it is really a mod issue and a mod should see about working with you.  Also on the issue of the bug what planet were you on and what time so logs can be looked at.

**Comment by awangatboo** [comment]
Also I was going to see if Liggo could get a mod on to help you but you are not on-line.

**Comment by lachie07** [comment]
I was on Grun at 20:43. I raged a bit tho...

**Comment by lachie07** [comment]
oops didnt mean to close it

**Comment by awangatboo** [comment]
I am getting someone to look at the logs now.

**Comment by QuietHelper** [comment]
What is the in-game name as it does not match to this Github name.

**Comment by lachie07** [comment]
SirGingar

**Comment by QuietHelper** [comment]
20:43 yesterday?  It is 16:56 EST Server time right now.

**Comment by lachie07** [comment]
Oh sorry that's British time

**Comment by lachie07** [comment]
And it may be a bit before then (5 mins or so)

**Comment by QuietHelper** [comment]
I have checked the logs and you were combat tagged and when you logged out Tank killed you.  That is why you logged on are were dead.  Moments after you die Tank destroys your ship sign so he must have fired his weapons at your ship and combat tagged you.  As to why you logged out this will be something a mod will need to decide on as there is no evidence it was a bug or server issue.

**Comment by awangatboo** [comment]
I will ask Liggo to get a mod to talk to you about it.

**Comment by awangatboo** [comment]
I messaged him.

**Comment by awangatboo** [comment]
You will need to be on the server when a mod gets on to talk to you about this.

**Comment by QuietHelper** [comment]
OK I forgot to look at one of the logs.  I looked at Grun but not the Bungee.  In the Bungee log I see it.  

12:30:29 [INFO] [SirGingar] disconnected with: §f§f[§2Developer§f]§9 Jane§f:§f Please§f do§f not§f swear.§f StarQuest§f is§f meant§f to§f be§f PG-rated§f in§f content.

and the last thing you had said was 

12:30:19 [INFO] [G]**GalacticTrade[L-Freighter Pilot][P] SirGingar: pls help me

OK A mod should refund you as this was a bug as I can't find any swearing by you until after you died.  By the way even when you get really mad keep it PG.

**Comment by lachie07** [comment]
Yeah I'm deeeeeply sorry about me not being PG. But you must understand how annoyed I was, that I didn't even swear and Jane kicked me... :P But that's no excuse. How would I get a refund for my stuff?

**Comment by awangatboo** [comment]
I know from past experience you login and ask a mod to look at this github report.

**Comment by awangatboo** [comment]
I know Beaver will refund if you get on and he is there.

**Comment by lachie07** [comment]
What stuff would be refunded?

**Comment by awangatboo** [comment]
That will be a mod decision but I would think your ship, and your inventory.  If you login now I can get Beaver to login.

**Comment by lachie07** [comment]
OK It's midnight here (UK) and my parents are sleeping, I'm not supposed to go on, but if I do, a mod has to be on the instant I get on, cus if I get caught... Lol. And also, how long would it take to get my stuff back?

**Comment by awangatboo** [comment]
As a parent and the parent of Beaver I think you need to go to bed.  If you see me tomorrow I will see who I can get on Skype.

**Comment by awangatboo** [comment]
Quiet said he refunded you.

**Comment by lachie07** [comment]
Yes he did. Thanks
