### ISSUE TITLE
Lost a bunch of iron tools due to lag

### ISSUE THREAD

**Issue by Aven666** [StarQuestMinecraft/StarQuestPublic#761]
I was flying my ship in Rakuria and my droppers for some reason spat out their entire inventory.  I lost a bunch of iron tools that I worked hard to get.  Here's a list of what I lost:

9 shears
3 swords
4 pickaxe
3 wood axe
4 shovels

If there is anything you can do to replace these items I would be very grateful.  It took me 6+ hours to mine everything.  Thanks

**Comment by awangatboo** [comment]
Talk to a mod about this.
