### ISSUE TITLE
autopilot bug(part II)

### ISSUE THREAD

**Issue by Mindaugas3** [StarQuestMinecraft/StarQuestPublic#762]
Got my ship(courier) front(it had 5 droppers) torn off. luckily, i have screenshotted dropper contents and torn off ship.
Happened on Tallimar entry; Once I spawned at entry point i STILL had the frontal part of the hull(droppers, some wool, armor, helm sign). But as I was flying home, it disappeared without explosion.
Luckily, i was standing near the torn off place, I would have died to falling damage if I was one block further.
During autopilot, random ship parts occassionally fail to load, or ships just toss players into the ground.
Shift flying is OK.

**Comment by Mindaugas3** [comment]
http://imgur.com/a/QLWbT
First 'shot shows torn off ship, other screenshots show droppers.

**Comment by Mindaugas3** [comment]
Thanks OreNinja for refunding, but bug is still present.

**Comment by awangatboo** [comment]
Mind can you reproduce the bug at will?

**Comment by Evancooldude** [comment]
You have posted a series of issues, all related to one issue: You autopiloting too close to a world border. We already know that world borders are glitchy at best, and that there's some sort of bug present here. However, you making multiple reports of it isn't going to help the bug get fixed. As it is, this bug could be rooted in half a dozen plugins. Solving it is low priority, as you seem to be the only person who is having issues with it. As some people have suggested before, if it's a continuous issue right where you are, then move. It's not convenient, but it's the logical solution.

**Comment by Mindaugas3** [comment]
http://imgur.com/QjPlvFl Another occourence at Uru. Here goes my gunship. Had cargo.

**Comment by awangatboo** [comment]
Closing all bugs in preparation for SQ 4.0.
