### ISSUE TITLE
Cryopod Not Reset After Booms

### ISSUE THREAD

**Issue by HollywoodSun** [StarQuestMinecraft/StarQuestPublic#763]
So Siig blew up my ship cryopod, and it stayed updated to that location, even after I did /removehome and broke it.

**Comment by Mindaugas3** [comment]
+Today I've caught someone who had a cryopod in their ship. Needless to say, their power was 0 when i figured out they can /kit spacesuit.

**Comment by awangatboo** [comment]
One of the Jr. Dev's that does not have GitHub to assignee them to is working on this bug

**Comment by awangatboo** [comment]
Closing all bugs in preparation for SQ 4.0.
