### ISSUE TITLE
Space Spawn

### ISSUE THREAD

**Issue by DestinyIntwined** [StarQuestMinecraft/StarQuestPublic#765]
So I was on Grun with a ship and a small base. I logged off for awhile (a month at the most), and I logged on yesterday (11/26/15) and I was spawned in space. Please help.

**Comment by awangatboo** [comment]
Has this been resolved?  Also seeing that it goes so far back I am not sure anyone will be able to see why it put you in space.  Just ask a mod if they can help but there is a chance they can not even do anything about it.
