### ISSUE TITLE
Anti-spawnkill is BUGGED

### ISSUE THREAD

**Issue by Mindaugas3** [StarQuestMinecraft/StarQuestPublic#769]
We were assaulting a faction which was about to fall today(in gamma, of course). People who were killed can come out of cryopods and punch the attackers'(or at least attempt to kill them with fists) without getting punished, meanwhile people get punished for defending themselves during an attack(if they desperately come out of cryopod and try to punch people with god gear). It shouldnt work like that. If a player attacks another player, anti-spawnkill protection status should be removed(so I dont get kicked and killed for defending myself). Or, rather than that, there should be invulnerability to PvP(you can't fight, you can't be hurt) for a small period of time(1 minute?) after you die. Or maybe make cryopod have a tiny nonPvP wg.

**Comment by awangatboo** [comment]
This is not bugged.  It worked the way it was designed.  How having said that you bring up some ideas as to weather this should be in the game or at least changed.  These are ideas that should be looked at but they should go in the suggestions location on the forums.
