### ISSUE TITLE
Elevators Get Stuck

### ISSUE THREAD

**Issue by Creepopolous** [StarQuestMinecraft/StarQuestPublic#770]
I created a couple of elevators, both of which won't let me get off. I arrive at the floor I chose, and the glass doesn't reappear, leaving me stuck in the elevator. I believe it may have something to do with me using a fishing rod while in the elevator, as my camera was stuck in the same direction I shot my fishing rod, and I misclicked it in the elevator.

**Comment by awangatboo** [comment]
Is this still an issue?

**Comment by awangatboo** [comment]
Issues like this get fixed each time the server is restarted and it is restarted twice a day.  Closing the issue.
