### ISSUE TITLE
Ship redetecting bug(sign auto breaking)

### ISSUE THREAD

**Issue by Mindaugas3** [StarQuestMinecraft/StarQuestPublic#771]
Happened to me, Yargon and Doctorwhofan so far, and this bug is apparently server wide. Ships are not saved in database and need to be redetected after each use. Also, once right-clicking the sign, it somehow attempts to break the sign(either you've piloted it 5 minutes(or less) ago and no sign is broken AND this pilots your ship properly OR you have piloted it more time ago then 5 minutes and the sign is somehow corrupted and ship needs redetection). This bug heavily impacts trade, selling at gamma stations, docking tubes, parking at eco stations and all similiar stuff, also probably impacts SvS. Other fellows tested that too and asked me to post it here.

**Comment by Millibyte1** [comment]
According to Yargon, you're able to repilot until 5 minutes after your last depilot. After that, you have to redetect. This bug has presented itself today, so it could be caused by an issue with one of the restarts.

**Comment by Mindaugas3** [comment]
^ exactly what i wanted to say.

**Comment by awangatboo** [comment]
I am giving this one to Dib as even if someone else fixes it I am sure they will need to ask Dib about where the issue is coming from.

**Comment by Mindaugas3** [comment]
Fixed by QuietHelper. Testing done in Rakuria, it seems OK.
