### ISSUE TITLE
I Died Using Parachute

### ISSUE THREAD

**Issue by JT14** [StarQuestMinecraft/StarQuestPublic#772]
so heres what happened i didn't have access to the elevator so instead of waiting for doctorwhofan to come fix it i decided to jump out from the wall and use my parachute to land on the ground and get back inside but instead i landed then died.

**Comment by awangatboo** [comment]
This is Nicks plugin

**Comment by awangatboo** [comment]
Closing all bugs in preparation for SQ 4.0.
