### ISSUE TITLE
Nickname Not Set - PatchworkFox

### ISSUE THREAD

**Issue by PatchyFox** [StarQuestMinecraft/StarQuestPublic#773]
Hi there,

Supposedly, Ekarlate shelled out some IRL cash to buy me a nickname on 12.2.15, but the transaction doesn't seem to have made it through properly. Can you take a look to make sure everything was spelled properly in the request, etc.? I've flown to Alpha, and it's been around 24 hours since the transaction.

In case you need to know, it was for user PatchworkFox, Desired Nickname: "Patchy" in Cyan Blue. 

Thanks much.

**Comment by awangatboo** [comment]
I will bug Dib

**Comment by awangatboo** [comment]
I was told it was fixed.
