### ISSUE TITLE
Droppers glitch?

### ISSUE THREAD

**Issue by Tank0696** [StarQuestMinecraft/StarQuestPublic#775]
I was flying back from eretoss with a courier full of wool and i got back to grun to find it missing? i don't have proof but thats what happened.

**Comment by Evancooldude** [comment]
This is a very broad report. There are so many things that could have happened here. First a foremost, did you check the wool was there right before flying? Did you encounter anybody or stop for any amount of time on your way there? When did you notice the wool was missing?

**Comment by Evancooldude** [comment]
Also, please try to follow the reporting guidelines a little closer. We need information about what happened, as much as you can give, not two sentences that are extremely unspecific. Until you write out a detailed description, I don't expect you'll get any help.

**Comment by awangatboo** [comment]
Without any real detailed information we will have to close this ticket.
