### ISSUE TITLE
Falling?

### ISSUE THREAD

**Issue by Tank0696** [StarQuestMinecraft/StarQuestPublic#777]
I logged in one day and i was falling, i couldnt see anything then my screen showed me inside some iron room with signs, then i fell to my death and lost all my god gear

**Comment by Evancooldude** [comment]
The room you speak of is most likely Limbo, a location that players are teleported to if some sort of death occurs that the system can't handle for some reason. I'm not authorized to deal with refunds, but I will ask a mod to deal with this.

**Comment by awangatboo** [comment]
Beaver stated he needed more proof.  I am closing this Github as it is not a repeatable bug and you are working with a mod over the issue.
