### ISSUE TITLE
Factions monster flag is broken

### ISSUE THREAD

**Issue by The1Ulost2** [StarQuestMinecraft/StarQuestPublic#779]
This is pretty annoying as it limits what we can do in faction land. For those unfamiliar with factions ill explain because when i asked in chat some people were confused. Factions by default has monster spawning set to off. However pretty much everything with factions is toggle able by flags its really up to do you have permissions for set flags. So when i toggled the monster flag to on to make sure i had permissions i was like cool built my bases accordingly then toggled the flag back on and to my suprise no monster spawn seems to be something conflicting with factions because this works on other factions servers. For trying to recreate you must be faction leader to toggle flags and we do have permission for monster flag so assuming this is not intended it would be kind of dumb if intended anyway but thanks in advance.

**Comment by awangatboo** [comment]
The server uses a custom plugin to spawn monsters.  I think this plugin is set to not spawn mobs in factions.

**Comment by awangatboo** [comment]
I think the reason for this was that when it spawned monsters in faction land it did not follow what monster should spawn on what planter.  Example:  Cows on Rackuria.

**Comment by The1Ulost2** [comment]
Interesting seems like a weird bug i know ive looked at factions code before and its interesting. But a simple workaround could just be if mob cow is on server rakuria delete entity or something like that just a thought off the top of my head. Being able to control monsters in faction land so that a darkroom isnt a liability to the base would be useful tho

**Comment by awangatboo** [comment]
Closing all bugs in preparation for SQ 4.0.
