### ISSUE TITLE
Alpha's Beta Slipgate

### ISSUE THREAD

**Issue by Creepopolous** [StarQuestMinecraft/StarQuestPublic#780]
If I go through the Slipgate in Beta, I'll end up on the east of the Slipgate in Alpha, even though the rest of the system is on the west of the Slipgate.

**Comment by Evancooldude** [comment]
This may just be how the system teleports the ship. I'm not certain if this
is a bug, or simply the way it was set up

**Comment by Siigillum** [comment]
This is normal.

**Comment by awangatboo** [comment]
This is just how it is.
