### ISSUE TITLE
EXP Booster Drops to Negative

### ISSUE THREAD

**Issue by brickworm2012** [StarQuestMinecraft/StarQuestPublic#782]
A few days ago, or on 12/14/15, I was on Rakuria during a 8x booster. The next morning, after the booster had run its course, I came on to discover that the booster had dropped to -1. I had little time to test, but it definitely either kept the player xp bar the same or reduced it slightly.

**Comment by awangatboo** [comment]
This happened today as well.  I have been told Ginger made this plugin so I will assign it to Ginger

**Comment by GingerWalnut** [comment]
I am working on fixing this so that boosters never drop to negative.

**Comment by GingerWalnut** [comment]
This has been fixed for all of the boosters. They should never drop below one.
