### ISSUE TITLE
Fell into void on planet

### ISSUE THREAD

**Issue by immensityofkaiq** [StarQuestMinecraft/StarQuestPublic#783]
I logged in after having logged out in flowing water slightly above bedrock, and died. It looked like I had suffocated somehow, but the death message suggests the void.
![2015-12-16_20 02 46 copy](https://cloud.githubusercontent.com/assets/10344166/11858513/64fd4ccc-a430-11e5-97ee-336467c23b6b.png)

**Comment by immensityofkaiq** [comment]
Also, refund if allowed?

**Comment by awangatboo** [comment]
I think this might be an issue where the client and server have a mix-up on where you are at.  I have had this happen to me as well.  I think this is a minecraft / spigot bug and will need to be fixed at this level.  Ask a mod for a refund, if you see one.  I think this is reasonable but make sure your tell them about the github report.

**Comment by immensityofkaiq** [comment]
Given I am one... could I refund myself? XD
