### ISSUE TITLE
Trinitos Beta Star doesn't eject people from their ships

### ISSUE THREAD

**Issue by TheBeaver99** [StarQuestMinecraft/StarQuestPublic#784]
Last I checked, whenever you fly too close to the Trinitos Alpha Star, you get ejected from your ship and cannot get it back. This does not seem to be the case for the BETA star however. People can use the Worldguard as a safe spot to avoid combat now.
![2015-12-23_18 42 27](https://cloud.githubusercontent.com/assets/12473340/11987522/81f000e2-a9a6-11e5-9abd-cab69be70ccf.png)

**Comment by Siigillum** [comment]
I suggest adding some plugin which will just explode the ship and melt the crew when going into that sun worldguard.

**Comment by TheBeaver99** [comment]
I agree with you Siig. I personally think it would be cool if the sun was filled with lava and whenever someone flew too close it deleted their ship and teleported them into the lava-filled sun.

**Comment by Siigillum** [comment]
Can this be done by adding some kind of teleport similar to planetary entry teleport? Also can gate worldguards be changed to fit only the gate too? I think that is doable, just takes some work (tedious).

**Comment by StarQuestMinecraft** [comment]
Fixed the stars to eject you properly. The lava plugin would be fun, but complicated and nobody has time for that.

**Comment by Siigillum** [comment]
Yea, but pvp is on in those worldguards so... one can still hide...
