### ISSUE TITLE
Tree Farm Fuel

### ISSUE THREAD

**Issue by Creepopolous** [StarQuestMinecraft/StarQuestPublic#786]
Deacs' video said that I could use charcoal or coal in my tree farm, but when I used charcoal, saplings were being planted, but trees weren't being chopped down.

**Comment by awangatboo** [comment]
Originally you could use charcoal but after about 2 weeks of that tree farms were looked on as an exp grinder as you could get more wood than charcoal and make charcoal in furnaces and get the exp.  This is not a bug just something they took out in SQ 2.0.
