### ISSUE TITLE
Mobs not spawning

### ISSUE THREAD

**Issue by rocky0121** [StarQuestMinecraft/StarQuestPublic#789]
java turned mob spawning and monsters on in tsa otavo base, yet no poison spiders are spawning within our claim (we have a grinder) is this a bug?

**Comment by Evancooldude** [comment]
First, are you certain that your spawning conditions are right for them? I'll ask about it though.

**Comment by Siigillum** [comment]
This is a feature.

**Comment by Evancooldude** [comment]
I see. Thank you.

**Comment by rocky0121** [comment]
no but monsters was on

**Comment by awangatboo** [comment]
after talking to Dib SQ uses a custom mob spawner.  There a specific rules about mobs spawing in faction land.  Do like everyone else build your exp / mob drop grinder outside of your faction.

**Comment by rocky0121** [comment]
??

**Comment by Evancooldude** [comment]
It's supposed to be that way, build your grinder outside your faction claim.

**Comment by rocky0121** [comment]
yah already on it

**Comment by Evancooldude** [comment]
I'm going to close this, as it's not a bug.
