### ISSUE TITLE
Recycler, bonemeal quantities

### ISSUE THREAD

**Issue by Architect752** [StarQuestMinecraft/StarQuestPublic#791]
I built and tested a recycler on Eratoss.  The machine worked but produced five bonemeal per bone instead of four as the post says it should.

**Comment by awangatboo** [comment]
I have been told by Tong that this is a hard coded plugin error.  He is working on a fix.

**Comment by awangatboo** [comment]
Closing all bugs in preparation for SQ 4.0.
