### ISSUE TITLE
Ship replicator not copying double slab

### ISSUE THREAD

**Issue by Mindaugas3** [StarQuestMinecraft/StarQuestPublic#792]
As title says, ship replicator cannot use 2 slabs and copy a doubleslab.

**Comment by awangatboo** [comment]
There are many things that the ship replicator can not copy.  Redstone for one.  I think this is how Dib coded it and not a bug.  I will still assign to him.

**Comment by Mindaugas3** [comment]
Anyway, copying armored ships should not be a pain. Also, I won't use clay either(too bad)

**Comment by awangatboo** [comment]
Closing all bugs in preparation for SQ 4.0.
