### ISSUE TITLE
Attacked by Skywatch after defending myself.

### ISSUE THREAD

**Issue by ArcticNebula** [StarQuestMinecraft/StarQuestPublic#793]
Today I was attacked by Skywatch, following an attempted attack on me. I successfully defended myself, and afterward, Skywatch came to attack me. An additional potential bug is that when skywatch came, I wasn't immediately killed.

I was told that since my armor had Thorns on it, my inventory (not sure about my ship o.O) may not be able to be restored since it was a legitimate kill.

I didn't realize that Skywatch would come so I didn't take a screenshot of my inventory prior to Skywatch coming. Just in case I can get my inventory back, I will list what I had here. I was also told there was a plugin for restoring inventories, so I apologize in advance if the enchantments are inaccurate, as I am listing these things based off of my memory.
- Diamond Sword with Sharpness V and Fire Aspect II
- Diamond Shovel with Efficiency IV
- Diamond Pickaxe with Efficiency IV and Unbreaking III
- Diamond Axe
- Bow with Power V, Punch II, Flame, Infinity, and Unbreaking 
- 63 Steak
- 2 Arrows
- Clock/Ship Controller
- ~13 Torches
- Water Bucket
- Shears
- Full set of Chain Armor
- Diamond Helmet with Protection IV and Unbreaking III 
- Diamond Chestplate with Protection IV, Unbreaking III, and Thorns III
- Diamond Leggings with Protection IV, Unbreaking III, and Thorns III
- Diamond Boots with Protection IV and Unbreaking III

Here is a screenshot of what happened in this period of time (taken after the 1v1 and Skywatch attack).

![2016-01-03_16 22 35](https://cloud.githubusercontent.com/assets/9258136/12081246/1997bd82-b239-11e5-8209-1ec60d24afcc.png)

EDIT: I also had a cryopod on my ship and I didn't go to it after I was killed. Either my cryopod bugged out (I was told they're bugged on ships currently) or it was destroyed by Skywatch.

**Comment by HollywoodSun** [comment]
Thank you for making this Github, someone will look into it soon.

**Comment by awangatboo** [comment]
Do not wear thorns in Alpha or beta.  You will die when attacked.  This is not a bug and it is up to a mod to decide if they will be nice to you.
