### ISSUE TITLE
Jaquobia_Bug_Issue

### ISSUE THREAD

**Issue by jaquobia** [StarQuestMinecraft/StarQuestPublic#795]
I left the server one night to go to bet logging off at Beta_North, when i get back on, i see limbo for a split second before getting tp'd to Grun and falling to my death and my inventory was also wiped(Prot 4 spacesuit Unbreaking 3 with prot 2 leggings, and 53 potatoes) so now i have nothing while stranded on grun.

**Comment by awangatboo** [comment]
Yes I was told there was a bug with Beta last night a mod should refund you.

**Comment by jaquobia** [comment]
ok, do i get my items back(btw, when you get dis, ill most likely be a sleeping rock)

**Comment by awangatboo** [comment]
You will need to catch a mod on.  If you are on now I will ask TheBeaver99 to get on.

**Comment by awangatboo** [comment]
I am going to assume that this was taken care of.  Closing.  If this is still and issue you might be out of luck as I have heard Beaver say that is only so far back they can restore.

**Comment by jaquobia** [comment]
I'm sorry Iwangatboo, i have been busy lately and haven't had time to look
at my gmails
