### ISSUE TITLE
Attacker's contract completion glitch

### ISSUE THREAD

**Issue by Millibyte1** [StarQuestMinecraft/StarQuestPublic#796]
Submitting this on behalf of Attacker15, as he can't create a Github account.

"I just completed a piracy contract at Beta North, and most of my money and infamy disappeared, idk why.  I had about 200k and 27 infamy before it glitched, now I have 30k and 18 infamy. Idk what happened, I really want to get the infamy back, it took a long time to get."

**Comment by Millibyte1** [comment]
It doesn't really make any sense for this issue to exist, so I find it somewhat likely that he's lying or mistaken. Going to check the logs

**Comment by Millibyte1** [comment]
Due to neither the client logs nor the server logs containing the results of /contract stats (his contract points), there's no way to prove whether or not this actually happened.

**Comment by awangatboo** [comment]
If I Jr. Dev states that it can not be proven I am going to close this as a bug as no one else has reported it.
