### ISSUE TITLE
Speeder autopilot bug

### ISSUE THREAD

**Issue by Millibyte1** [StarQuestMinecraft/StarQuestPublic#797]
While building an underground speeder tunnel near bedrock on Otavo, me and several of my members found that speeder autopiloting sometimes needlessly moves the craft up in the y direction. After several jumps in the tunnel, the pilot's ship would be at the roof and would receive a message stating that the craft is blocked at a location with a y value greater than what should be the uppermost y value for the craft. This same behavior occurred for other ground vehicles and in non-enclosed spaces (though not as often in non-enclosed spaces). Shift-flying causes the craft to move back down. I suppose this is a flaw in the algorithm that determines whether the craft is touching the ground and needs to be moved upwards.

**Comment by Evancooldude** [comment]
If I might throw out a suggestion, it may be due to the system believing the ceiling it somehow part of the floor, and thus trying to get the craft to be one block above it?

**Comment by Siigillum** [comment]
Use shuttles.

**Comment by Millibyte1** [comment]
They're slow, nu. I'm going to attempt to fix this bug this afternoon

**Comment by awangatboo** [comment]
I always thought it was because speeders try to hover 1 block over the ground and the ground level is at y=60 or y=80 so it would keep moving up until it got to ground.

**Comment by awangatboo** [comment]
Closing all bugs in preparation for SQ 4.0.
