### ISSUE TITLE
Able to open faction doors while not in duty

### ISSUE THREAD

**Issue by Beachguyryan** [StarQuestMinecraft/StarQuestPublic#798]
Okay so was hanging out at Galactec w/ Molly and noticed that I was able to open her faction doors. I was not in Duty mode or anything. It did show up in chat that "Galactec does not allow you to use doors" but it still opened the door. I was not able to open trapdoors but was able to open her oak doors. Also I am an ally of hers but she has it set to where allies cant use doors. Fixing to check if i can open Pirvate doors or not (to be updated)

Update: Okay turns out we can also open Private doors while not in duty

**Comment by Siigillum** [comment]
Were those oak doors or some different kind of doors?

**Comment by Beachguyryan** [comment]
Any doors including oak

**Comment by awangatboo** [comment]
I think I have heard of this before and it is a strange side affect of being a trlmod.

**Comment by awangatboo** [comment]
Closing all bugs in preparation for SQ 4.0.
