### ISSUE TITLE
Warp Freighter Upgrade CPs Wrong

### ISSUE THREAD

**Issue by PatchyFox** [StarQuestMinecraft/StarQuestPublic#799]
Hey there - was looking at some of my available certs, and noticed that Warp Freighters somehow got the preset for Dreadnoughts, in terms of contract point requirements. Warp Freighters should need Trading/Smuggling points to upgrade, not Infamy/Reputation, right?

Would you mind addressing? 

Thanks!
-Patchy

**Comment by QuietHelper** [comment]
Yes that is something that needs to be fixed.

**Comment by awangatboo** [comment]
I was told this has been fixed.  I have also been told this does not include speed and that speed will be removed as no warp ship should ever be able to movecraft move.
