### ISSUE TITLE
Smuggling contract not counting all items but taking them.

### ISSUE THREAD

**Issue by KillerMidget** [StarQuestMinecraft/StarQuestPublic#800]
I was doing a smuggling contract that required 27 stacks of thin glass. When I did /contract complete it took all 27 stacks but only counted 7.

**Comment by awangatboo** [comment]
What day and what time was this so someone can go through logs and see if they see anything?

**Comment by awangatboo** [comment]
Closing all bugs in preparation for SQ 4.0.
