### ISSUE TITLE
Gravity is enabled at Gamma West eco station

### ISSUE THREAD

**Issue by CleverDan** [StarQuestMinecraft/StarQuestPublic#801]
AKA LagothZanta

I was at eco station Gamma West. I opened my boarding ramp and fell to my death on the landing pads below. I should have been able to float and not fallen all the way down.

**Comment by awangatboo** [comment]
This is not the case.  I can only assume that you had blocks above your boarding ramps.  The way gravity is applied is if there is a block over you and block under you there is gravity.

**Comment by Siigillum** [comment]
Good job sir. Gravity well. SQ feature.

**Comment by CleverDan** [comment]
So there's no way to fix that?

**Comment by awangatboo** [comment]
Closing all bugs in preparation for SQ 4.0.
