### ISSUE TITLE
Trialmod able to TP without entering dutymode

### ISSUE THREAD

**Issue by MollyGrue1** [StarQuestMinecraft/StarQuestPublic#802]
Today (Jan 20) at about 2:30 Disasterstudios asked me to help him, and I accidentally did /tp before entering duty mode.  To my surprise I was able to TP to him (and back) with my inventory intact. We were both on Eratoss, so I did not leave the planet.

**Comment by awangatboo** [comment]
I have talked to Dib on this and there is not an easy fix for this without more server resources.  The permissions plugin that we use keeps a cashed copy on the local server (planet / space) you are on.  It gets updated every 2 mins.  This is to keep performance good. when mods /unduty their perms stick with them for another another 2 mins.

**Comment by awangatboo** [comment]
Closing all bugs in preparation for SQ 4.0.
