### ISSUE TITLE
Teleported underground on Avaquo

### ISSUE THREAD

**Issue by Xiiston** [StarQuestMinecraft/StarQuestPublic#803]
I was flying on Avaquo on autopilot from NW towards the spawn marker. Around the spawn point my ship suddenly went straight down 15 blocks. and it got completely covered in stone. Any space there was air was replaced with whatever was in the ground. Stone, sea lanterns, etc. My character suffocated in the stone he was suddenly thrown into. 
![2016-01-21_01 00 32](https://cloud.githubusercontent.com/assets/16813101/12473200/08cc6a90-bfde-11e5-9dec-3a171635639f.png)

**Comment by awangatboo** [comment]
Closing all bugs in preparation for SQ 4.0.
