### ISSUE TITLE
my ship was cut in half entering otavo(gunship class) a mod then reloaded(thebechyguyryan) afterwards i proceeded to check my droppers and two droppers i had packed wiwth stonebrick was gone, i have no screenshots, this among other miscalaneous items were destroyed i request a full refund of items

### ISSUE THREAD

**Issue by disasterstudios** [StarQuestMinecraft/StarQuestPublic#805]

**Comment by awangatboo** [comment]
If you are going to make a github report do not put everything in the title.  I am closing this report as if you want a refund contact a full mod but if they follow procedure I do not think you will get anything back as you need screenshots.
