### ISSUE TITLE
Trialmod able to pilot anyship while not in duty mode.

### ISSUE THREAD

**Issue by Beachguyryan** [StarQuestMinecraft/StarQuestPublic#807]
Okay so I was messing around in my base moving ships around and ran into a ship captained by my alt. I right clicked the pilot sign without looking and to my amazement I piloted the ship under my name without my name being on the ship sign. 

Also tested at Rakuria spawn and was able to pilot someone eles ship without my name being on the sign. 

Only tested on ships my account can fly. Haven't tried a ship class I haven't unlocked.

**Comment by awangatboo** [comment]
From what I heard this is a bug with the /duty command.  I was told that Ginger will work on this in a week or two.

**Comment by lawrencethefrog** [comment]
No longer a critical problem- everyone can now fly any ship

**Comment by awangatboo** [comment]
Closing all bugs in preparation for SQ 4.0.
