### ISSUE TITLE
Half of ship blew up in Alpha and teleported underground in Rakturia

### ISSUE THREAD

**Issue by Xiiston** [StarQuestMinecraft/StarQuestPublic#808]
Basically second time this has happened. Well first time my ship randomly blew up in alpha. No one was near me. no one was attacking me. i just randomly lost a massive chunk of my ship. And its the second time on a planet me and my ship has been teleported underground. First time on Avaquo and this time on Rakturia right when i entered the planet from the east side. Around coords -1661/100

**Comment by awangatboo** [comment]
There are issues like this when the server has loads of LAG.  I saw strangeness like this after they brought SQ up when they had the Down time and it was so Laggy.  I am going to close this one as it is a know issue but see a mod if you want a refund.  If they can refund you they should.
