### ISSUE TITLE
Lag on Ur

### ISSUE THREAD

**Issue by Jayymurpheyyy** [StarQuestMinecraft/StarQuestPublic#809]
I was flying in my  ship on uru. I started flying downwards and lagged out of the bottom of my ship, hit the ground 5 times and died. Nothing abnormal, it happened when i flew downwards on uru.

**Comment by awangatboo** [comment]
This is not the case.  Your ship was 2 blocks above the ground and a creeper whole was being filled in by the plugin that does that when I came to this location.  Your location was right next to the unsean faction claim.  Please do not make false reports.
