### ISSUE TITLE
Bought exp booster but it did not get credited 

### ISSUE THREAD

**Issue by KillerMidget** [StarQuestMinecraft/StarQuestPublic#810]
On 1/30/2016 1:23 AM EST I bought a 5x exp multiplier and it did not get credited. The Transaction ID is: 1V862173BE0187813

**Comment by awangatboo** [comment]
I reported this and have already been told it is now fixed and running.  Due to the error it  might run a little longer than 24 hours.

**Comment by KillerMidget** [comment]
Ok thanks Awang.
