### ISSUE TITLE
Contract Multiplication

### ISSUE THREAD

**Issue by lawrencethefrog** [StarQuestMinecraft/StarQuestPublic#812]
When one issues the command /contract complete twice in quick succession, such that one sends the second command once they have received the 'Completing contract...' dialog but not yet the 'Contract successfully completed' dialog, the items are removed twice from the ship, the contract points are given twice, but only one contract is removed from the list. In this way someone can complete more than 5 identical contracts (as shown in #813).

Tested in Gamma Wast with a contract for 155 gray wool.

This is possible simply using t+UP to repeat the last command. Using macros it may be possible to multiply a contract completion to even more than twice its original value.

**Comment by awangatboo** [comment]
Closing all bugs in preparation for SQ 4.0.
