### ISSUE TITLE
Skywatch griefing

### ISSUE THREAD

**Issue by JeffWizard** [StarQuestMinecraft/StarQuestPublic#814]
So I was hanging out in my base, when somebody shot me with an arrow. I was in my cow farm when it happened, and it spawned 2 skywatch ghasts in my cow farm. It tore up the fences and roof, killed most of my cows, and left a huge area for pirates and others to get in. The terrain regenerated, but my cows did not.
I don't know if this is a bug or not, but MollyGrue said to post this.

tl;dr
Skywatch can destroy claimed land, and kills peaceful mobs.

**Comment by awangatboo** [comment]
It is not a bug but is is illegal to use skywatch to grief.  If you know who it was you can request a ban.
