### ISSUE TITLE
Skywatch randomly spawned

### ISSUE THREAD

**Issue by LookMomImWalrus** [StarQuestMinecraft/StarQuestPublic#815]
WookieJesuz (me) and my friend Quinnbuskus were in trinitos beta space around eratoss when skywatch randomly spawned and killed us. We didn't do anything to spawn skywatch, I swear to that but it still spawned.

2 things
1. Fix bug pls skywatch shouldnt randomly spawn
2. I had 
-2 fighter cores
-1 shuttle core
-1 gunship core
-Unenchanted full diamond armor
-Diamond pickaxe/axe
-32 bread
-1 stack white wool

This loss of items was undeserved and I really want it back.

**Comment by LookMomImWalrus** [comment]
And 2 pistons. that was it.

**Comment by awangatboo** [comment]
Skywatch does not randomly spawn.  Did either of you have armor with thorns on it and did one of you accidentally hit the other one once? This is the #1 cause of skywatch just showing up.  If not then please state the time as close as possible to let the people that look at the logs a time to look at.  Please put the Time in US/EST.

**Comment by LookMomImWalrus** [comment]
1.no we didnt wear armor
2. I was outside my ship and he was inside my ship when they appeared. 
3. Around 6:30

**Comment by LookMomImWalrus** [comment]
Edit: 
1. we weren't wearing thorns enchanted armor.

**Comment by QuietHelper** [comment]
What was the data on this?  Also I am not sure if we can refund the cores as I am not sure how they are generated.  Also have you died more than 5 times since then?

**Comment by awangatboo** [comment]
Closing all bugs in preparation for SQ 4.0.
