### ISSUE TITLE
Ship collision glitch

### ISSUE THREAD

**Issue by LookMomImWalrus** [StarQuestMinecraft/StarQuestPublic#816]
I came out of TA portal and dodowizard's ship and mine collided. Mine kept autopiloting but I glitched out and suffocated in space. 
had 3 stacks of logs 
full iron gear
iron pick
iron shovel
and a runaway ship that is heaven knows where now

**Comment by JeffWizard** [comment]
As the person who was flying the other ship, I'm 90% sure I can confirm this.
I'm DodoWizard btw.

**Comment by LookMomImWalrus** [comment]
.

**Comment by awangatboo** [comment]
This can happen when the server lags.  If you have not died that many times get a mod to give you a refund.

**Comment by awangatboo** [comment]
Oh what is your in-game-name?  That way the mods know.

**Comment by Siigillum** [comment]
Use a SPACESUIT!

**Comment by awangatboo** [comment]
Closing all bugs in preparation for SQ 4.0.
