### ISSUE TITLE
Skywatch vengeance squad.

### ISSUE THREAD

**Issue by TacoLink** [StarQuestMinecraft/StarQuestPublic#817]
Something that might be worth looking into, **in TB space**, I killed a noob whom I offered to let go (Han shot first!), and I was surprised that skywatch was not being summoned after obliterating their ship, and shooting a few arrows at them. Expecting the skywatch message to interrupt my conversation with said noob to appear the moment I flung a shot at them, **it only appeared after I had killed them**, and I bested them easily. **I also 'tested' this on otavo, era, and samp, it functions as interceded on those planets.**

If this is intended, I HIGHLY recommend reverting this, as the point of skywatch is to help prevent death, not scare pirates into not doing piracy.

**Comment by awangatboo** [comment]
This is more of a suggestion than a bug.  I am closing the bug but I will mention it to someone in staff.
