### ISSUE TITLE
i entered eratross and glitched in my iron bars then reloged and fell and died

### ISSUE THREAD

**Issue by quinnbuskus** [StarQuestMinecraft/StarQuestPublic#819]

**Comment by Evancooldude** [comment]
Can you provide any more information than this?

**Comment by Siigillum** [comment]
Faulty ship cockpit design. Happens a lot. Make sure to have a solid block below the bars. This fixes the issue.

**Comment by quinnbuskus** [comment]
K

**Comment by quinnbuskus** [comment]
Ryan already dealed with it.

**Comment by quinnbuskus** [comment]
Hi

**Comment by awangatboo** [comment]
Since this has already been dealt with I am closing the issue.
