### ISSUE TITLE
Exited duty mode while riding a ship on same planet, was teleported back to ship

### ISSUE THREAD

**Issue by immensityofkaiq** [StarQuestMinecraft/StarQuestPublic#824]
...and now I'm unable to get myself back to my base in player mode without taking a really, really long walk.

**Comment by immensityofkaiq** [comment]
well, it just occurred to me that I could just do it again with a ship at my base, but this shouldn't be a thing that can happen. make /duty have an implicit /stopriding or something like that in it.

**Comment by awangatboo** [comment]
Closing all bugs in preparation for SQ 4.0.
