### ISSUE TITLE
Ship disapeared while flying into Loyavas

### ISSUE THREAD

**Issue by Mercykiller173** [StarQuestMinecraft/StarQuestPublic#826]
I had just entered atmo, had autopilot running, then suddenly i was in space naked. Ship gone cant get back into atmo.  Lost all my gear and mining load i was hauling back to base. Please help.

**Comment by TacoLink** [comment]
Can confirm, this happened to me too.

**Comment by awangatboo** [comment]
Closing all bugs in preparation for SQ 4.0.
