### ISSUE TITLE
Speeder stuck on Rakuria planet.

### ISSUE THREAD

**Issue by guillerub2001** [StarQuestMinecraft/StarQuestPublic#828]
I have recently started playing in StarQuest and I have had an issue. I went to Rakuria, bought a speed and this happened to me:
[
http://s8.postimg.org/pba0zbrdx/2016_03_18_21_07_46.png](url)

[http://s8.postimg.org/pba0zbrdx/2016_03_18_21_07_46.png](url)

I can't start my speeder as seen above. Hope this gets solved.

**Comment by awangatboo** [comment]
Closing all bugs in preparation for SQ 4.0.
