### ISSUE TITLE
Contract not completeting

### ISSUE THREAD

**Issue by StJosh1** [StarQuestMinecraft/StarQuestPublic#830]
Ok so im doing a contract its a wanted one so if i dont finish its bad for me. I started the contract got in my ship with the supplies in my storage crates but when i got there i typed "/contract complete 0 smuggling" It says it was completing but it never took my stuff and gave my money! Can you fi this if it is a bug or take off my contract if you cant fix it.

**Comment by Millibyte1** [comment]
This appears to just be a bug with the way contracts command handling (it does not expect the last argument "smuggling", so it just skips ahead to the message), causing it to tell you it's completing. Try "/contract complete 0"; you only have one list for your accepted contracts, so you don't have to specify the type. Tell me if that fixes it when you get the chance. Thanks

**Comment by Millibyte1** [comment]
Issue has been resolved. Don't think it's necessary to make a real fix since 4.0's coming soon.
