### ISSUE TITLE
Herobrine Takeover of Schenanigans

### ISSUE THREAD

**Issue by brickworm2012** [StarQuestMinecraft/StarQuestPublic#831]
Using smoothcraft appears to cause issues with the skin. The player blitzes between pieces of their own and steve's skin. The tablist is also messed with, with players not actually online still on the tablist, and the aforementioned skin switching.

**Comment by awangatboo** [comment]
Was this in SQ 3.0 or on the creative server?

**Comment by brickworm2012** [comment]
Creative server

**Comment by awangatboo** [comment]
I think the Creative server is down right now and I am sure they will add fixes that they are adding to production to the creative server.  Re-open if this is still an issue when the creative server come back up.
