### ISSUE TITLE
Empire Issues

### ISSUE THREAD

**Issue by Laserlance141** [StarQuestMinecraft/StarQuestPublic#835]
I pre-submitted my empire request before the launch, and got put in to my second place empire. When my friend logged on 2 min later he was in the empire choosing lobby, and assuming that I was there also, chose a different empire than I. As we would much prefer to be in the empire, and put friends over empire on our empire form things, i would like this to be fixed.
-Laserlance141
Sorry if i jumped at this to quickly, just wanted to get this in there...

**Comment by awangatboo** [comment]
what was your friends name?

**Comment by Laserlance141** [comment]
Creativbuildr, also Creativgamr, but didn't put gamr on my app form

**Comment by awangatboo** [comment]
your username laserlance141?  In game?

**Comment by Laserlance141** [comment]
yes
