### ISSUE TITLE
Stopping in a energy field keeps the glass

### ISSUE THREAD

**Issue by iV01d** [StarQuestMinecraft/StarQuestPublic#842]
So when I left my ship in an energy field without unpiloting, the energy field gobbled up my ship, but when I started flying again the parts that were removed were replaced by the glass.

**Comment by lawrencethefrog** [comment]
So you are saying that you can fly away with the glass?

**Comment by iV01d** [comment]
Yes and I did, all the parts that got replaced by the energy field became part of the ship.

**Comment by iV01d** [comment]
Yes @lawrencethefrog and I did, all the parts that got replaced by the energy field became part of the ship.

**Comment by GingerWalnut** [comment]
This should be fixed at the next restart
