### ISSUE TITLE
Teleported back into sun, inv was wiped.

### ISSUE THREAD

**Issue by ghost** [StarQuestMinecraft/StarQuestPublic#845]
I was on Jurion the night of April 30th. The server crashed.

Logged back in the next morning and I was back in the sun, inventory was wiped, and my cryopod wasn't working. I'm out of money for a noobfighter and the tree farm is broken, so I'm effectively stuck in spawn.

(In game name is miner_guy667)

**Comment by GingerWalnut** [comment]
This has been resolved. If you still need to be refunded and if you can provide proof, please contact a mod.
