### ISSUE TITLE
Colored Docking Tubes are messed up (SQ 4.0)

### ISSUE THREAD

**Issue by Estenoor** [StarQuestMinecraft/StarQuestPublic#846]
Date: 5/1/2016 Time: 2.24 UTC-06:00

Hello,

I purchaced the Colored Docking Tube perk during Starquest 2.0 and When I tried to use it in Starquest 4.0 it would not work. I am in the Arator Empire and My IGN is SamzFerg. I do not remember using Colored Docking Tubes in Starquest 3.0 so I do not remember if it was an issue then as well. Thank you for your time.

-Sam Ferguson

P.S. I know that Donater Perk questions are not supposed to be asked but Beaver told me to put it up.

**Comment by GingerWalnut** [comment]
The perm has been given to everybody who has bought it and has logged onto 4.0. You should be able to use colored docking tubes now.
