### ISSUE TITLE
Ship Glitch

### ISSUE THREAD

**Issue by JUSAPlayer1** [StarQuestMinecraft/StarQuestPublic#847]
Basically my ship left me and autopilot into Besk, when i started flying around in space it tp'd me to Besk but my ship had started auto piloting on Besk so I was tp'd 1 jump behind my ship and fell. Had leather so no death. But still annoying.

**Comment by awangatboo** [comment]
Dib has been making a lot of changes to Movecraft.  He said something about fixing a lot of bugs.  I am going to assume this one has been fixed.  Re-open if you see it again.
