### ISSUE TITLE
Ship Glitch Killed me

### ISSUE THREAD

**Issue by RapidPlaysGames** [StarQuestMinecraft/StarQuestPublic#850]
I was flying to spawn so my friend could buy a ship, and while autopiloting, i got glitchede into space, so i was like, ok, ill put on my spacesuit, but when i put my spacesuit on, my items disappeared and i died, this was happening to almost everyone except, i was the only one to die :(
 I had Full iron with an iron sword, axe, picaxe, shear and 40-somethingchorus fruit my ship and controller
sorry i had no screenshots because i died in a matter of 20 seconds

**Comment by awangatboo** [comment]
Dib mentioned that he fixed a lot of movecraft bugs.  I assume this was one of them.  If you still need your stuff back see a mod.  I will close this one but if the issue comes back please re-open.
