### ISSUE TITLE
Entire Sheep farm despawned On Yavar III

### ISSUE THREAD

**Issue by AlphaMoose1** [StarQuestMinecraft/StarQuestPublic#851]
Business as usual, Set up shop on Yavar III, Tamed 2 sheep with wheat, Made them reproduce until i had a cool 10-15 sheep, Log off to go make lunch, come back less than 3 minutes later and entire sheep farm is gone. Grass is still patchy from where the sheep were eating. Please help!

**Comment by GingerWalnut** [comment]
This shouldn't happen again
