### ISSUE TITLE
Recyclers dont work

### ISSUE THREAD

**Issue by Mindaugas3** [StarQuestMinecraft/StarQuestPublic#852]
Tested. They don't.

**Comment by awangatboo** [comment]
I have been using them foe 2 days.  They work.  It might be an empire thing.  What empire are you in?

**Comment by Mindaugas3** [comment]
REQUIEM

**Comment by QuietHelper** [comment]
I checked this out and it is a bug on Quillon.  It works on other planets.  Tong this one is for you.

**Comment by awangatboo** [comment]
Tong said that world did not have the config file and that is why it was not working.  It is working now.  Mind checked and it works well.
