### ISSUE TITLE
Tamed sheep dissapeared.

### ISSUE THREAD

**Issue by Michael-Fragano** [StarQuestMinecraft/StarQuestPublic#855]
I had 2 tamed sheep in a secure pen. They were there yesterday, but when I came online today, They were gone. Can someone please fix this?

**Comment by ghost** [comment]
This is most likely a bug that has to do with 1.9.2...
Again, it could be the server

**Comment by awangatboo** [comment]
I have been told it has been fixed by Dib.  Not sure what the issue was but closing this one.
