### ISSUE TITLE
java.net.ConnectException error

### ISSUE THREAD

**Issue by gregolegomonkey** [StarQuestMinecraft/StarQuestPublic#857]
[http://www.whirlwindgames.com/starquestforums/page/2/m/17078810/viewthread/27067674-javanetconnectexception-error](url)
Ask these guys, I don't have the problem but am reporting it nonetheless.

**Comment by awangatboo** [comment]
This happens when you are on Mincraft Ver 1.8.  You have to be on 1.9 in order to login.
