### ISSUE TITLE
Cryopods never activate

### ISSUE THREAD

**Issue by iV01d** [StarQuestMinecraft/StarQuestPublic#859]
Hello, I have built a cryopod correctly but whenI try click on the sign it still continues to give me and error about it being invalid, I've had mods check and they say its fine and to post on here.

**Comment by awangatboo** [comment]
If you are on a planet with silverfish make sure one of the blocks have not become a monster egg.  This can happen making the cryopod say it is invalid.

**Comment by awangatboo** [comment]
Have you been able to make a cryopod correctly?  If we do not get an update from you I will close this soon.

**Comment by iV01d** [comment]
@awangatboo yes I did recently be able to create a cryopod.
