### ISSUE TITLE
Ship stuck glitch

### ISSUE THREAD

**Issue by ghost** [StarQuestMinecraft/StarQuestPublic#861]
I flew into the sun for fun (hey that rhymes) and when i flew in, my starship got stuck in the protected area (the place you cant go into) and i can no longer enter, and i don't want to waste money on a new star ship.

**Comment by awangatboo** [comment]
You should never fly into the sun.  You will always loose your ship.  If you are a new player talk to a manager or higher and they might refund your ship but I think you just need to buy a new one.
