### ISSUE TITLE
Items despawning in less than 5 minutes

### ISSUE THREAD

**Issue by Will5091** [StarQuestMinecraft/StarQuestPublic#862]
I was mining on Arator and died to skeleton with my full set of powertools (all tier 1) several stacks of redstone (probably close to 5 and 1/2 stacks) about a stack of iron, a little over a stack of lapis, half a stack of potatoes, and 36 gold i then spawned at my cryopod on Jurion and rushed to Arator in less than 4 minutes only to find all my stuff gone. i believe there is somthing up here because items are supposed to take 5 minuted to despawn.

**Comment by awangatboo** [comment]
If the planet as a whole unloads I think that the 5 min rule does not matter.  Was there anyone else on Arator when you died?

**Comment by Will5091** [comment]
yah beaver and later that same night i died on Jurion in a similar way and all ym stuff was there waiting for me on the ground

**Comment by Will5091** [comment]
annd its happened again only this time 3 people were near by and it all dissappeared and i was back at my death point in 2 minutes

**Comment by Will5091** [comment]
i have the exact coords this time X -713 Y 90 Z 284 also this seems to only happen when i die to mobs its like the mob takes my whole inv and then despawns but they cant do that they can only pick up 1 item

**Comment by awangatboo** [comment]
I am not sure how this is repeatable so I am closing the bug.
