### ISSUE TITLE
Potion Loss

### ISSUE THREAD

**Issue by JUSAPlayer1** [StarQuestMinecraft/StarQuestPublic#863]
So, I started brewing potions on yavar yesterday and put them all in a chest. I had strength ext, regen ext, and speed 2. Today I got on and had 3 of them in my inventory and flew into space then to radawii. Not sure whether it happened when exiting yavar or entering radawii, but all my potions that I had in my inventory are now water bottles. No refund request, just fyi.

**Comment by JUSAPlayer1** [comment]
Just checking my droppers which also had potions in them. Also all turned to water bottles.

**Comment by martinjonsson01** [comment]
This has been fixed.
