### ISSUE TITLE
Some commands not working(Permissions)

### ISSUE THREAD

**Issue by Mindaugas3** [StarQuestMinecraft/StarQuestPublic#864]
Some commands, such as /rules, /help or /cmds, and /seen don't have their perms configured properly.

New player tried to do /rules, and asked me to report on github. Tested 3 more commands so far.

**Comment by awangatboo** [comment]
I am not sure what commands need to be enabled.  There is a chance some of these are disabled because they do not want uses to use them.  Someone dealing with permissions needs to look at this.

**Comment by Mindaugas3** [comment]
Accidental testing of /powertool(with intention to view recipes and the like) revealed that /powertool perms are also broken.

**Comment by awangatboo** [comment]
perms have been swapped out and I have been told that at the correct commands are now available.
