### ISSUE TITLE
Ship glitched + inventory wiped + can fly

### ISSUE THREAD

**Issue by ShadowStrike999** [StarQuestMinecraft/StarQuestPublic#865]
I was on Arator and I flew straight up to leave planet then when I should've been teleported out I was teleported back to the ground with my ship gone and my inventory wiped and I was able to fly like I was in space... Please help I lost about 4 stacks of iron 7 stacks of redstone and 53 gold and a Sabre as you could see this is EXTREMELY disappointing and would be nice to have resolved 

Thank you
- Shadow

**Comment by awangatboo** [comment]
I think I saw your ship right outside of Arator.  I think you tried to fly into Arator space when it was down and this is why you died.  Ask a mod for a refund.  If you luck your ship is still there and they will TP you to it and you will hopefully have all your stuff.

**Comment by awangatboo** [comment]
Also this is what sometimes will happen when the server you are going to is down.  See a mod for a refund.
