### ISSUE TITLE
Pur Pur Stairs do not change orientation when using helm.

### ISSUE THREAD

**Issue by TiatLief** [StarQuestMinecraft/StarQuestPublic#866]
Title.

**Comment by awangatboo** [comment]
what are pur pur stairs?

**Comment by TiatLief** [comment]
Stairs made of http://minecraft.gamepedia.com/Purpur_Block.
Block id 203: http://minecraft.gamepedia.com/Stairs#Data_values.

**Comment by TiatLief** [comment]
Thank you for fixing this.
