### ISSUE TITLE
Snubfighters.

### ISSUE THREAD

**Issue by TiatLief** [StarQuestMinecraft/StarQuestPublic#867]
Snubfighters cannot be carried by Warships (forbidden block (snub sign)) as stated by the SQ vehicle video. Not sure if that is a bug or just not added yet.

**Comment by awangatboo** [comment]
I will let Money know.

**Comment by TiatLief** [comment]
Also if it has not been checked yet I recommend checking if snub cannons are fired by the main ship.

**Comment by buba141** [comment]
This has been fixed, ships can now carry multiple ship signs as long as the pilot's name is on all of the signs.
