### ISSUE TITLE
Claiming is bugged

### ISSUE THREAD

**Issue by forgefan** [StarQuestMinecraft/StarQuestPublic#870]
I tried to claim some land in Radawii but it keeps saying" you cannot claim the territory of other faction in your empire." even though i am in the wild and not  even near another faction. Yes i do have money in my factions bank.

**Comment by awangatboo** [comment]
Where were you trying to claim?  Please provide x/z coordinates

**Comment by GingerWalnut** [comment]
Is this still an issue?

**Comment by GingerWalnut** [comment]
Seeing as I don't know of this bug happening recently, I will close this. If it happens again, please reopen/make another bug report.
