### ISSUE TITLE
beskytt atmosphere bugged

### ISSUE THREAD

**Issue by Consue** [StarQuestMinecraft/StarQuestPublic#873]
Today I entered beskytt atmosphere and ended up in the ground without my ship suffocating inside what I guess was a stone block. I dont know if this was due to my internet lag or server lag but it still is a thing that needs to be looked at.

**Comment by Consue** [comment]
some more information: it looks like it has to do with the atmospheric entry, apparently when someone enters the atmosphere from the west/ south west they end up inside a moutian were they eather suffocate to death or wonder why they are in such a place.

**Comment by awangatboo** [comment]
Really what would be helpful is a bunch of players go make it where the mountain is cleaned up so people can

**Comment by Consue** [comment]
the issue seems to be fix, there is now a hole in the mountain were most ships will get out of if thye teleport there
