### ISSUE TITLE
Selling Lapis at REQ spawn

### ISSUE THREAD

**Issue by Cutout1** [StarQuestMinecraft/StarQuestPublic#874]
I'm not sure if this is at all spawn sale shops or just REQ, but selling one lapis is 50 credits, but when you put multiple in the chest, it still just sells for 50. Like if you put in a stack of lapis you get 50. If you put 32 lapis you also get 50 credits. Not that big a deal, but still a bug.

**Comment by Cutout1** [comment]
Oh, also, it's based on stacks, so if you put them in separate squares in the sale chest, each square that has lapis is worth 50.

**Comment by awangatboo** [comment]
This was fixed the last restart.  At least that is what Tong said.
