### ISSUE TITLE
Cryospawns don't work! (For Yavari)

### ISSUE THREAD

**Issue by LuckyTheWookie** [StarQuestMinecraft/StarQuestPublic#875]
Hello, it has come to my attention that cryopod's spawns do not work, i don't know the situation for any other empire because I am in Yavari. Please fix.
Thank you
-LuckyTheWookie

**Comment by awangatboo** [comment]
please run the command /cryocheck to see what it says.

**Comment by awangatboo** [comment]
If you can not run /cryocheck and get something back I will close this ticket assuming it is fixed.

**Comment by Evancooldude** [comment]
Cryopods are working fine for Yavari. Closed.
