### ISSUE TITLE
Trees not growing on Beskytt

### ISSUE THREAD

**Issue by LuckyTheWookie** [StarQuestMinecraft/StarQuestPublic#877]
Hello, I am here to talk about the situation on Yavari's iron (only iron) planet Beskytt. I would like to inform the developers that trees whatever kind do not grow on Beskytt. I would like this fixed since I can't have tree farms at my base. I have waited real life days for my oak trees to grow on Beskytt and it simply does not work. If this is normal please can you change the tick speed for plant growth rate. I get really frustrated because I have so many saplings but no trees are coming out of them. I have a pool of water I am trying to grow them by and still doesn't work. Please can you fix these, great Developers
Thank you!
-LuckyTheWookie

**Comment by awangatboo** [comment]
Trees do not grow on any of the iron planets in the Rim.  If you want them to grow use bone meal.

**Comment by LuckyTheWookie** [comment]
why cant they grow? it has the same atmosphere as everywhere else

**Comment by LuckyTheWookie** [comment]
if i need to use bonemeal skeleton spawns need to be upped because around where i am they are rare.
