### ISSUE TITLE
Items stolen from my ship at REQ Spawn

### ISSUE THREAD

**Issue by AviatorEcho** [StarQuestMinecraft/StarQuestPublic#878]
Architect asked me to attach video evidence of my ship and its contents before they were stolen.
He also told me he would notify the staff/take note of the incident, so this report should be expected.

My take on the incident:
I logged off at REQ spawn a few days ago, with my ship relatively unprotected. I hadn't anticipated a theft, since I was under (and still am under) the impression that stealing from a player in one's own empire is prohibited (especially when said player's items are at spawn, i.e., not abandoned).

The videos were too long to upload directly into Github, so I uploaded a few to Youtube.

This link is to the first video:

In this video I happened to record me looking through each of my droppers before leaving for spawn, so this proves that the items in my droppers in the video do not match the items in my droppers at spawn. Also, it seems whoever stole from me didn't have enough inventory space to carry everything, so they deposited 1-2 starter kits worth of stone tools in my droppers, along with some junk that I know for a fact isn't mine, because I have never crafted these items before.

I can provide extra evidence if need be, but I feel that this is sufficient for the time being.

EDIT: Ignore the music in the background of the video, I have a strange taste in music)

**Comment by awangatboo** [comment]
GitHub is for bugs not for refunds and mod request.  Please send Architect your link and he should follow up with you.
