### ISSUE TITLE
Powertools Charging stations eat Tools

### ISSUE THREAD

**Issue by swils24** [StarQuestMinecraft/StarQuestPublic#879]
So, had a powertool recharging station runing on a tool, and absentmindedly tossed a second tool in.  The second tool was near-full power, and as soon as it was finished, it output to the slot and overwrote the first tool that was sitting in there.  Relogged & checked surroundings, the first tool appears to have just poofed.

**Comment by GingerWalnut** [comment]
This has been fixed
