### ISSUE TITLE
Ship Duplicated

### ISSUE THREAD

**Issue by iV01d** [StarQuestMinecraft/StarQuestPublic#880]
So I just got back to my planet after flying to a different planet and I've found my ship has been duplicated, I now have two of the same ship, the ship is parked where I usually keep it, this may have been caused by a server restart while after I left the planet.

**Comment by iV01d** [comment]
It also appears my chests in the same area as my ship were also reset because before I left the planet I took some stuff out to sell and I put my Hammer III power tool & Power shovel I in the chest, when I came back the items were back and my hammer and shovel are gone. Hoping a refund could happen, my Hammer also had an energy upgrade and its very expensive. Edit: my IGN is dan14941 Edit2: Oldskoolish gave me a refund.

**Comment by awangatboo** [comment]
I am going to close this ticket unless you can reproduce it I am not sure how anyone can track this issue down.
