### ISSUE TITLE
Radawii, the actual planet in space

### ISSUE THREAD

**Issue by winecraft-dev** [StarQuestMinecraft/StarQuestPublic#883]
Some Issues I have experience with Radawii:
-Shooting at the planet actually leaves holes in the wool (oops)
-Whenever I try to leave the planet, I always end up teleporting back in even though I try to fly in the opposite direction

Please Fix,
Wine_Craft

**Comment by awangatboo** [comment]
I have been told that the issue wth Shooting leaving holes is a plugin that has not worked since V1.9.  Also, when you come out of the planet it will only TP you back in if you get within a range.  Sometimes people go diagonally from the planet and this is what cause the issue.

**Comment by Consue** [comment]
yea, I think the entry hitbox might be a square instead of a circle so it really is a pain to go around a planet
