### ISSUE TITLE
TreeFarms and MCMMO

### ISSUE THREAD

**Issue by SilverCymbal** [StarQuestMinecraft/StarQuestPublic#885]
If you hold an axe in your hand while a TreeFarm is running, you receive woodcutting MCMMO points.  Note: I don't know how reproducible or persistent this is, as I did not want to skew my stats by testing.

EDIT: Monday 14:00 PST.  This glitch is definitely happening.  I forgot to be cautious and used a stone axe to harvest melons and pumpkins.  A few minutes later, the axe was still in my hand while I was standing still, and I received a woodcutting level.  The tree farm was running.  I did a brief test of turning off the tree farm, and holding the axe, and received no levels.

**Comment by soronthar** [comment]
I observed this behavior as well.

**Comment by awangatboo** [comment]
The real question is does management think this is ok?

**Comment by astronus5** [comment]
I have coded a fix for this glitch
