### ISSUE TITLE
Mcmmo Axes Passive

### ISSUE THREAD

**Issue by CrazyCreeper1o1** [StarQuestMinecraft/StarQuestPublic#886]
It is to my understanding that the mcmmo actives have been disabled on SQ, but Paddy and I (The people with more than 100 levels in axes) believe that the passives for the axes stat is disabled as well. First of all, we should be dealing +2 damage for the passive axe mastery, but every zombie still takes 3 hits to kill with a stone axe (2 if I get the jumping crits). Second, we should have a 5% chance to deal double damage to mobs, but never have I ever one shotted a zombie with a jumping crit and a critical strike. Lastly, I've never gotten a greater impact which should have a 25% chance ever time I hit an enemy to knock them back with knockback II and deal 2 extra hearts of damage (Not including the damage from my jumping crits). For those reasons, I do believe the axe's passives are not working and I hope to see them fixed to give me an even playing field against other people in PVP when the core comes out.

**Comment by Consue** [comment]
I think it has to do with pvp

**Comment by swils24** [comment]
Hey folks,

So I've been fairly hands-on with the perms setup lately.  A few days ago, I went and added (I thought) all the mcmmo passives to our setup (at least, those which staff wanted everyone to have).  I know a couple of the axe-related ones were specified to not be added.

Anyway, they worked for a brief time, then unexpectedly stopped working again.  Dib just made the switch today to a new permissions system, so I'll take some time over the next few days to try and make sure that everything is working properly.

**Comment by swils24** [comment]
After our switch to the new permissions system, all MCMMO related permissions seem to be functioning properly and not disappearing.  Certain skills (actives, in particular, though also some passives) are going to remain disabled by our choice.  Consider this one solved.

**Comment by Mindaugas3** [comment]
Dodge is also working right now. Not sure if intended.
I think combat skill passives should remain disabled, whether it is forceful entry(axes) or dodge(acroatics)

**Comment by Evancooldude** [comment]
Looks like this is solved.
