### ISSUE TITLE
Missing nick after the new permissions updated

### ISSUE THREAD

**Issue by icekoob** [StarQuestMinecraft/StarQuestPublic#887]
Rip my nick, anyways title explains it all. My nick was IceCube in cyan(&3 is cyan) incase you are going to refund it. Everyone that had a nick is experiencing this right now.

**Comment by icekoob** [comment]
ign is IceCube_ btw

**Comment by awangatboo** [comment]
Has this been resolved?

**Comment by icekoob** [comment]
Yes
