### ISSUE TITLE
Rank downgrade after rank upgrade

### ISSUE THREAD

**Issue by gregolegomonkey** [StarQuestMinecraft/StarQuestPublic#889]
I ranked up to Colonist, from Settler, using the /rankup command, and I had both 100 mcmmo points and more than 20k credits.  The credits were taken from my account, and I was downgraded to Guest- at least that's what I show up as in chat. Also, I am unable to use /r command to join REQUIEM chat. Nothing else other than this was affected, to my knowledge.

**Comment by gregolegomonkey** [comment]
I don't believe that machina perms are broken?

**Comment by buba141** [comment]
What planet were you on when you tried to rankup, and what was the date? I need to find the error in the logs.

**Comment by gregolegomonkey** [comment]
Quillon.  The issue occurred within 1 hour before I made the report.

**Comment by buba141** [comment]
It looks like you were unlucky enough to rank up while we were switching to a new permission system. Now that everything is working smoothly with the new permission system, this won't happen anymore. Has anyone fixed your permissions, or are you still unable to use REQ chat?

**Comment by gregolegomonkey** [comment]
Everything works perfectly fine for me.
