### ISSUE TITLE
Power armor lost in modifier

### ISSUE THREAD

**Issue by JUSAPlayer1** [StarQuestMinecraft/StarQuestPublic#890]
So just bought emeralds for tier 3 armor. Got back to base on Yavar and made the armor. As I was modifying the gear I went through all of it putting protection 4. As I was adding energy boost to it, I got through the helmet and was on the chest plate, I added 16 red stone to it, clicked the icon of the chest plate on the right side (the one that is the updated piece) and it kicked me out of the gui like it usually does but there was no chestplate in my inventory. I dug up around the area searching to see if it was thrown out of my inventory or something and it's non-existent. It's not in my inventory or on the ground anywhere. I'd like a refund if possible seeing as that was like 66k worth of emeralds...

**Comment by GingerWalnut** [comment]
Can anyone confirm this happening recently?
