### ISSUE TITLE
Charger Issue

### ISSUE THREAD

**Issue by ShadySpectre** [StarQuestMinecraft/StarQuestPublic#891]
I used a charger to fix my powertool, but when I took the power tool out of the charge, it created a duplicate tool in the slot where my remaining redstone was. The duplicate disappeared once it was placed in my inventory, but the redstone has vanished.
I disabled the charger before removing the tool

(Forgive me if this was brought up already)

**Comment by awangatboo** [comment]
Ginger any update on this?

**Comment by GingerWalnut** [comment]
Can anyone confirm that this still happens?

**Comment by GingerWalnut** [comment]
Closing due to the fact that there where some stabilization fixes for chargers since this was posted. If this happens to anyone, please make a new bug report.
