### ISSUE TITLE
Missing Doner Stuff

### ISSUE THREAD

**Issue by AlinaFicalton** [StarQuestMinecraft/StarQuestPublic#893]
So after the server was "fixed" all my doner stuff is missing. My nickname and my Dockingtube is what i rember.

**Comment by awangatboo** [comment]
The Database was completely changed out wiping things like colored docking tubes.  The Nicknaming system was changed and they are still working the bugs out.  At some point, you should get this back.

**Comment by AlinaFicalton** [comment]
I was given back my nickname.
