### ISSUE TITLE
Ship was raded

### ISSUE THREAD

**Issue by AlinaFicalton** [StarQuestMinecraft/StarQuestPublic#894]
So i got off 2 days ago, locked up my ship with lock signs on every door, and shielded it at spawn. Now i get back on after the server has been "fixed" and my ship has been raided. All my wool, all my power tools, all my coal and wood and everything is all gone.

**Comment by awangatboo** [comment]
This is not a bug.  This is a rules violation.  Please check with a mod to see what should be done.
