### ISSUE TITLE
Private messaging broken

### ISSUE THREAD

**Issue by AlinaFicalton** [StarQuestMinecraft/StarQuestPublic#896]
i can not privet message somone unless there in the same world as me (aka in the same space or planet as me), but staff can.

**Comment by awangatboo** [comment]
They are not broken.  I have tested them.  The only issue for me is I can not /w or /msg i mist /message to get it to work.

**Comment by Evancooldude** [comment]
PMs are functioning normally. I believe any issues associated with this were fixed by the permissions update. Closed.
