### ISSUE TITLE
Arator exit point

### ISSUE THREAD

**Issue by mcdouble** [StarQuestMinecraft/StarQuestPublic#897]
When you leave Arator on the East side, it first spawns you slightly northeast of the planet. From there, no matter which direction you face you automatically get put back into planet atmosphere, even if I'm facing directly away from the planet. I suspect what happens is it puts you inside that radius for planet entry. But then after that it spawns you back out directly east of the planet instead of northeast. From there you can pilot away easily. Not sure if this is a legitimately fixable thing but its a hassle having to leave twice, especially since freighters move upwards and downwards much more slowly now.

**Comment by awangatboo** [comment]
This does not happen to me.  Each time I leave the planet I fly due east and never go back into the planet.
