### ISSUE TITLE
Nickname Not Set - PatchworkFox

### ISSUE THREAD

**Issue by PatchyFox** [StarQuestMinecraft/StarQuestPublic#898]
Hey there,

With the chat resets, just wondering if I'll get my nick back. It was a Cyan - "Patchy"

IGN: PatchworkFox

Thanks!

**Comment by awangatboo** [comment]
I thought this has been resolved.  Is that the case?

**Comment by PatchyFox** [comment]
Nope - I'm still nicknameless as of 5 minutes ago!

**Comment by PatchyFox** [comment]
This can be resolved. Thanks!
