### ISSUE TITLE
Yavari Rankup

### ISSUE THREAD

**Issue by SamvWrath** [StarQuestMinecraft/StarQuestPublic#901]
I'm not sure if it's intention or not but ranking up in Yavari (Not quite sure about other empires) is currently not working, giving an internal error. Not sure if this is meant to be a pause but I just want to put that out there. Thanks!

**Comment by TiatLief** [comment]
I am also having this problem currently.

**Comment by StarQuestMinecraft** [comment]
Fixed as of the 6:45 supplemental restart. Thanks for your reports.
