### ISSUE TITLE
Power Armor

### ISSUE THREAD

**Issue by FlyingTaurus523** [StarQuestMinecraft/StarQuestPublic#905]
I have a set of power armor III and I had max protection upgrades on all 4 pieces and it had to enchant Protection IV on it with the max protection upgrades but now its lowered to 2.

**Comment by awangatboo** [comment]
How did it lower to Prot 2?  Also you will need screenshots to have a mod refund you.

**Comment by GingerWalnut** [comment]
This has been fixed.
