### ISSUE TITLE
Arator Atmosphere Glitch - Missing Ship and Entire Inv

### ISSUE THREAD

**Issue by Stilettos-anda45** [StarQuestMinecraft/StarQuestPublic#906]
At abou 1:55 p.m., PST I piloted out of the Arator atmosphere to make a spawn run.  As soon as I entered space, my character fell back into the Arator atmosphere, all the way to ground.  For some reason, I survived, but my personal inventory was completely empty and I no longer had a spacesuit.  My ship (not the large on parked by my base), but a light blue and grey one does not even show up on dynmap for Arator Space or Arator planet.  Idk how this was even possible, but I'm pretty upset that I lost the following (most important to me) items:  

1 stack plus 32 redstone blocks
22 Iron blocks 
60 iron ingots
#2 powered "hammer" pickaxe without any modifiers

roughly 40 torches
roughly 30 oak wood
46 xp levels
19 lapis blocks (was going to transport to another planet)
one blaze rod
16 bones
spacesuit, controller

The other misc items, tools, and ship (disappeared off the radar apparently) are not as important to me as the above list.

Relogging does not help.
Please both investigate this issue and restore the the listed items.  Imagine if someone who makes much larger spawn runs had this happen.  For me, this is a lot bc I don't have as much opportunity to play as most ppl.  It's not an amount where I'd be comfortable letting it slide.  Please resolve this.  Thanks for your time in looking into this matter.

-IGN: Stilettos
Nick: Lady

**Comment by Stilettos-anda45** [comment]
**I still have my xp levels.**  Everything else was wiped out though.

**Comment by awangatboo** [comment]
I was told by Quiet that he fixed this one.  Closing.
