### ISSUE TITLE
Disappearing Blaze Powder

### ISSUE THREAD

**Issue by mcdouble** [StarQuestMinecraft/StarQuestPublic#907]
When brewing potions, if you run out of fuel (blaze powder) while brewing a batch of potions, for example, in between 2nd and 3rd ingredient, and then you put in a blaze powder into the fuel slot and go to put in the last ingredient, it'll just chew the fuel and then put in your ingredient. I'm pretty sure this isn't intended.

You can priority low this because its an easy work around; just take the potions out and insert fuel, and then reinsert potions. I just think its worth mentioning in case its a 5 minute fix and dib gets bored of something else.

**Comment by awangatboo** [comment]
Seeing that this is something in base Minecraft It most likely a spigot bug.  If that is the case it will be fixed when they update Spigit but from talking to the Devs I know they will have to re-check all the plugins.  I would think this will not be fixed anytime soon.

**Comment by Millibyte1** [comment]
Is this issue still occurring?

**Comment by Millibyte1** [comment]
Just confirmed this is a spigot bug
