### ISSUE TITLE
Chest Glitch

### ISSUE THREAD

**Issue by AlinaFicalton** [StarQuestMinecraft/StarQuestPublic#908]
So the anti-theft chest plugin seems to be broken. it tells me i cant see the object sometimes when im looking right at it. Anyways it allows you to use the chest even if it does read you can not see this.

**Comment by awangatboo** [comment]
I think I know what you are talking about but please put the error message that pops up on the screen.

**Comment by dphfox** [comment]
I believe the reason this happens is that ChestFix does not take into account the bounding boxes of certain blocks (some that I have experienced are upside-down slabs and trapdoors) however inaccurate ChestFix is still better than none at all so hang in there :p

**Comment by Evancooldude** [comment]
Chestfix has always had this issue. It simply assumes that all blocks are solid blocks. I would guess that the collision checks and complexity of this plugin would be massively higher if it did so, so I doubt this will be fixed.
