### ISSUE TITLE
Drill/Creative Flashes

### ISSUE THREAD

**Issue by ShadySpectre** [StarQuestMinecraft/StarQuestPublic#909]
When using machina drills, it occasionally flickers intro creative mode for a split second before reverting to survival

**Comment by AlinaFicalton** [comment]
Can confirm this, bit i dont think theres a way to get items with this glitch because it flashes so fast.

**Comment by TheNoty** [comment]
it uses powertools if you hold them too, and mining by hand when you have drills runing is super buggy

**Comment by martinjonsson01** [comment]
These have been fixed.
