### ISSUE TITLE
Drill haste glitch

### ISSUE THREAD

**Issue by AlinaFicalton** [StarQuestMinecraft/StarQuestPublic#910]
So if you have a drill it will reset the haste of whatever item you have in your hand, and if your trying to mine something at the same time you have a drill going it will keep resetting your pick, making it impossible to mine at the same time you have a drill going.

**Comment by TheNoty** [comment]
Already posted the same ;p

**Comment by martinjonsson01** [comment]
This has been fixed, it was because the pick was simulating breaking all the blocks your drill was breaking, making the pick reset over and over again.
