### ISSUE TITLE
Power Shield Bug?

### ISSUE THREAD

**Issue by AlinaFicalton** [StarQuestMinecraft/StarQuestPublic#911]
So im not shure if this is suppose to be how the power shield works but power shields energy drians just from holding it.

**Comment by awangatboo** [comment]
I have never had this happen and I use the power
shield all the time.  Is there a chance you are seeing this while using a machina drill?

**Comment by AlinaFicalton** [comment]
this is possable as I use to always hold my shield in my off hand.

**Comment by GingerWalnut** [comment]
This has most likely been fixed. If this is still an issue, please reopen/post a new bug report.
