### ISSUE TITLE
Death by Arator atmosphere re-entry bug

### ISSUE THREAD

**Issue by Azure-the-Malk** [StarQuestMinecraft/StarQuestPublic#913]
As always expected, my ship got pulled back into Arator when I left on a delivery, however when I re-entered the planet I fell straight through the floor of the ship and died (rather than the usual falling and TPing back aboard), losing everything I had on me, and then proceeded to continuously respawn back where my ship was before it re-entered the planet and suffocating.

Items lost:
Hatchet 3 - Fully modded for Energy Boost, Attack Damage, Slow, and Looting
Hammer 3 - full Fortune, and Efficiency
Trowel 3 - no upgrades
Iron armour set
shield
controller
9 iron ingots
9 stacks of bones
41 exp levels
(and maybe some other junk, like some baked potatoes, but w/e)

Edit: Mod tried to TP me, but it just says "cancelled" every time

**Comment by Azure-the-Malk** [comment]
This has been addressed now - ship reloaded and items refunded; thank you Molly and Oli! <3

**Comment by Azure-the-Malk** [comment]
So, this happened again, only this time my ship exited the planet without me, so I'm continuously falling from 220 on Arator

**Comment by awangatboo** [comment]
Get a mod for the restore.  From talking to devs this can happen when the transfer system between server fails to work.  They are re-writing the transfer system and will close this now but when the new system is put in place this should not be an issue.
