### ISSUE TITLE
Always teleported back to planet

### ISSUE THREAD

**Issue by Creepopolous** [StarQuestMinecraft/StarQuestPublic#916]
No matter what direction I go in, and no matter how many blocks my autopilot is set to, I always re-enter the planet's atmosphere the first time I try to fly away from it. I'm always able to fly away on the second try.

**Comment by AlinaFicalton** [comment]
This is true for the autopilot. However if you fly away from the planet by about 20 blocks first, THEN autopilot it does work.

**Comment by Creepopolous** [comment]
You see, even I do just fly away manually, I still go back to the planet. So I'm afraid that solution won't work for me.

**Comment by TheNoty** [comment]
Happened to me when leaving mardos

**Comment by awangatboo** [comment]
Please specify what planet so it can be assigned to a dev that is in that empire.

**Comment by Creepopolous** [comment]
It happens near every planet in the Quillion System.
