### ISSUE TITLE
/clear Command

### ISSUE THREAD

**Issue by Cutout1** [StarQuestMinecraft/StarQuestPublic#917]
I accidentally cleared my inventory when trying to clear my shop cart earlier today. Swils said I should report that people can /clear their inventory. Not a huge issue if you don't wipe all your tier 3 gear like me... Anyway, it's not super important, just a thing that isn't as it should probably be.

**Comment by awangatboo** [comment]
This is something I think swils should be able to fix as he is the one making permission changes.

**Comment by GingerWalnut** [comment]
This has been fixed
