### ISSUE TITLE
Tier 1 Powertool Became Tier 3

### ISSUE THREAD

**Issue by Cutout1** [StarQuestMinecraft/StarQuestPublic#918]
I had two shovels. One tier 1 trowel, and one tier 3. I put my tier 1 in the charger, then went digging, logged off while digging, then when I came back later there was a tier 3 trowel in the charger. So now I have 2 tier 3 trowels. This doesn't seem to be a common issue, but I thought I may as well still report it. Also, I've used both, it's not a ghost item.

**Comment by TheNoty** [comment]
Maybe somoene took the tier 1 to charge hise tier 3?

**Comment by Cutout1** [comment]
Very unlikely. I was on Mardos with no one nearby on dynmap. I wasn't gone for that long either.

**Comment by awangatboo** [comment]
This bug needs to be reproduced or it might get closed.

**Comment by GingerWalnut** [comment]
Unless something else like this happens again, I think its been fixed.
