### ISSUE TITLE
Banner Bug

### ISSUE THREAD

**Issue by Nixx59** [StarQuestMinecraft/StarQuestPublic#919]
Whenever I leave a planet and go to space or the other way around, Banners are reset to their original color, and banner shields have the banner removed completely.

**Comment by awangatboo** [comment]
I think even is re-writing the system that moves ships from planet to planet and hopefully, this will be fixed when that re-write is complete.

**Comment by martinjonsson01** [comment]
I don't believe evan's new system will fix this, but what I'm working on, should.

**Comment by martinjonsson01** [comment]
Made a fix for banners, should work now.
