### ISSUE TITLE
Ship replicators

### ISSUE THREAD

**Issue by Volcanex** [StarQuestMinecraft/StarQuestPublic#920]
Its seems that ship replicators are still broken, when I right click the sign I hear a piston noise however nothing happens.

**Comment by gregolegomonkey** [comment]
Check to see if the chest contains ALL of the needed materials first.  If that isn't the problem, then rebuild the entire setup.

**Comment by icekoob** [comment]
I can confirm this problem

**Comment by Evancooldude** [comment]
Just confirmed that replicators are working. Closed. Also, you do not need all materials, it will build whatever it can. You can later add more materials and it will go off of what's already there, so it makes no difference if you build it all at once or replicate it as you get materials.
