### ISSUE TITLE
Netherwart on Quillon?

### ISSUE THREAD

**Issue by SilverCymbal** [StarQuestMinecraft/StarQuestPublic#924]
Netherwart is growing, albeit slowly, on Quillon.  This may or may not be a bug, however, I was informed by some fellow REQ folks that netherwart is supposed to be restricted to mining planets (as stated by Moneybags in chat).

**Comment by Cutout1** [comment]
Oh, yeah, I've been growing netherwarts on Quillon. Didn't realize we weren't supposed to.

**Comment by awangatboo** [comment]
This needs to be looked into.

**Comment by awangatboo** [comment]
I talked to Money about this and there was a bug in the configs They have fixed the bug but netherwart will still grow in all the planets.  But I think the non-mining planets will grow slower than the 5% the mining planets get.
