### ISSUE TITLE
Cant log in (Might have to do with recyclers)

### ISSUE THREAD

**Issue by SamvWrath** [StarQuestMinecraft/StarQuestPublic#925]
Made a recycler, used wood planks as my product and put wooden items in the top dropper. Everything lagged out, I timed out and now every time I log in, I cant open or do anything and end up timing out. Not sure if its my internet but it was working rather fine before

**Comment by awangatboo** [comment]
are you still having this issue?

**Comment by SamvWrath** [comment]
I think I should be fine thanks!
