### ISSUE TITLE
Ship Armoring

### ISSUE THREAD

**Issue by JUSAPlayer1** [StarQuestMinecraft/StarQuestPublic#926]
Just doing some testing with Bonzer in game since the 4.0 came out about ship armor. Pre-4.0, stained clay was 100% blast resistant to cannons and turrets, with only torpedoes being able to penetrate them. After we tested various armor types, it seems that clay is no longer on the detection list for armor blocks at all. Nether brick, quartz, and red sandstone slabs appear to be the top grade for armor, which they always have along with clay having their same blast resistance. Stone brick slabs and stairs etc all fall under those. Evan wanted me to make this just to clarify whether this is intended or if it's merely a config error that should be fixed. I'll post more if i find more about armor-related issues.

**Comment by GingerWalnut** [comment]
Armor has undergone some changes since this report. If this is still an issue, please reopen/make a new bug report.
