### ISSUE TITLE
My ship with a working shield has been raided

### ISSUE THREAD

**Issue by 7A7U** [StarQuestMinecraft/StarQuestPublic#927]
I would like to know how my ship has been destroyed and scrapped with the shield on...
I already put this on the Starquest forum but was told to put it here so...
http://www.whirlwindgames.com/starquestforums/m/17078810/viewthread/27162935-my-ship-working-shield-has-been-raided/post/118332763#p118332763
Heres a few pictures of the remains

![2016-05-14_13 17 30_1463221363](https://cloud.githubusercontent.com/assets/19430139/15359209/f5596400-1d10-11e6-9c20-33d9bdac3afc.png)
![2016-05-14_13 19 12_1463221354](https://cloud.githubusercontent.com/assets/19430139/15359207/f558c36a-1d10-11e6-82d8-ab9856b4484c.png)
![2016-05-14_13 19 38_1463221347](https://cloud.githubusercontent.com/assets/19430139/15359206/f5588e68-1d10-11e6-9682-50222dc13365.png)
![2016-05-14_13 19 24_1463221351](https://cloud.githubusercontent.com/assets/19430139/15359211/f55d1c26-1d10-11e6-85fd-a44685092906.png)
![2016-05-14_13 17 32_1463221359](https://cloud.githubusercontent.com/assets/19430139/15359208/f558f3ee-1d10-11e6-9edb-6463a997da8c.png)
![2016-05-14_13 19 38_1463221335](https://cloud.githubusercontent.com/assets/19430139/15359210/f55cfdea-1d10-11e6-9cb5-1a869b1aa61b.png)
![2016-05-14_13 19 33_1463221344](https://cloud.githubusercontent.com/assets/19430139/15359212/f570a232-1d10-11e6-888a-7a3b1f36c1e6.png)

**Comment by awangatboo** [comment]
The staff would like to know why that happened as well.  There have been many people saying that shields are not really working.  More testing is needed.  See a mod to get a refund.

**Comment by Pvt-Murphys** [comment]
same thing happened to me too, except only a piston off of the landing gear was raided.

**Comment by Starsword7** [comment]
This happened to me too: 
![2016-05-19_17 35 47](https://cloud.githubusercontent.com/assets/13322532/15456479/1b47af0e-2037-11e6-96c3-b93a1b373f2b.png)
When i do /region info, the region is still there, and seems to be working fine. 

From the looks of it, it seems that somone shot at my ship. 
Are ship cannons supposed to be able to destroy shielded ships?

**Comment by 7A7U** [comment]
huoh... still havent got a refund or any "useful" replies from mods...

**Comment by awangatboo** [comment]
Talk to a mod.  There is a bug where ship guns to not respect the W/G Shields.

**Comment by 7A7U** [comment]
awanhatboo I tried... they gave up helping just telling me to ask on github. sooo I got pissed off at them and called them fucking uselees :3 as you can probably imagine im now banned for a month.

**Comment by GingerWalnut** [comment]
This should nolonger be occuring

**Comment by 7A7U** [comment]
Soo... does that mean im gonna get my ship back?
