### ISSUE TITLE
Opening a door triggers Cannon Fire

### ISSUE THREAD

**Issue by winecraft-dev** [StarQuestMinecraft/StarQuestPublic#928]
Whenever I open my door while lining up to a docking tube, my side-cannons fire randomly, often blowing things up. I'm certain that I am not left-clicking my clock, only right-clicking on the door. Please fix this problem/tell me what I'm doing wrong.

-Wine_Craft

**Comment by awangatboo** [comment]
When opening your door do not have you controller / clock in your hand.  That will fix the issue.
