### ISSUE TITLE
Treefarms and mcmmo

### ISSUE THREAD

**Issue by TheNoty** [StarQuestMinecraft/StarQuestPublic#929]
When holding an axe and operating a treefarm, it gives you insane amount of xp.
Pretty sure this is not intended.

**Comment by soronthar** [comment]
It also drains any power tool you have in your hand, be it the pick, axe, sword or shears.
Also if the tool is drained of power, the farm will stop.

**Comment by ghost** [comment]
The Drills also give substantial McMMO Xp when you are mining with them and have a pick in your hand. I thought this had been fixed but apparently not.
