### ISSUE TITLE
Ship Shield Bug

### ISSUE THREAD

**Issue by Pvt-Murphys** [StarQuestMinecraft/StarQuestPublic#931]
So, there's a bug where if I put a ship shield on my ship and pilot it, the sign disappears, and the shield function too. This bug may be disastrous if left alone for too long, as my ship as already been robbed of landing gear because of this bug.

**Comment by Evancooldude** [comment]
While I've heard about bugs of shields not working, I have yet to hear any instance of a ship shield sign disappearing besides this. Can you confirm that you can replicate this, and post pictures if that is the case?

**Comment by Pvt-Murphys** [comment]
Actually, the ship sign reappeared, but it still doesn't work. So, still, the shields aren't working.

**Comment by awangatboo** [comment]
You need to make sure the shield is really up by doing '/rg info' while in your ship.

**Comment by awangatboo** [comment]
Shields work fine.  I have been told there is a way to get around ship shields and the devs are working on a fix.
