### ISSUE TITLE
Charcoal Not Selling

### ISSUE THREAD

**Issue by AlinaFicalton** [StarQuestMinecraft/StarQuestPublic#932]
So I] just tryed to sell Charcoal at spawn and it wont sell. I tryed /value again and it said that its worth 25c.

**Comment by gregolegomonkey** [comment]
Charcoal isn't on the list of things you can sell: [https://docs.google.com/spreadsheets/d/1A3zx_h9E4BcMh-Fuwer4oJ190gWBh2VSwmyI-5ddCDw/edit#gid=0](url)

**Comment by awangatboo** [comment]
You should not be able to sell charcoal
