### ISSUE TITLE
Machina drills don't respect mcmmo double drops

### ISSUE THREAD

**Issue by gregolegomonkey** [StarQuestMinecraft/StarQuestPublic#936]
The drill physically drops the double drops on the ground instead of sticking them in the chest, but it only drops double when the player that activated them is holding a pickaxe.

**Comment by awangatboo** [comment]
mcmmo perks are meant to be received when doing the task manualy.  I would say you are lucky to even get the double drops.  I am going to assign this but I think this is the way it is going to be.

**Comment by dphfox** [comment]
MCmmo has a few.. "features" with machina running, so just try not to hold any tools when using them. The problem is being worked on as I write this.

**Comment by awangatboo** [comment]
I have been told that the fix that Elttob was working on has been installed.
