### ISSUE TITLE
Cryopod Issue dcwhawk

### ISSUE THREAD

**Issue by Cutout1** [StarQuestMinecraft/StarQuestPublic#937]
I was at spawn station when dcwhawk reported a cryopod issue. He died and spawned in the RSS Sunflash, when he had a cryopod. I checked to make sure he had one, and he did, as seen in the image. I teleported him to it and refunded some items he lost. His faction member collected his drops for him, and it was just a few items he was missing, nothing major. 
![2016-05-21_19 42 26](https://cloud.githubusercontent.com/assets/10093818/15451862/38c528e0-1f8d-11e6-8780-01d748da0d45.png)

**Comment by awangatboo** [comment]
The user needs to run /chryocheck to make sure his cryopod is working.

**Comment by Cutout1** [comment]
I told him to break and replace the sign, but he left before he did. If I see hm on again I'll have him run /cryocheck.

**Comment by awangatboo** [comment]
Closing this issue as not enough info here to be helpful.  People need to run chryocheck before they die to really be 100% sure it is a bug.
