### ISSUE TITLE
Machina planters aren't working

### ISSUE THREAD

**Issue by jorcool** [StarQuestMinecraft/StarQuestPublic#939]
Activating a machina planter doesn't work for me. I have the appropriate rank (Colonist) and am on Erilon. If i click the lever the only thing it does is that the iron bar goes down, and if there's a mature crop under it it harvests it. It doesn't do anything after that however.

**Comment by awangatboo** [comment]
I have not made one but have you used oak in the building of it?  I know this is an old plugin and at the time it was written only oak fence posts were there.  It might have something to do with that. Please make sure all parts of it are made with oak.

**Comment by ltrester** [comment]
I am having the same issue and I used oak fences.

**Comment by awangatboo** [comment]
and oak logs?

**Comment by ltrester** [comment]
where would we use logs?

**Comment by awangatboo** [comment]
The side that tells is to go out.

**Comment by ltrester** [comment]
you can use fence for that i thought

**Comment by awangatboo** [comment]
Sorry not logs but planks.

**Comment by ltrester** [comment]
still not working

**Comment by awangatboo** [comment]
http://dev.bukkit.org/bukkit-plugins/machinacraft/pages/machina-planter/ 

Like that.  If that does not work then I will assign it to Tong.

**Comment by ltrester** [comment]
we did it the exact same way and it still doesn't work

**Comment by jorcool** [comment]
Everything's oak, i build it exactly like the forum page

**Comment by conkleon** [comment]
I made sure that I uses oak planks and everything is built like the wiki demonstrated also I had made a planter and on 3.0 so I have experience P.S. thanks that you are looking into the matter

**Comment by jorcool** [comment]
Planters are working for me now

**Comment by Evancooldude** [comment]
Thank you for posting that it's fixed, Jorcool. Closed.
