### ISSUE TITLE
Arrow glitch

### ISSUE THREAD

**Issue by 17madman** [StarQuestMinecraft/StarQuestPublic#940]
On the planet arator my tier 1 power hammer with 2 energy upgrades and fortune 1 was out of energy. I saw a skeleton that started shooting at me and I was getting my weapon out but I accidentally got out my power hammer and I spam left clicked and I then noticed the arrows would bounce off me and hit the skeleton if I was left clicking with the power hammer while he shot at me. I also stopped left clicking and the arrow would hit me normally if I wasnt spam left clicking. PS: My IGN is 17madman

**Comment by GingerWalnut** [comment]
This should be fixed at the next restart
