### ISSUE TITLE
Jammer not working

### ISSUE THREAD

**Issue by BatFC** [StarQuestMinecraft/StarQuestPublic#943]
When I try to enable jammer it says that I don't have permission.
![2016-05-20_06 31 09](https://cloud.githubusercontent.com/assets/7577409/15464726/e2f5ab94-210b-11e6-9a75-d6f3cf6ef066.png)

**Comment by awangatboo** [comment]
What rank are you?  Maybe you have to be a higher rank to operate them

**Comment by BatFC** [comment]
I am second rank in Arator.

**Comment by GingerWalnut** [comment]
This should be fixed.
