### ISSUE TITLE
Machina conveyer bug

### ISSUE THREAD

**Issue by BatFC** [StarQuestMinecraft/StarQuestPublic#944]
Machine conveyer is not working properly due to chestfix plugin.

When I put the receiving chest within sight it work properly like this:
![2016-05-21_22 30 55](https://cloud.githubusercontent.com/assets/7577409/15464806/4a8b7f90-210c-11e6-9a4a-c03920584408.png)

But if I put the receiving chest out of direct sightline it says this:
![2016-05-21_22 31 41](https://cloud.githubusercontent.com/assets/7577409/15464832/6e9ec770-210c-11e6-9c80-65e0c1dd0438.png)
and will not transfer the items.

**Comment by awangatboo** [comment]
This is not a bug but really a side effect of Chestfix.  If you do not like you please put a suggestion in the suggestion section of the forums to take it out.
