### ISSUE TITLE
Cant take power tools out of normal furnaces

### ISSUE THREAD

**Issue by falloutfan101** [StarQuestMinecraft/StarQuestPublic#945]
If you put a power tool into a furnace that isnt a charger, you cant get it out. It says in red text "You cannot put a power tool into this inventory" when you try to take it out.

**Comment by awangatboo** [comment]
can you break the furnace or change it back into a charger and get it out?

**Comment by falloutfan101** [comment]
@awangatboo Yes, it's easily fixable, but it just looks like it wasn't supposed to happen.

**Comment by GingerWalnut** [comment]
This should be fixed at the next restart
