### ISSUE TITLE
Deadlyjesaitis buycraft not working 

### ISSUE THREAD

**Issue by deadlyjesaitis** [StarQuestMinecraft/StarQuestPublic#946]
Hey I donated ten dollars for a blue nickname and jane said thanks for donation in chat but its been about five hours and my nickname still has not updated, just wondering how this can be fixed

**Comment by awangatboo** [comment]
I have contacted QuietHelper on this issue.  Hopefully you will hear from him soon.

**Comment by awangatboo** [comment]
http://www.whirlwindgames.com/starquest/m/17590832/article/3841155

I have been told they are working on it.
