### ISSUE TITLE
Silverfish egg-blocks spawn skeletons sometimes instead of silverfish.

### ISSUE THREAD

**Issue by TiatLief** [StarQuestMinecraft/StarQuestPublic#947]
Happens on Beskytt. Occurs just like any other trigger for silverfish to leave the block but sometimes a skeleton comes out instead.

**Comment by gregolegomonkey** [comment]
Occurs on Mardos as well, I would assume it happens on Arator as well.

**Comment by GingerWalnut** [comment]
I think this was fixed. If it wasn't, please reopen/post a new report.
