### ISSUE TITLE
Shielded ship griefed

### ISSUE THREAD

**Issue by ghost** [StarQuestMinecraft/StarQuestPublic#948]
I left my ship parked right outside of faction land and found that someone had griefed the back part of my ship. 

Picture of damage: 
![2016-05-23_16 46 33](https://cloud.githubusercontent.com/assets/18903592/15485760/bc314950-2106-11e6-85c4-515c9fbafb06.png)

**Comment by awangatboo** [comment]
Was your shield up?  Can you go to where the ship was and do /rg info to see if the shield is still there?

**Comment by awangatboo** [comment]
If you can not provide more info this Bug will be closed.

**Comment by awangatboo** [comment]
The staff knows the issue as to how and why this happened.
