### ISSUE TITLE
Lost nickname after leaving Jurion

### ISSUE THREAD

**Issue by icekoob** [StarQuestMinecraft/StarQuestPublic#953]
Anyways, today I was picking up a new recruit for my faction and I entered space to find that my nickname had been erased. My nickname &3IceCube or IceCube in cyan and my ign is IceCube.

**Comment by icekoob** [comment]
Aparently, my nick only works on Jurion

**Comment by awangatboo** [comment]
http://www.whirlwindgames.com/starquest/m/17590832/article/3841155

They are working on it.
