### ISSUE TITLE
Flew into Jurion- lost ship and inventory and did not even enter planet

### ISSUE THREAD

**Issue by ltrester** [StarQuestMinecraft/StarQuestPublic#954]
Hi I was flying from space into Jurion and the server lagged. I got an error code and then my ship disappeared as well as my inventory. I am now sitting inside the actual planet model so I do not suffocate. Please help!

**Comment by awangatboo** [comment]
Talk to a mod.  I have been told things like this happen when the server lags and the LAG should be fixed if we get newer hardware.
