### ISSUE TITLE
Elevator bug 

### ISSUE THREAD

**Issue by APnaptime** [StarQuestMinecraft/StarQuestPublic#956]
I was trying to use an elevator to transport mobs up 

a sheep got stuck in it so I killed it before It got to its destination

then when I tried to use it again, it wouldn't work, I broke and replaced everything but that didn't work either

I'm guessing that this has to do with where the elevator signs are placed because even though I broke everything, the signs and base were in the same place both times

**Comment by awangatboo** [comment]
> I was trying to use an elevator to transport mobs up
> Bad Idea
> a sheep got stuck in it so I killed it before It got to its destination
> Bad plan

The elevator is broken until the next time the server restarts.  This is the way that has been since SQ 2.0.  It was the same in SQ3 and now in SQ4.

**Comment by Millibyte1** [comment]
Moving the bottom floor with the iron blocks up or down 1 block allows the elevator to function again without the server restarting.
