### ISSUE TITLE
Posting Resource Pack Link Kicking People

### ISSUE THREAD

**Issue by Cutout1** [StarQuestMinecraft/StarQuestPublic#963]
So I was trying to tell a player the dynmap link, but when I posted it the first time I got an error message saying [Proxy] Lost Connection To The Server. and was disconnected. I tested again quite a few times. Sometimes it kicked me, sometimes it kicked random other players on the planet I was on, Erilon. This was the link I was using: http://www.whirlwindgames.com/starquest/m/17590832/article/3820260/page/3
I then went and tested it on Mardos, but nothing happened. When I came back to Erilon, I tried another SQ forums link and it kicked me too. Then I tried a google link, and it also kicked people. It is probably happening on other planets as well, but I'm not sure.

**Comment by awangatboo** [comment]
This really needs to be done by Jane.  I will ask beaver if he can get jane to give the resource pack so it does not kick people.

**Comment by Cutout1** [comment]
Well, as I said, after further testing, it wasn't just the resource pack link kicking people, it was any long link I was trying to use. I haven't had any more issues with it, but it was a very odd bug.

**Comment by GingerWalnut** [comment]
This has been fixed
