### ISSUE TITLE
Spawning into mountains

### ISSUE THREAD

**Issue by QuantumVelocity** [StarQuestMinecraft/StarQuestPublic#968]
This is a little late, but at one point, I had entered Jurion's atmosphere and 3/4 of my ship was submerged into a mountain. Even worse, there had been someone's base there and my ship replaced all the blocks in it. Beaver was an eyewitness as he helped me to recover my ship.

**Comment by awangatboo** [comment]
Other outstanding bugs on TP into mountains.  Closing this one.
