### ISSUE TITLE
/loadship is down

### ISSUE THREAD

**Issue by EnderProphet** [StarQuestMinecraft/StarQuestPublic#974]
According to Deacs, whenever he used /loadship, it gives him an error message.

**Comment by JavaInvader** [comment]
the error occurs if there isn't a ship to load, probably tried loading a ship from before the noon or midnight restart after

**Comment by awangatboo** [comment]
Deacs should have created the ticket and the error would be helpful.

**Comment by lawrencethefrog** [comment]
Works for me on Mardos
