### ISSUE TITLE
McMMO and Tree Farms

### ISSUE THREAD

**Issue by winecraft-dev** [StarQuestMinecraft/StarQuestPublic#976]
Mr. Devs:

I've recently purchased an emerald block for my new Tree Farms. I've noticed by holding a powertool in my hand, I get McMMO levels and loose energy. It is very annoying, especially when I am working with other tools such as shears and pickaxes. Also, when holding a normal ax in the hand, I gain levels without losing any of the endurance.

**Comment by dphfox** [comment]
This is a known bug.

**Comment by astronus5** [comment]
I have completed a fix for mcmmo being added; as for the energy loss, I believe this should already be fixed with this action, but ill confirm in the morning.

**Comment by awangatboo** [comment]
I have been told this has been fixed and is on the server
