### ISSUE TITLE
Space Ship glitch?

### ISSUE THREAD

**Issue by AlinaFicalton** [StarQuestMinecraft/StarQuestPublic#977]
so i made a new freighter class ship and when i auto pilot it, it will warp me into the walls of the ship, then the ship will move. This continues until i stop the autopilot or the ship flyes off without me nly to be released later and then i warp back into it. im not sure if this is a server wide thing or if this is just a my ship only thing. Also the ship taskes 2 and 1/2 min to fly to space from bedrock.

**Comment by awangatboo** [comment]
which planet?
