### ISSUE TITLE
Everyone online muted

### ISSUE THREAD

**Issue by AlinaFicalton** [StarQuestMinecraft/StarQuestPublic#980]
So at 3:00am est for some reason all nonstaff where muted "for spam" when we where all just talking.

**Comment by AlinaFicalton** [comment]
Ok so when i was unmuted i asked if anyone else was muted, and 2 min latter i asked "what is going on" and i was muted for spam once more.

**Comment by AlinaFicalton** [comment]
Ok now staff are being muted as well and nolonger have perms to unmute people

**Comment by AlinaFicalton** [comment]
Ok chat is muting everyone no matter the rank or anything if they wright 4 msges in global at all, no matter how long apart the msges are.

**Comment by AlinaFicalton** [comment]
This is a problem in global chat and in local chat

**Comment by awangatboo** [comment]
I think this was a one day issue as I have not see is at all.
