### ISSUE TITLE
Cannons extruding stained glass

### ISSUE THREAD

**Issue by lawrencethefrog** [StarQuestMinecraft/StarQuestPublic#981]
My warship has multiple cannons (facing in different directions) that share a single sponge block. When I fire the cannons out of the front of the ship, two side cannons (only the two pictured, not all of them), extrude stained glass as shown below:
![2016-06-01_16 10 05](https://cloud.githubusercontent.com/assets/10390088/15714782/d603aae4-2813-11e6-86a3-5723b5706193.png)

This glass does not go away with time.

**Comment by Millibyte1** [comment]
Is this still occurring?

**Comment by lawrencethefrog** [comment]
Yes.

**Comment by Millibyte1** [comment]
Fixed with the new cannons system
