### ISSUE TITLE
Treefarms are broken

### ISSUE THREAD

**Issue by DragonAether** [StarQuestMinecraft/StarQuestPublic#984]
When i tried to activate the treefarm i noticed that they can be activated but they don't cut trees, there is fuel, sapling, the machine is built correctly but it doesn't do his work.
![2016-06-02_11 49 44](https://cloud.githubusercontent.com/assets/19706562/15741256/27f6e37a-28b9-11e6-9662-0ab9307b3819.png)
![2016-06-02_11 49 50](https://cloud.githubusercontent.com/assets/19706562/15741257/27f920c2-28b9-11e6-8ad4-f64ce07fa719.png)

**Comment by awangatboo** [comment]
Not a bug.  Try using coal instead of charcoal.  They removed charcoal as a fuel source.
