### ISSUE TITLE
Power Tools

### ISSUE THREAD

**Issue by JUSAPlayer1** [StarQuestMinecraft/StarQuestPublic#988]
So I've been doing testing for a while of some of the power gear, and a few things. Slowness on swords doesn't do anything. There's no slowness unless mobs are not effected by it but players are. Second and third are that swing speed and damage boost do not work. I've tried various combinations, but my damage 2 axe and swords do the same damage as they did prior to adding the upgrades from what I can tell against mobs. If some staff could test this on actual player entities to verify that'd be great.

**Comment by GingerWalnut** [comment]
This seems to be working now. If it isn't please reopen/create a new bug report
