### ISSUE TITLE
Machina relays not moving items up

### ISSUE THREAD

**Issue by eventsbeyondme** [StarQuestMinecraft/StarQuestPublic#989]
I built a machina relay to try and automate moving some pumpkins and cactus to the top of a very tall building, after looking over the wiki and trying to make it work, I can't make the tubes move anything up higher than 2 blocks from the initial relay, it seems to move horizantaly just fine. 

this seems like a bug, but as there is little to no documentation on how the relay/tubes work in machina I am guessing, maybe this is by design? In anycase it would be great if I could relay things up and down, and also would be nice if a better explanation of a valid relay circuit was available.

Lilliaga in game, I have an example set up at the Yavar Public city.

**Comment by soronthar** [comment]
I confirm this, it happened to me in Quillon

**Comment by mcdouble** [comment]
Rather than make a new post I will just throw this in here.

Machina crafters don't seem to be working either. I made one on Tyder and it wasn't working.

**Comment by soronthar** [comment]
The machina crafters not working, and the whole "not transmitting upwards" may be related to  #965 and #994

**Comment by Denyol** [comment]
@eventsbeyondme, @mcdouble please post a picture of your setup.

**Comment by Denyol** [comment]
A fix should be installed on the next restart.

**Comment by eventsbeyondme** [comment]
checked after midnight restart, no improvement, and new behaviour, the switch when flipped always gives the "you can't see this" error now.  even when standing directly next to the switch.

test at rig in Yavar at 1485,120ish, 30 follow the elevator in the farm area of Redox Ark on Yavar to the floor labeled roof, the tester is sitting directly behind the elevator, put stuff in near chest, flip switch, check far chest, after 2 ticks or so the relay turns off and no items are transfered, as well as Can't see error message.

**Comment by Denyol** [comment]
Fixed :)
