### ISSUE TITLE
Refund Request

### ISSUE THREAD

**Issue by Laserlance141** [StarQuestMinecraft/StarQuestPublic#993]
5.5 double chests of cactus were stolen from me at spawn.
I have a screen shot of one of the droppers, but did not take 30 screenshots of the exact same thing.
![2016-06-02_16 14 15](https://cloud.githubusercontent.com/assets/13091148/15797534/fde50c9c-29d0-11e6-9fc7-f2bb8de7eac6.png)

**Comment by gregolegomonkey** [comment]
Not the right place for this, put it here [http://www.whirlwindgames.com/starquestforums/m/17078810/viewforum/4361853](url) when the forums decide to work again.
